 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08503     Cltot =  -0.00151     Cl'tot =  -0.00144
  CYtot =  -0.01054     Cmtot =  -0.17319
  CZtot =  -0.79124     Cntot =   0.00412     Cn'tot =   0.00415

  CLtot =   0.78964
  CDtot =   0.09882
  CDvis =   0.07000     CDind = 0.0288227
  CLff  =   0.79076     CDff  = 0.0295736    | Trefftz
  CYff  =  -0.00766         e =    0.9423    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.889856    CLb =  -0.061019
 y  force CY |    CYa =   0.000649    CYb =  -0.301432
 x' mom.  Cl'|    Cla =  -0.009110    Clb =  -0.041140
 y  mom.  Cm |    Cma =  -1.975379    Cmb =   0.031789
 z' mom.  Cn'|    Cna =   0.001520    Cnb =   0.118568

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005722    CLq =  10.563091    CLr =   0.008503
 y  force CY |    CYp =   0.090953    CYq =   0.023676    CYr =   0.248435
 x' mom.  Cl'|    Clp =  -0.462031    Clq =  -0.014553    Clr =   0.216253
 y  mom.  Cm |    Cmp =   0.003142    Cmq = -19.267399    Cmr =  -0.021987
 z' mom.  Cn'|    Cnp =  -0.054476    Cnq =  -0.012712    Cnr =  -0.141309

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.008020   CLd03 =  -0.000033
 y  force CY |   CYd01 =   0.000258   CYd02 =   0.000001   CYd03 =  -0.002865
 x' mom.  Cl'|   Cld01 =  -0.004510   Cld02 =  -0.000009   Cld03 =  -0.000252
 y  mom.  Cm |   Cmd01 =   0.000031   Cmd02 =  -0.030085   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000046   Cnd02 =  -0.000001   Cnd03 =   0.001554
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000166 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000048    ed02 =   0.013769    ed03 =  -0.002163



 Neutral point  Xnp =   0.171921

 Clb Cnr / Clr Cnb  =   0.226729    (  > 1 if spirally stable )
