 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09499     Cltot =  -0.00850     Cl'tot =  -0.00707
  CYtot =  -0.02044     Cmtot =  -0.16201
  CZtot =  -1.54425     Cntot =   0.00744     Cn'tot =   0.00880

  CLtot =   1.53729
  CDtot =   0.17461
  CDvis =   0.07000     CDind = 0.1046085
  CLff  =   1.55991     CDff  = 0.1082191    | Trefftz
  CYff  =  -0.01527         e =    1.0021    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.532275    CLb =  -0.223324
 y  force CY |    CYa =   0.004186    CYb =  -0.291232
 x' mom.  Cl'|    Cla =  -0.016456    Clb =  -0.100679
 y  mom.  Cm |    Cma =  -1.104716    Cmb =   0.046238
 z' mom.  Cn'|    Cna =   0.009864    Cnb =   0.125222

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010959    CLq =   7.434148    CLr =   0.014871
 y  force CY |    CYp =   0.189059    CYq =   0.066824    CYr =   0.198946
 x' mom.  Cl'|    Clp =  -0.426136    Clq =  -0.013467    Clr =   0.373427
 y  mom.  Cm |    Cmp =   0.004161    Cmq = -16.619170    Cmr =  -0.026256
 z' mom.  Cn'|    Cnp =  -0.102008    Cnq =  -0.031949    Cnr =  -0.152022

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000091   CLd02 =   0.007687   CLd03 =  -0.000055
 y  force CY |   CYd01 =   0.000144   CYd02 =   0.000001   CYd03 =  -0.002742
 x' mom.  Cl'|   Cld01 =  -0.004152   Cld02 =  -0.000018   Cld03 =  -0.000462
 y  mom.  Cm |   Cmd01 =   0.000036   Cmd02 =  -0.027876   Cmd03 =   0.000183
 z' mom.  Cn'|   Cnd01 =  -0.000172   Cnd02 =  -0.000002   Cnd03 =   0.001395
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000962 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000037    ed02 =   0.001134    ed03 =  -0.001253



 Neutral point  Xnp =   0.195236

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
