 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10337     Cltot =  -0.00145     Cl'tot =  -0.00198
  CYtot =  -0.02631     Cmtot =  -0.03363
  CZtot =  -0.43705     Cntot =   0.01026     Cn'tot =   0.01017

  CLtot =   0.44186
  CDtot =   0.08035
  CDvis =   0.07000     CDind = 0.0103499
  CLff  =   0.44370     CDff  = 0.0122219    | Trefftz
  CYff  =  -0.01914         e =    0.7192    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.934198    CLb =  -0.093788
 y  force CY |    CYa =   0.000206    CYb =  -0.298969
 x' mom.  Cl'|    Cla =  -0.022983    Clb =  -0.022507
 y  mom.  Cm |    Cma =  -1.945955    Cmb =   0.055220
 z' mom.  Cn'|    Cna =   0.000592    Cnb =   0.115316

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015770    CLq =  10.578933    CLr =   0.021975
 y  force CY |    CYp =   0.025164    CYq =   0.059127    CYr =   0.250578
 x' mom.  Cl'|    Clp =  -0.470265    Clq =  -0.034041    Clr =   0.148975
 y  mom.  Cm |    Cmp =   0.011658    Cmq = -19.098962    Cmr =  -0.054228
 z' mom.  Cn'|    Cnp =  -0.021813    Cnq =  -0.034204    Cnr =  -0.132981

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000126   CLd02 =   0.007928   CLd03 =  -0.000086
 y  force CY |   CYd01 =   0.000325   CYd02 =   0.000002   CYd03 =  -0.002846
 x' mom.  Cl'|   Cld01 =  -0.004553   Cld02 =  -0.000023   Cld03 =  -0.000259
 y  mom.  Cm |   Cmd01 =   0.000079   Cmd02 =  -0.029652   Cmd03 =   0.000293
 z' mom.  Cn'|   Cnd01 =   0.000142   Cnd02 =  -0.000003   Cnd03 =   0.001543
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =  -0.000225 CDffd03 =   0.000174
 span eff.   |    ed01 =   0.000218    ed02 =   0.038958    ed03 =  -0.009842



 Neutral point  Xnp =   0.169216

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
