 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02793     Cltot =  -0.00364     Cl'tot =  -0.00309
  CYtot =  -0.01569     Cmtot =  -0.30967
  CZtot =  -1.13168     Cntot =   0.00614     Cn'tot =   0.00644

  CLtot =   1.12494
  CDtot =   0.12646
  CDvis =   0.07000     CDind = 0.0564569
  CLff  =   1.13168     CDff  = 0.0579999    | Trefftz
  CYff  =  -0.01149         e =    0.9841    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.752082    CLb =  -0.125619
 y  force CY |    CYa =   0.001816    CYb =  -0.298820
 x' mom.  Cl'|    Cla =  -0.013201    Clb =  -0.058879
 y  mom.  Cm |    Cma =  -1.950872    Cmb =   0.062012
 z' mom.  Cn'|    Cna =   0.004156    Cnb =   0.122487

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007762    CLq =  10.486348    CLr =   0.012188
 y  force CY |    CYp =   0.155493    CYq =   0.035505    CYr =   0.236193
 x' mom.  Cl'|    Clp =  -0.448257    Clq =  -0.023101    Clr =   0.280579
 y  mom.  Cm |    Cmp =   0.002400    Cmq = -19.266004    Cmr =  -0.033220
 z' mom.  Cn'|    Cnp =  -0.087943    Cnq =  -0.017494    Cnr =  -0.149846

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000073   CLd02 =   0.007951   CLd03 =  -0.000046
 y  force CY |   CYd01 =   0.000189   CYd02 =   0.000001   CYd03 =  -0.002835
 x' mom.  Cl'|   Cld01 =  -0.004387   Cld02 =  -0.000014   Cld03 =  -0.000240
 y  mom.  Cm |   Cmd01 =   0.000045   Cmd02 =  -0.029988   Cmd03 =   0.000176
 z' mom.  Cn'|   Cnd01 =  -0.000047   Cnd02 =  -0.000002   Cnd03 =   0.001538
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000556 CDffd03 =   0.000104
 span eff.   |    ed01 =   0.000037    ed02 =   0.004433    ed03 =  -0.001722



 Neutral point  Xnp =   0.173769

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
