 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08619     Cltot =  -0.00035     Cl'tot =   0.00015
  CYtot =   0.01055     Cmtot =   0.09937
  CZtot =  -0.08788     Cntot =  -0.00410     Cn'tot =  -0.00411

  CLtot =   0.09773
  CDtot =   0.07484
  CDvis =   0.07000     CDind = 0.0048361
  CLff  =   0.09733     CDff  = 0.0050180    | Trefftz
  CYff  =   0.00766         e =    0.0846    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.982768    CLb =   0.014073
 y  force CY |    CYa =   0.000484    CYb =  -0.301761
 x' mom.  Cl'|    Cla =   0.009176    Clb =  -0.004390
 y  mom.  Cm |    Cma =  -1.903425    Cmb =  -0.012752
 z' mom.  Cn'|    Cna =   0.001050    Cnb =   0.117622

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006943    CLq =  10.642721    CLr =  -0.009010
 y  force CY |    CYp =  -0.040234    CYq =  -0.023676    CYr =   0.245155
 x' mom.  Cl'|    Clp =  -0.477560    Clq =   0.012642    Clr =   0.081045
 y  mom.  Cm |    Cmp =  -0.006171    Cmq = -18.959730    Cmr =   0.021336
 z' mom.  Cn'|    Cnp =   0.009937    Cnq =   0.014614    Cnr =  -0.126514

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000051   CLd02 =   0.007840   CLd03 =   0.000036
 y  force CY |   CYd01 =   0.000395   CYd02 =  -0.000001   CYd03 =  -0.002835
 x' mom.  Cl'|   Cld01 =  -0.004610   Cld02 =   0.000009   Cld03 =  -0.000268
 y  mom.  Cm |   Cmd01 =  -0.000032   Cmd02 =  -0.029313   Cmd03 =  -0.000117
 z' mom.  Cn'|   Cnd01 =   0.000242   Cnd02 =   0.000001   Cnd03 =   0.001536
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000612 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000005    ed02 =   0.024024    ed03 =   0.000797



 Neutral point  Xnp =   0.165724

 Clb Cnr / Clr Cnb  =   0.058262    (  > 1 if spirally stable )
