 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06517     Cltot =  -0.00167     Cl'tot =  -0.00133
  CYtot =  -0.00519     Cmtot =  -0.44578
  CZtot =  -1.46211     Cntot =   0.00203     Cn'tot =   0.00227

  CLtot =   1.45430
  CDtot =   0.16435
  CDvis =   0.07000     CDind = 0.0943522
  CLff  =   1.46947     CDff  = 0.0964657    | Trefftz
  CYff  =  -0.00383         e =    0.9975    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.580189    CLb =  -0.052958
 y  force CY |    CYa =   0.000885    CYb =  -0.297044
 x' mom.  Cl'|    Cla =  -0.004171    Clb =  -0.076346
 y  mom.  Cm |    Cma =  -1.896019    Cmb =   0.025406
 z' mom.  Cn'|    Cna =   0.001987    Cnb =   0.129844

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002344    CLq =  10.412722    CLr =   0.003840
 y  force CY |    CYp =   0.218062    CYq =   0.011840    CYr =   0.215528
 x' mom.  Cl'|    Clp =  -0.432022    Clq =  -0.008092    Clr =   0.342644
 y  mom.  Cm |    Cmp =   0.000026    Cmq = -19.208827    Cmr =  -0.011107
 z' mom.  Cn'|    Cnp =  -0.122649    Cnq =  -0.005282    Cnr =  -0.159109

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000023   CLd02 =   0.007817   CLd03 =  -0.000014
 y  force CY |   CYd01 =   0.000122   CYd02 =   0.000000   CYd03 =  -0.002788
 x' mom.  Cl'|   Cld01 =  -0.004239   Cld02 =  -0.000005   Cld03 =  -0.000227
 y  mom.  Cm |   Cmd01 =   0.000015   Cmd02 =  -0.029719   Cmd03 =   0.000058
 z' mom.  Cn'|   Cnd01 =  -0.000136   Cnd02 =  -0.000001   Cnd03 =   0.001513
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000939 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000007    ed02 =   0.001048    ed03 =  -0.000348



 Neutral point  Xnp =   0.174737

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
