 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09994     Cltot =  -0.00175     Cl'tot =  -0.00182
  CYtot =  -0.01050     Cmtot =   0.03093
  CZtot =  -0.62214     Cntot =   0.00382     Cn'tot =   0.00378

  CLtot =   0.62379
  CDtot =   0.08906
  CDvis =   0.07000     CDind = 0.0190621
  CLff  =   0.62397     CDff  = 0.0197407    | Trefftz
  CYff  =  -0.00764         e =    0.8790    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.962565    CLb =  -0.049754
 y  force CY |    CYa =   0.000572    CYb =  -0.300344
 x' mom.  Cl'|    Cla =  -0.009500    Clb =  -0.052086
 y  mom.  Cm |    Cma =  -0.888957    Cmb =   0.009615
 z' mom.  Cn'|    Cna =   0.001494    Cnb =   0.108247

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007274    CLq =   7.985181    CLr =   0.008227
 y  force CY |    CYp =   0.015113    CYq =   0.033432    CYr =   0.234034
 x' mom.  Cl'|    Clp =  -0.476140    Clq =  -0.003564    Clr =   0.201803
 y  mom.  Cm |    Cmp =   0.004550    Cmq = -16.452353    Cmr =  -0.012497
 z' mom.  Cn'|    Cnp =  -0.015523    Cnq =  -0.016976    Cnr =  -0.120215

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000049   CLd02 =   0.007951   CLd03 =  -0.000034
 y  force CY |   CYd01 =   0.000336   CYd02 =   0.000001   CYd03 =  -0.002862
 x' mom.  Cl'|   Cld01 =  -0.004525   Cld02 =  -0.000009   Cld03 =  -0.000507
 y  mom.  Cm |   Cmd01 =   0.000019   Cmd02 =  -0.028098   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000084   Cnd02 =  -0.000001   Cnd03 =   0.001453
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000059 CDffd03 =   0.000071
 span eff.   |    ed01 =   0.000093    ed02 =   0.024953    ed03 =  -0.003054



 Neutral point  Xnp =   0.177015

 Clb Cnr / Clr Cnb  =   0.286642    (  > 1 if spirally stable )
