 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00799     Cltot =   0.00399     Cl'tot =   0.00332
  CYtot =   0.01566     Cmtot =  -0.34362
  CZtot =  -1.21502     Cntot =  -0.00613     Cn'tot =  -0.00651

  CLtot =   1.20753
  CDtot =   0.13495
  CDvis =   0.07000     CDind = 0.0649502
  CLff  =   1.21626     CDff  = 0.0666869    | Trefftz
  CYff  =   0.01149         e =    0.9886    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.711134    CLb =   0.133994
 y  force CY |    CYa =  -0.002025    CYb =  -0.298182
 x' mom.  Cl'|    Cla =   0.013048    Clb =  -0.063238
 y  mom.  Cm |    Cma =  -1.939531    Cmb =  -0.065571
 z' mom.  Cn'|    Cna =  -0.004614    Cnb =   0.123943

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.007570    CLq =  10.466361    CLr =  -0.012029
 y  force CY |    CYp =   0.171333    CYq =  -0.035505    CYr =   0.231780
 x' mom.  Cl'|    Clp =  -0.444364    Clq =   0.023403    Clr =   0.296279
 y  mom.  Cm |    Cmp =  -0.001820    Cmq = -19.254651    Cmr =   0.033257
 z' mom.  Cn'|    Cnp =  -0.096481    Cnq =   0.017089    Cnr =  -0.152087

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000072   CLd02 =   0.007922   CLd03 =   0.000045
 y  force CY |   CYd01 =   0.000172   CYd02 =  -0.000001   CYd03 =  -0.002824
 x' mom.  Cl'|   Cld01 =  -0.004351   Cld02 =   0.000014   Cld03 =  -0.000237
 y  mom.  Cm |   Cmd01 =  -0.000045   Cmd02 =  -0.029930   Cmd03 =  -0.000176
 z' mom.  Cn'|   Cnd01 =  -0.000070   Cnd02 =   0.000002   Cnd03 =   0.001532
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000652 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000032    ed02 =   0.003273    ed03 =   0.001502



 Neutral point  Xnp =   0.174097

 Clb Cnr / Clr Cnb  =   0.261908    (  > 1 if spirally stable )
