 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01449     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.10663
  CZtot =  -1.31057     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.30257
  CDtot =   0.14533
  CDvis =   0.07000     CDind = 0.0753321
  CLff  =   1.31180     CDff  = 0.0766826    | Trefftz
  CYff  =   0.00000         e =    1.0000    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.705700    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.296420
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.088921
 y  mom.  Cm |    Cma =  -1.065183    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.119692

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.615958    CLr =  -0.000000
 y  force CY |    CYp =   0.143478    CYq =  -0.000000    CYr =   0.215526
 x' mom.  Cl'|    Clp =  -0.443138    Clq =   0.000000    Clr =   0.329876
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.666740    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.077391    Cnq =  -0.000000    Cnr =  -0.143262

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007860   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000196   CYd02 =   0.000000   CYd03 =  -0.002806
 x' mom.  Cl'|   Cld01 =  -0.004301   Cld02 =   0.000000   Cld03 =  -0.000479
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028252   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000107   Cnd02 =  -0.000000   Cnd03 =   0.001426
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000694 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.002981    ed03 =   0.000000



 Neutral point  Xnp =   0.190334

 Clb Cnr / Clr Cnb  =   0.322640    (  > 1 if spirally stable )
