 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07516     Cltot =  -0.00116     Cl'tot =  -0.00001
  CYtot =   0.02103     Cmtot =   0.13297
  CZtot =   0.00009     Cntot =  -0.00817     Cn'tot =  -0.00825

  CLtot =   0.01037
  CDtot =   0.07444
  CDvis =   0.07000     CDind = 0.0044445
  CLff  =   0.01022     CDff  = 0.0053179    | Trefftz
  CYff  =   0.01532         e =    0.0028    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.960504    CLb =   0.016290
 y  force CY |    CYa =   0.001248    CYb =  -0.299663
 x' mom.  Cl'|    Cla =   0.018223    Clb =   0.000179
 y  mom.  Cm |    Cma =  -1.876939    Cmb =  -0.020837
 z' mom.  Cn'|    Cna =   0.002732    Cnb =   0.117361

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014200    CLq =  10.627529    CLr =  -0.018087
 y  force CY |    CYp =  -0.056315    CYq =  -0.047323    CYr =   0.241732
 x' mom.  Cl'|    Clp =  -0.477492    Clq =   0.024756    Clr =   0.063656
 y  mom.  Cm |    Cmp =  -0.013078    Cmq = -18.860584    Cmr =   0.042424
 z' mom.  Cn'|    Cnp =   0.017762    Cnq =   0.029646    Cnr =  -0.124743

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000101   CLd02 =   0.007762   CLd03 =   0.000072
 y  force CY |   CYd01 =   0.000410   CYd02 =  -0.000001   CYd03 =  -0.002813
 x' mom.  Cl'|   Cld01 =  -0.004593   Cld02 =   0.000018   Cld03 =  -0.000268
 y  mom.  Cm |   Cmd01 =  -0.000064   Cmd02 =  -0.029030   Cmd03 =  -0.000233
 z' mom.  Cn'|   Cnd01 =   0.000265   Cnd02 =   0.000002   Cnd03 =   0.001524
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000705 CDffd03 =  -0.000138
 span eff.   |    ed01 =   0.000043    ed02 =   0.001727    ed03 =  -0.000628



 Neutral point  Xnp =   0.164702

 Clb Cnr / Clr Cnb  =  -0.002990    (  > 1 if spirally stable )
