 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09359     Cltot =   0.00064     Cl'tot =   0.00064
  CYtot =   0.00528     Cmtot =  -0.13910
  CZtot =  -0.70480     Cntot =  -0.00206     Cn'tot =  -0.00206

  CLtot =   0.70480
  CDtot =   0.09359
  CDvis =   0.07000     CDind = 0.0235926
  CLff  =   0.70497     CDff  = 0.0240701    | Trefftz
  CYff  =   0.00383         e =    0.9201    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.918314    CLb =   0.027628
 y  force CY |    CYa =  -0.000254    CYb =  -0.302176
 x' mom.  Cl'|    Cla =   0.004581    Clb =  -0.036648
 y  mom.  Cm |    Cma =  -1.976560    Cmb =  -0.014699
 z' mom.  Cn'|    Cna =  -0.000601    Cnb =   0.118104

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002933    CLq =  10.582194    CLr =  -0.004293
 y  force CY |    CYp =   0.074609    CYq =  -0.011840    CYr =   0.250146
 x' mom.  Cl'|    Clp =  -0.465036    Clq =   0.007166    Clr =   0.199831
 y  mom.  Cm |    Cmp =  -0.001763    Cmq = -19.258196    Cmr =   0.010966
 z' mom.  Cn'|    Cnp =  -0.046267    Cnq =   0.006483    Cnr =  -0.139316

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.008026   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000276   CYd02 =  -0.000000   CYd03 =  -0.002870
 x' mom.  Cl'|   Cld01 =  -0.004536   Cld02 =   0.000005   Cld03 =  -0.000255
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.030079   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000070   Cnd02 =   0.000001   Cnd03 =   0.001556
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000068 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000029    ed02 =   0.018288    ed03 =   0.001298



 Neutral point  Xnp =   0.171329

 Clb Cnr / Clr Cnb  =   0.216329    (  > 1 if spirally stable )
