 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06135     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.24271
  CZtot =  -0.96514     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.96061
  CDtot =   0.11178
  CDvis =   0.07000     CDind = 0.0417818
  CLff  =   0.96282     CDff  = 0.0424316    | Trefftz
  CYff  =   0.00000         e =    0.9736    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.836960    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.301249
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.050297
 y  mom.  Cm |    Cma =  -1.971812    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.120696

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.537431    CLr =   0.000000
 y  force CY |    CYp =   0.123568    CYq =   0.000000    CYr =   0.243682
 x' mom.  Cl'|    Clp =  -0.456033    Clq =  -0.000000    Clr =   0.248995
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.297549    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.071161    Cnq =  -0.000000    Cnr =  -0.145648

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.008014   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000224   CYd02 =   0.000000   CYd03 =  -0.002859
 x' mom.  Cl'|   Cld01 =  -0.004462   Cld02 =   0.000000   Cld03 =  -0.000247
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.030133   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =  -0.000000   Cnd03 =   0.001551
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000363 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.007857    ed03 =   0.000000



 Neutral point  Xnp =   0.172959

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
