 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10452     Cltot =   0.00058     Cl'tot =   0.00080
  CYtot =   0.01056     Cmtot =  -0.03565
  CZtot =  -0.44044     Cntot =  -0.00412     Cn'tot =  -0.00408

  CLtot =   0.44531
  CDtot =   0.08133
  CDvis =   0.07000     CDind = 0.0113254
  CLff  =   0.44513     CDff  = 0.0118072    | Trefftz
  CYff  =   0.00766         e =    0.7480    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.965001    CLb =   0.037676
 y  force CY |    CYa =  -0.000083    CYb =  -0.302162
 x' mom.  Cl'|    Cla =   0.009232    Clb =  -0.022798
 y  mom.  Cm |    Cma =  -1.958462    Cmb =  -0.022183
 z' mom.  Cn'|    Cna =  -0.000238    Cnb =   0.116810

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006315    CLq =  10.612874    CLr =  -0.008799
 y  force CY |    CYp =   0.025245    CYq =  -0.023676    CYr =   0.251382
 x' mom.  Cl'|    Clp =  -0.471773    Clq =   0.013631    Clr =   0.149453
 y  mom.  Cm |    Cmp =  -0.004668    Cmq = -19.160238    Cmr =   0.021714
 z' mom.  Cn'|    Cnp =  -0.021883    Cnq =   0.013696    Cnr =  -0.133408

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000051   CLd02 =   0.007979   CLd03 =   0.000035
 y  force CY |   CYd01 =   0.000327   CYd02 =  -0.000001   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004583   Cld02 =   0.000009   Cld03 =  -0.000261
 y  mom.  Cm |   Cmd01 =  -0.000032   Cmd02 =  -0.029843   Cmd03 =  -0.000118
 z' mom.  Cn'|   Cnd01 =   0.000143   Cnd02 =   0.000001   Cnd03 =   0.001552
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000226 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000095    ed02 =   0.041139    ed03 =   0.004263



 Neutral point  Xnp =   0.169236

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
