 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03879     Cltot =  -0.00775     Cl'tot =  -0.00627
  CYtot =  -0.02590     Cmtot =  -0.40746
  CZtot =  -1.37137     Cntot =   0.01013     Cn'tot =   0.01111

  CLtot =   1.36342
  CDtot =   0.15244
  CDvis =   0.07000     CDind = 0.0824438
  CLff  =   1.38091     CDff  = 0.0858629    | Trefftz
  CYff  =  -0.01914         e =    0.9899    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.597989    CLb =  -0.250015
 y  force CY |    CYa =   0.004058    CYb =  -0.294312
 x' mom.  Cl'|    Cla =  -0.021088    Clb =  -0.071090
 y  mom.  Cm |    Cma =  -1.900477    Cmb =   0.120633
 z' mom.  Cn'|    Cna =   0.009158    Cnb =   0.126064

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011996    CLq =  10.397765    CLr =   0.019472
 y  force CY |    CYp =   0.202010    CYq =   0.059127    CYr =   0.220770
 x' mom.  Cl'|    Clp =  -0.434914    Clq =  -0.039942    Clr =   0.326313
 y  mom.  Cm |    Cmp =   0.001096    Cmq = -19.167507    Cmr =  -0.055456
 z' mom.  Cn'|    Cnp =  -0.113481    Cnq =  -0.027080    Cnr =  -0.156246

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000118   CLd02 =   0.007807   CLd03 =  -0.000072
 y  force CY |   CYd01 =   0.000138   CYd02 =   0.000002   CYd03 =  -0.002783
 x' mom.  Cl'|   Cld01 =  -0.004251   Cld02 =  -0.000023   Cld03 =  -0.000229
 y  mom.  Cm |   Cmd01 =   0.000074   Cmd02 =  -0.029614   Cmd03 =   0.000291
 z' mom.  Cn'|   Cnd01 =  -0.000114   Cnd02 =  -0.000003   Cnd03 =   0.001510
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000839 CDffd03 =   0.000172
 span eff.   |    ed01 =   0.000041    ed02 =   0.001674    ed03 =  -0.001933



 Neutral point  Xnp =   0.174558

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
