 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07551     Cltot =   0.00024     Cl'tot =   0.00130
  CYtot =   0.02097     Cmtot =   0.12733
  CZtot =  -0.00205     Cntot =  -0.00758     Cn'tot =  -0.00747

  CLtot =   0.01253
  CDtot =   0.07449
  CDvis =   0.07000     CDind = 0.0044932
  CLff  =   0.01237     CDff  = 0.0053960    | Trefftz
  CYff  =   0.01527         e =    0.0032    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.989467    CLb =   0.016500
 y  force CY |    CYa =   0.000826    CYb =  -0.298805
 x' mom.  Cl'|    Cla =   0.019111    Clb =  -0.018450
 y  mom.  Cm |    Cma =  -0.676316    Cmb =  -0.005772
 z' mom.  Cn'|    Cna =   0.001692    Cnb =   0.106329

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.017023    CLq =   8.205681    CLr =  -0.016693
 y  force CY |    CYp =  -0.097434    CYq =  -0.066824    CYr =   0.220323
 x' mom.  Cl'|    Clp =  -0.491182    Clq =   0.002935    Clr =   0.081655
 y  mom.  Cm |    Cmp =  -0.012071    Cmq = -15.981408    Cmr =   0.023685
 z' mom.  Cn'|    Cnp =   0.033996    Cnq =   0.034547    Cnr =  -0.103587

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007697   CLd03 =   0.000072
 y  force CY |   CYd01 =   0.000453   CYd02 =  -0.000001   CYd03 =  -0.002812
 x' mom.  Cl'|   Cld01 =  -0.004564   Cld02 =   0.000018   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =  -0.000040   Cmd02 =  -0.027003   Cmd03 =  -0.000184
 z' mom.  Cn'|   Cnd01 =   0.000258   Cnd02 =   0.000002   Cnd03 =   0.001427
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =  -0.000709 CDffd03 =  -0.000140
 span eff.   |    ed01 =   0.000052    ed02 =   0.002017    ed03 =  -0.000607



 Neutral point  Xnp =   0.164725

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
