 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09966     Cltot =   0.00052     Cl'tot =   0.00056
  CYtot =   0.00528     Cmtot =  -0.10463
  CZtot =  -0.61713     Cntot =  -0.00206     Cn'tot =  -0.00205

  CLtot =   0.61878
  CDtot =   0.08887
  CDvis =   0.07000     CDind = 0.0188695
  CLff  =   0.61860     CDff  = 0.0192824    | Trefftz
  CYff  =   0.00383         e =    0.8844    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.938911    CLb =   0.024714
 y  force CY |    CYa =  -0.000183    CYb =  -0.302395
 x' mom.  Cl'|    Cla =   0.004600    Clb =  -0.032059
 y  mom.  Cm |    Cma =  -1.973526    Cmb =  -0.013496
 z' mom.  Cn'|    Cna =  -0.000441    Cnb =   0.117584

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003007    CLq =  10.595264    CLr =  -0.004331
 y  force CY |    CYp =   0.058177    CYq =  -0.011840    CYr =   0.251171
 x' mom.  Cl'|    Clp =  -0.467595    Clq =   0.007051    Clr =   0.183179
 y  mom.  Cm |    Cmp =  -0.001954    Cmq = -19.234319    Cmr =   0.010934
 z' mom.  Cn'|    Cnp =  -0.038089    Cnq =   0.006607    Cnr =  -0.137309

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.008019   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000293   CYd02 =  -0.000000   CYd03 =  -0.002871
 x' mom.  Cl'|   Cld01 =  -0.004556   Cld02 =   0.000005   Cld03 =  -0.000257
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.030028   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000095   Cnd02 =   0.000001   Cnd03 =   0.001556
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000030 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000035    ed02 =   0.024258    ed03 =   0.001555



 Neutral point  Xnp =   0.170684

 Clb Cnr / Clr Cnb  =   0.204371    (  > 1 if spirally stable )
