 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06271     Cltot =  -0.00122     Cl'tot =  -0.00025
  CYtot =   0.01578     Cmtot =   0.16529
  CZtot =   0.08695     Cntot =  -0.00612     Cn'tot =  -0.00623

  CLtot =  -0.07607
  CDtot =   0.07554
  CDvis =   0.07000     CDind = 0.0055370
  CLff  =  -0.07680     CDff  = 0.0058976    | Trefftz
  CYff  =   0.01149         e =    0.0456    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.962685    CLb =   0.003389
 y  force CY |    CYa =   0.001149    CYb =  -0.300378
 x' mom.  Cl'|    Cla =   0.013606    Clb =   0.004712
 y  mom.  Cm |    Cma =  -1.859083    Cmb =  -0.012229
 z' mom.  Cn'|    Cna =   0.002528    Cnb =   0.118626

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010898    CLq =  10.641859    CLr =  -0.013620
 y  force CY |    CYp =  -0.072433    CYq =  -0.035505    CYr =   0.238450
 x' mom.  Cl'|    Clp =  -0.478547    Clq =   0.018182    Clr =   0.046419
 y  mom.  Cm |    Cmp =  -0.010366    Cmq = -18.810419    Cmr =   0.031653
 z' mom.  Cn'|    Cnp =   0.025601    Cnq =   0.022563    Cnr =  -0.123411

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007724   CLd03 =   0.000055
 y  force CY |   CYd01 =   0.000427   CYd02 =  -0.000001   CYd03 =  -0.002806
 x' mom.  Cl'|   Cld01 =  -0.004600   Cld02 =   0.000014   Cld03 =  -0.000269
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.028899   Cmd03 =  -0.000175
 z' mom.  Cn'|   Cnd01 =   0.000290   Cnd02 =   0.000002   Cnd03 =   0.001520
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000800 CDffd03 =  -0.000103
 span eff.   |    ed01 =   0.000011    ed02 =  -0.002959    ed03 =   0.000325



 Neutral point  Xnp =   0.163641

 Clb Cnr / Clr Cnb  =  -0.105614    (  > 1 if spirally stable )
