 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09400     Cltot =   0.00178     Cl'tot =   0.00141
  CYtot =   0.00517     Cmtot =  -0.47870
  CZtot =  -1.54087     Cntot =  -0.00202     Cn'tot =  -0.00230

  CLtot =   1.53378
  CDtot =   0.17500
  CDvis =   0.07000     CDind = 0.1049963
  CLff  =   1.55252     CDff  = 0.1075861    | Trefftz
  CYff  =   0.00383         e =    0.9984    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.526797    CLb =   0.055636
 y  force CY |    CYa =  -0.000954    CYb =  -0.296125
 x' mom.  Cl'|    Cla =   0.004099    Clb =  -0.080480
 y  mom.  Cm |    Cma =  -1.875287    Cmb =  -0.026555
 z' mom.  Cn'|    Cna =  -0.002132    Cnb =   0.131903

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002288    CLq =  10.388552    CLr =  -0.003779
 y  force CY |    CYp =   0.233152    CYq =  -0.011840    CYr =   0.208945
 x' mom.  Cl'|    Clp =  -0.427352    Clq =   0.008183    Clr =   0.357568
 y  mom.  Cm |    Cmp =   0.000168    Cmq = -19.174009    Cmr =   0.011106
 z' mom.  Cn'|    Cnp =  -0.131469    Cnq =   0.005140    Cnr =  -0.161403

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000023   CLd02 =   0.007764   CLd03 =   0.000014
 y  force CY |   CYd01 =   0.000105   CYd02 =  -0.000000   CYd03 =  -0.002770
 x' mom.  Cl'|   Cld01 =  -0.004194   Cld02 =   0.000005   Cld03 =  -0.000223
 y  mom.  Cm |   Cmd01 =  -0.000015   Cmd02 =  -0.029588   Cmd03 =  -0.000058
 z' mom.  Cn'|   Cnd01 =  -0.000158   Cnd02 =   0.000001   Cnd03 =   0.001503
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.001032 CDffd03 =  -0.000034
 span eff.   |    ed01 =  -0.000007    ed02 =   0.000587    ed03 =   0.000311



 Neutral point  Xnp =   0.174822

 Clb Cnr / Clr Cnb  =   0.275413    (  > 1 if spirally stable )
