 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08634     Cltot =   0.00017     Cl'tot =  -0.00008
  CYtot =  -0.00528     Cmtot =   0.09920
  CZtot =  -0.08805     Cntot =   0.00205     Cn'tot =   0.00206

  CLtot =   0.09792
  CDtot =   0.07496
  CDvis =   0.07000     CDind = 0.0049635
  CLff  =   0.09737     CDff  = 0.0049524    | Trefftz
  CYff  =  -0.00383         e =    0.0854    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.987201    CLb =  -0.007041
 y  force CY |    CYa =  -0.000242    CYb =  -0.302218
 x' mom.  Cl'|    Cla =  -0.004591    Clb =  -0.004398
 y  mom.  Cm |    Cma =  -1.905166    Cmb =   0.006380
 z' mom.  Cn'|    Cna =  -0.000525    Cnb =   0.117837

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003472    CLq =  10.647586    CLr =   0.004506
 y  force CY |    CYp =  -0.040252    CYq =   0.011840    CYr =   0.245267
 x' mom.  Cl'|    Clp =  -0.477779    Clq =  -0.006322    Clr =   0.081082
 y  mom.  Cm |    Cmp =   0.003086    Cmq = -18.968398    Cmr =  -0.010669
 z' mom.  Cn'|    Cnp =   0.009941    Cnq =  -0.007308    Cnr =  -0.126572

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007847   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000395   CYd02 =   0.000000   CYd03 =  -0.002838
 x' mom.  Cl'|   Cld01 =  -0.004615   Cld02 =  -0.000005   Cld03 =  -0.000268
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.029340   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =   0.000242   Cnd02 =  -0.000001   Cnd03 =   0.001537
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000613 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000002    ed02 =   0.024464    ed03 =  -0.000409



 Neutral point  Xnp =   0.165727

 Clb Cnr / Clr Cnb  =   0.058262    (  > 1 if spirally stable )
