 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06230     Cltot =   0.00028     Cl'tot =  -0.00120
  CYtot =  -0.02616     Cmtot =   0.13893
  CZtot =   0.08537     Cntot =   0.00944     Cn'tot =   0.00937

  CLtot =  -0.07457
  CDtot =   0.07488
  CDvis =   0.07000     CDind = 0.0048842
  CLff  =  -0.07496     CDff  = 0.0062730    | Trefftz
  CYff  =  -0.01908         e =    0.0425    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.968138    CLb =  -0.005801
 y  force CY |    CYa =  -0.001381    CYb =  -0.297208
 x' mom.  Cl'|    Cla =  -0.023757    Clb =  -0.013636
 y  mom.  Cm |    Cma =  -0.641035    Cmb =   0.005192
 z' mom.  Cn'|    Cna =  -0.002942    Cnb =   0.106243

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.021715    CLq =   8.220044    CLr =   0.020839
 y  force CY |    CYp =  -0.112971    CYq =   0.083492    CYr =   0.215900
 x' mom.  Cl'|    Clp =  -0.491671    Clq =  -0.002913    Clr =   0.064077
 y  mom.  Cm |    Cmp =   0.015596    Cmq = -15.876955    Cmr =  -0.029325
 z' mom.  Cn'|    Cnp =   0.040750    Cnq =  -0.043222    Cnr =  -0.101486

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000124   CLd02 =   0.007621   CLd03 =  -0.000091
 y  force CY |   CYd01 =   0.000468   CYd02 =   0.000002   CYd03 =  -0.002792
 x' mom.  Cl'|   Cld01 =  -0.004548   Cld02 =  -0.000022   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =   0.000049   Cmd02 =  -0.026723   Cmd03 =   0.000230
 z' mom.  Cn'|   Cnd01 =   0.000282   Cnd02 =  -0.000003   Cnd03 =   0.001417
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =  -0.000796 CDffd03 =   0.000174
 span eff.   |    ed01 =  -0.000019    ed02 =  -0.002896    ed03 =  -0.000440



 Neutral point  Xnp =   0.162886

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
