 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09399     Cltot =   0.00357     Cl'tot =   0.00281
  CYtot =   0.01033     Cmtot =  -0.47800
  CZtot =  -1.53939     Cntot =  -0.00405     Cn'tot =  -0.00460

  CLtot =   1.53233
  CDtot =   0.17476
  CDvis =   0.07000     CDind = 0.1047551
  CLff  =   1.55181     CDff  = 0.1075579    | Trefftz
  CYff  =   0.00766         e =    0.9978    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.522806    CLb =   0.111204
 y  force CY |    CYa =  -0.001907    CYb =  -0.295679
 x' mom.  Cl'|    Cla =   0.008194    Clb =  -0.080333
 y  mom.  Cm |    Cma =  -1.873574    Cmb =  -0.053077
 z' mom.  Cn'|    Cna =  -0.004261    Cnb =   0.131662

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.004575    CLq =  10.383805    CLr =  -0.007557
 y  force CY |    CYp =   0.233046    CYq =  -0.023676    CYr =   0.208849
 x' mom.  Cl'|    Clp =  -0.427156    Clq =   0.016363    Clr =   0.357404
 y  mom.  Cm |    Cmp =   0.000336    Cmq = -19.165248    Cmr =   0.022208
 z' mom.  Cn'|    Cnp =  -0.131409    Cnq =   0.010279    Cnr =  -0.161329

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000046   CLd02 =   0.007757   CLd03 =   0.000028
 y  force CY |   CYd01 =   0.000105   CYd02 =  -0.000001   CYd03 =  -0.002767
 x' mom.  Cl'|   Cld01 =  -0.004190   Cld02 =   0.000009   Cld03 =  -0.000223
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.029561   Cmd03 =  -0.000116
 z' mom.  Cn'|   Cnd01 =  -0.000157   Cnd02 =   0.000001   Cnd03 =   0.001502
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.001031 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000013    ed02 =   0.000593    ed03 =   0.000621



 Neutral point  Xnp =   0.174819

 Clb Cnr / Clr Cnb  =   0.275413    (  > 1 if spirally stable )
