 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06068     Cltot =   0.00393     Cl'tot =   0.00350
  CYtot =   0.02097     Cmtot =  -0.24016
  CZtot =  -0.96004     Cntot =  -0.00820     Cn'tot =  -0.00840

  CLtot =   0.95555
  CDtot =   0.11085
  CDvis =   0.07000     CDind = 0.0408461
  CLff  =   0.96048     CDff  = 0.0425985    | Trefftz
  CYff  =   0.01532         e =    0.9653    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.814156    CLb =   0.144663
 y  force CY |    CYa =  -0.001857    CYb =  -0.298828
 x' mom.  Cl'|    Cla =   0.017919    Clb =  -0.049808
 y  mom.  Cm |    Cma =  -1.962217    Cmb =  -0.073020
 z' mom.  Cn'|    Cna =  -0.004293    Cnb =   0.119521

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010878    CLq =  10.511762    CLr =  -0.016639
 y  force CY |    CYp =   0.123267    CYq =  -0.047323    CYr =   0.243088
 x' mom.  Cl'|    Clp =  -0.454923    Clq =   0.029958    Clr =   0.248389
 y  mom.  Cm |    Cmp =  -0.004743    Cmq = -19.250541    Cmr =   0.044139
 z' mom.  Cn'|    Cnp =  -0.070987    Cnq =   0.024378    Cnr =  -0.145293

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000098   CLd02 =   0.007975   CLd03 =   0.000063
 y  force CY |   CYd01 =   0.000223   CYd02 =  -0.000001   CYd03 =  -0.002845
 x' mom.  Cl'|   Cld01 =  -0.004441   Cld02 =   0.000019   Cld03 =  -0.000246
 y  mom.  Cm |   Cmd01 =  -0.000061   Cmd02 =  -0.029986   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =   0.000002   Cnd03 =   0.001543
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000361 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000067    ed02 =   0.007859    ed03 =   0.003068



 Neutral point  Xnp =   0.172941

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
