 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10341     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.07034
  CZtot =  -0.52933     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.53261
  CDtot =   0.08487
  CDvis =   0.07000     CDind = 0.0148726
  CLff  =   0.53213     CDff  = 0.0151546    | Trefftz
  CYff  =   0.00000         e =    0.8327    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.957418    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.302695
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.027471
 y  mom.  Cm |    Cma =  -1.968688    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.117295

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.608728    CLr =   0.000000
 y  force CY |    CYp =   0.041726    CYq =   0.000000    CYr =   0.251659
 x' mom.  Cl'|    Clp =  -0.469986    Clq =  -0.000000    Clr =   0.166431
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.207508    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.029970    Cnq =  -0.000000    Cnr =  -0.135380

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.008008   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000310   CYd02 =   0.000000   CYd03 =  -0.002871
 x' mom.  Cl'|   Cld01 =  -0.004574   Cld02 =   0.000000   Cld03 =  -0.000259
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029967   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =   0.000119   Cnd02 =  -0.000000   Cnd03 =   0.001556
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000128 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.032074    ed03 =   0.000000



 Neutral point  Xnp =   0.169988

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
