 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10386     Cltot =  -0.00116     Cl'tot =  -0.00159
  CYtot =  -0.02108     Cmtot =  -0.03449
  CZtot =  -0.43850     Cntot =   0.00822     Cn'tot =   0.00815

  CLtot =   0.44334
  CDtot =   0.08077
  CDvis =   0.07000     CDind = 0.0107675
  CLff  =   0.44431     CDff  = 0.0120444    | Trefftz
  CYff  =  -0.01532         e =    0.7313    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.947383    CLb =  -0.075168
 y  force CY |    CYa =   0.000165    CYb =  -0.300336
 x' mom.  Cl'|    Cla =  -0.018420    Clb =  -0.022631
 y  mom.  Cm |    Cma =  -1.951309    Cmb =   0.044257
 z' mom.  Cn'|    Cna =   0.000474    Cnb =   0.115956

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012622    CLq =  10.593474    CLr =   0.017588
 y  force CY |    CYp =   0.025199    CYq =   0.047323    CYr =   0.250922
 x' mom.  Cl'|    Clp =  -0.470911    Clq =  -0.027245    Clr =   0.149180
 y  mom.  Cm |    Cmp =   0.009330    Cmq = -19.125215    Cmr =  -0.043402
 z' mom.  Cn'|    Cnp =  -0.021843    Cnq =  -0.027376    Cnr =  -0.133164

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000101   CLd02 =   0.007949   CLd03 =  -0.000069
 y  force CY |   CYd01 =   0.000326   CYd02 =   0.000001   CYd03 =  -0.002854
 x' mom.  Cl'|   Cld01 =  -0.004566   Cld02 =  -0.000018   Cld03 =  -0.000260
 y  mom.  Cm |   Cmd01 =   0.000063   Cmd02 =  -0.029734   Cmd03 =   0.000235
 z' mom.  Cn'|   Cnd01 =   0.000143   Cnd02 =  -0.000002   Cnd03 =   0.001547
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000225 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000180    ed02 =   0.039868    ed03 =  -0.008145



 Neutral point  Xnp =   0.169224

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
