 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07572     Cltot =   0.00058     Cl'tot =   0.00001
  CYtot =  -0.01054     Cmtot =   0.13242
  CZtot =  -0.00026     Cntot =   0.00409     Cn'tot =   0.00413

  CLtot =   0.01080
  CDtot =   0.07495
  CDvis =   0.07000     CDind = 0.0049473
  CLff  =   0.01023     CDff  = 0.0050561    | Trefftz
  CYff  =  -0.00766         e =    0.0014    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.978202    CLb =  -0.008165
 y  force CY |    CYa =  -0.000625    CYb =  -0.301484
 x' mom.  Cl'|    Cla =  -0.009134    Clb =   0.000180
 y  mom.  Cm |    Cma =  -1.883820    Cmb =   0.010444
 z' mom.  Cn'|    Cna =  -0.001369    Cnb =   0.118226

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007104    CLq =  10.646991    CLr =   0.009049
 y  force CY |    CYp =  -0.056418    CYq =   0.023676    CYr =   0.242175
 x' mom.  Cl'|    Clp =  -0.478366    Clq =  -0.012385    Clr =   0.063773
 y  mom.  Cm |    Cmp =   0.006543    Cmq = -18.895123    Cmr =  -0.021225
 z' mom.  Cn'|    Cnp =   0.017795    Cnq =  -0.014832    Cnr =  -0.124971

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000051   CLd02 =   0.007791   CLd03 =  -0.000036
 y  force CY |   CYd01 =   0.000411   CYd02 =   0.000001   CYd03 =  -0.002823
 x' mom.  Cl'|   Cld01 =  -0.004610   Cld02 =  -0.000009   Cld03 =  -0.000269
 y  mom.  Cm |   Cmd01 =   0.000032   Cmd02 =  -0.029136   Cmd03 =   0.000117
 z' mom.  Cn'|   Cnd01 =   0.000266   Cnd02 =  -0.000001   Cnd03 =   0.001530
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000707 CDffd03 =   0.000069
 span eff.   |    ed01 =  -0.000023    ed02 =   0.001627    ed03 =   0.000350



 Neutral point  Xnp =   0.164713

 Clb Cnr / Clr Cnb  =  -0.002990    (  > 1 if spirally stable )
