 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09388     Cltot =   0.00888     Cl'tot =   0.00699
  CYtot =   0.02575     Cmtot =  -0.47315
  CZtot =  -1.52909     Cntot =  -0.01007     Cn'tot =  -0.01146

  CLtot =   1.52216
  CDtot =   0.17307
  CDvis =   0.07000     CDind = 0.1030708
  CLff  =   1.54685     CDff  = 0.1073612    | Trefftz
  CYff  =   0.01914         e =    0.9933    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.494939    CLb =   0.276826
 y  force CY |    CYa =  -0.004747    CYb =  -0.292569
 x' mom.  Cl'|    Cla =   0.020398    Clb =  -0.079306
 y  mom.  Cm |    Cma =  -1.861610    Cmb =  -0.132127
 z' mom.  Cn'|    Cna =  -0.010607    Cnb =   0.129978

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011426    CLq =  10.350597    CLr =  -0.018871
 y  force CY |    CYp =   0.232300    CYq =  -0.059127    CYr =   0.208182
 x' mom.  Cl'|    Clp =  -0.425790    Clq =   0.040863    Clr =   0.356261
 y  mom.  Cm |    Cmp =   0.000840    Cmq = -19.103956    Cmr =   0.055460
 z' mom.  Cn'|    Cnp =  -0.130989    Cnq =   0.025670    Cnr =  -0.160813

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000116   CLd02 =   0.007708   CLd03 =   0.000069
 y  force CY |   CYd01 =   0.000105   CYd02 =  -0.000002   CYd03 =  -0.002750
 x' mom.  Cl'|   Cld01 =  -0.004163   Cld02 =   0.000023   Cld03 =  -0.000222
 y  mom.  Cm |   Cmd01 =  -0.000073   Cmd02 =  -0.029372   Cmd03 =  -0.000289
 z' mom.  Cn'|   Cnd01 =  -0.000156   Cnd02 =   0.000003   Cnd03 =   0.001492
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.001025 CDffd03 =  -0.000171
 span eff.   |    ed01 =  -0.000033    ed02 =   0.000632    ed03 =   0.001543



 Neutral point  Xnp =   0.174792

 Clb Cnr / Clr Cnb  =   0.275413    (  > 1 if spirally stable )
