 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07625     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.12713
  CZtot =  -0.00252     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   0.01311
  CDtot =   0.07516
  CDvis =   0.07000     CDind = 0.0051597
  CLff  =   0.01240     CDff  = 0.0050384    | Trefftz
  CYff  =  -0.00000         e =    0.0014    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.013220    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.301226
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.018632
 y  mom.  Cm |    Cma =  -0.679623    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.107374

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.225719    CLr =   0.000000
 y  force CY |    CYp =  -0.097672    CYq =   0.000000    CYr =   0.220861
 x' mom.  Cl'|    Clp =  -0.492381    Clq =   0.000000    Clr =   0.081854
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.020432    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.034079    Cnq =  -0.000000    Cnr =  -0.103840

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007735   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000455   CYd02 =   0.000000   CYd03 =  -0.002826
 x' mom.  Cl'|   Cld01 =  -0.004587   Cld02 =   0.000000   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027135   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000260   Cnd02 =  -0.000000   Cnd03 =   0.001434
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000712 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.001912    ed03 =   0.000000



 Neutral point  Xnp =   0.164730

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
