 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10335     Cltot =   0.00041     Cl'tot =   0.00048
  CYtot =   0.00528     Cmtot =  -0.07023
  CZtot =  -0.52914     Cntot =  -0.00206     Cn'tot =  -0.00205

  CLtot =   0.53242
  CDtot =   0.08482
  CDvis =   0.07000     CDind = 0.0148245
  CLff  =   0.53205     CDff  = 0.0151733    | Trefftz
  CYff  =   0.00383         e =    0.8314    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.955952    CLb =   0.021787
 y  force CY |    CYa =  -0.000112    CYb =  -0.302542
 x' mom.  Cl'|    Cla =   0.004612    Clb =  -0.027454
 y  mom.  Cm |    Cma =  -1.968089    Cmb =  -0.012295
 z' mom.  Cn'|    Cna =  -0.000280    Cnb =   0.117223

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003082    CLq =  10.607112    CLr =  -0.004367
 y  force CY |    CYp =   0.041720    CYq =  -0.011840    CYr =   0.251621
 x' mom.  Cl'|    Clp =  -0.469914    Clq =   0.006935    Clr =   0.166406
 y  mom.  Cm |    Cmp =  -0.002145    Cmq = -19.204583    Cmr =   0.010898
 z' mom.  Cn'|    Cnp =  -0.029965    Cnq =   0.006729    Cnr =  -0.135359

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.008006   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000310   CYd02 =  -0.000000   CYd03 =  -0.002870
 x' mom.  Cl'|   Cld01 =  -0.004573   Cld02 =   0.000005   Cld03 =  -0.000259
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.029958   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000119   Cnd02 =   0.000001   Cnd03 =   0.001556
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000128 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000041    ed02 =   0.032014    ed03 =   0.001853



 Neutral point  Xnp =   0.169987

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
