 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00820     Cltot =  -0.00133     Cl'tot =  -0.00111
  CYtot =  -0.00523     Cmtot =  -0.34515
  CZtot =  -1.21818     Cntot =   0.00205     Cn'tot =   0.00217

  CLtot =   1.21065
  CDtot =   0.13549
  CDvis =   0.07000     CDind = 0.0654858
  CLff  =   1.21774     CDff  = 0.0666623    | Trefftz
  CYff  =  -0.00383         e =    0.9913    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.722257    CLb =  -0.044737
 y  force CY |    CYa =   0.000676    CYb =  -0.299385
 x' mom.  Cl'|    Cla =  -0.004356    Clb =  -0.063548
 y  mom.  Cm |    Cma =  -1.944266    Cmb =   0.021893
 z' mom.  Cn'|    Cna =   0.001540    Cnb =   0.124550

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002524    CLq =  10.479128    CLr =   0.004011
 y  force CY |    CYp =   0.171542    CYq =   0.011840    CYr =   0.232063
 x' mom.  Cl'|    Clp =  -0.444906    Clq =  -0.007804    Clr =   0.296640
 y  mom.  Cm |    Cmp =   0.000607    Cmq = -19.278138    Cmr =  -0.011090
 z' mom.  Cn'|    Cnp =  -0.096599    Cnq =  -0.005698    Cnr =  -0.152273

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000024   CLd02 =   0.007941   CLd03 =  -0.000015
 y  force CY |   CYd01 =   0.000172   CYd02 =   0.000000   CYd03 =  -0.002831
 x' mom.  Cl'|   Cld01 =  -0.004362   Cld02 =  -0.000005   Cld03 =  -0.000238
 y  mom.  Cm |   Cmd01 =   0.000015   Cmd02 =  -0.030003   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =  -0.000070   Cnd02 =  -0.000001   Cnd03 =   0.001536
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000654 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000011    ed02 =   0.003256    ed03 =  -0.000503



 Neutral point  Xnp =   0.174106

 Clb Cnr / Clr Cnb  =   0.261908    (  > 1 if spirally stable )
