 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09396     Cltot =  -0.00534     Cl'tot =  -0.00421
  CYtot =  -0.01549     Cmtot =  -0.47684
  CZtot =  -1.53694     Cntot =   0.00606     Cn'tot =   0.00690

  CLtot =   1.52990
  CDtot =   0.17435
  CDvis =   0.07000     CDind = 0.1043534
  CLff  =   1.55063     CDff  = 0.1075110    | Trefftz
  CYff  =  -0.01149         e =    0.9967    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.516160    CLb =  -0.166637
 y  force CY |    CYa =   0.002857    CYb =  -0.294938
 x' mom.  Cl'|    Cla =  -0.012278    Clb =  -0.080088
 y  mom.  Cm |    Cma =  -1.870721    Cmb =   0.079535
 z' mom.  Cn'|    Cna =   0.006385    Cnb =   0.131261

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006861    CLq =  10.375895    CLr =   0.011332
 y  force CY |    CYp =   0.232868    CYq =   0.035505    CYr =   0.208690
 x' mom.  Cl'|    Clp =  -0.426831    Clq =  -0.024538    Clr =   0.357132
 y  mom.  Cm |    Cmp =  -0.000504    Cmq = -19.150649    Cmr =  -0.033303
 z' mom.  Cn'|    Cnp =  -0.131309    Cnq =  -0.015414    Cnr =  -0.161206

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000070   CLd02 =   0.007746   CLd03 =  -0.000042
 y  force CY |   CYd01 =   0.000105   CYd02 =   0.000001   CYd03 =  -0.002763
 x' mom.  Cl'|   Cld01 =  -0.004184   Cld02 =  -0.000014   Cld03 =  -0.000223
 y  mom.  Cm |   Cmd01 =   0.000044   Cmd02 =  -0.029516   Cmd03 =   0.000174
 z' mom.  Cn'|   Cnd01 =  -0.000157   Cnd02 =  -0.000002   Cnd03 =   0.001500
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.001030 CDffd03 =   0.000103
 span eff.   |    ed01 =   0.000020    ed02 =   0.000602    ed03 =  -0.000931



 Neutral point  Xnp =   0.174812

 Clb Cnr / Clr Cnb  =   0.275413    (  > 1 if spirally stable )
