 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09885     Cltot =  -0.00209     Cl'tot =  -0.00223
  CYtot =  -0.02107     Cmtot =  -0.10287
  CZtot =  -0.61392     Cntot =   0.00822     Cn'tot =   0.00819

  CLtot =   0.61555
  CDtot =   0.08812
  CDvis =   0.07000     CDind = 0.0181235
  CLff  =   0.61719     CDff  = 0.0195446    | Trefftz
  CYff  =  -0.01532         e =    0.8691    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.917036    CLb =  -0.098554
 y  force CY |    CYa =   0.000730    CYb =  -0.300114
 x' mom.  Cl'|    Cla =  -0.018342    Clb =  -0.031766
 y  mom.  Cm |    Cma =  -1.964522    Cmb =   0.053819
 z' mom.  Cn'|    Cna =   0.001758    Cnb =   0.116510

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012019    CLq =  10.571064    CLr =   0.017312
 y  force CY |    CYp =   0.058044    CYq =   0.047323    CYr =   0.250597
 x' mom.  Cl'|    Clp =  -0.466527    Clq =  -0.028184    Clr =   0.182761
 y  mom.  Cm |    Cmp =   0.007810    Cmq = -19.190388    Cmr =  -0.043701
 z' mom.  Cn'|    Cnp =  -0.038002    Cnq =  -0.026408    Cnr =  -0.136996

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000100   CLd02 =   0.007982   CLd03 =  -0.000067
 y  force CY |   CYd01 =   0.000292   CYd02 =   0.000001   CYd03 =  -0.002858
 x' mom.  Cl'|   Cld01 =  -0.004535   Cld02 =  -0.000019   Cld03 =  -0.000256
 y  mom.  Cm |   Cmd01 =   0.000062   Cmd02 =  -0.029891   Cmd03 =   0.000235
 z' mom.  Cn'|   Cnd01 =   0.000094   Cnd02 =  -0.000002   Cnd03 =   0.001549
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000030 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000133    ed02 =   0.023800    ed03 =  -0.006009



 Neutral point  Xnp =   0.170669

 Clb Cnr / Clr Cnb  =   0.204371    (  > 1 if spirally stable )
