 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04778     Cltot =  -0.00052     Cl'tot =   0.00047
  CYtot =   0.01572     Cmtot =   0.14973
  CZtot =   0.17235     Cntot =  -0.00567     Cn'tot =  -0.00567

  CLtot =  -0.16144
  CDtot =   0.07698
  CDvis =   0.07000     CDind = 0.0069829
  CLff  =  -0.16265     CDff  = 0.0072912    | Trefftz
  CYff  =   0.01146         e =    0.1625    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.980223    CLb =  -0.005394
 y  force CY |    CYa =   0.001042    CYb =  -0.299311
 x' mom.  Cl'|    Cla =   0.014230    Clb =  -0.009032
 y  mom.  Cm |    Cma =  -0.609799    Cmb =  -0.001979
 z' mom.  Cn'|    Cna =   0.002269    Cnb =   0.107962

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013307    CLq =   8.263737    CLr =  -0.012494
 y  force CY |    CYp =  -0.128802    CYq =  -0.050136    CYr =   0.211751
 x' mom.  Cl'|    Clp =  -0.493752    Clq =   0.001296    Clr =   0.046668
 y  mom.  Cm |    Cmp =  -0.009671    Cmq = -15.828195    Cmr =   0.017443
 z' mom.  Cn'|    Cnp =   0.047615    Cnq =   0.025981    Cnr =  -0.099876

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000074   CLd02 =   0.007598   CLd03 =   0.000055
 y  force CY |   CYd01 =   0.000486   CYd02 =  -0.000001   CYd03 =  -0.002792
 x' mom.  Cl'|   Cld01 =  -0.004565   Cld02 =   0.000013   Cld03 =  -0.000515
 y  mom.  Cm |   Cmd01 =  -0.000030   Cmd02 =  -0.026632   Cmd03 =  -0.000138
 z' mom.  Cn'|   Cnd01 =   0.000309   Cnd02 =   0.000002   Cnd03 =   0.001416
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000889 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000047    ed02 =   0.004354    ed03 =   0.001945



 Neutral point  Xnp =   0.161029

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
