 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10474     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =  -0.03604
  CZtot =  -0.44109     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.44597
  CDtot =   0.08151
  CDvis =   0.07000     CDind = 0.0115117
  CLff  =   0.44540     CDff  = 0.0117280    | Trefftz
  CYff  =   0.00000         e =    0.7538    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.970883    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.302772
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.022854
 y  mom.  Cm |    Cma =  -1.960850    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.117095

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.619343    CLr =   0.000000
 y  force CY |    CYp =   0.025260    CYq =   0.000000    CYr =   0.251535
 x' mom.  Cl'|    Clp =  -0.472061    Clq =  -0.000000    Clr =   0.149544
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.171917    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.021896    Cnq =  -0.000000    Cnr =  -0.133489

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007988   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000328   CYd02 =   0.000000   CYd03 =  -0.002868
 x' mom.  Cl'|   Cld01 =  -0.004588   Cld02 =   0.000000   Cld03 =  -0.000261
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029879   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =   0.000143   Cnd02 =  -0.000000   Cnd03 =   0.001554
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000226 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.041578    ed03 =   0.000000



 Neutral point  Xnp =   0.169240

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
