 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06292     Cltot =   0.00081     Cl'tot =   0.00017
  CYtot =  -0.01053     Cmtot =   0.16511
  CZtot =   0.08693     Cntot =   0.00408     Cn'tot =   0.00416

  CLtot =  -0.07602
  CDtot =   0.07574
  CDvis =   0.07000     CDind = 0.0057449
  CLff  =  -0.07686     CDff  = 0.0057895    | Trefftz
  CYff  =  -0.00766         e =    0.0459    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.970055    CLb =  -0.002262
 y  force CY |    CYa =  -0.000767    CYb =  -0.301137
 x' mom.  Cl'|    Cla =  -0.009080    Clb =   0.004727
 y  mom.  Cm |    Cma =  -1.861919    Cmb =   0.008161
 z' mom.  Cn'|    Cna =  -0.001687    Cnb =   0.118989

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007267    CLq =  10.649972    CLr =   0.009082
 y  force CY |    CYp =  -0.072488    CYq =   0.023676    CYr =   0.238632
 x' mom.  Cl'|    Clp =  -0.478912    Clq =  -0.012125    Clr =   0.046454
 y  mom.  Cm |    Cmp =   0.006912    Cmq = -18.824759    Cmr =  -0.021107
 z' mom.  Cn'|    Cnp =   0.025621    Cnq =  -0.015046    Cnr =  -0.123505

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000051   CLd02 =   0.007735   CLd03 =  -0.000037
 y  force CY |   CYd01 =   0.000428   CYd02 =   0.000001   CYd03 =  -0.002810
 x' mom.  Cl'|   Cld01 =  -0.004607   Cld02 =  -0.000009   Cld03 =  -0.000270
 y  mom.  Cm |   Cmd01 =   0.000032   Cmd02 =  -0.028943   Cmd03 =   0.000117
 z' mom.  Cn'|   Cnd01 =   0.000291   Cnd02 =  -0.000001   Cnd03 =   0.001522
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000801 CDffd03 =   0.000069
 span eff.   |    ed01 =  -0.000007    ed02 =  -0.002970    ed03 =  -0.000225



 Neutral point  Xnp =   0.163645

 Clb Cnr / Clr Cnb  =  -0.105614    (  > 1 if spirally stable )
