 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10469     Cltot =   0.00029     Cl'tot =   0.00040
  CYtot =   0.00528     Cmtot =  -0.03594
  CZtot =  -0.44093     Cntot =  -0.00206     Cn'tot =  -0.00204

  CLtot =   0.44580
  CDtot =   0.08147
  CDvis =   0.07000     CDind = 0.0114651
  CLff  =   0.44533     CDff  = 0.0117478    | Trefftz
  CYff  =   0.00383         e =    0.7523    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.969412    CLb =   0.018849
 y  force CY |    CYa =  -0.000041    CYb =  -0.302619
 x' mom.  Cl'|    Cla =   0.004619    Clb =  -0.022840
 y  mom.  Cm |    Cma =  -1.960253    Cmb =  -0.011098
 z' mom.  Cn'|    Cna =  -0.000119    Cnb =   0.117024

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003158    CLq =  10.617725    CLr =  -0.004400
 y  force CY |    CYp =   0.025256    CYq =  -0.011840    CYr =   0.251497
 x' mom.  Cl'|    Clp =  -0.471989    Clq =   0.006817    Clr =   0.149521
 y  mom.  Cm |    Cmp =  -0.002334    Cmq = -19.168997    Cmr =   0.010859
 z' mom.  Cn'|    Cnp =  -0.021893    Cnq =   0.006849    Cnr =  -0.133469

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007986   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000328   CYd02 =  -0.000000   CYd03 =  -0.002867
 x' mom.  Cl'|   Cld01 =  -0.004587   Cld02 =   0.000005   Cld03 =  -0.000261
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.029870   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000143   Cnd02 =   0.000001   Cnd03 =   0.001554
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000226 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000048    ed02 =   0.041467    ed03 =   0.002157



 Neutral point  Xnp =   0.169239

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
