 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12496     Cltot =  -0.00190     Cl'tot =  -0.00148
  CYtot =  -0.00515     Cmtot =  -0.51123
  CZtot =  -1.61819     Cntot =   0.00202     Cn'tot =   0.00234

  CLtot =   1.61230
  CDtot =   0.18611
  CDvis =   0.07000     CDind = 0.1161056
  CLff  =   1.63510     CDff  = 0.1192775    | Trefftz
  CYff  =  -0.00383         e =    0.9989    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.470533    CLb =  -0.058280
 y  force CY |    CYa =   0.001023    CYb =  -0.295137
 x' mom.  Cl'|    Cla =  -0.004023    Clb =  -0.084540
 y  mom.  Cm |    Cma =  -1.852271    Cmb =   0.027690
 z' mom.  Cn'|    Cna =   0.002273    Cnb =   0.134105

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002234    CLq =  10.363413    CLr =   0.003716
 y  force CY |    CYp =   0.248004    CYq =   0.011840    CYr =   0.201840
 x' mom.  Cl'|    Clp =  -0.422505    Clq =  -0.008271    Clr =   0.372275
 y  mom.  Cm |    Cmp =  -0.000362    Cmq = -19.133351    Cmr =  -0.011101
 z' mom.  Cn'|    Cnp =  -0.140358    Cnq =  -0.004997    Cnr =  -0.163693

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000023   CLd02 =   0.007706   CLd03 =  -0.000014
 y  force CY |   CYd01 =   0.000089   CYd02 =   0.000000   CYd03 =  -0.002751
 x' mom.  Cl'|   Cld01 =  -0.004146   Cld02 =  -0.000005   Cld03 =  -0.000220
 y  mom.  Cm |   Cmd01 =   0.000015   Cmd02 =  -0.029440   Cmd03 =   0.000058
 z' mom.  Cn'|   Cnd01 =  -0.000178   Cnd02 =  -0.000001   Cnd03 =   0.001493
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.001124 CDffd03 =   0.000034
 span eff.   |    ed01 =   0.000006    ed02 =   0.000215    ed03 =  -0.000280



 Neutral point  Xnp =   0.174841

 Clb Cnr / Clr Cnb  =   0.277193    (  > 1 if spirally stable )
