 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04761     Cltot =  -0.00157     Cl'tot =  -0.00048
  CYtot =   0.01575     Cmtot =   0.19753
  CZtot =   0.17349     Cntot =  -0.00610     Cn'tot =  -0.00628

  CLtot =  -0.16259
  CDtot =   0.07701
  CDvis =   0.07000     CDind = 0.0070146
  CLff  =  -0.16380     CDff  = 0.0073233    | Trefftz
  CYff  =   0.01149         e =    0.1641    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.950997    CLb =  -0.005442
 y  force CY |    CYa =   0.001360    CYb =  -0.299962
 x' mom.  Cl'|    Cla =   0.013510    Clb =   0.009216
 y  mom.  Cm |    Cma =  -1.834951    Cmb =  -0.008849
 z' mom.  Cn'|    Cna =   0.003001    Cnb =   0.119544

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011143    CLq =  10.643545    CLr =  -0.013661
 y  force CY |    CYp =  -0.088357    CYq =  -0.035505    CYr =   0.234352
 x' mom.  Cl'|    Clp =  -0.478830    Clq =   0.017786    Clr =   0.029079
 y  mom.  Cm |    Cmp =  -0.010917    Cmq = -18.734380    Cmr =   0.031467
 z' mom.  Cn'|    Cnp =   0.033393    Cnq =   0.022877    Cnr =  -0.122024

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007663   CLd03 =   0.000055
 y  force CY |   CYd01 =   0.000443   CYd02 =  -0.000001   CYd03 =  -0.002791
 x' mom.  Cl'|   Cld01 =  -0.004594   Cld02 =   0.000014   Cld03 =  -0.000270
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.028688   Cmd03 =  -0.000174
 z' mom.  Cn'|   Cnd01 =   0.000315   Cnd02 =   0.000002   Cnd03 =   0.001512
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000892 CDffd03 =  -0.000103
 span eff.   |    ed01 =  -0.000032    ed02 =   0.004347    ed03 =   0.001931



 Neutral point  Xnp =   0.162516

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
