 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09392     Cltot =   0.00711     Cl'tot =   0.00560
  CYtot =   0.02063     Cmtot =  -0.47523
  CZtot =  -1.53350     Cntot =  -0.00807     Cn'tot =  -0.00918

  CLtot =   1.52651
  CDtot =   0.17379
  CDvis =   0.07000     CDind = 0.1037917
  CLff  =   1.54897     CDff  = 0.1074454    | Trefftz
  CYff  =   0.01532         e =    0.9952    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.506867    CLb =   0.221866
 y  force CY |    CYa =  -0.003804    CYb =  -0.293900
 x' mom.  Cl'|    Cla =   0.016348    Clb =  -0.079745
 y  mom.  Cm |    Cma =  -1.866731    Cmb =  -0.105895
 z' mom.  Cn'|    Cna =  -0.008501    Cnb =   0.130699

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009145    CLq =  10.364825    CLr =  -0.015104
 y  force CY |    CYp =   0.232620    CYq =  -0.047323    CYr =   0.208468
 x' mom.  Cl'|    Clp =  -0.426375    Clq =   0.032705    Clr =   0.356751
 y  mom.  Cm |    Cmp =   0.000672    Cmq = -19.130216    Cmr =   0.044388
 z' mom.  Cn'|    Cnp =  -0.131169    Cnq =   0.020545    Cnr =  -0.161034

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000093   CLd02 =   0.007729   CLd03 =   0.000055
 y  force CY |   CYd01 =   0.000105   CYd02 =  -0.000001   CYd03 =  -0.002757
 x' mom.  Cl'|   Cld01 =  -0.004175   Cld02 =   0.000018   Cld03 =  -0.000222
 y  mom.  Cm |   Cmd01 =  -0.000058   Cmd02 =  -0.029453   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =  -0.000157   Cnd02 =   0.000002   Cnd03 =   0.001497
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.001028 CDffd03 =  -0.000137
 span eff.   |    ed01 =  -0.000026    ed02 =   0.000615    ed03 =   0.001238



 Neutral point  Xnp =   0.174804

 Clb Cnr / Clr Cnb  =   0.275413    (  > 1 if spirally stable )
