 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15803     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.54359
  CZtot =  -1.69452     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.69035
  CDtot =   0.19774
  CDvis =   0.07000     CDind = 0.1277384
  CLff  =   1.71744     CDff  = 0.1315423    | Trefftz
  CYff  =   0.00000         e =    0.9992    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.412791    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.294227
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.088574
 y  mom.  Cm |    Cma =  -1.827555    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.136531

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.338910    CLr =  -0.000000
 y  force CY |    CYp =   0.262638    CYq =  -0.000000    CYr =   0.194250
 x' mom.  Cl'|    Clp =  -0.417553    Clq =  -0.000000    Clr =   0.386816
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.089773    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.149337    Cnq =   0.000000    Cnr =  -0.165999

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007644   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000073   CYd02 =   0.000000   CYd03 =  -0.002731
 x' mom.  Cl'|   Cld01 =  -0.004097   Cld02 =   0.000000   Cld03 =  -0.000216
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029283   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000199   Cnd02 =  -0.000000   Cnd03 =   0.001482
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.001215 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =  -0.000089    ed03 =   0.000000



 Neutral point  Xnp =   0.174790

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
