 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04534     Cltot =   0.00439     Cl'tot =   0.00381
  CYtot =   0.02094     Cmtot =  -0.27435
  CZtot =  -1.04499     Cntot =  -0.00819     Cn'tot =  -0.00848

  CLtot =   1.03928
  CDtot =   0.11812
  CDvis =   0.07000     CDind = 0.0481246
  CLff  =   1.04563     CDff  = 0.0500000    | Trefftz
  CYff  =   0.01532         e =    0.9747    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.779875    CLb =   0.156004
 y  force CY |    CYa =  -0.002138    CYb =  -0.298332
 x' mom.  Cl'|    Cla =   0.017758    Clb =  -0.054239
 y  mom.  Cm |    Cma =  -1.955656    Cmb =  -0.077802
 z' mom.  Cn'|    Cna =  -0.004916    Cnb =   0.120665

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010608    CLq =  10.494023    CLr =  -0.016446
 y  force CY |    CYp =   0.139360    CYq =  -0.047323    CYr =   0.239794
 x' mom.  Cl'|    Clp =  -0.451458    Clq =   0.030379    Clr =   0.264419
 y  mom.  Cm |    Cmp =  -0.003971    Cmq = -19.250927    Cmr =   0.044216
 z' mom.  Cn'|    Cnp =  -0.079386    Cnq =   0.023851    Cnr =  -0.147473

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000098   CLd02 =   0.007958   CLd03 =   0.000062
 y  force CY |   CYd01 =   0.000206   CYd02 =  -0.000001   CYd03 =  -0.002838
 x' mom.  Cl'|   Cld01 =  -0.004410   Cld02 =   0.000019   Cld03 =  -0.000243
 y  mom.  Cm |   Cmd01 =  -0.000061   Cmd02 =  -0.029964   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =  -0.000024   Cnd02 =   0.000002   Cnd03 =   0.001539
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000458 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000057    ed02 =   0.005933    ed03 =   0.002637



 Neutral point  Xnp =   0.173379

 Clb Cnr / Clr Cnb  =   0.250698    (  > 1 if spirally stable )
