 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06143     Cltot =  -0.00134     Cl'tot =  -0.00124
  CYtot =  -0.00522     Cmtot =  -0.03481
  CZtot =  -0.97244     Cntot =   0.00190     Cn'tot =   0.00197

  CLtot =   0.96789
  CDtot =   0.11224
  CDvis =   0.07000     CDind = 0.0422406
  CLff  =   0.97029     CDff  = 0.0430043    | Trefftz
  CYff  =  -0.00382         e =    0.9756    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.862784    CLb =  -0.036525
 y  force CY |    CYa =   0.000566    CYb =  -0.299093
 x' mom.  Cl'|    Cla =  -0.004602    Clb =  -0.070915
 y  mom.  Cm |    Cma =  -0.986919    Cmb =   0.007101
 z' mom.  Cn'|    Cna =   0.001402    Cnb =   0.112750

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003295    CLq =   7.814270    CLr =   0.004011
 y  force CY |    CYp =   0.079940    CYq =   0.016719    CYr =   0.229304
 x' mom.  Cl'|    Clp =  -0.461542    Clq =  -0.002370    Clr =   0.267402
 y  mom.  Cm |    Cmp =   0.001834    Cmq = -16.602481    Cmr =  -0.006393
 z' mom.  Cn'|    Cnp =  -0.045676    Cnq =  -0.008344    Cnr =  -0.131372

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000024   CLd02 =   0.007956   CLd03 =  -0.000016
 y  force CY |   CYd01 =   0.000266   CYd02 =   0.000000   CYd03 =  -0.002848
 x' mom.  Cl'|   Cld01 =  -0.004435   Cld02 =  -0.000005   Cld03 =  -0.000496
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.028322   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =  -0.000001   Cnd03 =   0.001447
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000320 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000024    ed02 =   0.008688    ed03 =  -0.000780



 Neutral point  Xnp =   0.183733

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
