 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08601     Cltot =  -0.00071     Cl'tot =  -0.00163
  CYtot =  -0.02099     Cmtot =   0.11524
  CZtot =  -0.08985     Cntot =   0.00759     Cn'tot =   0.00745

  CLtot =   0.09966
  CDtot =   0.07442
  CDvis =   0.07000     CDind = 0.0044162
  CLff  =   0.09980     CDff  = 0.0054096    | Trefftz
  CYff  =  -0.01527         e =    0.0840    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.993907    CLb =  -0.028361
 y  force CY |    CYa =  -0.000545    CYb =  -0.298975
 x' mom.  Cl'|    Cla =  -0.019159    Clb =  -0.023203
 y  mom.  Cm |    Cma =  -0.709009    Cmb =   0.007463
 z' mom.  Cn'|    Cna =  -0.001024    Cnb =   0.105992

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.016665    CLq =   8.177965    CLr =   0.016695
 y  force CY |    CYp =  -0.081608    CYq =   0.066824    CYr =   0.223899
 x' mom.  Cl'|    Clp =  -0.489733    Clq =  -0.003537    Clr =   0.099073
 y  mom.  Cm |    Cmp =   0.011656    Cmq = -16.059168    Cmr =  -0.023892
 z' mom.  Cn'|    Cnp =   0.027131    Cnq =  -0.034491    Cnr =  -0.105652

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000099   CLd02 =   0.007747   CLd03 =  -0.000072
 y  force CY |   CYd01 =   0.000436   CYd02 =   0.000001   CYd03 =  -0.002823
 x' mom.  Cl'|   Cld01 =  -0.004565   Cld02 =  -0.000018   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =   0.000039   Cmd02 =  -0.027194   Cmd03 =   0.000185
 z' mom.  Cn'|   Cnd01 =   0.000233   Cnd02 =  -0.000002   Cnd03 =   0.001433
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000618 CDffd03 =   0.000140
 span eff.   |    ed01 =   0.000017    ed02 =   0.022480    ed03 =  -0.001485



 Neutral point  Xnp =   0.166537

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
