 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09447     Cltot =   0.00006     Cl'tot =  -0.00016
  CYtot =  -0.00528     Cmtot =   0.06580
  CZtot =  -0.17606     Cntot =   0.00205     Cn'tot =   0.00205

  CLtot =   0.18497
  CDtot =   0.07555
  CDvis =   0.07000     CDind = 0.0055460
  CLff  =   0.18447     CDff  = 0.0056103    | Trefftz
  CYff  =  -0.00383         e =    0.2704    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.988170    CLb =  -0.009998
 y  force CY |    CYa =  -0.000171    CYb =  -0.302424
 x' mom.  Cl'|    Cla =  -0.004606    Clb =  -0.008995
 y  mom.  Cm |    Cma =  -1.922469    Cmb =   0.007546
 z' mom.  Cn'|    Cna =  -0.000365    Cnb =   0.117393

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003392    CLq =  10.642029    CLr =   0.004483
 y  force CY |    CYp =  -0.023967    CYq =   0.011840    CYr =   0.247681
 x' mom.  Cl'|    Clp =  -0.476713    Clq =  -0.006449    Clr =   0.098305
 y  mom.  Cm |    Cmp =   0.002899    Cmq = -19.027257    Cmr =  -0.010722
 z' mom.  Cn'|    Cnp =   0.002044    Cnq =  -0.007197    Cnr =  -0.128190

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007891   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000378   CYd02 =   0.000000   CYd03 =  -0.002847
 x' mom.  Cl'|   Cld01 =  -0.004612   Cld02 =  -0.000005   Cld03 =  -0.000266
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.029499   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =   0.000217   Cnd02 =  -0.000001   Cnd03 =   0.001543
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000517 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000030    ed02 =   0.048213    ed03 =  -0.001509



 Neutral point  Xnp =   0.166684

 Clb Cnr / Clr Cnb  =   0.099917    (  > 1 if spirally stable )
