 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15936     Cltot =   0.00704     Cl'tot =   0.00574
  CYtot =   0.01523     Cmtot =  -0.20178
  CZtot =  -1.70129     Cntot =  -0.00554     Cn'tot =  -0.00688

  CLtot =   1.69725
  CDtot =   0.19784
  CDvis =   0.07000     CDind = 0.1278431
  CLff  =   1.72695     CDff  = 0.1322051    | Trefftz
  CYff  =   0.01146         e =    1.0053    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.426059    CLb =   0.183558
 y  force CY |    CYa =  -0.003550    CYb =  -0.290034
 x' mom.  Cl'|    Cla =   0.011813    Clb =  -0.109143
 y  mom.  Cm |    Cma =  -1.130238    Cmb =  -0.038822
 z' mom.  Cn'|    Cna =  -0.008253    Cnb =   0.130964

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.007792    CLq =   7.327446    CLr =  -0.010836
 y  force CY |    CYp =   0.218871    CYq =  -0.050136    CYr =   0.185809
 x' mom.  Cl'|    Clp =  -0.415089    Clq =   0.010934    Clr =   0.402192
 y  mom.  Cm |    Cmp =  -0.002433    Cmq = -16.606929    Cmr =   0.019796
 z' mom.  Cn'|    Cnp =  -0.119194    Cnq =   0.023603    Cnr =  -0.158257

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000067   CLd02 =   0.007585   CLd03 =   0.000040
 y  force CY |   CYd01 =   0.000111   CYd02 =  -0.000001   CYd03 =  -0.002707
 x' mom.  Cl'|   Cld01 =  -0.004064   Cld02 =   0.000013   Cld03 =  -0.000451
 y  mom.  Cm |   Cmd01 =  -0.000027   Cmd02 =  -0.027692   Cmd03 =  -0.000137
 z' mom.  Cn'|   Cnd01 =  -0.000214   Cnd02 =   0.000002   Cnd03 =   0.001377
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.001141 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000022    ed02 =   0.000384    ed03 =   0.000768



 Neutral point  Xnp =   0.198511

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
