 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09451     Cltot =  -0.00088     Cl'tot =  -0.00148
  CYtot =  -0.01576     Cmtot =   0.10245
  CZtot =  -0.17855     Cntot =   0.00571     Cn'tot =   0.00558

  CLtot =   0.18745
  CDtot =   0.07533
  CDvis =   0.07000     CDind = 0.0053292
  CLff  =   0.18741     CDff  = 0.0059599    | Trefftz
  CYff  =  -0.01146         e =    0.2636    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.005138    CLb =  -0.030211
 y  force CY |    CYa =  -0.000198    CYb =  -0.300135
 x' mom.  Cl'|    Cla =  -0.014408    Clb =  -0.028086
 y  mom.  Cm |    Cma =  -0.742422    Cmb =   0.006934
 z' mom.  Cn'|    Cna =  -0.000267    Cnb =   0.106275

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012235    CLq =   8.156930    CLr =   0.012517
 y  force CY |    CYp =  -0.065737    CYq =   0.050136    CYr =   0.227163
 x' mom.  Cl'|    Clp =  -0.488523    Clq =  -0.003105    Clr =   0.116534
 y  mom.  Cm |    Cmp =   0.008431    Cmq = -16.149267    Cmr =  -0.018075
 z' mom.  Cn'|    Cnp =   0.020226    Cnq =  -0.025827    Cnr =  -0.107931

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000075   CLd02 =   0.007807   CLd03 =  -0.000053
 y  force CY |   CYd01 =   0.000421   CYd02 =   0.000001   CYd03 =  -0.002838
 x' mom.  Cl'|   Cld01 =  -0.004572   Cld02 =  -0.000013   Cld03 =  -0.000515
 y  mom.  Cm |   Cmd01 =   0.000030   Cmd02 =  -0.027427   Cmd03 =   0.000139
 z' mom.  Cn'|   Cnd01 =   0.000209   Cnd02 =  -0.000002   Cnd03 =   0.001441
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000527 CDffd03 =   0.000105
 span eff.   |    ed01 =   0.000116    ed02 =   0.045355    ed03 =  -0.004191



 Neutral point  Xnp =   0.168330

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
