 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04534     Cltot =   0.00580     Cl'tot =   0.00526
  CYtot =   0.02079     Cmtot =  -0.05121
  CZtot =  -1.05305     Cntot =  -0.00757     Cn'tot =  -0.00795

  CLtot =   1.04732
  CDtot =   0.11869
  CDvis =   0.07000     CDind = 0.0486878
  CLff  =   1.05372     CDff  = 0.0506029    | Trefftz
  CYff  =   0.01527         e =    0.9780    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.806775    CLb =   0.157063
 y  force CY |    CYa =  -0.002537    CYb =  -0.296246
 x' mom.  Cl'|    Cla =   0.018147    Clb =  -0.074801
 y  mom.  Cm |    Cma =  -1.003670    Cmb =  -0.030742
 z' mom.  Cn'|    Cna =  -0.006227    Cnb =   0.113188

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012837    CLq =   7.748854    CLr =  -0.015900
 y  force CY |    CYp =   0.095771    CYq =  -0.066824    CYr =   0.226167
 x' mom.  Cl'|    Clp =  -0.456205    Clq =   0.010054    Clr =   0.282673
 y  mom.  Cm |    Cmp =  -0.006883    Cmq = -16.587540    Cmr =   0.025677
 z' mom.  Cn'|    Cnp =  -0.053328    Cnq =   0.033182    Cnr =  -0.133977

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000096   CLd02 =   0.007904   CLd03 =   0.000062
 y  force CY |   CYd01 =   0.000247   CYd02 =  -0.000001   CYd03 =  -0.002827
 x' mom.  Cl'|   Cld01 =  -0.004385   Cld02 =   0.000018   Cld03 =  -0.000490
 y  mom.  Cm |   Cmd01 =  -0.000038   Cmd02 =  -0.028199   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =   0.000002   Cnd03 =   0.001437
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000412 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000079    ed02 =   0.006704    ed03 =   0.002647



 Neutral point  Xnp =   0.185382

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
