 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03869     Cltot =   0.00621     Cl'tot =   0.00502
  CYtot =   0.02075     Cmtot =  -0.40936
  CZtot =  -1.37535     Cntot =  -0.00812     Cn'tot =  -0.00891

  CLtot =   1.36735
  CDtot =   0.15310
  CDvis =   0.07000     CDind = 0.0831020
  CLff  =   1.38281     CDff  = 0.0858879    | Trefftz
  CYff  =   0.01532         e =    0.9923    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.610207    CLb =   0.200379
 y  force CY |    CYa =  -0.003252    CYb =  -0.295653
 x' mom.  Cl'|    Cla =   0.016901    Clb =  -0.071484
 y  mom.  Cm |    Cma =  -1.905705    Cmb =  -0.096683
 z' mom.  Cn'|    Cna =  -0.007340    Cnb =   0.126763

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009601    CLq =  10.412058    CLr =  -0.015585
 y  force CY |    CYp =   0.202288    CYq =  -0.047323    CYr =   0.221073
 x' mom.  Cl'|    Clp =  -0.435512    Clq =   0.031968    Clr =   0.326761
 y  mom.  Cm |    Cmp =  -0.000877    Cmq = -19.193854    Cmr =   0.044385
 z' mom.  Cn'|    Cnp =  -0.113637    Cnq =   0.021674    Cnr =  -0.156461

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000095   CLd02 =   0.007829   CLd03 =   0.000058
 y  force CY |   CYd01 =   0.000138   CYd02 =  -0.000001   CYd03 =  -0.002791
 x' mom.  Cl'|   Cld01 =  -0.004263   Cld02 =   0.000018   Cld03 =  -0.000230
 y  mom.  Cm |   Cmd01 =  -0.000059   Cmd02 =  -0.029695   Cmd03 =  -0.000233
 z' mom.  Cn'|   Cnd01 =  -0.000114   Cnd02 =   0.000002   Cnd03 =   0.001514
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000841 CDffd03 =  -0.000138
 span eff.   |    ed01 =  -0.000033    ed02 =   0.001655    ed03 =   0.001552



 Neutral point  Xnp =   0.174569

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
