 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08444     Cltot =   0.00301     Cl'tot =   0.00287
  CYtot =   0.02103     Cmtot =  -0.17153
  CZtot =  -0.78804     Cntot =  -0.00822     Cn'tot =  -0.00827

  CLtot =   0.78645
  CDtot =   0.09818
  CDvis =   0.07000     CDind = 0.0281781
  CLff  =   0.78931     CDff  = 0.0297459    | Trefftz
  CYff  =   0.01532         e =    0.9337    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.872535    CLb =   0.121741
 y  force CY |    CYa =  -0.001294    CYb =  -0.299611
 x' mom.  Cl'|    Cla =   0.018175    Clb =  -0.040839
 y  mom.  Cm |    Cma =  -1.968164    Cmb =  -0.063423
 z' mom.  Cn'|    Cna =  -0.003033    Cnb =   0.117701

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011437    CLq =  10.543783    CLr =  -0.016996
 y  force CY |    CYp =   0.090787    CYq =  -0.047323    CYr =   0.247981
 x' mom.  Cl'|    Clp =  -0.461186    Clq =   0.029089    Clr =   0.215857
 y  mom.  Cm |    Cmp =  -0.006280    Cmq = -19.232180    Cmr =   0.043947
 z' mom.  Cn'|    Cnp =  -0.054377    Cnq =   0.025409    Cnr =  -0.141051

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007991   CLd03 =   0.000065
 y  force CY |   CYd01 =   0.000257   CYd02 =  -0.000001   CYd03 =  -0.002855
 x' mom.  Cl'|   Cld01 =  -0.004493   Cld02 =   0.000019   Cld03 =  -0.000251
 y  mom.  Cm |   Cmd01 =  -0.000062   Cmd02 =  -0.029975   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =   0.000046   Cnd02 =   0.000002   Cnd03 =   0.001548
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000166 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000094    ed02 =   0.013687    ed03 =   0.004251



 Neutral point  Xnp =   0.171908

 Clb Cnr / Clr Cnb  =   0.226729    (  > 1 if spirally stable )
