 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10383     Cltot =  -0.00076     Cl'tot =  -0.00083
  CYtot =  -0.00526     Cmtot =   0.04610
  CZtot =  -0.53430     Cntot =   0.00191     Cn'tot =   0.00188

  CLtot =   0.53760
  CDtot =   0.08512
  CDvis =   0.07000     CDind = 0.0151222
  CLff  =   0.53721     CDff  = 0.0155344    | Trefftz
  CYff  =  -0.00382         e =    0.8279    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.984191    CLb =  -0.021947
 y  force CY |    CYa =   0.000216    CYb =  -0.301049
 x' mom.  Cl'|    Cla =  -0.004776    Clb =  -0.047419
 y  mom.  Cm |    Cma =  -0.862695    Cmb =   0.004276
 z' mom.  Cn'|    Cna =   0.000581    Cnb =   0.107781

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003725    CLq =   8.028170    CLr =   0.004132
 y  force CY |    CYp =  -0.001142    CYq =   0.016719    CYr =   0.233933
 x' mom.  Cl'|    Clp =  -0.479440    Clq =  -0.001634    Clr =   0.185111
 y  mom.  Cm |    Cmp =   0.002384    Cmq = -16.411657    Cmr =  -0.006209
 z' mom.  Cn'|    Cnp =  -0.008217    Cnq =  -0.008519    Cnr =  -0.117662

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007944   CLd03 =  -0.000017
 y  force CY |   CYd01 =   0.000353   CYd02 =   0.000000   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004545   Cld02 =  -0.000005   Cld03 =  -0.000510
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.028031   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =   0.000109   Cnd02 =  -0.000001   Cnd03 =   0.001454
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000154 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000056    ed02 =   0.032609    ed03 =  -0.001824



 Neutral point  Xnp =   0.175310

 Clb Cnr / Clr Cnb  =   0.279649    (  > 1 if spirally stable )
