 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15793     Cltot =   0.00401     Cl'tot =   0.00309
  CYtot =   0.01026     Cmtot =  -0.54259
  CZtot =  -1.69237     Cntot =  -0.00402     Cn'tot =  -0.00476

  CLtot =   1.68822
  CDtot =   0.19739
  CDvis =   0.07000     CDind = 0.1273867
  CLff  =   1.71639     CDff  = 0.1314755    | Trefftz
  CYff  =   0.00766         e =    0.9986    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.407612    CLb =   0.121702
 y  force CY |    CYa =  -0.002181    CYb =  -0.293638
 x' mom.  Cl'|    Cla =   0.007877    Clb =  -0.088358
 y  mom.  Cm |    Cma =  -1.825329    Cmb =  -0.057588
 z' mom.  Cn'|    Cna =  -0.004822    Cnb =   0.136198

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.004365    CLq =  10.332612    CLr =  -0.007300
 y  force CY |    CYp =   0.262478    CYq =  -0.023676    CYr =   0.194132
 x' mom.  Cl'|    Clp =  -0.417298    Clq =   0.016711    Clr =   0.386580
 y  mom.  Cm |    Cmp =   0.001111    Cmq = -19.078144    Cmr =   0.022182
 z' mom.  Cn'|    Cnp =  -0.149246    Cnq =   0.009702    Cnr =  -0.165898

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000045   CLd02 =   0.007635   CLd03 =   0.000026
 y  force CY |   CYd01 =   0.000073   CYd02 =  -0.000001   CYd03 =  -0.002727
 x' mom.  Cl'|   Cld01 =  -0.004092   Cld02 =   0.000009   Cld03 =  -0.000215
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.029247   Cmd03 =  -0.000115
 z' mom.  Cn'|   Cnd01 =  -0.000198   Cnd02 =   0.000001   Cnd03 =   0.001481
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.001214 CDffd03 =  -0.000068
 span eff.   |    ed01 =  -0.000011    ed02 =  -0.000082    ed03 =   0.000505



 Neutral point  Xnp =   0.174785

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
