 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06241     Cltot =   0.00162     Cl'tot =   0.00033
  CYtot =  -0.02101     Cmtot =   0.16554
  CZtot =   0.08697     Cntot =   0.00815     Cn'tot =   0.00830

  CLtot =  -0.07614
  CDtot =   0.07525
  CDvis =   0.07000     CDind = 0.0052461
  CLff  =  -0.07672     CDff  = 0.0060487    | Trefftz
  CYff  =  -0.01532         e =    0.0451    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.952380    CLb =  -0.004513
 y  force CY |    CYa =  -0.001529    CYb =  -0.299318
 x' mom.  Cl'|    Cla =  -0.018116    Clb =   0.004692
 y  mom.  Cm |    Cma =  -1.855118    Cmb =   0.016282
 z' mom.  Cn'|    Cna =  -0.003366    Cnb =   0.118118

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.014525    CLq =  10.630505    CLr =   0.018153
 y  force CY |    CYp =  -0.072355    CYq =   0.047323    CYr =   0.238196
 x' mom.  Cl'|    Clp =  -0.478036    Clq =  -0.024235    Clr =   0.046369
 y  mom.  Cm |    Cmp =   0.013816    Cmq = -18.790350    Cmr =  -0.042189
 z' mom.  Cn'|    Cnp =   0.025574    Cnq =  -0.030074    Cnr =  -0.123279

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000101   CLd02 =   0.007707   CLd03 =  -0.000073
 y  force CY |   CYd01 =   0.000426   CYd02 =   0.000001   CYd03 =  -0.002800
 x' mom.  Cl'|   Cld01 =  -0.004590   Cld02 =  -0.000018   Cld03 =  -0.000269
 y  mom.  Cm |   Cmd01 =   0.000064   Cmd02 =  -0.028837   Cmd03 =   0.000233
 z' mom.  Cn'|   Cnd01 =   0.000290   Cnd02 =  -0.000002   Cnd03 =   0.001517
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000798 CDffd03 =   0.000138
 span eff.   |    ed01 =  -0.000014    ed02 =  -0.002942    ed03 =  -0.000411



 Neutral point  Xnp =   0.163635

 Clb Cnr / Clr Cnb  =  -0.105614    (  > 1 if spirally stable )
