 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04560     Cltot =  -0.00435     Cl'tot =  -0.00395
  CYtot =  -0.01561     Cmtot =  -0.05168
  CZtot =  -1.05547     Cntot =   0.00568     Cn'tot =   0.00597

  CLtot =   1.04972
  CDtot =   0.11911
  CDvis =   0.07000     CDind = 0.0491143
  CLff  =   1.05484     CDff  = 0.0505432    | Trefftz
  CYff  =  -0.01146         e =    0.9812    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.816726    CLb =  -0.117965
 y  force CY |    CYa =   0.001906    CYb =  -0.297293
 x' mom.  Cl'|    Cla =  -0.013630    Clb =  -0.075122
 y  mom.  Cm |    Cma =  -1.005815    Cmb =   0.023089
 z' mom.  Cn'|    Cna =   0.004677    Cnb =   0.113675

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.009631    CLq =   7.757131    CLr =   0.011929
 y  force CY |    CYp =   0.095873    CYq =   0.050136    CYr =   0.226409
 x' mom.  Cl'|    Clp =  -0.456692    Clq =  -0.007543    Clr =   0.282975
 y  mom.  Cm |    Cmp =   0.005164    Cmq = -16.605257    Cmr =  -0.019264
 z' mom.  Cn'|    Cnp =  -0.053385    Cnq =  -0.024895    Cnr =  -0.134120

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000072   CLd02 =   0.007921   CLd03 =  -0.000047
 y  force CY |   CYd01 =   0.000248   CYd02 =   0.000001   CYd03 =  -0.002833
 x' mom.  Cl'|   Cld01 =  -0.004395   Cld02 =  -0.000014   Cld03 =  -0.000491
 y  mom.  Cm |   Cmd01 =   0.000028   Cmd02 =  -0.028259   Cmd03 =   0.000140
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =  -0.000002   Cnd03 =   0.001440
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000413 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000060    ed02 =   0.006700    ed03 =  -0.001997



 Neutral point  Xnp =   0.185386

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
