 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10284     Cltot =   0.00263     Cl'tot =   0.00329
  CYtot =   0.02620     Cmtot =   0.07591
  CZtot =  -0.35350     Cntot =  -0.00950     Cn'tot =  -0.00929

  CLtot =   0.35981
  CDtot =   0.07793
  CDvis =   0.07000     CDind = 0.0079299
  CLff  =   0.36132     CDff  = 0.0097848    | Trefftz
  CYff  =   0.01908         e =    0.5962    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.972330    CLb =   0.079755
 y  force CY |    CYa =  -0.000372    CYb =  -0.297708
 x' mom.  Cl'|    Cla =   0.023907    Clb =  -0.037286
 y  mom.  Cm |    Cma =  -0.799552    Cmb =  -0.016219
 z' mom.  Cn'|    Cna =  -0.001228    Cnb =   0.105393

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.019485    CLq =   8.071744    CLr =  -0.020772
 y  force CY |    CYp =  -0.033470    CYq =  -0.083492    CYr =   0.230969
 x' mom.  Cl'|    Clp =  -0.483049    Clq =   0.006669    Clr =   0.150579
 y  mom.  Cm |    Cmp =  -0.012981    Cmq = -16.240688    Cmr =   0.030572
 z' mom.  Cn'|    Cnp =   0.006143    Cnq =   0.042803    Cnr =  -0.112275

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000124   CLd02 =   0.007839   CLd03 =   0.000087
 y  force CY |   CYd01 =   0.000385   CYd02 =  -0.000002   CYd03 =  -0.002837
 x' mom.  Cl'|   Cld01 =  -0.004537   Cld02 =   0.000022   Cld03 =  -0.000510
 y  mom.  Cm |   Cmd01 =  -0.000049   Cmd02 =  -0.027593   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =   0.000158   Cnd02 =   0.000003   Cnd03 =   0.001440
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000339 CDffd03 =  -0.000176
 span eff.   |    ed01 =  -0.000310    ed02 =   0.046605    ed03 =   0.010225



 Neutral point  Xnp =   0.171846

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
