 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10424     Cltot =   0.00087     Cl'tot =   0.00119
  CYtot =   0.01583     Cmtot =  -0.03517
  CZtot =  -0.43963     Cntot =  -0.00617     Cn'tot =  -0.00612

  CLtot =   0.44449
  CDtot =   0.08109
  CDvis =   0.07000     CDind = 0.0110928
  CLff  =   0.44479     CDff  = 0.0119061    | Trefftz
  CYff  =   0.01149         e =    0.7410    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.957655    CLb =   0.056456
 y  force CY |    CYa =  -0.000124    CYb =  -0.301401
 x' mom.  Cl'|    Cla =   0.013835    Clb =  -0.022729
 y  mom.  Cm |    Cma =  -1.955479    Cmb =  -0.033240
 z' mom.  Cn'|    Cna =  -0.000356    Cnb =   0.116454

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009470    CLq =  10.604789    CLr =  -0.013196
 y  force CY |    CYp =   0.025226    CYq =  -0.035505    CYr =   0.251190
 x' mom.  Cl'|    Clp =  -0.471414    Clq =   0.020441    Clr =   0.149339
 y  mom.  Cm |    Cmp =  -0.007000    Cmq = -19.145643    Cmr =   0.032563
 z' mom.  Cn'|    Cnp =  -0.021866    Cnq =   0.020539    Cnr =  -0.133306

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007966   CLd03 =   0.000052
 y  force CY |   CYd01 =   0.000327   CYd02 =  -0.000001   CYd03 =  -0.002860
 x' mom.  Cl'|   Cld01 =  -0.004576   Cld02 =   0.000014   Cld03 =  -0.000261
 y  mom.  Cm |   Cmd01 =  -0.000047   Cmd02 =  -0.029797   Cmd03 =  -0.000177
 z' mom.  Cn'|   Cnd01 =   0.000143   Cnd02 =   0.000002   Cnd03 =   0.001550
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000226 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000139    ed02 =   0.040601    ed03 =   0.006273



 Neutral point  Xnp =   0.169231

 Clb Cnr / Clr Cnb  =   0.174219    (  > 1 if spirally stable )
