 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07607     Cltot =  -0.00012     Cl'tot =  -0.00065
  CYtot =  -0.01051     Cmtot =   0.12718
  CZtot =  -0.00240     Cntot =   0.00380     Cn'tot =   0.00375

  CLtot =   0.01297
  CDtot =   0.07499
  CDvis =   0.07000     CDind = 0.0049929
  CLff  =   0.01239     CDff  = 0.0051279    | Trefftz
  CYff  =  -0.00764         e =    0.0018    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.007274    CLb =  -0.008270
 y  force CY |    CYa =  -0.000414    CYb =  -0.300620
 x' mom.  Cl'|    Cla =  -0.009579    Clb =  -0.018586
 y  mom.  Cm |    Cma =  -0.678795    Cmb =   0.002893
 z' mom.  Cn'|    Cna =  -0.000848    Cnb =   0.107113

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008517    CLq =   8.220708    CLr =   0.008352
 y  force CY |    CYp =  -0.097613    CYq =   0.033432    CYr =   0.220726
 x' mom.  Cl'|    Clp =  -0.492081    Clq =  -0.001468    Clr =   0.081804
 y  mom.  Cm |    Cmp =   0.006039    Cmq = -16.010673    Cmr =  -0.011850
 z' mom.  Cn'|    Cnp =   0.034058    Cnq =  -0.017284    Cnr =  -0.103777

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007725   CLd03 =  -0.000036
 y  force CY |   CYd01 =   0.000455   CYd02 =   0.000001   CYd03 =  -0.002823
 x' mom.  Cl'|   Cld01 =  -0.004581   Cld02 =  -0.000009   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.027102   Cmd03 =   0.000092
 z' mom.  Cn'|   Cnd01 =   0.000259   Cnd02 =  -0.000001   Cnd03 =   0.001432
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000711 CDffd03 =   0.000070
 span eff.   |    ed01 =  -0.000028    ed02 =   0.001943    ed03 =   0.000339



 Neutral point  Xnp =   0.164728

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
