 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10282     Cltot =   0.00070     Cl'tot =   0.00127
  CYtot =   0.02108     Cmtot =  -0.00052
  CZtot =  -0.35058     Cntot =  -0.00821     Cn'tot =  -0.00815

  CLtot =   0.35690
  CDtot =   0.07812
  CDvis =   0.07000     CDind = 0.0081191
  CLff  =   0.35766     CDff  = 0.0093191    | Trefftz
  CYff  =   0.01532         e =    0.6128    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.957193    CLb =   0.063422
 y  force CY |    CYa =   0.000118    CYb =  -0.300342
 x' mom.  Cl'|    Cla =   0.018425    Clb =  -0.018055
 y  mom.  Cm |    Cma =  -1.941131    Cmb =  -0.039506
 z' mom.  Cn'|    Cna =   0.000169    Cnb =   0.115918

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012930    CLq =  10.602818    CLr =  -0.017709
 y  force CY |    CYp =   0.008788    CYq =  -0.047323    CYr =   0.250225
 x' mom.  Cl'|    Clp =  -0.472734    Clq =   0.026763    Clr =   0.132233
 y  mom.  Cm |    Cmp =  -0.010086    Cmq = -19.083885    Cmr =   0.043232
 z' mom.  Cn'|    Cnp =  -0.013838    Cnq =   0.027847    Cnr =  -0.131341

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000101   CLd02 =   0.007924   CLd03 =   0.000070
 y  force CY |   CYd01 =   0.000343   CYd02 =  -0.000001   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004577   Cld02 =   0.000018   Cld03 =  -0.000262
 y  mom.  Cm |   Cmd01 =  -0.000063   Cmd02 =  -0.029628   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =   0.000167   Cnd02 =   0.000002   Cnd03 =   0.001544
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000322 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000192    ed02 =   0.048408    ed03 =   0.008747



 Neutral point  Xnp =   0.168425

 Clb Cnr / Clr Cnb  =   0.154708    (  > 1 if spirally stable )
