 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04792     Cltot =  -0.00052     Cl'tot =  -0.00016
  CYtot =   0.00526     Cmtot =   0.19733
  CZtot =   0.17367     Cntot =  -0.00204     Cn'tot =  -0.00210

  CLtot =  -0.16271
  CDtot =   0.07735
  CDvis =   0.07000     CDind = 0.0073464
  CLff  =  -0.16400     CDff  = 0.0071539    | Trefftz
  CYff  =   0.00383         e =    0.1676    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.962769    CLb =  -0.001817
 y  force CY |    CYa =   0.000454    CYb =  -0.301174
 x' mom.  Cl'|    Cla =   0.004511    Clb =   0.009261
 y  mom.  Cm |    Cma =  -1.839430    Cmb =  -0.002955
 z' mom.  Cn'|    Cna =   0.001002    Cnb =   0.120129

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003716    CLq =  10.656529    CLr =  -0.004555
 y  force CY |    CYp =  -0.088465    CYq =  -0.011840    CYr =   0.234638
 x' mom.  Cl'|    Clp =  -0.479414    Clq =   0.005931    Clr =   0.029115
 y  mom.  Cm |    Cmp =  -0.003640    Cmq = -18.757232    Cmr =   0.010493
 z' mom.  Cn'|    Cnp =   0.033434    Cnq =   0.007629    Cnr =  -0.122173

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007682   CLd03 =   0.000018
 y  force CY |   CYd01 =   0.000444   CYd02 =  -0.000000   CYd03 =  -0.002798
 x' mom.  Cl'|   Cld01 =  -0.004605   Cld02 =   0.000005   Cld03 =  -0.000271
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.028758   Cmd03 =  -0.000058
 z' mom.  Cn'|   Cnd01 =   0.000315   Cnd02 =   0.000001   Cnd03 =   0.001515
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000894 CDffd03 =  -0.000034
 span eff.   |    ed01 =  -0.000011    ed02 =   0.004906    ed03 =   0.000677



 Neutral point  Xnp =   0.162522

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
