 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01496     Cltot =   0.00893     Cl'tot =   0.00772
  CYtot =   0.02576     Cmtot =  -0.10454
  CZtot =  -1.30003     Cntot =  -0.00937     Cn'tot =  -0.01039

  CLtot =   1.29216
  CDtot =   0.14359
  CDvis =   0.07000     CDind = 0.0735854
  CLff  =   1.30681     CDff  = 0.0766967    | Trefftz
  CYff  =   0.01908         e =    0.9925    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.671129    CLb =   0.237951
 y  force CY |    CYa =  -0.004200    CYb =  -0.292714
 x' mom.  Cl'|    Cla =   0.021706    Clb =  -0.087570
 y  mom.  Cm |    Cma =  -1.057092    Cmb =  -0.047793
 z' mom.  Cn'|    Cna =  -0.010094    Cnb =   0.117874

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014832    CLq =   7.586977    CLr =  -0.019284
 y  force CY |    CYp =   0.142932    CYq =  -0.083492    CYr =   0.214706
 x' mom.  Cl'|    Clp =  -0.441452    Clq =   0.014714    Clr =   0.328621
 y  mom.  Cm |    Cmp =  -0.006909    Cmq = -16.603318    Cmr =   0.032488
 z' mom.  Cn'|    Cnp =  -0.077096    Cnq =   0.040744    Cnr =  -0.142717

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000117   CLd02 =   0.007800   CLd03 =   0.000074
 y  force CY |   CYd01 =   0.000195   CYd02 =  -0.000002   CYd03 =  -0.002785
 x' mom.  Cl'|   Cld01 =  -0.004268   Cld02 =   0.000022   Cld03 =  -0.000476
 y  mom.  Cm |   Cmd01 =  -0.000046   Cmd02 =  -0.028037   Cmd03 =  -0.000231
 z' mom.  Cn'|   Cnd01 =  -0.000106   Cnd02 =   0.000003   Cnd03 =   0.001416
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =   0.000689 CDffd03 =  -0.000175
 span eff.   |    ed01 =  -0.000065    ed02 =   0.003026    ed03 =   0.002201



 Neutral point  Xnp =   0.190318

 Clb Cnr / Clr Cnb  =   0.322640    (  > 1 if spirally stable )
