 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04501     Cltot =  -0.00548     Cl'tot =  -0.00476
  CYtot =  -0.02614     Cmtot =  -0.27283
  CZtot =  -1.04190     Cntot =   0.01022     Cn'tot =   0.01058

  CLtot =   1.03622
  CDtot =   0.11758
  CDvis =   0.07000     CDind = 0.0475759
  CLff  =   1.04420     CDff  = 0.0500734    | Trefftz
  CYff  =  -0.01914         e =    0.9707    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.767178    CLb =  -0.194648
 y  force CY |    CYa =   0.002667    CYb =  -0.296976
 x' mom.  Cl'|    Cla =  -0.022157    Clb =  -0.053940
 y  mom.  Cm |    Cma =  -1.950290    Cmb =   0.097075
 z' mom.  Cn'|    Cna =   0.006134    Cnb =   0.120000

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.013254    CLq =  10.479618    CLr =   0.020549
 y  force CY |    CYp =   0.139168    CYq =   0.059127    CYr =   0.239465
 x' mom.  Cl'|    Clp =  -0.450838    Clq =  -0.037956    Clr =   0.264056
 y  mom.  Cm |    Cmp =   0.004962    Cmq = -19.224501    Cmr =  -0.055244
 z' mom.  Cn'|    Cnp =  -0.079277    Cnq =  -0.029801    Cnr =  -0.147271

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000122   CLd02 =   0.007936   CLd03 =  -0.000078
 y  force CY |   CYd01 =   0.000205   CYd02 =   0.000002   CYd03 =  -0.002830
 x' mom.  Cl'|   Cld01 =  -0.004398   Cld02 =  -0.000023   Cld03 =  -0.000242
 y  mom.  Cm |   Cmd01 =   0.000076   Cmd02 =  -0.029882   Cmd03 =   0.000293
 z' mom.  Cn'|   Cnd01 =  -0.000024   Cnd02 =  -0.000003   Cnd03 =   0.001535
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000457 CDffd03 =   0.000174
 span eff.   |    ed01 =   0.000071    ed02 =   0.005944    ed03 =  -0.003272



 Neutral point  Xnp =   0.173368

 Clb Cnr / Clr Cnb  =   0.250698    (  > 1 if spirally stable )
