 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01451     Cltot =  -0.00179     Cl'tot =  -0.00155
  CYtot =  -0.00517     Cmtot =  -0.10654
  CZtot =  -1.31015     Cntot =   0.00188     Cn'tot =   0.00209

  CLtot =   1.30215
  CDtot =   0.14526
  CDvis =   0.07000     CDind = 0.0752620
  CLff  =   1.31160     CDff  = 0.0766832    | Trefftz
  CYff  =  -0.00382         e =    0.9997    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.704313    CLb =  -0.047823
 y  force CY |    CYa =   0.000844    CYb =  -0.296272
 x' mom.  Cl'|    Cla =  -0.004363    Clb =  -0.088867
 y  mom.  Cm |    Cma =  -1.064858    Cmb =   0.009605
 z' mom.  Cn'|    Cna =   0.002029    Cnb =   0.119619

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002970    CLq =   7.614798    CLr =   0.003862
 y  force CY |    CYp =   0.143456    CYq =   0.016719    CYr =   0.215493
 x' mom.  Cl'|    Clp =  -0.443071    Clq =  -0.002946    Clr =   0.329826
 y  mom.  Cm |    Cmp =   0.001384    Cmq = -16.664202    Cmr =  -0.006505
 z' mom.  Cn'|    Cnp =  -0.077379    Cnq =  -0.008159    Cnr =  -0.143240

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000024   CLd02 =   0.007858   CLd03 =  -0.000015
 y  force CY |   CYd01 =   0.000196   CYd02 =   0.000000   CYd03 =  -0.002805
 x' mom.  Cl'|   Cld01 =  -0.004299   Cld02 =  -0.000005   Cld03 =  -0.000479
 y  mom.  Cm |   Cmd01 =   0.000009   Cmd02 =  -0.028243   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000107   Cnd02 =  -0.000001   Cnd03 =   0.001426
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000694 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000013    ed02 =   0.002983    ed03 =  -0.000446



 Neutral point  Xnp =   0.190333

 Clb Cnr / Clr Cnb  =   0.322640    (  > 1 if spirally stable )
