 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08432     Cltot =  -0.00552     Cl'tot =  -0.00535
  CYtot =  -0.02609     Cmtot =   0.00009
  CZtot =  -0.79225     Cntot =   0.00949     Cn'tot =   0.00958

  CLtot =   0.79065
  CDtot =   0.09813
  CDvis =   0.07000     CDind = 0.0281291
  CLff  =   0.79485     CDff  = 0.0303711    | Trefftz
  CYff  =  -0.01908         e =    0.9275    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.887038    CLb =  -0.152961
 y  force CY |    CYa =   0.002122    CYb =  -0.296472
 x' mom.  Cl'|    Cla =  -0.023331    Clb =  -0.060724
 y  mom.  Cm |    Cma =  -0.933775    Cmb =   0.029486
 z' mom.  Cn'|    Cna =   0.005361    Cnb =   0.108662

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.017300    CLq =   7.876008    CLr =   0.020318
 y  force CY |    CYp =   0.047440    CYq =   0.083492    CYr =   0.232003
 x' mom.  Cl'|    Clp =  -0.467720    Clq =  -0.010374    Clr =   0.234136
 y  mom.  Cm |    Cmp =   0.010267    Cmq = -16.480820    Cmr =  -0.031587
 z' mom.  Cn'|    Cnp =  -0.030307    Cnq =  -0.042059    Cnr =  -0.125239

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000122   CLd02 =   0.007911   CLd03 =  -0.000082
 y  force CY |   CYd01 =   0.000299   CYd02 =   0.000002   CYd03 =  -0.002839
 x' mom.  Cl'|   Cld01 =  -0.004455   Cld02 =  -0.000023   Cld03 =  -0.000499
 y  mom.  Cm |   Cmd01 =   0.000048   Cmd02 =  -0.028051   Cmd03 =   0.000232
 z' mom.  Cn'|   Cnd01 =   0.000034   Cnd02 =  -0.000003   Cnd03 =   0.001442
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =   0.000130 CDffd03 =   0.000176
 span eff.   |    ed01 =   0.000159    ed02 =   0.014479    ed03 =  -0.005223



 Neutral point  Xnp =   0.180382

 Clb Cnr / Clr Cnb  =   0.298923    (  > 1 if spirally stable )
