 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09882     Cltot =   0.00437     Cl'tot =   0.00453
  CYtot =   0.02615     Cmtot =   0.03181
  CZtot =  -0.61761     Cntot =  -0.00950     Cn'tot =  -0.00942

  CLtot =   0.61924
  CDtot =   0.08802
  CDvis =   0.07000     CDind = 0.0180228
  CLff  =   0.62198     CDff  = 0.0201162    | Trefftz
  CYff  =   0.01908         e =    0.8578    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.931792    CLb =   0.123855
 y  force CY |    CYa =  -0.001423    CYb =  -0.297174
 x' mom.  Cl'|    Cla =   0.023648    Clb =  -0.051420
 y  mom.  Cm |    Cma =  -0.883280    Cmb =  -0.023935
 z' mom.  Cn'|    Cna =  -0.003720    Cnb =   0.106863

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.018164    CLq =   7.959644    CLr =  -0.020545
 y  force CY |    CYp =   0.015064    CYq =  -0.083492    CYr =   0.233285
 x' mom.  Cl'|    Clp =  -0.474617    Clq =   0.008900    Clr =   0.201157
 y  mom.  Cm |    Cmp =  -0.011363    Cmq = -16.399737    Cmr =   0.031210
 z' mom.  Cn'|    Cnp =  -0.015473    Cnq =   0.042396    Cnr =  -0.119831

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000123   CLd02 =   0.007900   CLd03 =   0.000084
 y  force CY |   CYd01 =   0.000333   CYd02 =  -0.000002   CYd03 =  -0.002844
 x' mom.  Cl'|   Cld01 =  -0.004496   Cld02 =   0.000023   Cld03 =  -0.000504
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.027919   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =   0.000083   Cnd02 =   0.000003   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000059 CDffd03 =  -0.000176
 span eff.   |    ed01 =  -0.000222    ed02 =   0.024269    ed03 =   0.007275



 Neutral point  Xnp =   0.177006

 Clb Cnr / Clr Cnb  =   0.286642    (  > 1 if spirally stable )
