 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02804     Cltot =   0.00157     Cl'tot =   0.00140
  CYtot =   0.00520     Cmtot =  -0.07000
  CZtot =  -1.14320     Cntot =  -0.00189     Cn'tot =  -0.00202

  CLtot =   1.13640
  CDtot =   0.12757
  CDvis =   0.07000     CDind = 0.0575735
  CLff  =   1.14164     CDff  = 0.0585849    | Trefftz
  CYff  =   0.00382         e =    0.9914    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.790106    CLb =   0.042224
 y  force CY |    CYa =  -0.000706    CYb =  -0.297821
 x' mom.  Cl'|    Cla =   0.004493    Clb =  -0.080011
 y  mom.  Cm |    Cma =  -1.028394    Cmb =  -0.008329
 z' mom.  Cn'|    Cna =  -0.001719    Cnb =   0.115871

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003130    CLq =   7.717416    CLr =  -0.003942
 y  force CY |    CYp =   0.111939    CYq =  -0.016719    CYr =   0.223508
 x' mom.  Cl'|    Clp =  -0.452734    Clq =   0.002660    Clr =   0.299036
 y  mom.  Cm |    Cmp =  -0.001610    Cmq = -16.643480    Cmr =   0.006453
 z' mom.  Cn'|    Cnp =  -0.061325    Cnq =   0.008257    Cnr =  -0.137237

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007919   CLd03 =   0.000015
 y  force CY |   CYd01 =   0.000231   CYd02 =  -0.000000   CYd03 =  -0.002830
 x' mom.  Cl'|   Cld01 =  -0.004373   Cld02 =   0.000005   Cld03 =  -0.000488
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.028317   Cmd03 =  -0.000047
 z' mom.  Cn'|   Cnd01 =  -0.000061   Cnd02 =   0.000001   Cnd03 =   0.001438
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000508 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000017    ed02 =   0.005151    ed03 =   0.000581



 Neutral point  Xnp =   0.187043

 Clb Cnr / Clr Cnb  =   0.316900    (  > 1 if spirally stable )
