 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07441     Cltot =   0.00087     Cl'tot =   0.00080
  CYtot =   0.00526     Cmtot =  -0.20811
  CZtot =  -0.87875     Cntot =  -0.00206     Cn'tot =  -0.00209

  CLtot =   0.87562
  CDtot =   0.10503
  CDvis =   0.07000     CDind = 0.0350323
  CLff  =   0.87703     CDff  = 0.0356569    | Trefftz
  CYff  =   0.00383         e =    0.9613    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.866584    CLb =   0.033412
 y  force CY |    CYa =  -0.000395    CYb =  -0.301528
 x' mom.  Cl'|    Cla =   0.004528    Clb =  -0.045757
 y  mom.  Cm |    Cma =  -1.975402    Cmb =  -0.017108
 z' mom.  Cn'|    Cna =  -0.000919    Cnb =   0.119625

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002791    CLq =  10.552457    CLr =  -0.004209
 y  force CY |    CYp =   0.107315    CYq =  -0.011840    CYr =   0.246381
 x' mom.  Cl'|    Clp =  -0.459216    Clq =   0.007388    Clr =   0.232730
 y  mom.  Cm |    Cmp =  -0.001379    Cmq = -19.288346    Cmr =   0.011021
 z' mom.  Cn'|    Cnp =  -0.062795    Cnq =   0.006229    Cnr =  -0.143479

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.008023   CLd03 =   0.000016
 y  force CY |   CYd01 =   0.000241   CYd02 =  -0.000000   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004489   Cld02 =   0.000005   Cld03 =  -0.000250
 y  mom.  Cm |   Cmd01 =  -0.000015   Cmd02 =  -0.030127   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000022   Cnd02 =   0.000001   Cnd03 =   0.001553
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000265 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000020    ed02 =   0.010410    ed03 =   0.000916



 Neutral point  Xnp =   0.172467

 Clb Cnr / Clr Cnb  =   0.235816    (  > 1 if spirally stable )
