 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10436     Cltot =  -0.00257     Cl'tot =  -0.00297
  CYtot =  -0.02098     Cmtot =   0.06141
  CZtot =  -0.44315     Cntot =   0.00762     Cn'tot =   0.00747

  CLtot =   0.44800
  CDtot =   0.08102
  CDvis =   0.07000     CDind = 0.0110249
  CLff  =   0.44896     CDff  = 0.0123671    | Trefftz
  CYff  =  -0.01527         e =    0.7272    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.975659    CLb =  -0.075738
 y  force CY |    CYa =   0.000579    CYb =  -0.298958
 x' mom.  Cl'|    Cla =  -0.019115    Clb =  -0.042247
 y  mom.  Cm |    Cma =  -0.830761    Cmb =   0.014992
 z' mom.  Cn'|    Cna =   0.001652    Cnb =   0.106304

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015241    CLq =   8.047267    CLr =   0.016577
 y  force CY |    CYp =  -0.017346    CYq =   0.066824    CYr =   0.232625
 x' mom.  Cl'|    Clp =  -0.481161    Clq =  -0.005935    Clr =   0.167802
 y  mom.  Cm |    Cmp =   0.009961    Cmq = -16.321078    Cmr =  -0.024647
 z' mom.  Cn'|    Cnp =  -0.000984    Cnq =  -0.034160    Cnr =  -0.114870

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000099   CLd02 =   0.007887   CLd03 =  -0.000069
 y  force CY |   CYd01 =   0.000369   CYd02 =   0.000001   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004538   Cld02 =  -0.000018   Cld03 =  -0.000510
 y  mom.  Cm |   Cmd01 =   0.000039   Cmd02 =  -0.027795   Cmd03 =   0.000186
 z' mom.  Cn'|   Cnd01 =   0.000133   Cnd02 =  -0.000002   Cnd03 =   0.001446
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000247 CDffd03 =   0.000141
 span eff.   |    ed01 =   0.000244    ed02 =   0.040066    ed03 =  -0.007983



 Neutral point  Xnp =   0.173584

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
