 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06331     Cltot =   0.00006     Cl'tot =  -0.00024
  CYtot =  -0.00525     Cmtot =   0.13871
  CZtot =   0.08529     Cntot =   0.00190     Cn'tot =   0.00188

  CLtot =  -0.07433
  CDtot =   0.07587
  CDvis =   0.07000     CDind = 0.0058749
  CLff  =  -0.07524     CDff  = 0.0057420    | Trefftz
  CYff  =  -0.00382         e =    0.0440    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.003686    CLb =  -0.001166
 y  force CY |    CYa =  -0.000278    CYb =  -0.300832
 x' mom.  Cl'|    Cla =  -0.004775    Clb =  -0.013838
 y  mom.  Cm |    Cma =  -0.645745    Cmb =   0.001044
 z' mom.  Cn'|    Cna =  -0.000591    Cnb =   0.107817

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004348    CLq =   8.250187    CLr =   0.004173
 y  force CY |    CYp =  -0.113385    CYq =   0.016719    CYr =   0.216692
 x' mom.  Cl'|    Clp =  -0.493474    Clq =  -0.000583    Clr =   0.064312
 y  mom.  Cm |    Cmp =   0.003123    Cmq = -15.935175    Cmr =  -0.005872
 z' mom.  Cn'|    Cnp =   0.040899    Cnq =  -0.008655    Cnr =  -0.101858

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007677   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000471   CYd02 =   0.000000   CYd03 =  -0.002813
 x' mom.  Cl'|   Cld01 =  -0.004582   Cld02 =  -0.000004   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.026920   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =   0.000285   Cnd02 =  -0.000001   Cnd03 =   0.001427
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000802 CDffd03 =   0.000035
 span eff.   |    ed01 =  -0.000004    ed02 =  -0.002972    ed03 =  -0.000106



 Neutral point  Xnp =   0.162893

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
