 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06119     Cltot =   0.00197     Cl'tot =   0.00175
  CYtot =   0.01051     Cmtot =  -0.24207
  CZtot =  -0.96387     Cntot =  -0.00411     Cn'tot =  -0.00421

  CLtot =   0.95934
  CDtot =   0.11155
  CDvis =   0.07000     CDind = 0.0415476
  CLff  =   0.96223     CDff  = 0.0424733    | Trefftz
  CYff  =   0.00766         e =    0.9715    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.831252    CLb =   0.072508
 y  force CY |    CYa =  -0.000931    CYb =  -0.300643
 x' mom.  Cl'|    Cla =   0.008981    Clb =  -0.050175
 y  mom.  Cm |    Cma =  -1.969410    Cmb =  -0.036599
 z' mom.  Cn'|    Cna =  -0.002152    Cnb =   0.120402

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.005442    CLq =  10.531012    CLr =  -0.008325
 y  force CY |    CYp =   0.123493    CYq =  -0.023676    CYr =   0.243533
 x' mom.  Cl'|    Clp =  -0.455756    Clq =   0.014988    Clr =   0.248844
 y  mom.  Cm |    Cmp =  -0.002373    Cmq = -19.285793    Cmr =   0.022083
 z' mom.  Cn'|    Cnp =  -0.071117    Cnq =   0.012196    Cnr =  -0.145559

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000049   CLd02 =   0.008004   CLd03 =   0.000032
 y  force CY |   CYd01 =   0.000224   CYd02 =  -0.000001   CYd03 =  -0.002856
 x' mom.  Cl'|   Cld01 =  -0.004457   Cld02 =   0.000009   Cld03 =  -0.000247
 y  mom.  Cm |   Cmd01 =  -0.000031   Cmd02 =  -0.030096   Cmd03 =  -0.000118
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =   0.000001   Cnd03 =   0.001549
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000362 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000034    ed02 =   0.007858    ed03 =   0.001553



 Neutral point  Xnp =   0.172954

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
