 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10010     Cltot =  -0.00088     Cl'tot =  -0.00091
  CYtot =  -0.00525     Cmtot =   0.03081
  CZtot =  -0.62279     Cntot =   0.00191     Cn'tot =   0.00189

  CLtot =   0.62444
  CDtot =   0.08921
  CDvis =   0.07000     CDind = 0.0192109
  CLff  =   0.62426     CDff  = 0.0196869    | Trefftz
  CYff  =  -0.00382         e =    0.8822    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.966972    CLb =  -0.024892
 y  force CY |    CYa =   0.000286    CYb =  -0.300798
 x' mom.  Cl'|    Cla =  -0.004753    Clb =  -0.052182
 y  mom.  Cm |    Cma =  -0.889770    Cmb =   0.004810
 z' mom.  Cn'|    Cna =   0.000748    Cnb =   0.108446

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003637    CLq =   7.988832    CLr =   0.004114
 y  force CY |    CYp =   0.015120    CYq =   0.016719    CYr =   0.234141
 x' mom.  Cl'|    Clp =  -0.476358    Clq =  -0.001782    Clr =   0.201895
 y  mom.  Cm |    Cmp =   0.002275    Cmq = -16.459874    Cmr =  -0.006250
 z' mom.  Cn'|    Cnp =  -0.015530    Cnq =  -0.008489    Cnr =  -0.120270

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007959   CLd03 =  -0.000017
 y  force CY |   CYd01 =   0.000336   CYd02 =   0.000000   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004529   Cld02 =  -0.000005   Cld03 =  -0.000508
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.028124   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =   0.000084   Cnd02 =  -0.000001   Cnd03 =   0.001455
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000059 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000047    ed02 =   0.025053    ed03 =  -0.001538



 Neutral point  Xnp =   0.177017

 Clb Cnr / Clr Cnb  =   0.286642    (  > 1 if spirally stable )
