 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09398     Cltot =  -0.00099     Cl'tot =  -0.00099
  CYtot =  -0.00525     Cmtot =   0.01505
  CZtot =  -0.71096     Cntot =   0.00191     Cn'tot =   0.00191

  CLtot =   0.71096
  CDtot =   0.09398
  CDvis =   0.07000     CDind = 0.0239780
  CLff  =   0.71112     CDff  = 0.0245165    | Trefftz
  CYff  =  -0.00382         e =    0.9192    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.946186    CLb =  -0.027824
 y  force CY |    CYa =   0.000356    CYb =  -0.300477
 x' mom.  Cl'|    Cla =  -0.004724    Clb =  -0.056919
 y  mom.  Cm |    Cma =  -0.915761    Cmb =   0.005361
 z' mom.  Cn'|    Cna =   0.000913    Cnb =   0.109276

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003550    CLq =   7.947721    CLr =   0.004093
 y  force CY |    CYp =   0.031378    CYq =   0.016719    CYr =   0.233781
 x' mom.  Cl'|    Clp =  -0.473021    Clq =  -0.001930    Clr =   0.218526
 y  mom.  Cm |    Cmp =   0.002166    Cmq = -16.503078    Cmr =  -0.006288
 z' mom.  Cn'|    Cnp =  -0.022929    Cnq =  -0.008457    Cnr =  -0.122951

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007967   CLd03 =  -0.000017
 y  force CY |   CYd01 =   0.000318   CYd02 =   0.000000   CYd03 =  -0.002863
 x' mom.  Cl'|   Cld01 =  -0.004510   Cld02 =  -0.000005   Cld03 =  -0.000505
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.028199   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =  -0.000001   Cnd03 =   0.001454
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000036 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000039    ed02 =   0.019166    ed03 =  -0.001288



 Neutral point  Xnp =   0.178711

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
