 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03855     Cltot =   0.00311     Cl'tot =   0.00252
  CYtot =   0.01040     Cmtot =  -0.41189
  CZtot =  -1.38068     Cntot =  -0.00407     Cn'tot =  -0.00446

  CLtot =   1.37261
  CDtot =   0.15398
  CDvis =   0.07000     CDind = 0.0839815
  CLff  =   1.38534     CDff  = 0.0859215    | Trefftz
  CYff  =   0.00766         e =    0.9954    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.626532    CLb =   0.100434
 y  force CY |    CYa =  -0.001630    CYb =  -0.297445
 x' mom.  Cl'|    Cla =   0.008471    Clb =  -0.072010
 y  mom.  Cm |    Cma =  -1.912691    Cmb =  -0.048460
 z' mom.  Cn'|    Cna =  -0.003679    Cnb =   0.127697

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.004804    CLq =  10.431125    CLr =  -0.007797
 y  force CY |    CYp =   0.202658    CYq =  -0.023676    CYr =   0.221478
 x' mom.  Cl'|    Clp =  -0.436310    Clq =   0.015994    Clr =   0.327360
 y  mom.  Cm |    Cmp =  -0.000439    Cmq = -19.229003    Cmr =   0.022206
 z' mom.  Cn'|    Cnp =  -0.113846    Cnq =   0.010844    Cnr =  -0.156747

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000047   CLd02 =   0.007857   CLd03 =   0.000029
 y  force CY |   CYd01 =   0.000139   CYd02 =  -0.000001   CYd03 =  -0.002801
 x' mom.  Cl'|   Cld01 =  -0.004279   Cld02 =   0.000009   Cld03 =  -0.000230
 y  mom.  Cm |   Cmd01 =  -0.000030   Cmd02 =  -0.029804   Cmd03 =  -0.000117
 z' mom.  Cn'|   Cnd01 =  -0.000115   Cnd02 =   0.000001   Cnd03 =   0.001520
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000844 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000017    ed02 =   0.001630    ed03 =   0.000780



 Neutral point  Xnp =   0.174584

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
