 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10292     Cltot =   0.00122     Cl'tot =   0.00144
  CYtot =   0.01583     Cmtot =  -0.06937
  CZtot =  -0.52763     Cntot =  -0.00618     Cn'tot =  -0.00613

  CLtot =   0.53090
  CDtot =   0.08444
  CDvis =   0.07000     CDind = 0.0144400
  CLff  =   0.53140     CDff  = 0.0153233    | Trefftz
  CYff  =   0.01149         e =    0.8216    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.944231    CLb =   0.065254
 y  force CY |    CYa =  -0.000336    CYb =  -0.301324
 x' mom.  Cl'|    Cla =   0.013814    Clb =  -0.027320
 y  mom.  Cm |    Cma =  -1.963296    Cmb =  -0.036825
 z' mom.  Cn'|    Cna =  -0.000839    Cnb =   0.116652

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009242    CLq =  10.594189    CLr =  -0.013096
 y  force CY |    CYp =   0.041669    CYq =  -0.035505    CYr =   0.251314
 x' mom.  Cl'|    Clp =  -0.469342    Clq =   0.020797    Clr =   0.166203
 y  mom.  Cm |    Cmp =  -0.006431    Cmq = -19.181185    Cmr =   0.032680
 z' mom.  Cn'|    Cnp =  -0.029929    Cnq =   0.020179    Cnr =  -0.135194

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007986   CLd03 =   0.000051
 y  force CY |   CYd01 =   0.000310   CYd02 =  -0.000001   CYd03 =  -0.002863
 x' mom.  Cl'|   Cld01 =  -0.004562   Cld02 =   0.000014   Cld03 =  -0.000259
 y  mom.  Cm |   Cmd01 =  -0.000047   Cmd02 =  -0.029885   Cmd03 =  -0.000177
 z' mom.  Cn'|   Cnd01 =   0.000119   Cnd02 =   0.000002   Cnd03 =   0.001552
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000128 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000121    ed02 =   0.031542    ed03 =   0.005429



 Neutral point  Xnp =   0.169979

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
