 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04590     Cltot =   0.00110     Cl'tot =   0.00096
  CYtot =   0.00525     Cmtot =  -0.27690
  CZtot =  -1.05015     Cntot =  -0.00205     Cn'tot =  -0.00213

  CLtot =   1.04439
  CDtot =   0.11904
  CDvis =   0.07000     CDind = 0.0490412
  CLff  =   1.04802     CDff  = 0.0498774    | Trefftz
  CYff  =   0.00383         e =    0.9813    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.801088    CLb =   0.039120
 y  force CY |    CYa =  -0.000536    CYb =  -0.300597
 x' mom.  Cl'|    Cla =   0.004453    Clb =  -0.054738
 y  mom.  Cm |    Cma =  -1.964620    Cmb =  -0.019510
 z' mom.  Cn'|    Cna =  -0.001233    Cnb =   0.121777

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002654    CLq =  10.518046    CLr =  -0.004115
 y  force CY |    CYp =   0.139679    CYq =  -0.011840    CYr =   0.240343
 x' mom.  Cl'|    Clp =  -0.452491    Clq =   0.007600    Clr =   0.265024
 y  mom.  Cm |    Cmp =  -0.000994    Cmq = -19.294996    Cmr =   0.011062
 z' mom.  Cn'|    Cnp =  -0.079568    Cnq =   0.005967    Cnr =  -0.147811

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007994   CLd03 =   0.000016
 y  force CY |   CYd01 =   0.000207   CYd02 =  -0.000000   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004431   Cld02 =   0.000005   Cld03 =  -0.000244
 y  mom.  Cm |   Cmd01 =  -0.000015   Cmd02 =  -0.030102   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =  -0.000025   Cnd02 =   0.000001   Cnd03 =   0.001546
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000460 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000015    ed02 =   0.005913    ed03 =   0.000668



 Neutral point  Xnp =   0.173395

 Clb Cnr / Clr Cnb  =   0.250698    (  > 1 if spirally stable )
