 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08517     Cltot =  -0.00076     Cl'tot =  -0.00072
  CYtot =  -0.00527     Cmtot =  -0.17361
  CZtot =  -0.79205     Cntot =   0.00206     Cn'tot =   0.00207

  CLtot =   0.79044
  CDtot =   0.09898
  CDvis =   0.07000     CDind = 0.0289841
  CLff  =   0.79112     CDff  = 0.0295305    | Trefftz
  CYff  =  -0.00383         e =    0.9445    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.894193    CLb =  -0.030528
 y  force CY |    CYa =   0.000325    CYb =  -0.301887
 x' mom.  Cl'|    Cla =  -0.004558    Clb =  -0.041216
 y  mom.  Cm |    Cma =  -1.977185    Cmb =   0.015904
 z' mom.  Cn'|    Cna =   0.000761    Cnb =   0.118785

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002861    CLq =  10.567920    CLr =   0.004252
 y  force CY |    CYp =   0.090995    CYq =   0.011840    CYr =   0.248549
 x' mom.  Cl'|    Clp =  -0.462242    Clq =  -0.007278    Clr =   0.216351
 y  mom.  Cm |    Cmp =   0.001571    Cmq = -19.276207    Cmr =  -0.010995
 z' mom.  Cn'|    Cnp =  -0.054501    Cnq =  -0.006357    Cnr =  -0.141373

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.008028   CLd03 =  -0.000016
 y  force CY |   CYd01 =   0.000259   CYd02 =   0.000000   CYd03 =  -0.002868
 x' mom.  Cl'|   Cld01 =  -0.004514   Cld02 =  -0.000005   Cld03 =  -0.000252
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.030112   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =   0.000046   Cnd02 =  -0.000001   Cnd03 =   0.001555
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000166 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000024    ed02 =   0.013789    ed03 =  -0.001087



 Neutral point  Xnp =   0.171924

 Clb Cnr / Clr Cnb  =   0.226729    (  > 1 if spirally stable )
