 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09837     Cltot =   0.00261     Cl'tot =   0.00279
  CYtot =   0.02629     Cmtot =  -0.10181
  CZtot =  -0.61199     Cntot =  -0.01026     Cn'tot =  -0.01022

  CLtot =   0.61361
  CDtot =   0.08768
  CDvis =   0.07000     CDind = 0.0176769
  CLff  =   0.61634     CDff  = 0.0197015    | Trefftz
  CYff  =   0.01914         e =    0.8601    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.903943    CLb =   0.122967
 y  force CY |    CYa =  -0.000911    CYb =  -0.298748
 x' mom.  Cl'|    Cla =   0.022886    Clb =  -0.031591
 y  mom.  Cm |    Cma =  -1.959132    Cmb =  -0.067151
 z' mom.  Cn'|    Cna =  -0.002193    Cnb =   0.115868

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.015017    CLq =  10.556554    CLr =  -0.021631
 y  force CY |    CYp =   0.057964    CYq =  -0.059127    CYr =   0.250253
 x' mom.  Cl'|    Clp =  -0.465887    Clq =   0.035214    Clr =   0.182510
 y  mom.  Cm |    Cmp =  -0.009758    Cmq = -19.164045    Cmr =   0.054601
 z' mom.  Cn'|    Cnp =  -0.037950    Cnq =   0.032995    Cnr =  -0.136808

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000125   CLd02 =   0.007961   CLd03 =   0.000084
 y  force CY |   CYd01 =   0.000291   CYd02 =  -0.000002   CYd03 =  -0.002850
 x' mom.  Cl'|   Cld01 =  -0.004523   Cld02 =   0.000023   Cld03 =  -0.000255
 y  mom.  Cm |   Cmd01 =  -0.000078   Cmd02 =  -0.029809   Cmd03 =  -0.000294
 z' mom.  Cn'|   Cnd01 =   0.000094   Cnd02 =   0.000003   Cnd03 =   0.001545
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =  -0.000030 CDffd03 =  -0.000174
 span eff.   |    ed01 =  -0.000163    ed02 =   0.023532    ed03 =   0.007358



 Neutral point  Xnp =   0.170659

 Clb Cnr / Clr Cnb  =   0.204371    (  > 1 if spirally stable )
