 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02809     Cltot =  -0.00243     Cl'tot =  -0.00206
  CYtot =  -0.01047     Cmtot =  -0.31057
  CZtot =  -1.13353     Cntot =   0.00410     Cn'tot =   0.00430

  CLtot =   1.12677
  CDtot =   0.12678
  CDvis =   0.07000     CDind = 0.0567766
  CLff  =   1.13254     CDff  = 0.0579713    | Trefftz
  CYff  =  -0.00766         e =    0.9860    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.759097    CLb =  -0.083831
 y  force CY |    CYa =   0.001212    CYb =  -0.299573
 x' mom.  Cl'|    Cla =  -0.008809    Clb =  -0.059059
 y  mom.  Cm |    Cma =  -1.953847    Cmb =   0.041384
 z' mom.  Cn'|    Cna =   0.002773    Cnb =   0.122861

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005176    CLq =  10.494342    CLr =   0.008127
 y  force CY |    CYp =   0.155612    CYq =   0.023676    CYr =   0.236373
 x' mom.  Cl'|    Clp =  -0.448598    Clq =  -0.015404    Clr =   0.280793
 y  mom.  Cm |    Cmp =   0.001601    Cmq = -19.280691    Cmr =  -0.022153
 z' mom.  Cn'|    Cnp =  -0.088010    Cnq =  -0.011666    Cnr =  -0.149960

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000049   CLd02 =   0.007964   CLd03 =  -0.000031
 y  force CY |   CYd01 =   0.000189   CYd02 =   0.000001   CYd03 =  -0.002839
 x' mom.  Cl'|   Cld01 =  -0.004393   Cld02 =  -0.000009   Cld03 =  -0.000241
 y  mom.  Cm |   Cmd01 =   0.000030   Cmd02 =  -0.030034   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =  -0.000048   Cnd02 =  -0.000001   Cnd03 =   0.001540
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000557 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000025    ed02 =   0.004423    ed03 =  -0.001152



 Neutral point  Xnp =   0.173775

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
