 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07404     Cltot =   0.00261     Cl'tot =   0.00239
  CYtot =   0.01577     Cmtot =  -0.20691
  CZtot =  -0.87641     Cntot =  -0.00617     Cn'tot =  -0.00626

  CLtot =   0.87329
  CDtot =   0.10458
  CDvis =   0.07000     CDind = 0.0345838
  CLff  =   0.87596     CDff  = 0.0357570    | Trefftz
  CYff  =   0.01149         e =    0.9565    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.855096    CLb =   0.100072
 y  force CY |    CYa =  -0.001184    CYb =  -0.300314
 x' mom.  Cl'|    Cla =   0.013563    Clb =  -0.045534
 y  mom.  Cm |    Cma =  -1.970591    Cmb =  -0.051242
 z' mom.  Cn'|    Cna =  -0.002753    Cnb =   0.119042

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008368    CLq =  10.539601    CLr =  -0.012621
 y  force CY |    CYp =   0.107184    CYq =  -0.035505    CYr =   0.246081
 x' mom.  Cl'|    Clp =  -0.458656    Clq =   0.022154    Clr =   0.232446
 y  mom.  Cm |    Cmp =  -0.004136    Cmq = -19.264846    Cmr =   0.033049
 z' mom.  Cn'|    Cnp =  -0.062718    Cnq =   0.018679    Cnr =  -0.143304

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000074   CLd02 =   0.008003   CLd03 =   0.000048
 y  force CY |   CYd01 =   0.000241   CYd02 =  -0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004478   Cld02 =   0.000014   Cld03 =  -0.000249
 y  mom.  Cm |   Cmd01 =  -0.000046   Cmd02 =  -0.030054   Cmd03 =  -0.000177
 z' mom.  Cn'|   Cnd01 =   0.000022   Cnd02 =   0.000002   Cnd03 =   0.001549
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000264 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000060    ed02 =   0.010391    ed03 =   0.002721



 Neutral point  Xnp =   0.172458

 Clb Cnr / Clr Cnb  =   0.235816    (  > 1 if spirally stable )
