 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12614     Cltot =   0.00671     Cl'tot =   0.00553
  CYtot =   0.01529     Cmtot =  -0.18215
  CZtot =  -1.62527     Cntot =  -0.00556     Cn'tot =  -0.00674

  CLtot =   1.61948
  CDtot =   0.18629
  CDvis =   0.07000     CDind = 0.1162895
  CLff  =   1.64451     CDff  = 0.1199671    | Trefftz
  CYff  =   0.01146         e =    1.0046    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.485228    CLb =   0.175698
 y  force CY |    CYa =  -0.003348    CYb =  -0.291179
 x' mom.  Cl'|    Cla =   0.012094    Clb =  -0.105173
 y  mom.  Cm |    Cma =  -1.119339    Cmb =  -0.036764
 z' mom.  Cn'|    Cna =  -0.007836    Cnb =   0.128292

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008005    CLq =   7.385290    CLr =  -0.011000
 y  force CY |    CYp =   0.204182    CYq =  -0.050136    CYr =   0.192742
 x' mom.  Cl'|    Clp =  -0.420922    Clq =   0.010521    Clr =   0.388137
 y  mom.  Cm |    Cmp =  -0.002778    Cmq = -16.624457    Cmr =   0.019750
 z' mom.  Cn'|    Cnp =  -0.110603    Cnq =   0.023791    Cnr =  -0.155227

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000068   CLd02 =   0.007647   CLd03 =   0.000041
 y  force CY |   CYd01 =   0.000128   CYd02 =  -0.000001   CYd03 =  -0.002728
 x' mom.  Cl'|   Cld01 =  -0.004114   Cld02 =   0.000013   Cld03 =  -0.000457
 y  mom.  Cm |   Cmd01 =  -0.000027   Cmd02 =  -0.027822   Cmd03 =  -0.000137
 z' mom.  Cn'|   Cnd01 =  -0.000193   Cnd02 =   0.000002   Cnd03 =   0.001388
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.001053 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000025    ed02 =   0.000717    ed03 =   0.000848



 Neutral point  Xnp =   0.196876

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
