 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09415     Cltot =   0.00118     Cl'tot =   0.00197
  CYtot =   0.02099     Cmtot =   0.10259
  CZtot =  -0.17797     Cntot =  -0.00760     Cn'tot =  -0.00744

  CLtot =   0.18683
  CDtot =   0.07503
  CDvis =   0.07000     CDind = 0.0050291
  CLff  =   0.18721     CDff  = 0.0061147    | Trefftz
  CYff  =   0.01527         e =    0.2571    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.994752    CLb =   0.040224
 y  force CY |    CYa =   0.000264    CYb =  -0.299076
 x' mom.  Cl'|    Cla =   0.019183    Clb =  -0.027965
 y  mom.  Cm |    Cma =  -0.740838    Cmb =  -0.009232
 z' mom.  Cn'|    Cna =   0.000355    Cnb =   0.105821

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.016308    CLq =   8.148227    CLr =  -0.016684
 y  force CY |    CYp =  -0.065666    CYq =  -0.066824    CYr =   0.226921
 x' mom.  Cl'|    Clp =  -0.488002    Clq =   0.004139    Clr =   0.116409
 y  mom.  Cm |    Cmp =  -0.011237    Cmq = -16.132037    Cmr =   0.024092
 z' mom.  Cn'|    Cnp =   0.020205    Cnq =   0.034424    Cnr =  -0.107816

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007790   CLd03 =   0.000071
 y  force CY |   CYd01 =   0.000420   CYd02 =  -0.000001   CYd03 =  -0.002832
 x' mom.  Cl'|   Cld01 =  -0.004562   Cld02 =   0.000018   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =  -0.000039   Cmd02 =  -0.027369   Cmd03 =  -0.000185
 z' mom.  Cn'|   Cnd01 =   0.000208   Cnd02 =   0.000002   Cnd03 =   0.001437
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =  -0.000526 CDffd03 =  -0.000140
 span eff.   |    ed01 =  -0.000145    ed02 =   0.043555    ed03 =   0.005290



 Neutral point  Xnp =   0.168327

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
