 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03851     Cltot =   0.00156     Cl'tot =   0.00126
  CYtot =   0.00520     Cmtot =  -0.41253
  CZtot =  -1.38201     Cntot =  -0.00204     Cn'tot =  -0.00223

  CLtot =   1.37392
  CDtot =   0.15420
  CDvis =   0.07000     CDind = 0.0842017
  CLff  =   1.38598     CDff  = 0.0859299    | Trefftz
  CYff  =   0.00383         e =    0.9962    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.630620    CLb =   0.050248
 y  force CY |    CYa =  -0.000816    CYb =  -0.297894
 x' mom.  Cl'|    Cla =   0.004238    Clb =  -0.072142
 y  mom.  Cm |    Cma =  -1.914440    Cmb =  -0.024245
 z' mom.  Cn'|    Cna =  -0.001841    Cnb =   0.127931

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002402    CLq =  10.435893    CLr =  -0.003899
 y  force CY |    CYp =   0.202751    CYq =  -0.011840    CYr =   0.221579
 x' mom.  Cl'|    Clp =  -0.436509    Clq =   0.007998    Clr =   0.327509
 y  mom.  Cm |    Cmp =  -0.000220    Cmq = -19.237793    Cmr =   0.011105
 z' mom.  Cn'|    Cnp =  -0.113898    Cnq =   0.005423    Cnr =  -0.156819

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007865   CLd03 =   0.000015
 y  force CY |   CYd01 =   0.000139   CYd02 =  -0.000000   CYd03 =  -0.002804
 x' mom.  Cl'|   Cld01 =  -0.004283   Cld02 =   0.000005   Cld03 =  -0.000231
 y  mom.  Cm |   Cmd01 =  -0.000015   Cmd02 =  -0.029832   Cmd03 =  -0.000058
 z' mom.  Cn'|   Cnd01 =  -0.000115   Cnd02 =   0.000001   Cnd03 =   0.001521
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000845 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000008    ed02 =   0.001623    ed03 =   0.000391



 Neutral point  Xnp =   0.174587

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
