 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10333     Cltot =   0.00211     Cl'tot =   0.00263
  CYtot =   0.02099     Cmtot =   0.07565
  CZtot =  -0.35472     Cntot =  -0.00761     Cn'tot =  -0.00745

  CLtot =   0.36107
  CDtot =   0.07833
  CDvis =   0.07000     CDind = 0.0083337
  CLff  =   0.36181     CDff  = 0.0095956    | Trefftz
  CYff  =   0.01527         e =    0.6090    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.985627    CLb =   0.063921
 y  force CY |    CYa =  -0.000298    CYb =  -0.299067
 x' mom.  Cl'|    Cla =   0.019161    Clb =  -0.037493
 y  mom.  Cm |    Cma =  -0.801751    Cmb =  -0.012999
 z' mom.  Cn'|    Cna =  -0.000984    Cnb =   0.105977

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.015595    CLq =   8.082839    CLr =  -0.016625
 y  force CY |    CYp =  -0.033516    CYq =  -0.066824    CYr =   0.231286
 x' mom.  Cl'|    Clp =  -0.483712    Clq =   0.005338    Clr =   0.150785
 y  mom.  Cm |    Cmp =  -0.010390    Cmq = -16.263012    Cmr =   0.024469
 z' mom.  Cn'|    Cnp =   0.006152    Cnq =   0.034258    Cnr =  -0.112429

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007861   CLd03 =   0.000070
 y  force CY |   CYd01 =   0.000386   CYd02 =  -0.000001   CYd03 =  -0.002845
 x' mom.  Cl'|   Cld01 =  -0.004549   Cld02 =   0.000018   Cld03 =  -0.000511
 y  mom.  Cm |   Cmd01 =  -0.000039   Cmd02 =  -0.027669   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =   0.000158   Cnd02 =   0.000002   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =  -0.000340 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000260    ed02 =   0.048109    ed03 =   0.008545



 Neutral point  Xnp =   0.171849

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
