 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10253     Cltot =  -0.00163     Cl'tot =  -0.00191
  CYtot =  -0.02108     Cmtot =  -0.06862
  CZtot =  -0.52632     Cntot =   0.00822     Cn'tot =   0.00816

  CLtot =   0.52958
  CDtot =   0.08410
  CDvis =   0.07000     CDind = 0.0141041
  CLff  =   0.53083     CDff  = 0.0154543    | Trefftz
  CYff  =  -0.01532         e =    0.8132    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.933991    CLb =  -0.086881
 y  force CY |    CYa =   0.000447    CYb =  -0.300260
 x' mom.  Cl'|    Cla =  -0.018392    Clb =  -0.027204
 y  mom.  Cm |    Cma =  -1.959109    Cmb =   0.049030
 z' mom.  Cn'|    Cna =   0.001117    Cnb =   0.116153

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012318    CLq =  10.582886    CLr =   0.017455
 y  force CY |    CYp =   0.041624    CYq =   0.047323    CYr =   0.251046
 x' mom.  Cl'|    Clp =  -0.468841    Clq =  -0.027719    Clr =   0.166026
 y  mom.  Cm |    Cmp =   0.008572    Cmq = -19.160720    Cmr =  -0.043558
 z' mom.  Cn'|    Cnp =  -0.029897    Cnq =  -0.026896    Cnr =  -0.135050

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000101   CLd02 =   0.007969   CLd03 =  -0.000068
 y  force CY |   CYd01 =   0.000309   CYd02 =   0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004552   Cld02 =  -0.000019   Cld03 =  -0.000258
 y  mom.  Cm |   Cmd01 =   0.000063   Cmd02 =  -0.029821   Cmd03 =   0.000235
 z' mom.  Cn'|   Cnd01 =   0.000118   Cnd02 =  -0.000002   Cnd03 =   0.001549
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000128 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000157    ed02 =   0.031138    ed03 =  -0.007092



 Neutral point  Xnp =   0.169972

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
