 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09282     Cltot =  -0.00255     Cl'tot =  -0.00255
  CYtot =  -0.02105     Cmtot =  -0.13718
  CZtot =  -0.70119     Cntot =   0.00822     Cn'tot =   0.00822

  CLtot =   0.70119
  CDtot =   0.09282
  CDvis =   0.07000     CDind = 0.0228180
  CLff  =   0.70336     CDff  = 0.0243104    | Trefftz
  CYff  =  -0.01532         e =    0.9073    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.896540    CLb =  -0.110176
 y  force CY |    CYa =   0.001012    CYb =  -0.299897
 x' mom.  Cl'|    Cla =  -0.018270    Clb =  -0.036313
 y  mom.  Cm |    Cma =  -1.967541    Cmb =   0.058619
 z' mom.  Cn'|    Cna =   0.002397    Cnb =   0.117026

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011725    CLq =  10.558025    CLr =   0.017159
 y  force CY |    CYp =   0.074438    CYq =   0.047323    CYr =   0.249575
 x' mom.  Cl'|    Clp =  -0.463974    Clq =  -0.028641    Clr =   0.199375
 y  mom.  Cm |    Cmp =   0.007046    Cmq = -19.214211    Cmr =  -0.043831
 z' mom.  Cn'|    Cnp =  -0.046161    Cnq =  -0.025912    Cnr =  -0.138997

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000100   CLd02 =   0.007990   CLd03 =  -0.000066
 y  force CY |   CYd01 =   0.000275   CYd02 =   0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004516   Cld02 =  -0.000019   Cld03 =  -0.000254
 y  mom.  Cm |   Cmd01 =   0.000062   Cmd02 =  -0.029942   Cmd03 =   0.000235
 z' mom.  Cn'|   Cnd01 =   0.000070   Cnd02 =  -0.000002   Cnd03 =   0.001549
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000068 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000112    ed02 =   0.018060    ed03 =  -0.005051



 Neutral point  Xnp =   0.171314

 Clb Cnr / Clr Cnb  =   0.216329    (  > 1 if spirally stable )
