 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06319     Cltot =  -0.00011     Cl'tot =   0.00048
  CYtot =   0.01050     Cmtot =   0.13874
  CZtot =   0.08530     Cntot =  -0.00379     Cn'tot =  -0.00376

  CLtot =  -0.07436
  CDtot =   0.07575
  CDvis =   0.07000     CDind = 0.0057508
  CLff  =  -0.07520     CDff  = 0.0058085    | Trefftz
  CYff  =   0.00764         e =    0.0438    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.999233    CLb =   0.002330
 y  force CY |    CYa =   0.000555    CYb =  -0.300378
 x' mom.  Cl'|    Cla =   0.009544    Clb =  -0.013813
 y  mom.  Cm |    Cma =  -0.645155    Cmb =  -0.002086
 z' mom.  Cn'|    Cna =   0.001182    Cnb =   0.107620

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008695    CLq =   8.246417    CLr =  -0.008344
 y  force CY |    CYp =  -0.113333    CYq =  -0.033432    CYr =   0.216593
 x' mom.  Cl'|    Clp =  -0.493248    Clq =   0.001167    Clr =   0.064283
 y  mom.  Cm |    Cmp =  -0.006245    Cmq = -15.927893    Cmr =   0.011742
 z' mom.  Cn'|    Cnp =   0.040881    Cnq =   0.017307    Cnr =  -0.101811

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000050   CLd02 =   0.007670   CLd03 =   0.000037
 y  force CY |   CYd01 =   0.000471   CYd02 =  -0.000001   CYd03 =  -0.002810
 x' mom.  Cl'|   Cld01 =  -0.004578   Cld02 =   0.000009   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =  -0.000020   Cmd02 =  -0.026895   Cmd03 =  -0.000092
 z' mom.  Cn'|   Cnd01 =   0.000284   Cnd02 =   0.000001   Cnd03 =   0.001426
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000801 CDffd03 =  -0.000070
 span eff.   |    ed01 =   0.000008    ed02 =  -0.002964    ed03 =   0.000207



 Neutral point  Xnp =   0.162892

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
