 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00758     Cltot =   0.00662     Cl'tot =   0.00552
  CYtot =   0.02603     Cmtot =  -0.34058
  CZtot =  -1.20871     Cntot =  -0.01018     Cn'tot =  -0.01082

  CLtot =   1.20130
  CDtot =   0.13388
  CDvis =   0.07000     CDind = 0.0638818
  CLff  =   1.21329     CDff  = 0.0667359    | Trefftz
  CYff  =   0.01914         e =    0.9832    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.688941    CLb =   0.222598
 y  force CY |    CYa =  -0.003365    CYb =  -0.295782
 x' mom.  Cl'|    Cla =   0.021675    Clb =  -0.062621
 y  mom.  Cm |    Cma =  -1.930085    Cmb =  -0.108930
 z' mom.  Cn'|    Cna =  -0.007665    Cnb =   0.122732

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012606    CLq =  10.440842    CLr =  -0.020032
 y  force CY |    CYp =   0.170916    CYq =  -0.059127    CYr =   0.231215
 x' mom.  Cl'|    Clp =  -0.443281    Clq =   0.038973    Clr =   0.295556
 y  mom.  Cm |    Cmp =  -0.003031    Cmq = -19.207705    Cmr =   0.055384
 z' mom.  Cn'|    Cnp =  -0.096246    Cnq =   0.028458    Cnr =  -0.151716

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000120   CLd02 =   0.007883   CLd03 =   0.000075
 y  force CY |   CYd01 =   0.000171   CYd02 =  -0.000002   CYd03 =  -0.002810
 x' mom.  Cl'|   Cld01 =  -0.004330   Cld02 =   0.000023   Cld03 =  -0.000236
 y  mom.  Cm |   Cmd01 =  -0.000075   Cmd02 =  -0.029784   Cmd03 =  -0.000292
 z' mom.  Cn'|   Cnd01 =  -0.000070   Cnd02 =   0.000003   Cnd03 =   0.001524
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000649 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000054    ed02 =   0.003307    ed03 =   0.002480



 Neutral point  Xnp =   0.174078

 Clb Cnr / Clr Cnb  =   0.261908    (  > 1 if spirally stable )
