 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09494     Cltot =   0.01060     Cl'tot =   0.00883
  CYtot =   0.02551     Cmtot =  -0.16111
  CZtot =  -1.53981     Cntot =  -0.00928     Cn'tot =  -0.01098

  CLtot =   1.53291
  CDtot =   0.17389
  CDvis =   0.07000     CDind = 0.1038882
  CLff  =   1.55777     CDff  = 0.1081377    | Trefftz
  CYff  =   0.01908         e =    1.0002    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.520274    CLb =   0.278644
 y  force CY |    CYa =  -0.005223    CYb =  -0.289915
 x' mom.  Cl'|    Cla =   0.020532    Clb =  -0.100124
 y  mom.  Cm |    Cma =  -1.101685    Cmb =  -0.057691
 z' mom.  Cn'|    Cna =  -0.012308    Cnb =   0.124532

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013693    CLq =   7.423944    CLr =  -0.018580
 y  force CY |    CYp =   0.188799    CYq =  -0.083492    CYr =   0.198673
 x' mom.  Cl'|    Clp =  -0.425551    Clq =   0.016826    Clr =   0.372915
 y  mom.  Cm |    Cmp =  -0.005199    Cmq = -16.596357    Cmr =   0.032805
 z' mom.  Cn'|    Cnp =  -0.101868    Cnq =   0.039918    Cnr =  -0.151814

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000114   CLd02 =   0.007666   CLd03 =   0.000069
 y  force CY |   CYd01 =   0.000144   CYd02 =  -0.000002   CYd03 =  -0.002735
 x' mom.  Cl'|   Cld01 =  -0.004141   Cld02 =   0.000022   Cld03 =  -0.000460
 y  mom.  Cm |   Cmd01 =  -0.000045   Cmd02 =  -0.027800   Cmd03 =  -0.000229
 z' mom.  Cn'|   Cnd01 =  -0.000171   Cnd02 =   0.000003   Cnd03 =   0.001391
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =   0.000960 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000046    ed02 =   0.001149    ed03 =   0.001561



 Neutral point  Xnp =   0.195229

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
