 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06526     Cltot =  -0.00832     Cl'tot =  -0.00663
  CYtot =  -0.02583     Cmtot =  -0.44047
  CZtot =  -1.45089     Cntot =   0.01010     Cn'tot =   0.01128

  CLtot =   1.44324
  CDtot =   0.16251
  CDvis =   0.07000     CDind = 0.0925122
  CLff  =   1.46410     CDff  = 0.0963219    | Trefftz
  CYff  =  -0.01914         e =    0.9919    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.547934    CLb =  -0.263501
 y  force CY |    CYa =   0.004403    CYb =  -0.293475
 x' mom.  Cl'|    Cla =  -0.020755    Clb =  -0.075232
 y  mom.  Cm |    Cma =  -1.882190    Cmb =   0.126410
 z' mom.  Cn'|    Cna =   0.009888    Cnb =   0.127950

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011706    CLq =  10.374679    CLr =   0.019177
 y  force CY |    CYp =   0.217265    CYq =   0.059127    CYr =   0.214740
 x' mom.  Cl'|    Clp =  -0.430444    Clq =  -0.040409    Clr =   0.341392
 y  mom.  Cm |    Cmp =   0.000128    Cmq = -19.138646    Cmr =  -0.055466
 z' mom.  Cn'|    Cnp =  -0.122201    Cnq =  -0.026379    Cnr =  -0.158528

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000117   CLd02 =   0.007760   CLd03 =  -0.000071
 y  force CY |   CYd01 =   0.000121   CYd02 =   0.000002   CYd03 =  -0.002767
 x' mom.  Cl'|   Cld01 =  -0.004209   Cld02 =  -0.000023   Cld03 =  -0.000225
 y  mom.  Cm |   Cmd01 =   0.000073   Cmd02 =  -0.029502   Cmd03 =   0.000290
 z' mom.  Cn'|   Cnd01 =  -0.000135   Cnd02 =  -0.000003   Cnd03 =   0.001502
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000932 CDffd03 =   0.000172
 span eff.   |    ed01 =   0.000037    ed02 =   0.001097    ed03 =  -0.001722



 Neutral point  Xnp =   0.174707

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
