 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12484     Cltot =   0.00568     Cl'tot =   0.00442
  CYtot =   0.01544     Cmtot =  -0.50930
  CZtot =  -1.61407     Cntot =  -0.00604     Cn'tot =  -0.00701

  CLtot =   1.60824
  CDtot =   0.18543
  CDvis =   0.07000     CDind = 0.1154332
  CLff  =   1.63310     CDff  = 0.1191739    | Trefftz
  CYff  =   0.01149         e =    0.9973    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.460036    CLb =   0.174556
 y  force CY |    CYa =  -0.003063    CYb =  -0.293954
 x' mom.  Cl'|    Cla =   0.012048    Clb =  -0.084128
 y  mom.  Cm |    Cma =  -1.847761    Cmb =  -0.082936
 z' mom.  Cn'|    Cna =  -0.006809    Cnb =   0.133452

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006700    CLq =  10.350787    CLr =  -0.011143
 y  force CY |    CYp =   0.247701    CYq =  -0.035505    CYr =   0.201594
 x' mom.  Cl'|    Clp =  -0.421990    Clq =   0.024803    Clr =   0.371821
 y  mom.  Cm |    Cmp =   0.001085    Cmq = -19.110040    Cmr =   0.033289
 z' mom.  Cn'|    Cnp =  -0.140187    Cnq =   0.014984    Cnr =  -0.163494

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000069   CLd02 =   0.007687   CLd03 =   0.000041
 y  force CY |   CYd01 =   0.000089   CYd02 =  -0.000001   CYd03 =  -0.002744
 x' mom.  Cl'|   Cld01 =  -0.004136   Cld02 =   0.000014   Cld03 =  -0.000219
 y  mom.  Cm |   Cmd01 =  -0.000043   Cmd02 =  -0.029368   Cmd03 =  -0.000174
 z' mom.  Cn'|   Cnd01 =  -0.000178   Cnd02 =   0.000002   Cnd03 =   0.001490
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.001122 CDffd03 =  -0.000103
 span eff.   |    ed01 =  -0.000018    ed02 =   0.000229    ed03 =   0.000837



 Neutral point  Xnp =   0.174831

 Clb Cnr / Clr Cnb  =   0.277193    (  > 1 if spirally stable )
