 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07510     Cltot =  -0.00030     Cl'tot =  -0.00162
  CYtot =  -0.02618     Cmtot =   0.12745
  CZtot =  -0.00178     Cntot =   0.00946     Cn'tot =   0.00932

  CLtot =   0.01221
  CDtot =   0.07412
  CDvis =   0.07000     CDind = 0.0041193
  CLff  =   0.01235     CDff  = 0.0055967    | Trefftz
  CYff  =  -0.01908         e =    0.0041    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.976140    CLb =  -0.020587
 y  force CY |    CYa =  -0.001031    CYb =  -0.297447
 x' mom.  Cl'|    Cla =  -0.023845    Clb =  -0.018349
 y  mom.  Cm |    Cma =  -0.674460    Cmb =   0.007201
 z' mom.  Cn'|    Cna =  -0.002111    Cnb =   0.105743

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.021269    CLq =   8.194417    CLr =   0.020857
 y  force CY |    CYp =  -0.097300    CYq =   0.083492    CYr =   0.220020
 x' mom.  Cl'|    Clp =  -0.490507    Clq =  -0.003667    Clr =   0.081542
 y  mom.  Cm |    Cmp =   0.015082    Cmq = -15.959470    Cmr =  -0.029592
 z' mom.  Cn'|    Cnp =   0.033950    Cnq =  -0.043164    Cnr =  -0.103445

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000124   CLd02 =   0.007676   CLd03 =  -0.000090
 y  force CY |   CYd01 =   0.000452   CYd02 =   0.000002   CYd03 =  -0.002805
 x' mom.  Cl'|   Cld01 =  -0.004552   Cld02 =  -0.000022   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =   0.000049   Cmd02 =  -0.026929   Cmd03 =   0.000230
 z' mom.  Cn'|   Cnd01 =   0.000258   Cnd02 =  -0.000003   Cnd03 =   0.001423
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =  -0.000707 CDffd03 =   0.000174
 span eff.   |    ed01 =  -0.000061    ed02 =   0.002056    ed03 =   0.000702



 Neutral point  Xnp =   0.164722

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
