 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08478     Cltot =   0.00226     Cl'tot =   0.00216
  CYtot =   0.01579     Cmtot =  -0.17250
  CZtot =  -0.78991     Cntot =  -0.00617     Cn'tot =  -0.00621

  CLtot =   0.78831
  CDtot =   0.09855
  CDvis =   0.07000     CDind = 0.0285540
  CLff  =   0.79016     CDff  = 0.0296454    | Trefftz
  CYff  =   0.01149         e =    0.9387    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.882634    CLb =   0.091436
 y  force CY |    CYa =  -0.000972    CYb =  -0.300672
 x' mom.  Cl'|    Cla =   0.013650    Clb =  -0.041015
 y  mom.  Cm |    Cma =  -1.972370    Cmb =  -0.047635
 z' mom.  Cn'|    Cna =  -0.002278    Cnb =   0.118206

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008580    CLq =  10.555044    CLr =  -0.012751
 y  force CY |    CYp =   0.090884    CYq =  -0.035505    CYr =   0.248246
 x' mom.  Cl'|    Clp =  -0.461679    Clq =   0.021824    Clr =   0.216088
 y  mom.  Cm |    Cmp =  -0.004712    Cmq = -19.252722    Cmr =   0.032972
 z' mom.  Cn'|    Cnp =  -0.054435    Cnq =   0.019063    Cnr =  -0.141201

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000075   CLd02 =   0.008008   CLd03 =   0.000049
 y  force CY |   CYd01 =   0.000258   CYd02 =  -0.000001   CYd03 =  -0.002861
 x' mom.  Cl'|   Cld01 =  -0.004503   Cld02 =   0.000014   Cld03 =  -0.000252
 y  mom.  Cm |   Cmd01 =  -0.000046   Cmd02 =  -0.030039   Cmd03 =  -0.000177
 z' mom.  Cn'|   Cnd01 =   0.000046   Cnd02 =   0.000002   Cnd03 =   0.001551
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000166 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000071    ed02 =   0.013735    ed03 =   0.003221



 Neutral point  Xnp =   0.171916

 Clb Cnr / Clr Cnb  =   0.226729    (  > 1 if spirally stable )
