 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10008     Cltot =  -0.00012     Cl'tot =  -0.00047
  CYtot =  -0.01056     Cmtot =   0.03234
  CZtot =  -0.26396     Cntot =   0.00411     Cn'tot =   0.00409

  CLtot =   0.27168
  CDtot =   0.07669
  CDvis =   0.07000     CDind = 0.0066912
  CLff  =   0.27139     CDff  = 0.0070271    | Trefftz
  CYff  =  -0.00766         e =    0.4675    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.981100    CLb =  -0.025890
 y  force CY |    CYa =  -0.000201    CYb =  -0.302103
 x' mom.  Cl'|    Cla =  -0.009227    Clb =  -0.013580
 y  mom.  Cm |    Cma =  -1.935659    Cmb =   0.017434
 z' mom.  Cn'|    Cna =  -0.000407    Cnb =   0.116895

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006625    CLq =  10.630335    CLr =   0.008916
 y  force CY |    CYp =  -0.007603    CYq =   0.023676    CYr =   0.249412
 x' mom.  Cl'|    Clp =  -0.475174    Clq =  -0.013145    Clr =   0.115407
 y  mom.  Cm |    Cmp =   0.005423    Cmq = -19.071602    Cmr =  -0.021538
 z' mom.  Cn'|    Cnp =  -0.005889    Cnq =  -0.014164    Cnr =  -0.129822

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000051   CLd02 =   0.007921   CLd03 =  -0.000035
 y  force CY |   CYd01 =   0.000361   CYd02 =   0.000001   CYd03 =  -0.002853
 x' mom.  Cl'|   Cld01 =  -0.004602   Cld02 =  -0.000009   Cld03 =  -0.000265
 y  mom.  Cm |   Cmd01 =   0.000032   Cmd02 =  -0.029613   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000192   Cnd02 =  -0.000001   Cnd03 =   0.001546
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000420 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000094    ed02 =   0.055355    ed03 =  -0.004365



 Neutral point  Xnp =   0.167585

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
