 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10024     Cltot =   0.00006     Cl'tot =   0.00024
  CYtot =   0.00528     Cmtot =   0.03211
  CZtot =  -0.26428     Cntot =  -0.00206     Cn'tot =  -0.00204

  CLtot =   0.27201
  CDtot =   0.07682
  CDvis =   0.07000     CDind = 0.0068236
  CLff  =   0.27151     CDff  = 0.0069634    | Trefftz
  CYff  =   0.00383         e =    0.4719    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.985528    CLb =   0.012953
 y  force CY |    CYa =   0.000100    CYb =  -0.302560
 x' mom.  Cl'|    Cla =   0.004616    Clb =  -0.013605
 y  mom.  Cm |    Cma =  -1.937429    Cmb =  -0.008722
 z' mom.  Cn'|    Cna =   0.000204    Cnb =   0.117109

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003313    CLq =  10.635194    CLr =  -0.004458
 y  force CY |    CYp =  -0.007607    CYq =  -0.011840    CYr =   0.249526
 x' mom.  Cl'|    Clp =  -0.475392    Clq =   0.006573    Clr =   0.115460
 y  mom.  Cm |    Cmp =  -0.002712    Cmq = -19.080321    Cmr =   0.010771
 z' mom.  Cn'|    Cnp =  -0.005891    Cnq =   0.007083    Cnr =  -0.129881

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007928   CLd03 =   0.000018
 y  force CY |   CYd01 =   0.000362   CYd02 =  -0.000000   CYd03 =  -0.002856
 x' mom.  Cl'|   Cld01 =  -0.004606   Cld02 =   0.000005   Cld03 =  -0.000265
 y  mom.  Cm |   Cmd01 =  -0.000016   Cmd02 =  -0.029640   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =   0.000193   Cnd02 =   0.000001   Cnd03 =   0.001547
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000421 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000048    ed02 =   0.056181    ed03 =   0.002226



 Neutral point  Xnp =   0.167588

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
