 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09923     Cltot =   0.00157     Cl'tot =   0.00168
  CYtot =   0.01582     Cmtot =  -0.10369
  CZtot =  -0.61542     Cntot =  -0.00618     Cn'tot =  -0.00615

  CLtot =   0.61705
  CDtot =   0.08847
  CDvis =   0.07000     CDind = 0.0184713
  CLff  =   0.61785     CDff  = 0.0194224    | Trefftz
  CYff  =   0.01149         e =    0.8762    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.927236    CLb =   0.074020
 y  force CY |    CYa =  -0.000548    CYb =  -0.301177
 x' mom.  Cl'|    Cla =   0.013776    Clb =  -0.031902
 y  mom.  Cm |    Cma =  -1.968721    Cmb =  -0.040422
 z' mom.  Cn'|    Cna =  -0.001320    Cnb =   0.117011

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009017    CLq =  10.582355    CLr =  -0.012989
 y  force CY |    CYp =   0.058106    CYq =  -0.035505    CYr =   0.250865
 x' mom.  Cl'|    Clp =  -0.467026    Clq =   0.021146    Clr =   0.182956
 y  mom.  Cm |    Cmp =  -0.005860    Cmq = -19.210885    Cmr =   0.032787
 z' mom.  Cn'|    Cnp =  -0.038042    Cnq =   0.019813    Cnr =  -0.137142

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000075   CLd02 =   0.007999   CLd03 =   0.000051
 y  force CY |   CYd01 =   0.000292   CYd02 =  -0.000001   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004545   Cld02 =   0.000014   Cld03 =  -0.000256
 y  mom.  Cm |   Cmd01 =  -0.000047   Cmd02 =  -0.029955   Cmd03 =  -0.000177
 z' mom.  Cn'|   Cnd01 =   0.000094   Cnd02 =   0.000002   Cnd03 =   0.001553
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000030 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000102    ed02 =   0.024012    ed03 =   0.004580



 Neutral point  Xnp =   0.170676

 Clb Cnr / Clr Cnb  =   0.204371    (  > 1 if spirally stable )
