 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08559     Cltot =  -0.00070     Cl'tot =   0.00031
  CYtot =   0.02105     Cmtot =   0.10004
  CZtot =  -0.08721     Cntot =  -0.00818     Cn'tot =  -0.00820

  CLtot =   0.09699
  CDtot =   0.07433
  CDvis =   0.07000     CDind = 0.0043271
  CLff  =   0.09715     CDff  = 0.0052800    | Trefftz
  CYff  =   0.01532         e =    0.0816    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.965060    CLb =   0.028078
 y  force CY |    CYa =   0.000966    CYb =  -0.299938
 x' mom.  Cl'|    Cla =   0.018307    Clb =  -0.004358
 y  mom.  Cm |    Cma =  -1.896473    Cmb =  -0.025443
 z' mom.  Cn'|    Cna =   0.002094    Cnb =   0.116762

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013878    CLq =  10.623267    CLr =  -0.018009
 y  force CY |    CYp =  -0.040160    CYq =  -0.047323    CYr =   0.244707
 x' mom.  Cl'|    Clp =  -0.476687    Clq =   0.025269    Clr =   0.080897
 y  mom.  Cm |    Cmp =  -0.012335    Cmq = -18.925074    Cmr =   0.042645
 z' mom.  Cn'|    Cnp =   0.009919    Cnq =   0.029210    Cnr =  -0.126283

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000101   CLd02 =   0.007811   CLd03 =   0.000072
 y  force CY |   CYd01 =   0.000393   CYd02 =  -0.000001   CYd03 =  -0.002825
 x' mom.  Cl'|   Cld01 =  -0.004593   Cld02 =   0.000018   Cld03 =  -0.000267
 y  mom.  Cm |   Cmd01 =  -0.000064   Cmd02 =  -0.029206   Cmd03 =  -0.000234
 z' mom.  Cn'|   Cnd01 =   0.000241   Cnd02 =   0.000002   Cnd03 =   0.001530
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000610 CDffd03 =  -0.000138
 span eff.   |    ed01 =  -0.000007    ed02 =   0.022401    ed03 =   0.001432



 Neutral point  Xnp =   0.165714

 Clb Cnr / Clr Cnb  =   0.058262    (  > 1 if spirally stable )
