 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10348     Cltot =  -0.00035     Cl'tot =  -0.00064
  CYtot =  -0.01056     Cmtot =  -0.00156
  CZtot =  -0.35220     Cntot =   0.00412     Cn'tot =   0.00408

  CLtot =   0.35856
  CDtot =   0.07866
  CDvis =   0.07000     CDind = 0.0086613
  CLff  =   0.35831     CDff  = 0.0090719    | Trefftz
  CYff  =  -0.00766         e =    0.6310    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.974853    CLb =  -0.031789
 y  force CY |    CYa =  -0.000059    CYb =  -0.302168
 x' mom.  Cl'|    Cla =  -0.009235    Clb =  -0.018188
 y  mom.  Cm |    Cma =  -1.948247    Cmb =   0.019801
 z' mom.  Cn'|    Cna =  -0.000085    Cnb =   0.116772

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006469    CLq =  10.622234    CLr =   0.008860
 y  force CY |    CYp =   0.008804    CYq =   0.023676    CYr =   0.250683
 x' mom.  Cl'|    Clp =  -0.473599    Clq =  -0.013390    Clr =   0.132475
 y  mom.  Cm |    Cmp =   0.005046    Cmq = -19.118832    Cmr =  -0.021629
 z' mom.  Cn'|    Cnp =  -0.013863    Cnq =  -0.013932    Cnr =  -0.131581

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000051   CLd02 =   0.007953   CLd03 =  -0.000035
 y  force CY |   CYd01 =   0.000344   CYd02 =   0.000001   CYd03 =  -0.002859
 x' mom.  Cl'|   Cld01 =  -0.004594   Cld02 =  -0.000009   Cld03 =  -0.000263
 y  mom.  Cm |   Cmd01 =   0.000032   Cmd02 =  -0.029737   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000168   Cnd02 =  -0.000001   Cnd03 =   0.001550
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000324 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000102    ed02 =   0.050556    ed03 =  -0.004643



 Neutral point  Xnp =   0.168437

 Clb Cnr / Clr Cnb  =   0.154708    (  > 1 if spirally stable )
