 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04700     Cltot =  -0.00260     Cl'tot =  -0.00080
  CYtot =   0.02619     Cmtot =   0.19794
  CZtot =   0.17313     Cntot =  -0.01014     Cn'tot =  -0.01044

  CLtot =  -0.16234
  CDtot =   0.07635
  CDvis =   0.07000     CDind = 0.0063525
  CLff  =  -0.16341     CDff  = 0.0076614    | Trefftz
  CYff  =   0.01914         e =    0.1574    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.927512    CLb =  -0.009040
 y  force CY |    CYa =   0.002259    CYb =  -0.297544
 x' mom.  Cl'|    Cla =   0.022443    Clb =   0.009126
 y  mom.  Cm |    Cma =  -1.826014    Cmb =  -0.014701
 z' mom.  Cn'|    Cna =   0.004986    Cnb =   0.118377

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.018556    CLq =  10.617594    CLr =  -0.022750
 y  force CY |    CYp =  -0.088142    CYq =  -0.059127    CYr =   0.233780
 x' mom.  Cl'|    Clp =  -0.477663    Clq =   0.029619    Clr =   0.029008
 y  mom.  Cm |    Cmp =  -0.018179    Cmq = -18.688702    Cmr =   0.052403
 z' mom.  Cn'|    Cnp =   0.033311    Cnq =   0.038098    Cnr =  -0.121726

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000126   CLd02 =   0.007626   CLd03 =   0.000092
 y  force CY |   CYd01 =   0.000441   CYd02 =  -0.000002   CYd03 =  -0.002777
 x' mom.  Cl'|   Cld01 =  -0.004572   Cld02 =   0.000023   Cld03 =  -0.000269
 y  mom.  Cm |   Cmd01 =  -0.000080   Cmd02 =  -0.028549   Cmd03 =  -0.000289
 z' mom.  Cn'|   Cnd01 =   0.000313   Cnd02 =   0.000003   Cnd03 =   0.001504
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =  -0.000888 CDffd03 =  -0.000171
 span eff.   |    ed01 =  -0.000047    ed02 =   0.003365    ed03 =   0.002917



 Neutral point  Xnp =   0.162502

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
