 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04718     Cltot =  -0.00086     Cl'tot =   0.00079
  CYtot =   0.02613     Cmtot =   0.14982
  CZtot =   0.17199     Cntot =  -0.00942     Cn'tot =  -0.00943

  CLtot =  -0.16119
  CDtot =   0.07633
  CDvis =   0.07000     CDind = 0.0063253
  CLff  =  -0.16226     CDff  = 0.0076382    | Trefftz
  CYff  =   0.01908         e =    0.1557    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.956591    CLb =  -0.008961
 y  force CY |    CYa =   0.001731    CYb =  -0.296900
 x' mom.  Cl'|    Cla =   0.023640    Clb =  -0.008944
 y  mom.  Cm |    Cma =  -0.606829    Cmb =  -0.003287
 z' mom.  Cn'|    Cna =   0.003770    Cnb =   0.106908

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.022161    CLq =   8.243589    CLr =  -0.020806
 y  force CY |    CYp =  -0.128488    CYq =  -0.083492    CYr =   0.211235
 x' mom.  Cl'|    Clp =  -0.492548    Clq =   0.002158    Clr =   0.046554
 y  mom.  Cm |    Cmp =  -0.016106    Cmq = -15.789603    Cmr =   0.029048
 z' mom.  Cn'|    Cnp =   0.047499    Cnq =   0.043266    Cnr =  -0.099633

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000123   CLd02 =   0.007561   CLd03 =   0.000091
 y  force CY |   CYd01 =   0.000484   CYd02 =  -0.000002   CYd03 =  -0.002778
 x' mom.  Cl'|   Cld01 =  -0.004542   Cld02 =   0.000022   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =  -0.000050   Cmd02 =  -0.026502   Cmd03 =  -0.000229
 z' mom.  Cn'|   Cnd01 =   0.000307   Cnd02 =   0.000003   Cnd03 =   0.001409
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000885 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000070    ed02 =   0.003351    ed03 =   0.002931



 Neutral point  Xnp =   0.161025

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
