 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09981     Cltot =   0.00017     Cl'tot =   0.00071
  CYtot =   0.01583     Cmtot =   0.03272
  CZtot =  -0.26341     Cntot =  -0.00616     Cn'tot =  -0.00612

  CLtot =   0.27111
  CDtot =   0.07647
  CDvis =   0.07000     CDind = 0.0064707
  CLff  =   0.27118     CDff  = 0.0071333    | Trefftz
  CYff  =   0.01149         e =    0.4603    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.973724    CLb =   0.038795
 y  force CY |    CYa =   0.000301    CYb =  -0.301342
 x' mom.  Cl'|    Cla =   0.013826    Clb =  -0.013538
 y  mom.  Cm |    Cma =  -1.932711    Cmb =  -0.026124
 z' mom.  Cn'|    Cna =   0.000610    Cnb =   0.116538

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009935    CLq =  10.622237    CLr =  -0.013370
 y  force CY |    CYp =  -0.007597    CYq =  -0.035505    CYr =   0.249222
 x' mom.  Cl'|    Clp =  -0.474813    Clq =   0.019712    Clr =   0.115319
 y  mom.  Cm |    Cmp =  -0.008132    Cmq = -19.057074    Cmr =   0.032299
 z' mom.  Cn'|    Cnp =  -0.005884    Cnq =   0.021240    Cnr =  -0.129723

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007909   CLd03 =   0.000053
 y  force CY |   CYd01 =   0.000361   CYd02 =  -0.000001   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004595   Cld02 =   0.000014   Cld03 =  -0.000264
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.029568   Cmd03 =  -0.000176
 z' mom.  Cn'|   Cnd01 =   0.000192   Cnd02 =   0.000002   Cnd03 =   0.001544
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000420 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000136    ed02 =   0.054025    ed03 =   0.006338



 Neutral point  Xnp =   0.167581

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
