 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10398     Cltot =   0.00106     Cl'tot =   0.00132
  CYtot =   0.01052     Cmtot =   0.07531
  CZtot =  -0.35636     Cntot =  -0.00382     Cn'tot =  -0.00373

  CLtot =   0.36274
  CDtot =   0.07887
  CDvis =   0.07000     CDind = 0.0088732
  CLff  =   0.36248     CDff  = 0.0093429    | Trefftz
  CYff  =   0.00764         e =    0.6270    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.003395    CLb =   0.032039
 y  force CY |    CYa =  -0.000149    CYb =  -0.300884
 x' mom.  Cl'|    Cla =   0.009604    Clb =  -0.037769
 y  mom.  Cm |    Cma =  -0.804691    Cmb =  -0.006515
 z' mom.  Cn'|    Cna =  -0.000493    Cnb =   0.106758

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.007802    CLq =   8.097640    CLr =  -0.008318
 y  force CY |    CYp =  -0.033577    CYq =  -0.033432    CYr =   0.231710
 x' mom.  Cl'|    Clp =  -0.484598    Clq =   0.002670    Clr =   0.151062
 y  mom.  Cm |    Cmp =  -0.005198    Cmq = -16.292793    Cmr =   0.012242
 z' mom.  Cn'|    Cnp =   0.006163    Cnq =   0.017140    Cnr =  -0.112635

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000050   CLd02 =   0.007890   CLd03 =   0.000035
 y  force CY |   CYd01 =   0.000387   CYd02 =  -0.000001   CYd03 =  -0.002855
 x' mom.  Cl'|   Cld01 =  -0.004566   Cld02 =   0.000009   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =  -0.000020   Cmd02 =  -0.027771   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =   0.000159   Cnd02 =   0.000001   Cnd03 =   0.001450
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000342 CDffd03 =  -0.000071
 span eff.   |    ed01 =  -0.000138    ed02 =   0.050247    ed03 =   0.004534



 Neutral point  Xnp =   0.171854

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
