 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06297     Cltot =  -0.00017     Cl'tot =   0.00072
  CYtot =   0.01574     Cmtot =   0.13878
  CZtot =   0.08531     Cntot =  -0.00568     Cn'tot =  -0.00564

  CLtot =  -0.07441
  CDtot =   0.07554
  CDvis =   0.07000     CDind = 0.0055442
  CLff  =  -0.07515     CDff  = 0.0059193    | Trefftz
  CYff  =   0.01146         e =    0.0435    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.991818    CLb =   0.003492
 y  force CY |    CYa =   0.000831    CYb =  -0.299622
 x' mom.  Cl'|    Cla =   0.014301    Clb =  -0.013771
 y  mom.  Cm |    Cma =  -0.644172    Cmb =  -0.003126
 z' mom.  Cn'|    Cna =   0.001771    Cnb =   0.107291

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013040    CLq =   8.240135    CLr =  -0.012514
 y  force CY |    CYp =  -0.113247    CYq =  -0.050136    CYr =   0.216428
 x' mom.  Cl'|    Clp =  -0.492873    Clq =   0.001749    Clr =   0.064234
 y  mom.  Cm |    Cmp =  -0.009365    Cmq = -15.915760    Cmr =   0.017609
 z' mom.  Cn'|    Cnp =   0.040849    Cnq =   0.025954    Cnr =  -0.101734

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000074   CLd02 =   0.007658   CLd03 =   0.000055
 y  force CY |   CYd01 =   0.000470   CYd02 =  -0.000001   CYd03 =  -0.002806
 x' mom.  Cl'|   Cld01 =  -0.004571   Cld02 =   0.000013   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =  -0.000030   Cmd02 =  -0.026854   Cmd03 =  -0.000138
 z' mom.  Cn'|   Cnd01 =   0.000284   Cnd02 =   0.000002   Cnd03 =   0.001424
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000800 CDffd03 =  -0.000105
 span eff.   |    ed01 =   0.000012    ed02 =  -0.002949    ed03 =   0.000298



 Neutral point  Xnp =   0.162891

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
