 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07354     Cltot =  -0.00609     Cl'tot =  -0.00576
  CYtot =  -0.02605     Cmtot =  -0.01642
  CZtot =  -0.87881     Cntot =   0.00947     Cn'tot =   0.00968

  CLtot =   0.87571
  CDtot =   0.10417
  CDvis =   0.07000     CDind = 0.0341664
  CLff  =   0.88093     CDff  = 0.0364912    | Trefftz
  CYff  =  -0.01908         e =    0.9482    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.859436    CLb =  -0.167395
 y  force CY |    CYa =   0.002471    CYb =  -0.296018
 x' mom.  Cl'|    Cla =  -0.023130    Clb =  -0.065324
 y  mom.  Cm |    Cma =  -0.957331    Cmb =   0.032374
 z' mom.  Cn'|    Cna =   0.006172    Cnb =   0.109803

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.016875    CLq =   7.831669    CLr =   0.020182
 y  force CY |    CYp =   0.063575    CYq =   0.083492    CYr =   0.230516
 x' mom.  Cl'|    Clp =  -0.463905    Clq =  -0.011107    Clr =   0.250372
 y  mom.  Cm |    Cmp =   0.009714    Cmq = -16.513836    Cmr =  -0.031762
 z' mom.  Cn'|    Cnp =  -0.037861    Cnq =  -0.041872    Cnr =  -0.128038

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000121   CLd02 =   0.007908   CLd03 =  -0.000080
 y  force CY |   CYd01 =   0.000281   CYd02 =   0.000002   CYd03 =  -0.002834
 x' mom.  Cl'|   Cld01 =  -0.004430   Cld02 =  -0.000023   Cld03 =  -0.000496
 y  mom.  Cm |   Cmd01 =   0.000048   Cmd02 =  -0.028092   Cmd03 =   0.000232
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =  -0.000003   Cnd03 =   0.001440
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =   0.000224 CDffd03 =   0.000176
 span eff.   |    ed01 =   0.000135    ed02 =   0.011194    ed03 =  -0.004444



 Neutral point  Xnp =   0.182055

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
