 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09508     Cltot =   0.00213     Cl'tot =   0.00177
  CYtot =   0.00512     Cmtot =  -0.16353
  CZtot =  -1.55167     Cntot =  -0.00186     Cn'tot =  -0.00221

  CLtot =   1.54461
  CDtot =   0.17581
  CDvis =   0.07000     CDind = 0.1058120
  CLff  =   1.56348     CDff  = 0.1083552    | Trefftz
  CYff  =   0.00382         e =    1.0053    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.552326    CLb =   0.056001
 y  force CY |    CYa =  -0.001050    CYb =  -0.293431
 x' mom.  Cl'|    Cla =   0.004127    Clb =  -0.101607
 y  mom.  Cm |    Cma =  -1.109780    Cmb =  -0.011595
 z' mom.  Cn'|    Cna =  -0.002474    Cnb =   0.126376

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002742    CLq =   7.451167    CLr =  -0.003721
 y  force CY |    CYp =   0.189492    CYq =  -0.016719    CYr =   0.199401
 x' mom.  Cl'|    Clp =  -0.427112    Clq =   0.003369    Clr =   0.374282
 y  mom.  Cm |    Cmp =  -0.001041    Cmq = -16.657215    Cmr =   0.006569
 z' mom.  Cn'|    Cnp =  -0.102241    Cnq =   0.007993    Cnr =  -0.152371

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000023   CLd02 =   0.007722   CLd03 =   0.000014
 y  force CY |   CYd01 =   0.000145   CYd02 =  -0.000000   CYd03 =  -0.002755
 x' mom.  Cl'|   Cld01 =  -0.004171   Cld02 =   0.000004   Cld03 =  -0.000464
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.028004   Cmd03 =  -0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000173   Cnd02 =   0.000001   Cnd03 =   0.001401
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000967 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000009    ed02 =   0.001109    ed03 =   0.000315



 Neutral point  Xnp =   0.195247

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
