 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03850     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.41274
  CZtot =  -1.38246     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   1.37436
  CDtot =   0.15428
  CDvis =   0.07000     CDind = 0.0842751
  CLff  =   1.38619     CDff  = 0.0859327    | Trefftz
  CYff  =   0.00000         e =    0.9965    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.631983    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.298043
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.072186
 y  mom.  Cm |    Cma =  -1.915024    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.128009

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.437483    CLr =   0.000000
 y  force CY |    CYp =   0.202782    CYq =  -0.000000    CYr =   0.221613
 x' mom.  Cl'|    Clp =  -0.436576    Clq =  -0.000000    Clr =   0.327559
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.240723    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.113915    Cnq =   0.000000    Cnr =  -0.156843

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007867   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000139   CYd02 =   0.000000   CYd03 =  -0.002804
 x' mom.  Cl'|   Cld01 =  -0.004284   Cld02 =   0.000000   Cld03 =  -0.000231
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029841   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000115   Cnd02 =  -0.000000   Cnd03 =   0.001522
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000845 CDffd03 =   0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.001621    ed03 =  -0.000000



 Neutral point  Xnp =   0.174589

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
