 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07549     Cltot =  -0.00087     Cl'tot =  -0.00001
  CYtot =   0.01579     Cmtot =   0.13265
  CZtot =  -0.00012     Cntot =  -0.00613     Cn'tot =  -0.00619

  CLtot =   0.01062
  CDtot =   0.07474
  CDvis =   0.07000     CDind = 0.0047377
  CLff  =   0.01023     CDff  = 0.0051653    | Trefftz
  CYff  =   0.01149         e =    0.0020    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.970822    CLb =   0.012235
 y  force CY |    CYa =   0.000937    CYb =  -0.300725
 x' mom.  Cl'|    Cla =   0.013686    Clb =   0.000180
 y  mom.  Cm |    Cma =  -1.880951    Cmb =  -0.015650
 z' mom.  Cn'|    Cna =   0.002052    Cnb =   0.117865

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010654    CLq =  10.638880    CLr =  -0.013570
 y  force CY |    CYp =  -0.056375    CYq =  -0.035505    CYr =   0.241990
 x' mom.  Cl'|    Clp =  -0.478002    Clq =   0.018573    Clr =   0.063724
 y  mom.  Cm |    Cmp =  -0.009812    Cmq = -18.880729    Cmr =   0.031829
 z' mom.  Cn'|    Cnp =   0.017781    Cnq =   0.022243    Cnr =  -0.124876

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007779   CLd03 =   0.000054
 y  force CY |   CYd01 =   0.000411   CYd02 =  -0.000001   CYd03 =  -0.002819
 x' mom.  Cl'|   Cld01 =  -0.004603   Cld02 =   0.000014   Cld03 =  -0.000268
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.029092   Cmd03 =  -0.000175
 z' mom.  Cn'|   Cnd01 =   0.000266   Cnd02 =   0.000002   Cnd03 =   0.001527
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000706 CDffd03 =  -0.000104
 span eff.   |    ed01 =   0.000033    ed02 =   0.001672    ed03 =  -0.000502



 Neutral point  Xnp =   0.164708

 Clb Cnr / Clr Cnb  =  -0.002990    (  > 1 if spirally stable )
