 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15896     Cltot =  -0.01170     Cl'tot =  -0.00953
  CYtot =  -0.02532     Cmtot =  -0.19998
  CZtot =  -1.69266     Cntot =   0.00920     Cn'tot =   0.01143

  CLtot =   1.68872
  CDtot =   0.19644
  CDvis =   0.07000     CDind = 0.1264416
  CLff  =   1.72274     CDff  = 0.1319437    | Trefftz
  CYff  =  -0.01908         e =    1.0025    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.405281    CLb =  -0.304937
 y  force CY |    CYa =   0.005898    CYb =  -0.287713
 x' mom.  Cl'|    Cla =  -0.019624    Clb =  -0.108077
 y  mom.  Cm |    Cma =  -1.124733    Cmb =   0.064494
 z' mom.  Cn'|    Cna =   0.013710    Cnb =   0.129685

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012977    CLq =   7.309580    CLr =   0.018046
 y  force CY |    CYp =   0.218337    CYq =   0.083492    CYr =   0.185356
 x' mom.  Cl'|    Clp =  -0.414077    Clq =  -0.018209    Clr =   0.401211
 y  mom.  Cm |    Cmp =   0.004051    Cmq = -16.566438    Cmr =  -0.032966
 z' mom.  Cn'|    Cnp =  -0.118903    Cnq =  -0.039307    Cnr =  -0.157872

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000111   CLd02 =   0.007548   CLd03 =  -0.000066
 y  force CY |   CYd01 =   0.000110   CYd02 =   0.000002   CYd03 =  -0.002693
 x' mom.  Cl'|   Cld01 =  -0.004044   Cld02 =  -0.000022   Cld03 =  -0.000449
 y  mom.  Cm |   Cmd01 =   0.000044   Cmd02 =  -0.027557   Cmd03 =   0.000227
 z' mom.  Cn'|   Cnd01 =  -0.000213   Cnd02 =  -0.000003   Cnd03 =   0.001370
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =   0.001135 CDffd03 =   0.000172
 span eff.   |    ed01 =   0.000037    ed02 =   0.000407    ed03 =  -0.001274



 Neutral point  Xnp =   0.198499

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
