 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10029     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.03203
  CZtot =  -0.26439     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.27213
  CDtot =   0.07687
  CDvis =   0.07000     CDind = 0.0068677
  CLff  =   0.27156     CDff  = 0.0069421    | Trefftz
  CYff  =  -0.00000         e =    0.4734    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.987005    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.302712
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.013613
 y  mom.  Cm |    Cma =  -1.938019    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.117180

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.636814    CLr =   0.000000
 y  force CY |    CYp =  -0.007608    CYq =   0.000000    CYr =   0.249564
 x' mom.  Cl'|    Clp =  -0.475464    Clq =  -0.000000    Clr =   0.115478
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -19.083227    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.005892    Cnq =  -0.000000    Cnr =  -0.129901

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007931   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000362   CYd02 =   0.000000   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004608   Cld02 =   0.000000   Cld03 =  -0.000265
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029649   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =   0.000193   Cnd02 =  -0.000000   Cnd03 =   0.001548
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000421 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.056461    ed03 =   0.000000



 Neutral point  Xnp =   0.167589

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
