 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15918     Cltot =  -0.00938     Cl'tot =  -0.00764
  CYtot =  -0.02029     Cmtot =  -0.20099
  CZtot =  -1.69751     Cntot =   0.00738     Cn'tot =   0.00916

  CLtot =   1.69351
  CDtot =   0.19723
  CDvis =   0.07000     CDind = 0.1272294
  CLff  =   1.72511     CDff  = 0.1320906    | Trefftz
  CYff  =  -0.01527         e =    1.0041    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.416960    CLb =  -0.244396
 y  force CY |    CYa =   0.004727    CYb =  -0.289018
 x' mom.  Cl'|    Cla =  -0.015728    Clb =  -0.108676
 y  mom.  Cm |    Cma =  -1.127827    Cmb =   0.051689
 z' mom.  Cn'|    Cna =   0.010988    Cnb =   0.130404

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010386    CLq =   7.319628    CLr =   0.014443
 y  force CY |    CYp =   0.218638    CYq =   0.066824    CYr =   0.185611
 x' mom.  Cl'|    Clp =  -0.414646    Clq =  -0.014574    Clr =   0.401763
 y  mom.  Cm |    Cmp =   0.003243    Cmq = -16.589210    Cmr =  -0.026385
 z' mom.  Cn'|    Cnp =  -0.119067    Cnq =  -0.031460    Cnr =  -0.158089

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000089   CLd02 =   0.007569   CLd03 =  -0.000053
 y  force CY |   CYd01 =   0.000111   CYd02 =   0.000001   CYd03 =  -0.002701
 x' mom.  Cl'|   Cld01 =  -0.004055   Cld02 =  -0.000018   Cld03 =  -0.000450
 y  mom.  Cm |   Cmd01 =   0.000036   Cmd02 =  -0.027633   Cmd03 =   0.000182
 z' mom.  Cn'|   Cnd01 =  -0.000213   Cnd02 =  -0.000002   Cnd03 =   0.001374
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.001138 CDffd03 =   0.000138
 span eff.   |    ed01 =   0.000030    ed02 =   0.000394    ed03 =  -0.001022



 Neutral point  Xnp =   0.198506

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
