 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06031     Cltot =   0.00491     Cl'tot =   0.00437
  CYtot =   0.02618     Cmtot =  -0.23873
  CZtot =  -0.95718     Cntot =  -0.01024     Cn'tot =  -0.01048

  CLtot =   0.95271
  CDtot =   0.11032
  CDvis =   0.07000     CDind = 0.0403211
  CLff  =   0.95916     CDff  = 0.0426922    | Trefftz
  CYff  =   0.01914         e =    0.9607    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.801361    CLb =   0.180498
 y  force CY |    CYa =  -0.002317    CYb =  -0.297469
 x' mom.  Cl'|    Cla =   0.022358    Clb =  -0.049533
 y  mom.  Cm |    Cma =  -1.956834    Cmb =  -0.091108
 z' mom.  Cn'|    Cna =  -0.005357    Cnb =   0.118862

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013591    CLq =  10.497333    CLr =  -0.020789
 y  force CY |    CYp =   0.123098    CYq =  -0.059127    CYr =   0.242754
 x' mom.  Cl'|    Clp =  -0.454298    Clq =   0.037430    Clr =   0.248048
 y  mom.  Cm |    Cmp =  -0.005925    Cmq = -19.224116    Cmr =   0.055149
 z' mom.  Cn'|    Cnp =  -0.070890    Cnq =   0.030458    Cnr =  -0.145094

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000123   CLd02 =   0.007953   CLd03 =   0.000079
 y  force CY |   CYd01 =   0.000222   CYd02 =  -0.000002   CYd03 =  -0.002837
 x' mom.  Cl'|   Cld01 =  -0.004429   Cld02 =   0.000023   Cld03 =  -0.000245
 y  mom.  Cm |   Cmd01 =  -0.000076   Cmd02 =  -0.029904   Cmd03 =  -0.000293
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =   0.000003   Cnd03 =   0.001539
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000360 CDffd03 =  -0.000174
 span eff.   |    ed01 =  -0.000083    ed02 =   0.007859    ed03 =   0.003801



 Neutral point  Xnp =   0.172931

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
