 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01457     Cltot =   0.00359     Cl'tot =   0.00310
  CYtot =   0.01034     Cmtot =  -0.10629
  CZtot =  -1.30888     Cntot =  -0.00377     Cn'tot =  -0.00417

  CLtot =   1.30090
  CDtot =   0.14505
  CDvis =   0.07000     CDind = 0.0750520
  CLff  =   1.31100     CDff  = 0.0766849    | Trefftz
  CYff  =   0.00764         e =    0.9988    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.700156    CLb =   0.095587
 y  force CY |    CYa =  -0.001687    CYb =  -0.295826
 x' mom.  Cl'|    Cla =   0.008720    Clb =  -0.088704
 y  mom.  Cm |    Cma =  -1.063885    Cmb =  -0.019199
 z' mom.  Cn'|    Cna =  -0.004055    Cnb =   0.119401

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.005939    CLq =   7.611319    CLr =  -0.007722
 y  force CY |    CYp =   0.143390    CYq =  -0.033432    CYr =   0.215395
 x' mom.  Cl'|    Clp =  -0.442869    Clq =   0.005892    Clr =   0.329675
 y  mom.  Cm |    Cmp =  -0.002767    Cmq = -16.656587    Cmr =   0.013009
 z' mom.  Cn'|    Cnp =  -0.077344    Cnq =   0.016315    Cnr =  -0.143175

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000047   CLd02 =   0.007850   CLd03 =   0.000030
 y  force CY |   CYd01 =   0.000196   CYd02 =  -0.000001   CYd03 =  -0.002802
 x' mom.  Cl'|   Cld01 =  -0.004295   Cld02 =   0.000009   Cld03 =  -0.000479
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028218   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =  -0.000107   Cnd02 =   0.000001   Cnd03 =   0.001425
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000693 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000026    ed02 =   0.002988    ed03 =   0.000890



 Neutral point  Xnp =   0.190331

 Clb Cnr / Clr Cnb  =   0.322640    (  > 1 if spirally stable )
