 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10321     Cltot =   0.00052     Cl'tot =   0.00095
  CYtot =   0.01583     Cmtot =  -0.00113
  CZtot =  -0.35153     Cntot =  -0.00617     Cn'tot =  -0.00612

  CLtot =   0.35787
  CDtot =   0.07844
  CDvis =   0.07000     CDind = 0.0084352
  CLff  =   0.35804     CDff  = 0.0091750    | Trefftz
  CYff  =   0.01149         e =    0.6233    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.967489    CLb =   0.047635
 y  force CY |    CYa =   0.000089    CYb =  -0.301406
 x' mom.  Cl'|    Cla =   0.013839    Clb =  -0.018133
 y  mom.  Cm |    Cma =  -1.945280    Cmb =  -0.029672
 z' mom.  Cn'|    Cna =   0.000127    Cnb =   0.116416

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009701    CLq =  10.614142    CLr =  -0.013287
 y  force CY |    CYp =   0.008797    CYq =  -0.035505    CYr =   0.250492
 x' mom.  Cl'|    Clp =  -0.473239    Clq =   0.020080    Clr =   0.132374
 y  mom.  Cm |    Cmp =  -0.007568    Cmq = -19.104268    Cmr =   0.032436
 z' mom.  Cn'|    Cnp =  -0.013853    Cnq =   0.020893    Cnr =  -0.131481

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007941   CLd03 =   0.000052
 y  force CY |   CYd01 =   0.000344   CYd02 =  -0.000001   CYd03 =  -0.002855
 x' mom.  Cl'|   Cld01 =  -0.004587   Cld02 =   0.000014   Cld03 =  -0.000263
 y  mom.  Cm |   Cmd01 =  -0.000047   Cmd02 =  -0.029692   Cmd03 =  -0.000176
 z' mom.  Cn'|   Cnd01 =   0.000168   Cnd02 =   0.000002   Cnd03 =   0.001547
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000323 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000149    ed02 =   0.049641    ed03 =   0.006792



 Neutral point  Xnp =   0.168432

 Clb Cnr / Clr Cnb  =   0.154708    (  > 1 if spirally stable )
