 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10340     Cltot =  -0.00228     Cl'tot =  -0.00248
  CYtot =  -0.01575     Cmtot =   0.04640
  CZtot =  -0.53278     Cntot =   0.00572     Cn'tot =   0.00564

  CLtot =   0.53607
  CDtot =   0.08474
  CDvis =   0.07000     CDind = 0.0147393
  CLff  =   0.53655     CDff  = 0.0156878    | Trefftz
  CYff  =  -0.01146         e =    0.8182    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.972400    CLb =  -0.065735
 y  force CY |    CYa =   0.000646    CYb =  -0.299838
 x' mom.  Cl'|    Cla =  -0.014304    Clb =  -0.047188
 y  mom.  Cm |    Cma =  -0.860594    Cmb =   0.012809
 z' mom.  Cn'|    Cna =   0.001741    Cnb =   0.107256

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011170    CLq =   8.018389    CLr =   0.012392
 y  force CY |    CYp =  -0.001140    CYq =   0.050136    CYr =   0.233648
 x' mom.  Cl'|    Clp =  -0.478856    Clq =  -0.004899    Clr =   0.184886
 y  mom.  Cm |    Cmp =   0.007150    Cmq = -16.391662    Cmr =  -0.018619
 z' mom.  Cn'|    Cnp =  -0.008207    Cnq =  -0.025547    Cnr =  -0.117519

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000074   CLd02 =   0.007925   CLd03 =  -0.000051
 y  force CY |   CYd01 =   0.000352   CYd02 =   0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004534   Cld02 =  -0.000014   Cld03 =  -0.000509
 y  mom.  Cm |   Cmd01 =   0.000029   Cmd02 =  -0.027963   Cmd03 =   0.000140
 z' mom.  Cn'|   Cnd01 =   0.000109   Cnd02 =  -0.000002   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000153 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000164    ed02 =   0.032116    ed03 =  -0.005345



 Neutral point  Xnp =   0.175307

 Clb Cnr / Clr Cnb  =   0.279649    (  > 1 if spirally stable )
