 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12461     Cltot =   0.00943     Cl'tot =   0.00734
  CYtot =   0.02566     Cmtot =  -0.50544
  CZtot =  -1.60585     Cntot =  -0.01004     Cn'tot =  -0.01165

  CLtot =   1.60013
  CDtot =   0.18409
  CDvis =   0.07000     CDind = 0.1140916
  CLff  =   1.62912     CDff  = 0.1189673    | Trefftz
  CYff  =   0.01914         e =    0.9943    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.439093    CLb =   0.289981
 y  force CY |    CYa =  -0.005089    CYb =  -0.291596
 x' mom.  Cl'|    Cla =   0.020015    Clb =  -0.083306
 y  mom.  Cm |    Cma =  -1.838761    Cmb =  -0.137778
 z' mom.  Cn'|    Cna =  -0.011312    Cnb =   0.132148

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011158    CLq =  10.325550    CLr =  -0.018556
 y  force CY |    CYp =   0.247098    CYq =  -0.059127    CYr =   0.201102
 x' mom.  Cl'|    Clp =  -0.420961    Clq =   0.041305    Clr =   0.370914
 y  mom.  Cm |    Cmp =   0.001807    Cmq = -19.063447    Cmr =   0.055437
 z' mom.  Cn'|    Cnp =  -0.139845    Cnq =   0.024953    Cnr =  -0.163095

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000114   CLd02 =   0.007650   CLd03 =   0.000068
 y  force CY |   CYd01 =   0.000088   CYd02 =  -0.000002   CYd03 =  -0.002731
 x' mom.  Cl'|   Cld01 =  -0.004116   Cld02 =   0.000023   Cld03 =  -0.000218
 y  mom.  Cm |   Cmd01 =  -0.000072   Cmd02 =  -0.029225   Cmd03 =  -0.000288
 z' mom.  Cn'|   Cnd01 =  -0.000177   Cnd02 =   0.000003   Cnd03 =   0.001482
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.001116 CDffd03 =  -0.000171
 span eff.   |    ed01 =  -0.000029    ed02 =   0.000257    ed03 =   0.001389



 Neutral point  Xnp =   0.174810

 Clb Cnr / Clr Cnb  =   0.277193    (  > 1 if spirally stable )
