 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08594     Cltot =  -0.00052     Cl'tot =   0.00023
  CYtot =   0.01581     Cmtot =   0.09965
  CZtot =  -0.08760     Cntot =  -0.00614     Cn'tot =  -0.00616

  CLtot =   0.09742
  CDtot =   0.07462
  CDvis =   0.07000     CDind = 0.0046238
  CLff  =   0.09725     CDff  = 0.0051272    | Trefftz
  CYff  =   0.01149         e =    0.0834    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.975384    CLb =   0.021089
 y  force CY |    CYa =   0.000725    CYb =  -0.301001
 x' mom.  Cl'|    Cla =   0.013750    Clb =  -0.004377
 y  mom.  Cm |    Cma =  -1.900527    Cmb =  -0.019109
 z' mom.  Cn'|    Cna =   0.001573    Cnb =   0.117263

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010412    CLq =  10.634614    CLr =  -0.013512
 y  force CY |    CYp =  -0.040203    CYq =  -0.035505    CYr =   0.244968
 x' mom.  Cl'|    Clp =  -0.477196    Clq =   0.018959    Clr =   0.080983
 y  mom.  Cm |    Cmp =  -0.009255    Cmq = -18.945288    Cmr =   0.031995
 z' mom.  Cn'|    Cnp =   0.009929    Cnq =   0.021915    Cnr =  -0.126418

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000076   CLd02 =   0.007828   CLd03 =   0.000054
 y  force CY |   CYd01 =   0.000394   CYd02 =  -0.000001   CYd03 =  -0.002831
 x' mom.  Cl'|   Cld01 =  -0.004603   Cld02 =   0.000014   Cld03 =  -0.000267
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.029268   Cmd03 =  -0.000176
 z' mom.  Cn'|   Cnd01 =   0.000241   Cnd02 =   0.000002   Cnd03 =   0.001534
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000611 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000006    ed02 =   0.023323    ed03 =   0.001142



 Neutral point  Xnp =   0.165720

 Clb Cnr / Clr Cnb  =   0.058262    (  > 1 if spirally stable )
