 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06043     Cltot =  -0.00667     Cl'tot =  -0.00616
  CYtot =  -0.02600     Cmtot =  -0.03332
  CZtot =  -0.96475     Cntot =   0.00946     Cn'tot =   0.00980

  CLtot =   0.96026
  CDtot =   0.11084
  CDvis =   0.07000     CDind = 0.0408420
  CLff  =   0.96675     CDff  = 0.0432634    | Trefftz
  CYff  =  -0.01908         e =    0.9631    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.828407    CLb =  -0.181734
 y  force CY |    CYa =   0.002819    CYb =  -0.295494
 x' mom.  Cl'|    Cla =  -0.022900    Clb =  -0.069880
 y  mom.  Cm |    Cma =  -0.979720    Cmb =   0.035332
 z' mom.  Cn'|    Cna =   0.006975    Cnb =   0.111105

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.016454    CLq =   7.785720    CLr =   0.020031
 y  force CY |    CYp =   0.079648    CYq =   0.083492    CYr =   0.228466
 x' mom.  Cl'|    Clp =  -0.459856    Clq =  -0.011836    Clr =   0.266425
 y  mom.  Cm |    Cmp =   0.009159    Cmq = -16.541823    Cmr =  -0.031926
 z' mom.  Cn'|    Cnp =  -0.045509    Cnq =  -0.041671    Cnr =  -0.130892

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000121   CLd02 =   0.007898   CLd03 =  -0.000079
 y  force CY |   CYd01 =   0.000264   CYd02 =   0.000002   CYd03 =  -0.002828
 x' mom.  Cl'|   Cld01 =  -0.004403   Cld02 =  -0.000023   Cld03 =  -0.000492
 y  mom.  Cm |   Cmd01 =   0.000047   Cmd02 =  -0.028115   Cmd03 =   0.000232
 z' mom.  Cn'|   Cnd01 =  -0.000013   Cnd02 =  -0.000003   Cnd03 =   0.001437
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =   0.000318 CDffd03 =   0.000176
 span eff.   |    ed01 =   0.000115    ed02 =   0.008665    ed03 =  -0.003806



 Neutral point  Xnp =   0.183720

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
