 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03933     Cltot =   0.00761     Cl'tot =   0.00649
  CYtot =   0.02058     Cmtot =  -0.12393
  CZtot =  -1.38524     Cntot =  -0.00749     Cn'tot =  -0.00848

  CLtot =   1.37723
  CDtot =   0.15384
  CDvis =   0.07000     CDind = 0.0838365
  CLff  =   1.39281     CDff  = 0.0866124    | Trefftz
  CYff  =   0.01527         e =    0.9982    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.636140    CLb =   0.201705
 y  force CY |    CYa =  -0.003641    CYb =  -0.293176
 x' mom.  Cl'|    Cla =   0.017104    Clb =  -0.092341
 y  mom.  Cm |    Cma =  -1.076222    Cmb =  -0.040912
 z' mom.  Cn'|    Cna =  -0.008692    Cnb =   0.120612

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011561    CLq =   7.544213    CLr =  -0.015257
 y  force CY |    CYp =   0.158622    CYq =  -0.066824    CYr =   0.210185
 x' mom.  Cl'|    Clp =  -0.436938    Clq =   0.012344    Clr =   0.344095
 y  mom.  Cm |    Cmp =  -0.005075    Cmq = -16.628882    Cmr =   0.026094
 z' mom.  Cn'|    Cnp =  -0.085366    Cnq =   0.032400    Cnr =  -0.145940

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000093   CLd02 =   0.007783   CLd03 =   0.000058
 y  force CY |   CYd01 =   0.000178   CYd02 =  -0.000001   CYd03 =  -0.002777
 x' mom.  Cl'|   Cld01 =  -0.004240   Cld02 =   0.000018   Cld03 =  -0.000472
 y  mom.  Cm |   Cmd01 =  -0.000037   Cmd02 =  -0.028052   Cmd03 =  -0.000184
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =   0.000002   Cnd03 =   0.001412
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000782 CDffd03 =  -0.000140
 span eff.   |    ed01 =  -0.000046    ed02 =   0.002247    ed03 =   0.001568



 Neutral point  Xnp =   0.191963

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
