 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00781     Cltot =  -0.00531     Cl'tot =  -0.00442
  CYtot =  -0.02086     Cmtot =  -0.34229
  CZtot =  -1.21226     Cntot =   0.00816     Cn'tot =   0.00867

  CLtot =   1.20480
  CDtot =   0.13448
  CDvis =   0.07000     CDind = 0.0644824
  CLff  =   1.21496     CDff  = 0.0667083    | Trefftz
  CYff  =  -0.01532         e =    0.9863    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.701415    CLb =  -0.178404
 y  force CY |    CYa =   0.002697    CYb =  -0.297131
 x' mom.  Cl'|    Cla =  -0.017372    Clb =  -0.062968
 y  mom.  Cm |    Cma =  -1.935395    Cmb =   0.087304
 z' mom.  Cn'|    Cna =   0.006143    Cnb =   0.123413

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010090    CLq =  10.455194    CLr =   0.016033
 y  force CY |    CYp =   0.171151    CYq =   0.047323    CYr =   0.231533
 x' mom.  Cl'|    Clp =  -0.443890    Clq =  -0.031192    Clr =   0.295963
 y  mom.  Cm |    Cmp =   0.002426    Cmq = -19.234107    Cmr =  -0.044327
 z' mom.  Cn'|    Cnp =  -0.096378    Cnq =  -0.022777    Cnr =  -0.151925

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000096   CLd02 =   0.007905   CLd03 =  -0.000060
 y  force CY |   CYd01 =   0.000172   CYd02 =   0.000001   CYd03 =  -0.002818
 x' mom.  Cl'|   Cld01 =  -0.004342   Cld02 =  -0.000018   Cld03 =  -0.000236
 y  mom.  Cm |   Cmd01 =   0.000060   Cmd02 =  -0.029866   Cmd03 =   0.000234
 z' mom.  Cn'|   Cnd01 =  -0.000070   Cnd02 =  -0.000002   Cnd03 =   0.001529
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000651 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000043    ed02 =   0.003288    ed03 =  -0.001995



 Neutral point  Xnp =   0.174089

 Clb Cnr / Clr Cnb  =   0.261908    (  > 1 if spirally stable )
