 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06268     Cltot =   0.00022     Cl'tot =  -0.00096
  CYtot =  -0.02096     Cmtot =   0.13885
  CZtot =   0.08534     Cntot =   0.00757     Cn'tot =   0.00751

  CLtot =  -0.07448
  CDtot =   0.07526
  CDvis =   0.07000     CDind = 0.0052552
  CLff  =  -0.07507     CDff  = 0.0060742    | Trefftz
  CYff  =  -0.01527         e =    0.0431    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.981448    CLb =  -0.004649
 y  force CY |    CYa =  -0.001107    CYb =  -0.298565
 x' mom.  Cl'|    Cla =  -0.019041    Clb =  -0.013712
 y  mom.  Cm |    Cma =  -0.642798    Cmb =   0.004162
 z' mom.  Cn'|    Cna =  -0.002358    Cnb =   0.106832

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.017380    CLq =   8.231344    CLr =   0.016679
 y  force CY |    CYp =  -0.113126    CYq =   0.066824    CYr =   0.216197
 x' mom.  Cl'|    Clp =  -0.492347    Clq =  -0.002332    Clr =   0.064165
 y  mom.  Cm |    Cmp =   0.012483    Cmq = -15.898779    Cmr =  -0.023470
 z' mom.  Cn'|    Cnp =   0.040806    Cnq =  -0.034593    Cnr =  -0.101625

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000099   CLd02 =   0.007642   CLd03 =  -0.000073
 y  force CY |   CYd01 =   0.000469   CYd02 =   0.000001   CYd03 =  -0.002800
 x' mom.  Cl'|   Cld01 =  -0.004561   Cld02 =  -0.000018   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =   0.000040   Cmd02 =  -0.026797   Cmd03 =   0.000184
 z' mom.  Cn'|   Cnd01 =   0.000283   Cnd02 =  -0.000002   Cnd03 =   0.001421
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000799 CDffd03 =   0.000139
 span eff.   |    ed01 =  -0.000016    ed02 =  -0.002927    ed03 =  -0.000377



 Neutral point  Xnp =   0.162889

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
