 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09967     Cltot =  -0.00263     Cl'tot =  -0.00273
  CYtot =  -0.01573     Cmtot =   0.03114
  CZtot =  -0.62106     Cntot =   0.00572     Cn'tot =   0.00567

  CLtot =   0.62271
  CDtot =   0.08881
  CDvis =   0.07000     CDind = 0.0188143
  CLff  =   0.62350     CDff  = 0.0198302    | Trefftz
  CYff  =  -0.01146         e =    0.8739    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.955226    CLb =  -0.074555
 y  force CY |    CYa =   0.000857    CYb =  -0.299588
 x' mom.  Cl'|    Cla =  -0.014235    Clb =  -0.051928
 y  mom.  Cm |    Cma =  -0.887603    Cmb =   0.014408
 z' mom.  Cn'|    Cna =   0.002239    Cnb =   0.107917

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010908    CLq =   7.979099    CLr =   0.012337
 y  force CY |    CYp =   0.015101    CYq =   0.050136    CYr =   0.233855
 x' mom.  Cl'|    Clp =  -0.475777    Clq =  -0.005344    Clr =   0.201649
 y  mom.  Cm |    Cmp =   0.006824    Cmq = -16.439821    Cmr =  -0.018741
 z' mom.  Cn'|    Cnp =  -0.015511    Cnq =  -0.025458    Cnr =  -0.120123

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000074   CLd02 =   0.007939   CLd03 =  -0.000050
 y  force CY |   CYd01 =   0.000335   CYd02 =   0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004518   Cld02 =  -0.000014   Cld03 =  -0.000507
 y  mom.  Cm |   Cmd01 =   0.000029   Cmd02 =  -0.028055   Cmd03 =   0.000140
 z' mom.  Cn'|   Cnd01 =   0.000084   Cnd02 =  -0.000002   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000059 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000139    ed02 =   0.024787    ed03 =  -0.004528



 Neutral point  Xnp =   0.177013

 Clb Cnr / Clr Cnb  =   0.286642    (  > 1 if spirally stable )
