 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00812     Cltot =   0.00266     Cl'tot =   0.00222
  CYtot =   0.01045     Cmtot =  -0.34458
  CZtot =  -1.21699     Cntot =  -0.00409     Cn'tot =  -0.00435

  CLtot =   1.20948
  CDtot =   0.13528
  CDvis =   0.07000     CDind = 0.0652848
  CLff  =   1.21719     CDff  = 0.0666716    | Trefftz
  CYff  =   0.00766         e =    0.9903    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.718084    CLb =   0.089420
 y  force CY |    CYa =  -0.001352    CYb =  -0.298934
 x' mom.  Cl'|    Cla =   0.008707    Clb =  -0.063432
 y  mom.  Cm |    Cma =  -1.942490    Cmb =  -0.043759
 z' mom.  Cn'|    Cna =  -0.003079    Cnb =   0.124322

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.005048    CLq =  10.474340    CLr =  -0.008022
 y  force CY |    CYp =   0.171464    CYq =  -0.023676    CYr =   0.231957
 x' mom.  Cl'|    Clp =  -0.444703    Clq =   0.015606    Clr =   0.296505
 y  mom.  Cm |    Cmp =  -0.001214    Cmq = -19.269329    Cmr =   0.022177
 z' mom.  Cn'|    Cnp =  -0.096555    Cnq =   0.011395    Cnr =  -0.152203

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000048   CLd02 =   0.007934   CLd03 =   0.000030
 y  force CY |   CYd01 =   0.000172   CYd02 =  -0.000001   CYd03 =  -0.002828
 x' mom.  Cl'|   Cld01 =  -0.004358   Cld02 =   0.000009   Cld03 =  -0.000237
 y  mom.  Cm |   Cmd01 =  -0.000030   Cmd02 =  -0.029976   Cmd03 =  -0.000117
 z' mom.  Cn'|   Cnd01 =  -0.000070   Cnd02 =   0.000001   Cnd03 =   0.001534
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000653 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000022    ed02 =   0.003262    ed03 =   0.001005



 Neutral point  Xnp =   0.174103

 Clb Cnr / Clr Cnb  =   0.261908    (  > 1 if spirally stable )
