 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04795     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.19730
  CZtot =   0.17370     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =  -0.16273
  CDtot =   0.07739
  CDvis =   0.07000     CDind = 0.0073879
  CLff  =  -0.16403     CDff  = 0.0071326    | Trefftz
  CYff  =  -0.00000         e =    0.1681    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.964241    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.301325
 x' mom.  Cl'|    Cla =  -0.000000    Clb =   0.009266
 y  mom.  Cm |    Cma =  -1.839991    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.120203

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.658152    CLr =   0.000000
 y  force CY |    CYp =  -0.088479    CYq =   0.000000    CYr =   0.234673
 x' mom.  Cl'|    Clp =  -0.479487    Clq =  -0.000000    Clr =   0.029119
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -18.760090    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.033439    Cnq =  -0.000000    Cnr =  -0.122191

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007684   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000444   CYd02 =   0.000000   CYd03 =  -0.002799
 x' mom.  Cl'|   Cld01 =  -0.004607   Cld02 =   0.000000   Cld03 =  -0.000271
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028767   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =   0.000315   Cnd02 =  -0.000000   Cnd03 =   0.001516
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000895 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.004980    ed03 =   0.000000



 Neutral point  Xnp =   0.162523

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
