 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09318     Cltot =  -0.00192     Cl'tot =  -0.00192
  CYtot =  -0.01581     Cmtot =  -0.13808
  CZtot =  -0.70288     Cntot =   0.00618     Cn'tot =   0.00618

  CLtot =   0.70288
  CDtot =   0.09318
  CDvis =   0.07000     CDind = 0.0231792
  CLff  =   0.70411     CDff  = 0.0241983    | Trefftz
  CYff  =  -0.01149         e =    0.9132    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.906693    CLb =  -0.082750
 y  force CY |    CYa =   0.000760    CYb =  -0.300960
 x' mom.  Cl'|    Cla =  -0.013722    Clb =  -0.036469
 y  mom.  Cm |    Cma =  -1.971747    Cmb =   0.044027
 z' mom.  Cn'|    Cna =   0.001800    Cnb =   0.117529

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008797    CLq =  10.569302    CLr =   0.012874
 y  force CY |    CYp =   0.074518    CYq =   0.035505    CYr =   0.249841
 x' mom.  Cl'|    Clp =  -0.464470    Clq =  -0.021488    Clr =   0.199588
 y  mom.  Cm |    Cmp =   0.005286    Cmq = -19.234733    Cmr =  -0.032885
 z' mom.  Cn'|    Cnp =  -0.046210    Cnq =  -0.019441    Cnr =  -0.139146

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000075   CLd02 =   0.008007   CLd03 =  -0.000050
 y  force CY |   CYd01 =   0.000275   CYd02 =   0.000001   CYd03 =  -0.002863
 x' mom.  Cl'|   Cld01 =  -0.004525   Cld02 =  -0.000014   Cld03 =  -0.000254
 y  mom.  Cm |   Cmd01 =   0.000047   Cmd02 =  -0.030006   Cmd03 =   0.000177
 z' mom.  Cn'|   Cnd01 =   0.000070   Cnd02 =  -0.000002   Cnd03 =   0.001553
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000068 CDffd03 =   0.000105
 span eff.   |    ed01 =   0.000085    ed02 =   0.018166    ed03 =  -0.003837



 Neutral point  Xnp =   0.171321

 Clb Cnr / Clr Cnb  =   0.216329    (  > 1 if spirally stable )
