 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04752     Cltot =   0.00069     Cl'tot =  -0.00063
  CYtot =  -0.02093     Cmtot =   0.14977
  CZtot =   0.17220     Cntot =   0.00755     Cn'tot =   0.00755

  CLtot =  -0.16133
  CDtot =   0.07669
  CDvis =   0.07000     CDind = 0.0066949
  CLff  =  -0.16248     CDff  = 0.0074431    | Trefftz
  CYff  =  -0.01527         e =    0.1595    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.969874    CLb =   0.007182
 y  force CY |    CYa =  -0.001387    CYb =  -0.298255
 x' mom.  Cl'|    Cla =  -0.018947    Clb =  -0.008994
 y  mom.  Cm |    Cma =  -0.608498    Cmb =   0.002634
 z' mom.  Cn'|    Cna =  -0.003021    Cnb =   0.107501

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.017737    CLq =   8.254920    CLr =   0.016652
 y  force CY |    CYp =  -0.128664    CYq =   0.066824    CYr =   0.211525
 x' mom.  Cl'|    Clp =  -0.493225    Clq =  -0.001727    Clr =   0.046618
 y  mom.  Cm |    Cmp =   0.012890    Cmq = -15.811307    Cmr =  -0.023249
 z' mom.  Cn'|    Cnp =   0.047565    Cnq =  -0.034628    Cnr =  -0.099770

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000099   CLd02 =   0.007581   CLd03 =  -0.000073
 y  force CY |   CYd01 =   0.000485   CYd02 =   0.000001   CYd03 =  -0.002786
 x' mom.  Cl'|   Cld01 =  -0.004555   Cld02 =  -0.000018   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =   0.000040   Cmd02 =  -0.026575   Cmd03 =   0.000183
 z' mom.  Cn'|   Cnd01 =   0.000308   Cnd02 =  -0.000002   Cnd03 =   0.001413
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000887 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000060    ed02 =   0.003893    ed03 =  -0.002480



 Neutral point  Xnp =   0.161027

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
