 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04560     Cltot =  -0.00330     Cl'tot =  -0.00286
  CYtot =  -0.01572     Cmtot =  -0.27554
  CZtot =  -1.04740     Cntot =   0.00615     Cn'tot =   0.00637

  CLtot =   1.04167
  CDtot =   0.11855
  CDvis =   0.07000     CDind = 0.0485520
  CLff  =   1.04675     CDff  = 0.0499429    | Trefftz
  CYff  =  -0.01149         e =    0.9778    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.789766    CLb =  -0.117169
 y  force CY |    CYa =   0.001605    CYb =  -0.299388
 x' mom.  Cl'|    Cla =  -0.013338    Clb =  -0.054472
 y  mom.  Cm |    Cma =  -1.959835    Cmb =   0.058435
 z' mom.  Cn'|    Cna =   0.003692    Cnb =   0.121183

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007959    CLq =  10.505232    CLr =   0.012339
 y  force CY |    CYp =   0.139508    CYq =   0.035505    CYr =   0.240050
 x' mom.  Cl'|    Clp =  -0.451940    Clq =  -0.022792    Clr =   0.264701
 y  mom.  Cm |    Cmp =   0.002980    Cmq = -19.271488    Cmr =  -0.033173
 z' mom.  Cn'|    Cnp =  -0.079471    Cnq =  -0.017895    Cnr =  -0.147631

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000073   CLd02 =   0.007975   CLd03 =  -0.000047
 y  force CY |   CYd01 =   0.000206   CYd02 =   0.000001   CYd03 =  -0.002844
 x' mom.  Cl'|   Cld01 =  -0.004420   Cld02 =  -0.000014   Cld03 =  -0.000243
 y  mom.  Cm |   Cmd01 =   0.000046   Cmd02 =  -0.030028   Cmd03 =   0.000176
 z' mom.  Cn'|   Cnd01 =  -0.000024   Cnd02 =  -0.000002   Cnd03 =   0.001543
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000459 CDffd03 =   0.000105
 span eff.   |    ed01 =   0.000043    ed02 =   0.005924    ed03 =  -0.001989



 Neutral point  Xnp =   0.173386

 Clb Cnr / Clr Cnb  =   0.250698    (  > 1 if spirally stable )
