 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06603     Cltot =   0.00202     Cl'tot =   0.00170
  CYtot =   0.00514     Cmtot =  -0.14428
  CZtot =  -1.47248     Cntot =  -0.00187     Cn'tot =  -0.00216

  CLtot =   1.46468
  CDtot =   0.16513
  CDvis =   0.07000     CDind = 0.0951270
  CLff  =   1.47996     CDff  = 0.0972110    | Trefftz
  CYff  =   0.00382         e =    1.0041    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.605985    CLb =   0.053307
 y  force CY |    CYa =  -0.000982    CYb =  -0.294447
 x' mom.  Cl'|    Cla =   0.004210    Clb =  -0.097440
 y  mom.  Cm |    Cma =  -1.096135    Cmb =  -0.010923
 z' mom.  Cn'|    Cna =  -0.002328    Cnb =   0.123976

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002816    CLq =   7.506917    CLr =  -0.003770
 y  force CY |    CYp =   0.174337    CYq =  -0.016719    CYr =   0.205300
 x' mom.  Cl'|    Clp =  -0.432615    Clq =   0.003229    Clr =   0.359704
 y  mom.  Cm |    Cmp =  -0.001156    Cmq = -16.664620    Cmr =   0.006550
 z' mom.  Cn'|    Cnp =  -0.093849    Cnq =   0.008051    Cnr =  -0.149320

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000023   CLd02 =   0.007773   CLd03 =   0.000014
 y  force CY |   CYd01 =   0.000162   CYd02 =  -0.000000   CYd03 =  -0.002773
 x' mom.  Cl'|   Cld01 =  -0.004216   Cld02 =   0.000004   Cld03 =  -0.000469
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.028101   Cmd03 =  -0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000151   Cnd02 =   0.000001   Cnd03 =   0.001410
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000877 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000010    ed02 =   0.001606    ed03 =   0.000351



 Neutral point  Xnp =   0.193611

 Clb Cnr / Clr Cnb  =   0.326266    (  > 1 if spirally stable )
