 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02822     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.31130
  CZtot =  -1.13501     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.12823
  CDtot =   0.12703
  CDvis =   0.07000     CDind = 0.0570327
  CLff  =   1.13323     CDff  = 0.0579484    | Trefftz
  CYff  =   0.00000         e =    0.9876    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.764714    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.300177
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.059203
 y  mom.  Cm |    Cma =  -1.956230    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.123161

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.500739    CLr =   0.000000
 y  force CY |    CYp =   0.155706    CYq =   0.000000    CYr =   0.236517
 x' mom.  Cl'|    Clp =  -0.448872    Clq =  -0.000000    Clr =   0.280964
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.292443    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.088064    Cnq =  -0.000000    Cnr =  -0.150051

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007973   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000190   CYd02 =   0.000000   CYd03 =  -0.002842
 x' mom.  Cl'|   Cld01 =  -0.004399   Cld02 =   0.000000   Cld03 =  -0.000241
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.030071   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000048   Cnd02 =  -0.000000   Cnd03 =   0.001542
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000558 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.004416    ed03 =   0.000000



 Neutral point  Xnp =   0.173780

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
