 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06520     Cltot =  -0.00501     Cl'tot =  -0.00399
  CYtot =  -0.01554     Cmtot =  -0.44401
  CZtot =  -1.45837     Cntot =   0.00608     Cn'tot =   0.00679

  CLtot =   1.45061
  CDtot =   0.16374
  CDvis =   0.07000     CDind = 0.0937379
  CLff  =   1.46768     CDff  = 0.0964177    | Trefftz
  CYff  =  -0.01149         e =    0.9957    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.569420    CLb =  -0.158616
 y  force CY |    CYa =   0.002650    CYb =  -0.295852
 x' mom.  Cl'|    Cla =  -0.012494    Clb =  -0.075974
 y  mom.  Cm |    Cma =  -1.891402    Cmb =   0.076093
 z' mom.  Cn'|    Cna =   0.005952    Cnb =   0.129212

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007029    CLq =  10.400036    CLr =   0.011515
 y  force CY |    CYp =   0.217796    CYq =   0.035505    CYr =   0.215265
 x' mom.  Cl'|    Clp =  -0.431496    Clq =  -0.024265    Clr =   0.342226
 y  mom.  Cm |    Cmp =   0.000077    Cmq = -19.185424    Cmr =  -0.033307
 z' mom.  Cn'|    Cnp =  -0.122500    Cnq =  -0.015840    Cnr =  -0.158915

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000070   CLd02 =   0.007798   CLd03 =  -0.000043
 y  force CY |   CYd01 =   0.000122   CYd02 =   0.000001   CYd03 =  -0.002781
 x' mom.  Cl'|   Cld01 =  -0.004229   Cld02 =  -0.000014   Cld03 =  -0.000227
 y  mom.  Cm |   Cmd01 =   0.000044   Cmd02 =  -0.029646   Cmd03 =   0.000175
 z' mom.  Cn'|   Cnd01 =  -0.000136   Cnd02 =  -0.000002   Cnd03 =   0.001509
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000937 CDffd03 =   0.000103
 span eff.   |    ed01 =   0.000022    ed02 =   0.001065    ed03 =  -0.001040



 Neutral point  Xnp =   0.174727

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
