 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08635     Cltot =  -0.00053     Cl'tot =  -0.00122
  CYtot =  -0.01576     Cmtot =   0.11513
  CZtot =  -0.09024     Cntot =   0.00570     Cn'tot =   0.00559

  CLtot =   0.10009
  CDtot =   0.07471
  CDvis =   0.07000     CDind = 0.0047113
  CLff  =   0.09991     CDff  = 0.0052533    | Trefftz
  CYff  =  -0.01146         e =    0.0858    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.004295    CLb =  -0.021301
 y  force CY |    CYa =  -0.000410    CYb =  -0.300034
 x' mom.  Cl'|    Cla =  -0.014390    Clb =  -0.023303
 y  mom.  Cm |    Cma =  -0.710524    Cmb =   0.005605
 z' mom.  Cn'|    Cna =  -0.000769    Cnb =   0.106447

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012503    CLq =   8.186699    CLr =   0.012525
 y  force CY |    CYp =  -0.081695    CYq =   0.050136    CYr =   0.224138
 x' mom.  Cl'|    Clp =  -0.490256    Clq =  -0.002654    Clr =   0.099179
 y  mom.  Cm |    Cmp =   0.008745    Cmq = -16.076321    Cmr =  -0.017925
 z' mom.  Cn'|    Cnp =   0.027160    Cnq =  -0.025877    Cnr =  -0.105764

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000075   CLd02 =   0.007763   CLd03 =  -0.000054
 y  force CY |   CYd01 =   0.000437   CYd02 =   0.000001   CYd03 =  -0.002829
 x' mom.  Cl'|   Cld01 =  -0.004574   Cld02 =  -0.000013   Cld03 =  -0.000515
 y  mom.  Cm |   Cmd01 =   0.000030   Cmd02 =  -0.027252   Cmd03 =   0.000139
 z' mom.  Cn'|   Cnd01 =   0.000234   Cnd02 =  -0.000002   Cnd03 =   0.001436
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000619 CDffd03 =   0.000105
 span eff.   |    ed01 =   0.000015    ed02 =   0.023412    ed03 =  -0.001185



 Neutral point  Xnp =   0.166539

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
