 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03920     Cltot =  -0.00381     Cl'tot =  -0.00325
  CYtot =  -0.01031     Cmtot =  -0.12501
  CZtot =  -1.39060     Cntot =   0.00375     Cn'tot =   0.00425

  CLtot =   1.38252
  CDtot =   0.15471
  CDvis =   0.07000     CDind = 0.0847149
  CLff  =   1.39536     CDff  = 0.0866420    | Trefftz
  CYff  =  -0.00764         e =    1.0015    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.652564    CLb =  -0.101099
 y  force CY |    CYa =   0.001825    CYb =  -0.294949
 x' mom.  Cl'|    Cla =  -0.008573    Clb =  -0.093021
 y  mom.  Cm |    Cma =  -1.080168    Cmb =   0.020506
 z' mom.  Cn'|    Cna =   0.004357    Cnb =   0.121500

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005784    CLq =   7.558028    CLr =   0.007633
 y  force CY |    CYp =   0.158913    CYq =   0.033432    CYr =   0.210570
 x' mom.  Cl'|    Clp =  -0.437738    Clq =  -0.006176    Clr =   0.344725
 y  mom.  Cm |    Cmp =   0.002539    Cmq = -16.659334    Cmr =  -0.013055
 z' mom.  Cn'|    Cnp =  -0.085523    Cnq =  -0.016210    Cnr =  -0.146207

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000047   CLd02 =   0.007811   CLd03 =  -0.000029
 y  force CY |   CYd01 =   0.000179   CYd02 =   0.000001   CYd03 =  -0.002787
 x' mom.  Cl'|   Cld01 =  -0.004255   Cld02 =  -0.000009   Cld03 =  -0.000474
 y  mom.  Cm |   Cmd01 =   0.000018   Cmd02 =  -0.028155   Cmd03 =   0.000092
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =  -0.000001   Cnd03 =   0.001417
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000785 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000023    ed02 =   0.002225    ed03 =  -0.000788



 Neutral point  Xnp =   0.191971

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
