 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10057     Cltot =  -0.00082     Cl'tot =  -0.00115
  CYtot =  -0.01052     Cmtot =   0.08910
  CZtot =  -0.26761     Cntot =   0.00381     Cn'tot =   0.00373

  CLtot =   0.27536
  CDtot =   0.07686
  CDvis =   0.07000     CDind = 0.0068606
  CLff  =   0.27505     CDff  = 0.0072503    | Trefftz
  CYff  =  -0.00764         e =    0.4654    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.009790    CLb =  -0.026104
 y  force CY |    CYa =   0.000008    CYb =  -0.300924
 x' mom.  Cl'|    Cla =  -0.009615    Clb =  -0.032972
 y  mom.  Cm |    Cma =  -0.774594    Cmb =   0.005553
 z' mom.  Cn'|    Cna =   0.000158    Cnb =   0.106595

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007980    CLq =   8.131369    CLr =   0.008335
 y  force CY |    CYp =  -0.049720    CYq =   0.033432    CYr =   0.229804
 x' mom.  Cl'|    Clp =  -0.486884    Clq =  -0.002371    Clr =   0.133896
 y  mom.  Cm |    Cmp =   0.005411    Cmq = -16.229658    Cmr =  -0.012149
 z' mom.  Cn'|    Cnp =   0.013238    Cnq =  -0.017184    Cnr =  -0.110278

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007857   CLd03 =  -0.000035
 y  force CY |   CYd01 =   0.000404   CYd02 =   0.000001   CYd03 =  -0.002850
 x' mom.  Cl'|   Cld01 =  -0.004574   Cld02 =  -0.000009   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.027628   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000184   Cnd02 =  -0.000001   Cnd03 =   0.001447
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000435 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000127    ed02 =   0.054595    ed03 =  -0.004264



 Neutral point  Xnp =   0.170102

 Clb Cnr / Clr Cnb  =   0.254756    (  > 1 if spirally stable )
