 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09943     Cltot =   0.00023     Cl'tot =   0.00095
  CYtot =   0.02108     Cmtot =   0.03325
  CZtot =  -0.26265     Cntot =  -0.00821     Cn'tot =  -0.00815

  CLtot =   0.27032
  CDtot =   0.07616
  CDvis =   0.07000     CDind = 0.0061624
  CLff  =   0.27089     CDff  = 0.0072818    | Trefftz
  CYff  =   0.01532         e =    0.4505    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.963411    CLb =   0.051653
 y  force CY |    CYa =   0.000401    CYb =  -0.300277
 x' mom.  Cl'|    Cla =   0.018408    Clb =  -0.013481
 y  mom.  Cm |    Cma =  -1.928589    Cmb =  -0.034783
 z' mom.  Cn'|    Cna =   0.000812    Cnb =   0.116040

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013243    CLq =  10.610904    CLr =  -0.017820
 y  force CY |    CYp =  -0.007589    CYq =  -0.047323    CYr =   0.248956
 x' mom.  Cl'|    Clp =  -0.474306    Clq =   0.026273    Clr =   0.115196
 y  mom.  Cm |    Cmp =  -0.010839    Cmq = -19.036741    Cmr =   0.043050
 z' mom.  Cn'|    Cnp =  -0.005878    Cnq =   0.028310    Cnr =  -0.129584

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000101   CLd02 =   0.007892   CLd03 =   0.000071
 y  force CY |   CYd01 =   0.000360   CYd02 =  -0.000001   CYd03 =  -0.002843
 x' mom.  Cl'|   Cld01 =  -0.004585   Cld02 =   0.000018   Cld03 =  -0.000264
 y  mom.  Cm |   Cmd01 =  -0.000063   Cmd02 =  -0.029505   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =   0.000192   Cnd02 =   0.000002   Cnd03 =   0.001540
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000419 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000173    ed02 =   0.052251    ed03 =   0.008082



 Neutral point  Xnp =   0.167574

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
