 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10502     Cltot =  -0.00129     Cl'tot =  -0.00149
  CYtot =  -0.01051     Cmtot =   0.06101
  CZtot =  -0.44510     Cntot =   0.00382     Cn'tot =   0.00374

  CLtot =   0.44999
  CDtot =   0.08158
  CDvis =   0.07000     CDind = 0.0115804
  CLff  =   0.44979     CDff  = 0.0121246    | Trefftz
  CYff  =  -0.00764         e =    0.7438    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.993383    CLb =  -0.037962
 y  force CY |    CYa =   0.000290    CYb =  -0.300775
 x' mom.  Cl'|    Cla =  -0.009581    Clb =  -0.042558
 y  mom.  Cm |    Cma =  -0.833807    Cmb =   0.007514
 z' mom.  Cn'|    Cna =   0.000828    Cnb =   0.107088

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007625    CLq =   8.062004    CLr =   0.008293
 y  force CY |    CYp =  -0.017378    CYq =   0.033432    CYr =   0.233051
 x' mom.  Cl'|    Clp =  -0.482042    Clq =  -0.002969    Clr =   0.168109
 y  mom.  Cm |    Cmp =   0.004984    Cmq = -16.350966    Cmr =  -0.012331
 z' mom.  Cn'|    Cnp =  -0.000986    Cnq =  -0.017090    Cnr =  -0.115080

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007916   CLd03 =  -0.000035
 y  force CY |   CYd01 =   0.000370   CYd02 =   0.000001   CYd03 =  -0.002859
 x' mom.  Cl'|   Cld01 =  -0.004555   Cld02 =  -0.000009   Cld03 =  -0.000512
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.027897   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000134   Cnd02 =  -0.000001   Cnd03 =   0.001452
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000248 CDffd03 =   0.000071
 span eff.   |    ed01 =   0.000128    ed02 =   0.041357    ed03 =  -0.004178



 Neutral point  Xnp =   0.173589

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
