 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10371     Cltot =   0.00158     Cl'tot =   0.00198
  CYtot =   0.01576     Cmtot =   0.07546
  CZtot =  -0.35568     Cntot =  -0.00572     Cn'tot =  -0.00559

  CLtot =   0.36204
  CDtot =   0.07865
  CDvis =   0.07000     CDind = 0.0086483
  CLff  =   0.36220     CDff  = 0.0094483    | Trefftz
  CYff  =   0.01146         e =    0.6194    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.995986    CLb =   0.048009
 y  force CY |    CYa =  -0.000224    CYb =  -0.300127
 x' mom.  Cl'|    Cla =   0.014391    Clb =  -0.037654
 y  mom.  Cm |    Cma =  -0.803465    Cmb =  -0.009763
 z' mom.  Cn'|    Cna =  -0.000739    Cnb =   0.106432

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011700    CLq =   8.091472    CLr =  -0.012473
 y  force CY |    CYp =  -0.033552    CYq =  -0.050136    CYr =   0.231533
 x' mom.  Cl'|    Clp =  -0.484229    Clq =   0.004005    Clr =   0.150947
 y  mom.  Cm |    Cmp =  -0.007795    Cmq = -16.280382    Cmr =   0.018358
 z' mom.  Cn'|    Cnp =   0.006158    Cnq =   0.025703    Cnr =  -0.112549

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000074   CLd02 =   0.007878   CLd03 =   0.000052
 y  force CY |   CYd01 =   0.000387   CYd02 =  -0.000001   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004559   Cld02 =   0.000014   Cld03 =  -0.000512
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.027728   Cmd03 =  -0.000140
 z' mom.  Cn'|   Cnd01 =   0.000158   Cnd02 =   0.000002   Cnd03 =   0.001447
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000341 CDffd03 =  -0.000106
 span eff.   |    ed01 =  -0.000202    ed02 =   0.049337    ed03 =   0.006634



 Neutral point  Xnp =   0.171852

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
