 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15781     Cltot =  -0.00601     Cl'tot =  -0.00463
  CYtot =  -0.01538     Cmtot =  -0.54133
  CZtot =  -1.68968     Cntot =   0.00602     Cn'tot =   0.00714

  CLtot =   1.68557
  CDtot =   0.19695
  CDvis =   0.07000     CDind = 0.1269476
  CLff  =   1.71508     CDff  = 0.1313922    | Trefftz
  CYff  =  -0.01149         e =    0.9977    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.401145    CLb =  -0.182368
 y  force CY |    CYa =   0.003268    CYb =  -0.292903
 x' mom.  Cl'|    Cla =  -0.011803    Clb =  -0.088089
 y  mom.  Cm |    Cma =  -1.822549    Cmb =   0.086294
 z' mom.  Cn'|    Cna =   0.007226    Cnb =   0.135783

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006545    CLq =  10.324741    CLr =   0.010948
 y  force CY |    CYp =   0.262278    CYq =   0.035505    CYr =   0.193984
 x' mom.  Cl'|    Clp =  -0.416980    Clq =  -0.025061    Clr =   0.386286
 y  mom.  Cm |    Cmp =  -0.001666    Cmq = -19.063611    Cmr =  -0.033265
 z' mom.  Cn'|    Cnp =  -0.149132    Cnq =  -0.014549    Cnr =  -0.165772

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000068   CLd02 =   0.007623   CLd03 =  -0.000040
 y  force CY |   CYd01 =   0.000073   CYd02 =   0.000001   CYd03 =  -0.002723
 x' mom.  Cl'|   Cld01 =  -0.004086   Cld02 =  -0.000014   Cld03 =  -0.000215
 y  mom.  Cm |   Cmd01 =   0.000043   Cmd02 =  -0.029202   Cmd03 =   0.000173
 z' mom.  Cn'|   Cnd01 =  -0.000198   Cnd02 =  -0.000002   Cnd03 =   0.001478
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.001212 CDffd03 =   0.000102
 span eff.   |    ed01 =   0.000016    ed02 =  -0.000074    ed03 =  -0.000757



 Neutral point  Xnp =   0.174778

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
