 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09321     Cltot =   0.00396     Cl'tot =   0.00396
  CYtot =   0.02093     Cmtot =   0.01575
  CZtot =  -0.70732     Cntot =  -0.00761     Cn'tot =  -0.00761

  CLtot =   0.70732
  CDtot =   0.09321
  CDvis =   0.07000     CDind = 0.0232060
  CLff  =   0.70949     CDff  = 0.0247630    | Trefftz
  CYff  =   0.01527         e =    0.9063    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.924280    CLb =   0.110959
 y  force CY |    CYa =  -0.001421    CYb =  -0.298213
 x' mom.  Cl'|    Cla =   0.018837    Clb =  -0.056399
 y  mom.  Cm |    Cma =  -0.911582    Cmb =  -0.021377
 z' mom.  Cn'|    Cna =  -0.003641    Cnb =   0.108278

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014191    CLq =   7.929569    CLr =  -0.016359
 y  force CY |    CYp =   0.031306    CYq =  -0.066824    CYr =   0.233247
 x' mom.  Cl'|    Clp =  -0.471940    Clq =   0.007714    Clr =   0.218027
 y  mom.  Cm |    Cmp =  -0.008657    Cmq = -16.465385    Cmr =   0.025134
 z' mom.  Cn'|    Cnp =  -0.022877    Cnq =   0.033802    Cnr =  -0.122670

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000098   CLd02 =   0.007931   CLd03 =   0.000066
 y  force CY |   CYd01 =   0.000317   CYd02 =  -0.000001   CYd03 =  -0.002850
 x' mom.  Cl'|   Cld01 =  -0.004489   Cld02 =   0.000018   Cld03 =  -0.000503
 y  mom.  Cm |   Cmd01 =  -0.000038   Cmd02 =  -0.028070   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =   0.000002   Cnd03 =   0.001448
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000036 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000153    ed02 =   0.018908    ed03 =   0.005013



 Neutral point  Xnp =   0.178704

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
