 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15742     Cltot =  -0.00999     Cl'tot =  -0.00769
  CYtot =  -0.02557     Cmtot =  -0.53732
  CZtot =  -1.68110     Cntot =   0.01000     Cn'tot =   0.01185

  CLtot =   1.67710
  CDtot =   0.19555
  CDvis =   0.07000     CDind = 0.1255452
  CLff  =   1.71090     CDff  = 0.1311260    | Trefftz
  CYff  =  -0.01914         e =    0.9949    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.380493    CLb =  -0.302959
 y  force CY |    CYa =   0.005429    CYb =  -0.290554
 x' mom.  Cl'|    Cla =  -0.019608    Clb =  -0.087228
 y  mom.  Cm |    Cma =  -1.813673    Cmb =   0.143356
 z' mom.  Cn'|    Cna =   0.012004    Cnb =   0.134456

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010900    CLq =  10.299567    CLr =   0.018232
 y  force CY |    CYp =   0.261639    CYq =   0.059127    CYr =   0.193511
 x' mom.  Cl'|    Clp =  -0.415964    Clq =  -0.041734    Clr =   0.385344
 y  mom.  Cm |    Cmp =  -0.002775    Cmq = -19.017130    Cmr =  -0.055397
 z' mom.  Cn'|    Cnp =  -0.148769    Cnq =  -0.024228    Cnr =  -0.165368

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000113   CLd02 =   0.007586   CLd03 =  -0.000066
 y  force CY |   CYd01 =   0.000072   CYd02 =   0.000002   CYd03 =  -0.002710
 x' mom.  Cl'|   Cld01 =  -0.004066   Cld02 =  -0.000023   Cld03 =  -0.000214
 y  mom.  Cm |   Cmd01 =   0.000072   Cmd02 =  -0.029060   Cmd03 =   0.000287
 z' mom.  Cn'|   Cnd01 =  -0.000197   Cnd02 =  -0.000003   Cnd03 =   0.001471
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.001206 CDffd03 =   0.000170
 span eff.   |    ed01 =   0.000026    ed02 =  -0.000049    ed03 =  -0.001257



 Neutral point  Xnp =   0.174758

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
