 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09235     Cltot =  -0.00318     Cl'tot =  -0.00318
  CYtot =  -0.02627     Cmtot =  -0.13603
  CZtot =  -0.69903     Cntot =   0.01026     Cn'tot =   0.01026

  CLtot =   0.69903
  CDtot =   0.09235
  CDvis =   0.07000     CDind = 0.0223544
  CLff  =   0.70239     CDff  = 0.0244543    | Trefftz
  CYff  =  -0.01914         e =    0.8997    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.883507    CLb =  -0.137469
 y  force CY |    CYa =   0.001263    CYb =  -0.298533
 x' mom.  Cl'|    Cla =  -0.022795    Clb =  -0.036113
 y  mom.  Cm |    Cma =  -1.962143    Cmb =   0.073139
 z' mom.  Cn'|    Cna =   0.002991    Cnb =   0.116381

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.014649    CLq =  10.543532    CLr =   0.021439
 y  force CY |    CYp =   0.074336    CYq =   0.059127    CYr =   0.249232
 x' mom.  Cl'|    Clp =  -0.463337    Clq =  -0.035785    Clr =   0.199101
 y  mom.  Cm |    Cmp =   0.008804    Cmq = -19.187835    Cmr =  -0.054763
 z' mom.  Cn'|    Cnp =  -0.046098    Cnq =  -0.032376    Cnr =  -0.138807

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000125   CLd02 =   0.007968   CLd03 =  -0.000083
 y  force CY |   CYd01 =   0.000274   CYd02 =   0.000002   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004503   Cld02 =  -0.000023   Cld03 =  -0.000253
 y  mom.  Cm |   Cmd01 =   0.000078   Cmd02 =  -0.029860   Cmd03 =   0.000294
 z' mom.  Cn'|   Cnd01 =   0.000070   Cnd02 =  -0.000003   Cnd03 =   0.001545
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000068 CDffd03 =   0.000174
 span eff.   |    ed01 =   0.000137    ed02 =   0.017926    ed03 =  -0.006211



 Neutral point  Xnp =   0.171305

 Clb Cnr / Clr Cnb  =   0.216329    (  > 1 if spirally stable )
