 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15948     Cltot =   0.00470     Cl'tot =   0.00383
  CYtot =   0.01016     Cmtot =  -0.20235
  CZtot =  -1.70400     Cntot =  -0.00370     Cn'tot =  -0.00459

  CLtot =   1.69992
  CDtot =   0.19828
  CDvis =   0.07000     CDind = 0.1282820
  CLff  =   1.72827     CDff  = 0.1322869    | Trefftz
  CYff  =   0.00764         e =    1.0062    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.432565    CLb =   0.122497
 y  force CY |    CYa =  -0.002369    CYb =  -0.290761
 x' mom.  Cl'|    Cla =   0.007883    Clb =  -0.109477
 y  mom.  Cm |    Cma =  -1.131962    Cmb =  -0.025908
 z' mom.  Cn'|    Cna =  -0.005508    Cnb =   0.131365

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.005196    CLq =   7.333032    CLr =  -0.007226
 y  force CY |    CYp =   0.219038    CYq =  -0.033432    CYr =   0.185951
 x' mom.  Cl'|    Clp =  -0.415405    Clq =   0.007291    Clr =   0.402498
 y  mom.  Cm |    Cmp =  -0.001622    Cmq = -16.619589    Cmr =   0.013200
 z' mom.  Cn'|    Cnp =  -0.119285    Cnq =   0.015740    Cnr =  -0.158378

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000045   CLd02 =   0.007597   CLd03 =   0.000026
 y  force CY |   CYd01 =   0.000111   CYd02 =  -0.000001   CYd03 =  -0.002711
 x' mom.  Cl'|   Cld01 =  -0.004070   Cld02 =   0.000009   Cld03 =  -0.000452
 y  mom.  Cm |   Cmd01 =  -0.000018   Cmd02 =  -0.027735   Cmd03 =  -0.000091
 z' mom.  Cn'|   Cnd01 =  -0.000214   Cnd02 =   0.000001   Cnd03 =   0.001379
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.001142 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000015    ed02 =   0.000377    ed03 =   0.000512



 Neutral point  Xnp =   0.198515

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
