 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04593     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.05229
  CZtot =  -1.05859     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.05281
  CDtot =   0.11966
  CDvis =   0.07000     CDind = 0.0496636
  CLff  =   1.05629     CDff  = 0.0504663    | Trefftz
  CYff  =   0.00000         e =    0.9852    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.829542    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.298642
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.075536
 y  mom.  Cm |    Cma =  -1.008578    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.114301

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.767776    CLr =   0.000000
 y  force CY |    CYp =   0.096004    CYq =   0.000000    CYr =   0.226720
 x' mom.  Cl'|    Clp =  -0.457319    Clq =   0.000000    Clr =   0.283363
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.628045    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.053459    Cnq =  -0.000000    Cnr =  -0.134304

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007943   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000248   CYd02 =   0.000000   CYd03 =  -0.002841
 x' mom.  Cl'|   Cld01 =  -0.004407   Cld02 =   0.000000   Cld03 =  -0.000492
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028337   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =  -0.000000   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000414 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.006695    ed03 =   0.000000



 Neutral point  Xnp =   0.185391

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
