 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08400     Cltot =   0.00376     Cl'tot =   0.00358
  CYtot =   0.02625     Cmtot =  -0.17029
  CZtot =  -0.78565     Cntot =  -0.01026     Cn'tot =  -0.01032

  CLtot =   0.78406
  CDtot =   0.09770
  CDvis =   0.07000     CDind = 0.0276957
  CLff  =   0.78823     CDff  = 0.0298748    | Trefftz
  CYff  =   0.01914         e =    0.9273    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.859573    CLb =   0.151898
 y  force CY |    CYa =  -0.001615    CYb =  -0.298248
 x' mom.  Cl'|    Cla =   0.022677    Clb =  -0.040614
 y  mom.  Cm |    Cma =  -1.962764    Cmb =  -0.079133
 z' mom.  Cn'|    Cna =  -0.003784    Cnb =   0.117052

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014289    CLq =  10.529309    CLr =  -0.021235
 y  force CY |    CYp =   0.090662    CYq =  -0.059127    CYr =   0.247641
 x' mom.  Cl'|    Clp =  -0.460553    Clq =   0.036344    Clr =   0.215561
 y  mom.  Cm |    Cmp =  -0.007847    Cmq = -19.205780    Cmr =   0.054909
 z' mom.  Cn'|    Cnp =  -0.054302    Cnq =   0.031746    Cnr =  -0.140857

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000124   CLd02 =   0.007969   CLd03 =   0.000082
 y  force CY |   CYd01 =   0.000257   CYd02 =  -0.000002   CYd03 =  -0.002847
 x' mom.  Cl'|   Cld01 =  -0.004481   Cld02 =   0.000023   Cld03 =  -0.000250
 y  mom.  Cm |   Cmd01 =  -0.000077   Cmd02 =  -0.029893   Cmd03 =  -0.000294
 z' mom.  Cn'|   Cnd01 =   0.000046   Cnd02 =   0.000003   Cnd03 =   0.001544
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000165 CDffd03 =  -0.000174
 span eff.   |    ed01 =  -0.000116    ed02 =   0.013626    ed03 =   0.005244



 Neutral point  Xnp =   0.171899

 Clb Cnr / Clr Cnb  =   0.226729    (  > 1 if spirally stable )
