 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01420     Cltot =  -0.00433     Cl'tot =  -0.00355
  CYtot =  -0.01562     Cmtot =  -0.37736
  CZtot =  -1.29731     Cntot =   0.00612     Cn'tot =   0.00660

  CLtot =   1.28937
  CDtot =   0.14401
  CDvis =   0.07000     CDind = 0.0740106
  CLff  =   1.30047     CDff  = 0.0759932    | Trefftz
  CYff  =  -0.01149         e =    0.9918    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.666990    CLb =  -0.142289
 y  force CY |    CYa =   0.002234    CYb =  -0.297475
 x' mom.  Cl'|    Cla =  -0.012879    Clb =  -0.067544
 y  mom.  Cm |    Cma =  -1.925828    Cmb =   0.069107
 z' mom.  Cn'|    Cna =   0.005066    Cnb =   0.125551

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007384    CLq =  10.445296    CLr =   0.011864
 y  force CY |    CYp =   0.187010    CYq =   0.035505    CYr =   0.226817
 x' mom.  Cl'|    Clp =  -0.440269    Clq =  -0.023697    Clr =   0.311792
 y  mom.  Cm |    Cmp =   0.001239    Cmq = -19.237433    Cmr =  -0.033284
 z' mom.  Cn'|    Cnp =  -0.105086    Cnq =  -0.016677    Cnr =  -0.154350

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000072   CLd02 =   0.007887   CLd03 =  -0.000044
 y  force CY |   CYd01 =   0.000155   CYd02 =   0.000001   CYd03 =  -0.002811
 x' mom.  Cl'|   Cld01 =  -0.004313   Cld02 =  -0.000014   Cld03 =  -0.000234
 y  mom.  Cm |   Cmd01 =   0.000045   Cmd02 =  -0.029853   Cmd03 =   0.000176
 z' mom.  Cn'|   Cnd01 =  -0.000092   Cnd02 =  -0.000002   Cnd03 =   0.001525
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000748 CDffd03 =   0.000104
 span eff.   |    ed01 =   0.000028    ed02 =   0.002362    ed03 =  -0.001320



 Neutral point  Xnp =   0.174367

 Clb Cnr / Clr Cnb  =   0.266323    (  > 1 if spirally stable )
