 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09493     Cltot =  -0.00030     Cl'tot =  -0.00049
  CYtot =  -0.00526     Cmtot =   0.10229
  CZtot =  -0.17921     Cntot =   0.00191     Cn'tot =   0.00186

  CLtot =   0.18815
  CDtot =   0.07567
  CDvis =   0.07000     CDind = 0.0056728
  CLff  =   0.18763     CDff  = 0.0057828    | Trefftz
  CYff  =  -0.00382         e =    0.2714    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.017026    CLb =  -0.010087
 y  force CY |    CYa =  -0.000066    CYb =  -0.301348
 x' mom.  Cl'|    Cla =  -0.004810    Clb =  -0.028223
 y  mom.  Cm |    Cma =  -0.744234    Cmb =   0.002315
 z' mom.  Cn'|    Cna =  -0.000089    Cnb =   0.106796

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004080    CLq =   8.166881    CLr =   0.004174
 y  force CY |    CYp =  -0.065817    CYq =   0.016719    CYr =   0.227440
 x' mom.  Cl'|    Clp =  -0.489119    Clq =  -0.001036    Clr =   0.116676
 y  mom.  Cm |    Cmp =   0.002811    Cmq = -16.168967    Cmr =  -0.006027
 z' mom.  Cn'|    Cnp =   0.020251    Cnq =  -0.008612    Cnr =  -0.108063

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007826   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000422   CYd02 =   0.000000   CYd03 =  -0.002845
 x' mom.  Cl'|   Cld01 =  -0.004583   Cld02 =  -0.000004   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.027494   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =   0.000209   Cnd02 =  -0.000001   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000528 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000041    ed02 =   0.047574    ed03 =  -0.001490



 Neutral point  Xnp =   0.168332

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
