 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01450     Cltot =  -0.00719     Cl'tot =  -0.00590
  CYtot =  -0.02597     Cmtot =  -0.37415
  CZtot =  -1.29061     Cntot =   0.01016     Cn'tot =   0.01096

  CLtot =   1.28276
  CDtot =   0.14289
  CDvis =   0.07000     CDind = 0.0728921
  CLff  =   1.29730     CDff  = 0.0759969    | Trefftz
  CYff  =  -0.01914         e =    0.9871    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.645018    CLb =  -0.236378
 y  force CY |    CYa =   0.003712    CYb =  -0.295081
 x' mom.  Cl'|    Cla =  -0.021395    Clb =  -0.066884
 y  mom.  Cm |    Cma =  -1.916448    Cmb =   0.114804
 z' mom.  Cn'|    Cna =   0.008416    Cnb =   0.124324

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.012296    CLq =  10.419829    CLr =   0.019758
 y  force CY |    CYp =   0.186554    CYq =   0.059127    CYr =   0.226264
 x' mom.  Cl'|    Clp =  -0.439196    Clq =  -0.039464    Clr =   0.311032
 y  mom.  Cm |    Cmp =   0.002064    Cmq = -19.190528    Cmr =  -0.055428
 z' mom.  Cn'|    Cnp =  -0.104830    Cnq =  -0.027773    Cnr =  -0.153974

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000119   CLd02 =   0.007848   CLd03 =  -0.000074
 y  force CY |   CYd01 =   0.000154   CYd02 =   0.000002   CYd03 =  -0.002797
 x' mom.  Cl'|   Cld01 =  -0.004292   Cld02 =  -0.000023   Cld03 =  -0.000232
 y  mom.  Cm |   Cmd01 =   0.000075   Cmd02 =  -0.029708   Cmd03 =   0.000292
 z' mom.  Cn'|   Cnd01 =  -0.000092   Cnd02 =  -0.000003   Cnd03 =   0.001518
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000745 CDffd03 =   0.000173
 span eff.   |    ed01 =   0.000047    ed02 =   0.002397    ed03 =  -0.002182



 Neutral point  Xnp =   0.174348

 Clb Cnr / Clr Cnb  =   0.266323    (  > 1 if spirally stable )
