 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09949     Cltot =  -0.00105     Cl'tot =  -0.00112
  CYtot =  -0.01055     Cmtot =  -0.10428
  CZtot =  -0.61649     Cntot =   0.00412     Cn'tot =   0.00410

  CLtot =   0.61813
  CDtot =   0.08872
  CDvis =   0.07000     CDind = 0.0187201
  CLff  =   0.61832     CDff  = 0.0193349    | Trefftz
  CYff  =  -0.00766         e =    0.8813    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.934530    CLb =  -0.049397
 y  force CY |    CYa =   0.000366    CYb =  -0.301938
 x' mom.  Cl'|    Cla =  -0.009193    Clb =  -0.032000
 y  mom.  Cm |    Cma =  -1.971723    Cmb =   0.026975
 z' mom.  Cn'|    Cna =   0.000881    Cnb =   0.117369

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006013    CLq =  10.590423    CLr =   0.008661
 y  force CY |    CYp =   0.058150    CYq =   0.023676    CYr =   0.251056
 x' mom.  Cl'|    Clp =  -0.467382    Clq =  -0.014101    Clr =   0.183096
 y  mom.  Cm |    Cmp =   0.003907    Cmq = -19.225530    Cmr =  -0.021864
 z' mom.  Cn'|    Cnp =  -0.038071    Cnq =  -0.013212    Cnr =  -0.137247

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.008012   CLd03 =  -0.000034
 y  force CY |   CYd01 =   0.000293   CYd02 =   0.000001   CYd03 =  -0.002868
 x' mom.  Cl'|   Cld01 =  -0.004552   Cld02 =  -0.000009   Cld03 =  -0.000257
 y  mom.  Cm |   Cmd01 =   0.000031   Cmd02 =  -0.030000   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000094   Cnd02 =  -0.000001   Cnd03 =   0.001555
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000030 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000069    ed02 =   0.024165    ed03 =  -0.003089



 Neutral point  Xnp =   0.170681

 Clb Cnr / Clr Cnb  =   0.204371    (  > 1 if spirally stable )
