 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02742     Cltot =   0.00605     Cl'tot =   0.00514
  CYtot =   0.02609     Cmtot =  -0.30679
  CZtot =  -1.12578     Cntot =  -0.01020     Cn'tot =  -0.01069

  CLtot =   1.11910
  CDtot =   0.12544
  CDvis =   0.07000     CDind = 0.0554360
  CLff  =   1.12892     CDff  = 0.0580912    | Trefftz
  CYff  =   0.01914         e =    0.9779    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.729684    CLb =   0.208685
 y  force CY |    CYa =  -0.003016    CYb =  -0.296413
 x' mom.  Cl'|    Cla =   0.021930    Clb =  -0.058304
 y  mom.  Cm |    Cma =  -1.941370    Cmb =  -0.103018
 z' mom.  Cn'|    Cna =  -0.006904    Cnb =   0.121290

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012926    CLq =  10.460780    CLr =  -0.020296
 y  force CY |    CYp =   0.155114    CYq =  -0.059127    CYr =   0.235617
 x' mom.  Cl'|    Clp =  -0.447164    Clq =   0.038470    Clr =   0.279895
 y  mom.  Cm |    Cmp =  -0.003997    Cmq = -19.219030    Cmr =   0.055322
 z' mom.  Cn'|    Cnp =  -0.087729    Cnq =   0.029134    Cnr =  -0.149480

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000121   CLd02 =   0.007913   CLd03 =   0.000077
 y  force CY |   CYd01 =   0.000188   CYd02 =  -0.000002   CYd03 =  -0.002821
 x' mom.  Cl'|   Cld01 =  -0.004365   Cld02 =   0.000023   Cld03 =  -0.000239
 y  mom.  Cm |   Cmd01 =  -0.000076   Cmd02 =  -0.029842   Cmd03 =  -0.000293
 z' mom.  Cn'|   Cnd01 =  -0.000047   Cnd02 =   0.000003   Cnd03 =   0.001530
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000553 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000062    ed02 =   0.004463    ed03 =   0.002838



 Neutral point  Xnp =   0.173751

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
