 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09503     Cltot =  -0.00638     Cl'tot =  -0.00531
  CYtot =  -0.01535     Cmtot =  -0.16272
  CZtot =  -1.54771     Cntot =   0.00559     Cn'tot =   0.00661

  CLtot =   1.54070
  CDtot =   0.17517
  CDvis =   0.07000     CDind = 0.1051697
  CLff  =   1.56157     CDff  = 0.1082825    | Trefftz
  CYff  =  -0.01146         e =    1.0036    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.541625    CLb =  -0.167731
 y  force CY |    CYa =   0.003144    CYb =  -0.292257
 x' mom.  Cl'|    Cla =  -0.012360    Clb =  -0.101112
 y  mom.  Cm |    Cma =  -1.107077    Cmb =   0.034728
 z' mom.  Cn'|    Cna =   0.007409    Cnb =   0.125760

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008222    CLq =   7.442089    CLr =   0.011157
 y  force CY |    CYp =   0.189261    CYq =   0.050136    CYr =   0.199158
 x' mom.  Cl'|    Clp =  -0.426591    Clq =  -0.010104    Clr =   0.373826
 y  mom.  Cm |    Cmp =   0.003122    Cmq = -16.636921    Cmr =  -0.019699
 z' mom.  Cn'|    Cnp =  -0.102117    Cnq =  -0.023970    Cnr =  -0.152185

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000069   CLd02 =   0.007703   CLd03 =  -0.000042
 y  force CY |   CYd01 =   0.000144   CYd02 =   0.000001   CYd03 =  -0.002748
 x' mom.  Cl'|   Cld01 =  -0.004161   Cld02 =  -0.000013   Cld03 =  -0.000463
 y  mom.  Cm |   Cmd01 =   0.000027   Cmd02 =  -0.027936   Cmd03 =   0.000138
 z' mom.  Cn'|   Cnd01 =  -0.000172   Cnd02 =  -0.000002   Cnd03 =   0.001398
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000964 CDffd03 =   0.000104
 span eff.   |    ed01 =   0.000027    ed02 =   0.001122    ed03 =  -0.000942



 Neutral point  Xnp =   0.195241

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
