 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06606     Cltot =   0.00605     Cl'tot =   0.00510
  CYtot =   0.01540     Cmtot =  -0.14351
  CZtot =  -1.46871     Cntot =  -0.00561     Cn'tot =  -0.00648

  CLtot =   1.46096
  CDtot =   0.16451
  CDvis =   0.07000     CDind = 0.0945133
  CLff  =   1.47816     CDff  = 0.0971655    | Trefftz
  CYff  =   0.01146         e =    1.0022    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.595151    CLb =   0.159661
 y  force CY |    CYa =  -0.002940    CYb =  -0.293268
 x' mom.  Cl'|    Cla =   0.012611    Clb =  -0.096965
 y  mom.  Cm |    Cma =  -1.093466    Cmb =  -0.032715
 z' mom.  Cn'|    Cna =  -0.006973    Cnb =   0.123372

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008446    CLq =   7.497771    CLr =  -0.011306
 y  force CY |    CYp =   0.174124    CYq =  -0.050136    CYr =   0.205050
 x' mom.  Cl'|    Clp =  -0.432088    Clq =   0.009684    Clr =   0.359266
 y  mom.  Cm |    Cmp =  -0.003466    Cmq = -16.644317    Cmr =   0.019641
 z' mom.  Cn'|    Cnp =  -0.093735    Cnq =   0.024143    Cnr =  -0.149139

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000069   CLd02 =   0.007754   CLd03 =   0.000042
 y  force CY |   CYd01 =   0.000161   CYd02 =  -0.000001   CYd03 =  -0.002766
 x' mom.  Cl'|   Cld01 =  -0.004206   Cld02 =   0.000013   Cld03 =  -0.000468
 y  mom.  Cm |   Cmd01 =  -0.000027   Cmd02 =  -0.028033   Cmd03 =  -0.000138
 z' mom.  Cn'|   Cnd01 =  -0.000151   Cnd02 =   0.000002   Cnd03 =   0.001407
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000875 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000031    ed02 =   0.001620    ed03 =   0.001051



 Neutral point  Xnp =   0.193605

 Clb Cnr / Clr Cnb  =   0.326266    (  > 1 if spirally stable )
