 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09405     Cltot =   0.00017     Cl'tot =  -0.00047
  CYtot =  -0.01582     Cmtot =   0.06632
  CZtot =  -0.17540     Cntot =   0.00615     Cn'tot =   0.00614

  CLtot =   0.18427
  CDtot =   0.07520
  CDvis =   0.07000     CDind = 0.0052005
  CLff  =   0.18425     CDff  = 0.0057835    | Trefftz
  CYff  =  -0.01149         e =    0.2626    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.976355    CLb =  -0.029944
 y  force CY |    CYa =  -0.000513    CYb =  -0.301206
 x' mom.  Cl'|    Cla =  -0.013796    Clb =  -0.008951
 y  mom.  Cm |    Cma =  -1.917787    Cmb =   0.022602
 z' mom.  Cn'|    Cna =  -0.001092    Cnb =   0.116821

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010173    CLq =  10.629064    CLr =   0.013445
 y  force CY |    CYp =  -0.023937    CYq =   0.035505    CYr =   0.247379
 x' mom.  Cl'|    Clp =  -0.476133    Clq =  -0.019338    Clr =   0.098185
 y  mom.  Cm |    Cmp =   0.008695    Cmq = -19.004075    Cmr =  -0.032152
 z' mom.  Cn'|    Cnp =   0.002042    Cnq =  -0.021581    Cnr =  -0.128034

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000076   CLd02 =   0.007871   CLd03 =  -0.000053
 y  force CY |   CYd01 =   0.000377   CYd02 =   0.000001   CYd03 =  -0.002841
 x' mom.  Cl'|   Cld01 =  -0.004601   Cld02 =  -0.000014   Cld03 =  -0.000266
 y  mom.  Cm |   Cmd01 =   0.000048   Cmd02 =  -0.029427   Cmd03 =   0.000176
 z' mom.  Cn'|   Cnd01 =   0.000217   Cnd02 =  -0.000002   Cnd03 =   0.001539
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000516 CDffd03 =   0.000104
 span eff.   |    ed01 =   0.000083    ed02 =   0.045956    ed03 =  -0.004243



 Neutral point  Xnp =   0.166677

 Clb Cnr / Clr Cnb  =   0.099917    (  > 1 if spirally stable )
