 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07372     Cltot =   0.00347     Cl'tot =   0.00319
  CYtot =   0.02100     Cmtot =  -0.20587
  CZtot =  -0.87436     Cntot =  -0.00821     Cn'tot =  -0.00833

  CLtot =   0.87126
  CDtot =   0.10419
  CDvis =   0.07000     CDind = 0.0341921
  CLff  =   0.87503     CDff  = 0.0358444    | Trefftz
  CYff  =   0.01532         e =    0.9522    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.845059    CLb =   0.133239
 y  force CY |    CYa =  -0.001576    CYb =  -0.299254
 x' mom.  Cl'|    Cla =   0.018058    Clb =  -0.045339
 y  mom.  Cm |    Cma =  -1.966388    Cmb =  -0.068225
 z' mom.  Cn'|    Cna =  -0.003665    Cnb =   0.118533

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011154    CLq =  10.528356    CLr =  -0.016822
 y  force CY |    CYp =   0.107070    CYq =  -0.047323    CYr =   0.245818
 x' mom.  Cl'|    Clp =  -0.458167    Clq =   0.029528    Clr =   0.232198
 y  mom.  Cm |    Cmp =  -0.005512    Cmq = -19.244292    Cmr =   0.044050
 z' mom.  Cn'|    Cnp =  -0.062652    Cnq =   0.024897    Cnr =  -0.143151

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007986   CLd03 =   0.000064
 y  force CY |   CYd01 =   0.000240   CYd02 =  -0.000001   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004468   Cld02 =   0.000019   Cld03 =  -0.000248
 y  mom.  Cm |   Cmd01 =  -0.000062   Cmd02 =  -0.029990   Cmd03 =  -0.000235
 z' mom.  Cn'|   Cnd01 =   0.000022   Cnd02 =   0.000002   Cnd03 =   0.001546
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000263 CDffd03 =  -0.000139
 span eff.   |    ed01 =  -0.000079    ed02 =   0.010375    ed03 =   0.003598



 Neutral point  Xnp =   0.172451

 Clb Cnr / Clr Cnb  =   0.235816    (  > 1 if spirally stable )
