 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10387     Cltot =  -0.00321     Cl'tot =  -0.00370
  CYtot =  -0.02619     Cmtot =   0.06170
  CZtot =  -0.44168     Cntot =   0.00950     Cn'tot =   0.00932

  CLtot =   0.44651
  CDtot =   0.08061
  CDvis =   0.07000     CDind = 0.0106092
  CLff  =   0.44835     CDff  = 0.0125487    | Trefftz
  CYff  =  -0.01908         e =    0.7152    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.962393    CLb =  -0.094500
 y  force CY |    CYa =   0.000723    CYb =  -0.297599
 x' mom.  Cl'|    Cla =  -0.023850    Clb =  -0.042014
 y  mom.  Cm |    Cma =  -0.828482    Cmb =   0.018705
 z' mom.  Cn'|    Cna =   0.002061    Cnb =   0.105718

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.019042    CLq =   8.036221    CLr =   0.020712
 y  force CY |    CYp =  -0.017322    CYq =   0.083492    CYr =   0.232306
 x' mom.  Cl'|    Clp =  -0.480501    Clq =  -0.007415    Clr =   0.167572
 y  mom.  Cm |    Cmp =   0.012446    Cmq = -16.298675    Cmr =  -0.030794
 z' mom.  Cn'|    Cnp =  -0.000983    Cnq =  -0.042680    Cnr =  -0.114712

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000124   CLd02 =   0.007866   CLd03 =  -0.000086
 y  force CY |   CYd01 =   0.000368   CYd02 =   0.000002   CYd03 =  -0.002841
 x' mom.  Cl'|   Cld01 =  -0.004526   Cld02 =  -0.000022   Cld03 =  -0.000508
 y  mom.  Cm |   Cmd01 =   0.000049   Cmd02 =  -0.027718   Cmd03 =   0.000232
 z' mom.  Cn'|   Cnd01 =   0.000133   Cnd02 =  -0.000003   Cnd03 =   0.001443
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =  -0.000246 CDffd03 =   0.000176
 span eff.   |    ed01 =   0.000295    ed02 =   0.039143    ed03 =  -0.009648



 Neutral point  Xnp =   0.173580

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
