 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09508     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.16363
  CZtot =  -1.55217     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.54510
  CDtot =   0.17589
  CDvis =   0.07000     CDind = 0.1058923
  CLff  =   1.56372     CDff  = 0.1083642    | Trefftz
  CYff  =   0.00000         e =    1.0056    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.553665    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.293578
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.101669
 y  mom.  Cm |    Cma =  -1.110118    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.126453

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.452302    CLr =   0.000000
 y  force CY |    CYp =   0.189521    CYq =   0.000000    CYr =   0.199431
 x' mom.  Cl'|    Clp =  -0.427177    Clq =  -0.000000    Clr =   0.374339
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.659752    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.102257    Cnq =  -0.000000    Cnr =  -0.152394

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007725   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000145   CYd02 =   0.000000   CYd03 =  -0.002756
 x' mom.  Cl'|   Cld01 =  -0.004172   Cld02 =   0.000000   Cld03 =  -0.000464
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028013   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000173   Cnd02 =  -0.000000   Cnd03 =   0.001401
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000967 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.001107    ed03 =   0.000000



 Neutral point  Xnp =   0.195248

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
