 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07586     Cltot =   0.00029     Cl'tot =   0.00000
  CYtot =  -0.00527     Cmtot =   0.13229
  CZtot =  -0.00035     Cntot =   0.00205     Cn'tot =   0.00207

  CLtot =   0.01091
  CDtot =   0.07507
  CDvis =   0.07000     CDind = 0.0050732
  CLff  =   0.01024     CDff  = 0.0049905    | Trefftz
  CYff  =  -0.00383         e =    0.0011    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.982633    CLb =  -0.004085
 y  force CY |    CYa =  -0.000313    CYb =  -0.301940
 x' mom.  Cl'|    Cla =  -0.004570    Clb =   0.000181
 y  mom.  Cm |    Cma =  -1.885542    Cmb =   0.005225
 z' mom.  Cn'|    Cna =  -0.000685    Cnb =   0.118442

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003553    CLq =  10.651858    CLr =   0.004525
 y  force CY |    CYp =  -0.056444    CYq =   0.011840    CYr =   0.242286
 x' mom.  Cl'|    Clp =  -0.478585    Clq =  -0.006194    Clr =   0.063802
 y  mom.  Cm |    Cmp =   0.003272    Cmq = -18.903760    Cmr =  -0.010614
 z' mom.  Cn'|    Cnp =   0.017803    Cnq =  -0.007417    Cnr =  -0.125028

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007798   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000412   CYd02 =   0.000000   CYd03 =  -0.002826
 x' mom.  Cl'|   Cld01 =  -0.004614   Cld02 =  -0.000005   Cld03 =  -0.000269
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.029163   Cmd03 =   0.000058
 z' mom.  Cn'|   Cnd01 =   0.000266   Cnd02 =  -0.000001   Cnd03 =   0.001531
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000708 CDffd03 =   0.000035
 span eff.   |    ed01 =  -0.000012    ed02 =   0.001597    ed03 =   0.000180



 Neutral point  Xnp =   0.164715

 Clb Cnr / Clr Cnb  =  -0.002990    (  > 1 if spirally stable )
