 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10204     Cltot =  -0.00203     Cl'tot =  -0.00239
  CYtot =  -0.02630     Cmtot =  -0.06766
  CZtot =  -0.52463     Cntot =   0.01026     Cn'tot =   0.01018

  CLtot =   0.52787
  CDtot =   0.08367
  CDvis =   0.07000     CDind = 0.0136729
  CLff  =   0.53010     CDff  = 0.0156224    | Trefftz
  CYff  =  -0.01914         e =    0.8026    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.920848    CLb =  -0.108403
 y  force CY |    CYa =   0.000558    CYb =  -0.298893
 x' mom.  Cl'|    Cla =  -0.022948    Clb =  -0.027054
 y  mom.  Cm |    Cma =  -1.953734    Cmb =   0.061176
 z' mom.  Cn'|    Cna =   0.001393    Cnb =   0.115513

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015390    CLq =  10.568359    CLr =   0.021809
 y  force CY |    CYp =   0.041567    CYq =   0.059127    CYr =   0.250702
 x' mom.  Cl'|    Clp =  -0.468197    Clq =  -0.034633    Clr =   0.165798
 y  mom.  Cm |    Cmp =   0.010709    Cmq = -19.134418    Cmr =  -0.054423
 z' mom.  Cn'|    Cnp =  -0.029856    Cnq =  -0.033605    Cnr =  -0.134865

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000125   CLd02 =   0.007947   CLd03 =  -0.000085
 y  force CY |   CYd01 =   0.000308   CYd02 =   0.000002   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004539   Cld02 =  -0.000023   Cld03 =  -0.000257
 y  mom.  Cm |   Cmd01 =   0.000078   Cmd02 =  -0.029739   Cmd03 =   0.000294
 z' mom.  Cn'|   Cnd01 =   0.000118   Cnd02 =  -0.000003   Cnd03 =   0.001544
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =  -0.000127 CDffd03 =   0.000174
 span eff.   |    ed01 =   0.000192    ed02 =   0.030632    ed03 =  -0.008635



 Neutral point  Xnp =   0.169963

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
