 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15764     Cltot =   0.00800     Cl'tot =   0.00616
  CYtot =   0.02049     Cmtot =  -0.53957
  CZtot =  -1.68593     Cntot =  -0.00801     Cn'tot =  -0.00950

  CLtot =   1.68186
  CDtot =   0.19633
  CDvis =   0.07000     CDind = 0.1263335
  CLff  =   1.71325     CDff  = 0.1312756    | Trefftz
  CYff  =   0.01532         e =    0.9965    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.392102    CLb =   0.242811
 y  force CY |    CYa =  -0.004351    CYb =  -0.291875
 x' mom.  Cl'|    Cla =   0.015715    Clb =  -0.087712
 y  mom.  Cm |    Cma =  -1.818662    Cmb =  -0.114895
 z' mom.  Cn'|    Cna =  -0.009621    Cnb =   0.135202

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008724    CLq =  10.313725    CLr =  -0.014592
 y  force CY |    CYp =   0.261998    CYq =  -0.047323    CYr =   0.193777
 x' mom.  Cl'|    Clp =  -0.416536    Clq =   0.033402    Clr =   0.385874
 y  mom.  Cm |    Cmp =   0.002221    Cmq = -19.043271    Cmr =   0.044338
 z' mom.  Cn'|    Cnp =  -0.148973    Cnq =   0.019391    Cnr =  -0.165595

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000091   CLd02 =   0.007607   CLd03 =   0.000053
 y  force CY |   CYd01 =   0.000072   CYd02 =  -0.000001   CYd03 =  -0.002717
 x' mom.  Cl'|   Cld01 =  -0.004077   Cld02 =   0.000018   Cld03 =  -0.000215
 y  mom.  Cm |   Cmd01 =  -0.000057   Cmd02 =  -0.029140   Cmd03 =  -0.000230
 z' mom.  Cn'|   Cnd01 =  -0.000198   Cnd02 =   0.000002   Cnd03 =   0.001475
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.001210 CDffd03 =  -0.000136
 span eff.   |    ed01 =  -0.000021    ed02 =  -0.000063    ed03 =   0.001008



 Neutral point  Xnp =   0.174769

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
