 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06131     Cltot =  -0.00099     Cl'tot =  -0.00088
  CYtot =  -0.00526     Cmtot =  -0.24255
  CZtot =  -0.96483     Cntot =   0.00206     Cn'tot =   0.00211

  CLtot =   0.96029
  CDtot =   0.11172
  CDvis =   0.07000     CDind = 0.0417232
  CLff  =   0.96267     CDff  = 0.0424420    | Trefftz
  CYff  =  -0.00383         e =    0.9731    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.835532    CLb =  -0.036276
 y  force CY |    CYa =   0.000466    CYb =  -0.301097
 x' mom.  Cl'|    Cla =  -0.004493    Clb =  -0.050267
 y  mom.  Cm |    Cma =  -1.971212    Cmb =   0.018311
 z' mom.  Cn'|    Cna =   0.001077    Cnb =   0.120622

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002722    CLq =  10.535826    CLr =   0.004163
 y  force CY |    CYp =   0.123549    CYq =   0.011840    CYr =   0.243644
 x' mom.  Cl'|    Clp =  -0.455964    Clq =  -0.007495    Clr =   0.248957
 y  mom.  Cm |    Cmp =   0.001187    Cmq = -19.294610    Cmr =  -0.011043
 z' mom.  Cn'|    Cnp =  -0.071150    Cnq =  -0.006099    Cnr =  -0.145626

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.008011   CLd03 =  -0.000016
 y  force CY |   CYd01 =   0.000224   CYd02 =   0.000000   CYd03 =  -0.002858
 x' mom.  Cl'|   Cld01 =  -0.004461   Cld02 =  -0.000005   Cld03 =  -0.000247
 y  mom.  Cm |   Cmd01 =   0.000015   Cmd02 =  -0.030124   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =  -0.000001   Cnd03 =   0.001550
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000363 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000017    ed02 =   0.007858    ed03 =  -0.000779



 Neutral point  Xnp =   0.172958

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
