 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07427     Cltot =  -0.00174     Cl'tot =  -0.00160
  CYtot =  -0.01052     Cmtot =  -0.20766
  CZtot =  -0.87787     Cntot =   0.00412     Cn'tot =   0.00417

  CLtot =   0.87475
  CDtot =   0.10486
  CDvis =   0.07000     CDind = 0.0348640
  CLff  =   0.87663     CDff  = 0.0356945    | Trefftz
  CYff  =  -0.00766         e =    0.9595    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.862274    CLb =  -0.066782
 y  force CY |    CYa =   0.000790    CYb =  -0.301072
 x' mom.  Cl'|    Cla =  -0.009051    Clb =  -0.045673
 y  mom.  Cm |    Cma =  -1.973597    Cmb =   0.034196
 z' mom.  Cn'|    Cna =   0.001837    Cnb =   0.119406

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005580    CLq =  10.547636    CLr =   0.008416
 y  force CY |    CYp =   0.107266    CYq =   0.023676    CYr =   0.246268
 x' mom.  Cl'|    Clp =  -0.459006    Clq =  -0.014773    Clr =   0.232624
 y  mom.  Cm |    Cmp =   0.002758    Cmq = -19.279533    Cmr =  -0.022038
 z' mom.  Cn'|    Cnp =  -0.062766    Cnq =  -0.012456    Cnr =  -0.143413

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.008015   CLd03 =  -0.000032
 y  force CY |   CYd01 =   0.000241   CYd02 =   0.000001   CYd03 =  -0.002861
 x' mom.  Cl'|   Cld01 =  -0.004485   Cld02 =  -0.000009   Cld03 =  -0.000249
 y  mom.  Cm |   Cmd01 =   0.000031   Cmd02 =  -0.030100   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000022   Cnd02 =  -0.000001   Cnd03 =   0.001552
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000264 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000040    ed02 =   0.010403    ed03 =  -0.001825



 Neutral point  Xnp =   0.172464

 Clb Cnr / Clr Cnb  =   0.235816    (  > 1 if spirally stable )
