 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03861     Cltot =   0.00467     Cl'tot =   0.00377
  CYtot =   0.01558     Cmtot =  -0.41084
  CZtot =  -1.37846     Cntot =  -0.00610     Cn'tot =  -0.00669

  CLtot =   1.37042
  CDtot =   0.15361
  CDvis =   0.07000     CDind = 0.0836148
  CLff  =   1.38429     CDff  = 0.0859075    | Trefftz
  CYff  =   0.01149         e =    0.9941    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.619725    CLb =   0.150498
 y  force CY |    CYa =  -0.002443    CYb =  -0.296698
 x' mom.  Cl'|    Cla =   0.012694    Clb =  -0.071791
 y  mom.  Cm |    Cma =  -1.909778    Cmb =  -0.072616
 z' mom.  Cn'|    Cna =  -0.005513    Cnb =   0.127308

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.007203    CLq =  10.423179    CLr =  -0.011693
 y  force CY |    CYp =   0.202504    CYq =  -0.035505    CYr =   0.221310
 x' mom.  Cl'|    Clp =  -0.435977    Clq =   0.023985    Clr =   0.327110
 y  mom.  Cm |    Cmp =  -0.000658    Cmq = -19.214355    Cmr =   0.033300
 z' mom.  Cn'|    Cnp =  -0.113759    Cnq =   0.016261    Cnr =  -0.156628

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000071   CLd02 =   0.007845   CLd03 =   0.000043
 y  force CY |   CYd01 =   0.000138   CYd02 =  -0.000001   CYd03 =  -0.002797
 x' mom.  Cl'|   Cld01 =  -0.004272   Cld02 =   0.000014   Cld03 =  -0.000230
 y  mom.  Cm |   Cmd01 =  -0.000045   Cmd02 =  -0.029759   Cmd03 =  -0.000175
 z' mom.  Cn'|   Cnd01 =  -0.000114   Cnd02 =   0.000002   Cnd03 =   0.001518
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000843 CDffd03 =  -0.000104
 span eff.   |    ed01 =  -0.000025    ed02 =   0.001640    ed03 =   0.001168



 Neutral point  Xnp =   0.174578

 Clb Cnr / Clr Cnb  =   0.270016    (  > 1 if spirally stable )
