 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02771     Cltot =  -0.00485     Cl'tot =  -0.00412
  CYtot =  -0.02090     Cmtot =  -0.30841
  CZtot =  -1.12909     Cntot =   0.00818     Cn'tot =   0.00857

  CLtot =   1.12238
  CDtot =   0.12601
  CDvis =   0.07000     CDind = 0.0560098
  CLff  =   1.13047     CDff  = 0.0580399    | Trefftz
  CYff  =  -0.01532         e =    0.9814    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.742274    CLb =  -0.167254
 y  force CY |    CYa =   0.002417    CYb =  -0.297766
 x' mom.  Cl'|    Cla =  -0.017576    Clb =  -0.058627
 y  mom.  Cm |    Cma =  -1.946711    Cmb =   0.082565
 z' mom.  Cn'|    Cna =   0.005533    Cnb =   0.121963

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010345    CLq =  10.475159    CLr =   0.016244
 y  force CY |    CYp =   0.155327    CYq =   0.047323    CYr =   0.235941
 x' mom.  Cl'|    Clp =  -0.447778    Clq =  -0.030790    Clr =   0.280280
 y  mom.  Cm |    Cmp =   0.003199    Cmq = -19.245448    Cmr =  -0.044278
 z' mom.  Cn'|    Cnp =  -0.087849    Cnq =  -0.023317    Cnr =  -0.149686

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000097   CLd02 =   0.007934   CLd03 =  -0.000061
 y  force CY |   CYd01 =   0.000189   CYd02 =   0.000001   CYd03 =  -0.002829
 x' mom.  Cl'|   Cld01 =  -0.004377   Cld02 =  -0.000018   Cld03 =  -0.000240
 y  mom.  Cm |   Cmd01 =   0.000061   Cmd02 =  -0.029924   Cmd03 =   0.000235
 z' mom.  Cn'|   Cnd01 =  -0.000047   Cnd02 =  -0.000002   Cnd03 =   0.001534
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000555 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000050    ed02 =   0.004446    ed03 =  -0.002285



 Neutral point  Xnp =   0.173761

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
