 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06523     Cltot =  -0.00666     Cl'tot =  -0.00532
  CYtot =  -0.02069     Cmtot =  -0.44246
  CZtot =  -1.45509     Cntot =   0.00810     Cn'tot =   0.00904

  CLtot =   1.44738
  CDtot =   0.16320
  CDvis =   0.07000     CDind = 0.0932012
  CLff  =   1.46612     CDff  = 0.0963757    | Trefftz
  CYff  =  -0.01532         e =    0.9940    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.560011    CLb =  -0.211187
 y  force CY |    CYa =   0.003529    CYb =  -0.294811
 x' mom.  Cl'|    Cla =  -0.016635    Clb =  -0.075649
 y  mom.  Cm |    Cma =  -1.887368    Cmb =   0.101313
 z' mom.  Cn'|    Cna =   0.007925    Cnb =   0.128659

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.009369    CLq =  10.388940    CLr =   0.015348
 y  force CY |    CYp =   0.217564    CYq =   0.047323    CYr =   0.215035
 x' mom.  Cl'|    Clp =  -0.431035    Clq =  -0.032342    Clr =   0.341861
 y  mom.  Cm |    Cmp =   0.000103    Cmq = -19.164954    Cmr =  -0.044393
 z' mom.  Cn'|    Cnp =  -0.122369    Cnq =  -0.021113    Cnr =  -0.158746

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000094   CLd02 =   0.007782   CLd03 =  -0.000057
 y  force CY |   CYd01 =   0.000121   CYd02 =   0.000001   CYd03 =  -0.002775
 x' mom.  Cl'|   Cld01 =  -0.004220   Cld02 =  -0.000018   Cld03 =  -0.000226
 y  mom.  Cm |   Cmd01 =   0.000059   Cmd02 =  -0.029583   Cmd03 =   0.000233
 z' mom.  Cn'|   Cnd01 =  -0.000136   Cnd02 =  -0.000002   Cnd03 =   0.001506
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000935 CDffd03 =   0.000138
 span eff.   |    ed01 =   0.000029    ed02 =   0.001079    ed03 =  -0.001382



 Neutral point  Xnp =   0.174719

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
