 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09322     Cltot =  -0.00029     Cl'tot =   0.00078
  CYtot =   0.02629     Cmtot =   0.06737
  CZtot =  -0.17409     Cntot =  -0.01022     Cn'tot =  -0.01020

  CLtot =   0.18288
  CDtot =   0.07451
  CDvis =   0.07000     CDind = 0.0045113
  CLff  =   0.18380     CDff  = 0.0061291    | Trefftz
  CYff  =   0.01914         e =    0.2483    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.952782    CLb =   0.049745
 y  force CY |    CYa =   0.000852    CYb =  -0.298777
 x' mom.  Cl'|    Cla =   0.022919    Clb =  -0.008864
 y  mom.  Cm |    Cma =  -1.908447    Cmb =  -0.037548
 z' mom.  Cn'|    Cna =   0.001814    Cnb =   0.115680

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.016941    CLq =  10.603148    CLr =  -0.022390
 y  force CY |    CYp =  -0.023879    CYq =  -0.059127    CYr =   0.246776
 x' mom.  Cl'|    Clp =  -0.474972    Clq =   0.032204    Clr =   0.097946
 y  mom.  Cm |    Cmp =  -0.014480    Cmq = -18.957740    Cmr =   0.053543
 z' mom.  Cn'|    Cnp =   0.002037    Cnq =   0.035939    Cnr =  -0.127722

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000126   CLd02 =   0.007833   CLd03 =   0.000089
 y  force CY |   CYd01 =   0.000376   CYd02 =  -0.000002   CYd03 =  -0.002827
 x' mom.  Cl'|   Cld01 =  -0.004578   Cld02 =   0.000023   Cld03 =  -0.000264
 y  mom.  Cm |   Cmd01 =  -0.000079   Cmd02 =  -0.029284   Cmd03 =  -0.000292
 z' mom.  Cn'|   Cnd01 =   0.000216   Cnd02 =   0.000003   Cnd03 =   0.001532
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =  -0.000513 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000120    ed02 =   0.041955    ed03 =   0.006248



 Neutral point  Xnp =   0.166663

 Clb Cnr / Clr Cnb  =   0.099917    (  > 1 if spirally stable )
