 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03926     Cltot =   0.00571     Cl'tot =   0.00487
  CYtot =   0.01545     Cmtot =  -0.12456
  CZtot =  -1.38837     Cntot =  -0.00563     Cn'tot =  -0.00637

  CLtot =   1.38032
  CDtot =   0.15435
  CDvis =   0.07000     CDind = 0.0843486
  CLff  =   1.39429     CDff  = 0.0866296    | Trefftz
  CYff  =   0.01146         e =    1.0001    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.645716    CLb =   0.151494
 y  force CY |    CYa =  -0.002734    CYb =  -0.294210
 x' mom.  Cl'|    Cla =   0.012846    Clb =  -0.092737
 y  mom.  Cm |    Cma =  -1.078523    Cmb =  -0.030728
 z' mom.  Cn'|    Cna =  -0.006529    Cnb =   0.121130

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008674    CLq =   7.552271    CLr =  -0.011447
 y  force CY |    CYp =   0.158791    CYq =  -0.050136    CYr =   0.210409
 x' mom.  Cl'|    Clp =  -0.437405    Clq =   0.009261    Clr =   0.344463
 y  mom.  Cm |    Cmp =  -0.003808    Cmq = -16.646643    Cmr =   0.019578
 z' mom.  Cn'|    Cnp =  -0.085458    Cnq =   0.024309    Cnr =  -0.146096

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000070   CLd02 =   0.007799   CLd03 =   0.000043
 y  force CY |   CYd01 =   0.000178   CYd02 =  -0.000001   CYd03 =  -0.002783
 x' mom.  Cl'|   Cld01 =  -0.004249   Cld02 =   0.000013   Cld03 =  -0.000473
 y  mom.  Cm |   Cmd01 =  -0.000028   Cmd02 =  -0.028112   Cmd03 =  -0.000139
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =   0.000002   Cnd03 =   0.001415
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000784 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000035    ed02 =   0.002234    ed03 =   0.001180



 Neutral point  Xnp =   0.191967

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
