 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02819     Cltot =  -0.00122     Cl'tot =  -0.00103
  CYtot =  -0.00524     Cmtot =  -0.31112
  CZtot =  -1.13464     Cntot =   0.00205     Cn'tot =   0.00215

  CLtot =   1.12786
  CDtot =   0.12697
  CDvis =   0.07000     CDind = 0.0569686
  CLff  =   1.13306     CDff  = 0.0579542    | Trefftz
  CYff  =  -0.00383         e =    0.9872    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.763309    CLb =  -0.041941
 y  force CY |    CYa =   0.000606    CYb =  -0.300026
 x' mom.  Cl'|    Cla =  -0.004407    Clb =  -0.059167
 y  mom.  Cm |    Cma =  -1.955634    Cmb =   0.020704
 z' mom.  Cn'|    Cna =   0.001387    Cnb =   0.123086

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002588    CLq =  10.499139    CLr =   0.004064
 y  force CY |    CYp =   0.155683    CYq =   0.011840    CYr =   0.236481
 x' mom.  Cl'|    Clp =  -0.448803    Clq =  -0.007703    Clr =   0.280921
 y  mom.  Cm |    Cmp =   0.000800    Cmq = -19.289505    Cmr =  -0.011078
 z' mom.  Cn'|    Cnp =  -0.088050    Cnq =  -0.005834    Cnr =  -0.150028

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000024   CLd02 =   0.007971   CLd03 =  -0.000015
 y  force CY |   CYd01 =   0.000190   CYd02 =   0.000000   CYd03 =  -0.002841
 x' mom.  Cl'|   Cld01 =  -0.004397   Cld02 =  -0.000005   Cld03 =  -0.000241
 y  mom.  Cm |   Cmd01 =   0.000015   Cmd02 =  -0.030062   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =  -0.000048   Cnd02 =  -0.000001   Cnd03 =   0.001541
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000557 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000013    ed02 =   0.004418    ed03 =  -0.000577



 Neutral point  Xnp =   0.173779

 Clb Cnr / Clr Cnb  =   0.256721    (  > 1 if spirally stable )
