 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09895     Cltot =  -0.00029     Cl'tot =  -0.00118
  CYtot =  -0.02631     Cmtot =   0.03393
  CZtot =  -0.26168     Cntot =   0.01024     Cn'tot =   0.01017

  CLtot =   0.26931
  CDtot =   0.07577
  CDvis =   0.07000     CDind = 0.0057667
  CLff  =   0.27052     CDff  = 0.0074723    | Trefftz
  CYff  =  -0.01914         e =    0.4386    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.950172    CLb =  -0.064448
 y  force CY |    CYa =  -0.000500    CYb =  -0.298911
 x' mom.  Cl'|    Cla =  -0.022968    Clb =  -0.013406
 y  mom.  Cm |    Cma =  -1.923298    Cmb =   0.043399
 z' mom.  Cn'|    Cna =  -0.001013    Cnb =   0.115400

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.016546    CLq =  10.596338    CLr =   0.022265
 y  force CY |    CYp =  -0.007579    CYq =   0.059127    CYr =   0.248614
 x' mom.  Cl'|    Clp =  -0.473655    Clq =  -0.032827    Clr =   0.115038
 y  mom.  Cm |    Cmp =   0.013543    Cmq = -19.010610    Cmr =  -0.053788
 z' mom.  Cn'|    Cnp =  -0.005870    Cnq =  -0.035371    Cnr =  -0.129407

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000126   CLd02 =   0.007871   CLd03 =  -0.000088
 y  force CY |   CYd01 =   0.000359   CYd02 =   0.000002   CYd03 =  -0.002835
 x' mom.  Cl'|   Cld01 =  -0.004573   Cld02 =  -0.000023   Cld03 =  -0.000263
 y  mom.  Cm |   Cmd01 =   0.000079   Cmd02 =  -0.029424   Cmd03 =   0.000293
 z' mom.  Cn'|   Cnd01 =   0.000191   Cnd02 =  -0.000003   Cnd03 =   0.001536
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =  -0.000418 CDffd03 =   0.000173
 span eff.   |    ed01 =   0.000203    ed02 =   0.050114    ed03 =  -0.009550



 Neutral point  Xnp =   0.167566

 Clb Cnr / Clr Cnb  =   0.130682    (  > 1 if spirally stable )
