 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09369     Cltot =   0.00023     Cl'tot =  -0.00063
  CYtot =  -0.02107     Cmtot =   0.06678
  CZtot =  -0.17483     Cntot =   0.00819     Cn'tot =   0.00817

  CLtot =   0.18367
  CDtot =   0.07490
  CDvis =   0.07000     CDind = 0.0048987
  CLff  =   0.18405     CDff  = 0.0059348    | Trefftz
  CYff  =  -0.01532         e =    0.2561    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.966032    CLb =  -0.039869
 y  force CY |    CYa =  -0.000683    CYb =  -0.300143
 x' mom.  Cl'|    Cla =  -0.018369    Clb =  -0.008913
 y  mom.  Cm |    Cma =  -1.913697    Cmb =   0.030093
 z' mom.  Cn'|    Cna =  -0.001454    Cnb =   0.116321

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.013559    CLq =  10.617723    CLr =   0.017920
 y  force CY |    CYp =  -0.023912    CYq =   0.047323    CYr =   0.247115
 x' mom.  Cl'|    Clp =  -0.475625    Clq =  -0.025775    Clr =   0.098081
 y  mom.  Cm |    Cmp =   0.011589    Cmq = -18.983799    Cmr =  -0.042854
 z' mom.  Cn'|    Cnp =   0.002040    Cnq =  -0.028764    Cnr =  -0.127898

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000101   CLd02 =   0.007855   CLd03 =  -0.000071
 y  force CY |   CYd01 =   0.000377   CYd02 =   0.000001   CYd03 =  -0.002834
 x' mom.  Cl'|   Cld01 =  -0.004591   Cld02 =  -0.000018   Cld03 =  -0.000265
 y  mom.  Cm |   Cmd01 =   0.000064   Cmd02 =  -0.029364   Cmd03 =   0.000234
 z' mom.  Cn'|   Cnd01 =   0.000216   Cnd02 =  -0.000002   Cnd03 =   0.001536
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000515 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000104    ed02 =   0.044127    ed03 =  -0.005355



 Neutral point  Xnp =   0.166671

 Clb Cnr / Clr Cnb  =   0.099917    (  > 1 if spirally stable )
