 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04735     Cltot =   0.00209     Cl'tot =   0.00064
  CYtot =  -0.02098     Cmtot =   0.19771
  CZtot =   0.17333     Cntot =   0.00813     Cn'tot =   0.00836

  CLtot =  -0.16248
  CDtot =   0.07672
  CDvis =   0.07000     CDind = 0.0067247
  CLff  =  -0.16363     CDff  = 0.0074714    | Trefftz
  CYff  =  -0.01532         e =    0.1611    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.940713    CLb =   0.007245
 y  force CY |    CYa =  -0.001810    CYb =  -0.298903
 x' mom.  Cl'|    Cla =  -0.017988    Clb =   0.009176
 y  mom.  Cm |    Cma =  -1.831037    Cmb =   0.011782
 z' mom.  Cn'|    Cna =  -0.003996    Cnb =   0.119033

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.014852    CLq =  10.632189    CLr =   0.018208
 y  force CY |    CYp =  -0.088263    CYq =   0.047323    CYr =   0.234102
 x' mom.  Cl'|    Clp =  -0.478319    Clq =  -0.023706    Clr =   0.029048
 y  mom.  Cm |    Cmp =   0.014550    Cmq = -18.714391    Cmr =  -0.041941
 z' mom.  Cn'|    Cnp =   0.033357    Cnq =  -0.030492    Cnr =  -0.121894

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000101   CLd02 =   0.007647   CLd03 =  -0.000073
 y  force CY |   CYd01 =   0.000442   CYd02 =   0.000001   CYd03 =  -0.002785
 x' mom.  Cl'|   Cld01 =  -0.004584   Cld02 =  -0.000018   Cld03 =  -0.000270
 y  mom.  Cm |   Cmd01 =   0.000064   Cmd02 =  -0.028627   Cmd03 =   0.000232
 z' mom.  Cn'|   Cnd01 =   0.000314   Cnd02 =  -0.000002   Cnd03 =   0.001508
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000890 CDffd03 =   0.000137
 span eff.   |    ed01 =   0.000041    ed02 =   0.003896    ed03 =  -0.002465



 Neutral point  Xnp =   0.162510

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
