 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10319     Cltot =   0.00081     Cl'tot =   0.00096
  CYtot =   0.01056     Cmtot =  -0.06991
  CZtot =  -0.52857     Cntot =  -0.00412     Cn'tot =  -0.00409

  CLtot =   0.53185
  CDtot =   0.08468
  CDvis =   0.07000     CDind = 0.0146802
  CLff  =   0.53180     CDff  = 0.0152296    | Trefftz
  CYff  =   0.00766         e =    0.8277    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.951554    CLb =   0.043547
 y  force CY |    CYa =  -0.000224    CYb =  -0.302085
 x' mom.  Cl'|    Cla =   0.009219    Clb =  -0.027404
 y  mom.  Cm |    Cma =  -1.966290    Cmb =  -0.024575
 z' mom.  Cn'|    Cna =  -0.000560    Cnb =   0.117009

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006163    CLq =  10.602266    CLr =  -0.008733
 y  force CY |    CYp =   0.041701    CYq =  -0.023676    CYr =   0.251506
 x' mom.  Cl'|    Clp =  -0.469700    Clq =   0.013868    Clr =   0.166330
 y  mom.  Cm |    Cmp =  -0.004288    Cmq = -19.195808    Cmr =   0.021792
 z' mom.  Cn'|    Cnp =  -0.029951    Cnq =   0.013456    Cnr =  -0.135297

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000050   CLd02 =   0.007998   CLd03 =   0.000034
 y  force CY |   CYd01 =   0.000310   CYd02 =  -0.000001   CYd03 =  -0.002867
 x' mom.  Cl'|   Cld01 =  -0.004569   Cld02 =   0.000009   Cld03 =  -0.000259
 y  mom.  Cm |   Cmd01 =  -0.000031   Cmd02 =  -0.029931   Cmd03 =  -0.000118
 z' mom.  Cn'|   Cnd01 =   0.000119   Cnd02 =   0.000001   Cnd03 =   0.001554
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =  -0.000128 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000082    ed02 =   0.031836    ed03 =   0.003673



 Neutral point  Xnp =   0.169984

 Clb Cnr / Clr Cnb  =   0.190507    (  > 1 if spirally stable )
