 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01404     Cltot =   0.00144     Cl'tot =   0.00119
  CYtot =   0.00521     Cmtot =  -0.37897
  CZtot =  -1.30067     Cntot =  -0.00204     Cn'tot =  -0.00220

  CLtot =   1.29268
  CDtot =   0.14457
  CDvis =   0.07000     CDind = 0.0745712
  CLff  =   1.30206     CDff  = 0.0759914    | Trefftz
  CYff  =   0.00383         e =    0.9942    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.678003    CLb =   0.047507
 y  force CY |    CYa =  -0.000746    CYb =  -0.298674
 x' mom.  Cl'|    Cla =   0.004300    Clb =  -0.067875
 y  mom.  Cm |    Cma =  -1.930529    Cmb =  -0.023073
 z' mom.  Cn'|    Cna =  -0.001692    Cnb =   0.126165

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002462    CLq =  10.458038    CLr =  -0.003956
 y  force CY |    CYp =   0.187238    CYq =  -0.011840    CYr =   0.227093
 x' mom.  Cl'|    Clp =  -0.440806    Clq =   0.007902    Clr =   0.312172
 y  mom.  Cm |    Cmp =  -0.000413    Cmq = -19.260899    Cmr =   0.011099
 z' mom.  Cn'|    Cnp =  -0.105214    Cnq =   0.005561    Cnr =  -0.154538

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007906   CLd03 =   0.000015
 y  force CY |   CYd01 =   0.000155   CYd02 =  -0.000000   CYd03 =  -0.002818
 x' mom.  Cl'|   Cld01 =  -0.004323   Cld02 =   0.000005   Cld03 =  -0.000234
 y  mom.  Cm |   Cmd01 =  -0.000015   Cmd02 =  -0.029926   Cmd03 =  -0.000059
 z' mom.  Cn'|   Cnd01 =  -0.000093   Cnd02 =   0.000001   Cnd03 =   0.001529
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000750 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000009    ed02 =   0.002344    ed03 =   0.000442



 Neutral point  Xnp =   0.174376

 Clb Cnr / Clr Cnb  =   0.266323    (  > 1 if spirally stable )
