 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04797     Cltot =   0.00035     Cl'tot =  -0.00032
  CYtot =  -0.01049     Cmtot =   0.14970
  CZtot =   0.17247     Cntot =   0.00378     Cn'tot =   0.00379

  CLtot =  -0.16152
  CDtot =   0.07719
  CDvis =   0.07000     CDind = 0.0071889
  CLff  =  -0.16278     CDff  = 0.0071825    | Trefftz
  CYff  =  -0.00764         e =    0.1648    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.987623    CLb =   0.003600
 y  force CY |    CYa =  -0.000695    CYb =  -0.300066
 x' mom.  Cl'|    Cla =  -0.009496    Clb =  -0.009060
 y  mom.  Cm |    Cma =  -0.610729    Cmb =   0.001320
 z' mom.  Cn'|    Cna =  -0.001514    Cnb =   0.108293

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008874    CLq =   8.270037    CLr =   0.008331
 y  force CY |    CYp =  -0.128900    CYq =   0.033432    CYr =   0.211913
 x' mom.  Cl'|    Clp =  -0.494128    Clq =  -0.000864    Clr =   0.046704
 y  mom.  Cm |    Cmp =   0.006449    Cmq = -15.840261    Cmr =  -0.011632
 z' mom.  Cn'|    Cnp =   0.047652    Cnq =  -0.017325    Cnr =  -0.099952

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007609   CLd03 =  -0.000037
 y  force CY |   CYd01 =   0.000487   CYd02 =   0.000001   CYd03 =  -0.002796
 x' mom.  Cl'|   Cld01 =  -0.004572   Cld02 =  -0.000009   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.026672   Cmd03 =   0.000092
 z' mom.  Cn'|   Cnd01 =   0.000309   Cnd02 =  -0.000001   Cnd03 =   0.001419
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000891 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000033    ed02 =   0.004707    ed03 =  -0.001340



 Neutral point  Xnp =   0.161031

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
