 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04579     Cltot =  -0.00220     Cl'tot =  -0.00191
  CYtot =  -0.01049     Cmtot =  -0.27639
  CZtot =  -1.04912     Cntot =   0.00411     Cn'tot =   0.00425

  CLtot =   1.04337
  CDtot =   0.11886
  CDvis =   0.07000     CDind = 0.0488577
  CLff  =   1.04755     CDff  = 0.0499020    | Trefftz
  CYff  =  -0.00766         e =    0.9800    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.796840    CLb =  -0.078192
 y  force CY |    CYa =   0.001071    CYb =  -0.300143
 x' mom.  Cl'|    Cla =  -0.008901    Clb =  -0.054638
 y  mom.  Cm |    Cma =  -1.962825    Cmb =   0.038996
 z' mom.  Cn'|    Cna =   0.002464    Cnb =   0.121554

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005307    CLq =  10.513240    CLr =   0.008228
 y  force CY |    CYp =   0.139615    CYq =   0.023676    CYr =   0.240233
 x' mom.  Cl'|    Clp =  -0.452285    Clq =  -0.015199    Clr =   0.264903
 y  mom.  Cm |    Cmp =   0.001987    Cmq = -19.286180    Cmr =  -0.022121
 z' mom.  Cn'|    Cnp =  -0.079531    Cnq =  -0.011933    Cnr =  -0.147744

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000049   CLd02 =   0.007987   CLd03 =  -0.000031
 y  force CY |   CYd01 =   0.000207   CYd02 =   0.000001   CYd03 =  -0.002848
 x' mom.  Cl'|   Cld01 =  -0.004427   Cld02 =  -0.000009   Cld03 =  -0.000244
 y  mom.  Cm |   Cmd01 =   0.000031   Cmd02 =  -0.030074   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =  -0.000024   Cnd02 =  -0.000001   Cnd03 =   0.001545
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000460 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000029    ed02 =   0.005917    ed03 =  -0.001332



 Neutral point  Xnp =   0.173392

 Clb Cnr / Clr Cnb  =   0.250698    (  > 1 if spirally stable )
