 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09344     Cltot =  -0.00128     Cl'tot =  -0.00128
  CYtot =  -0.01055     Cmtot =  -0.13872
  CZtot =  -0.70408     Cntot =   0.00412     Cn'tot =   0.00412

  CLtot =   0.70408
  CDtot =   0.09344
  CDvis =   0.07000     CDind = 0.0234375
  CLff  =   0.70465     CDff  = 0.0241182    | Trefftz
  CYff  =  -0.00766         e =    0.9175    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.913954    CLb =  -0.055223
 y  force CY |    CYa =   0.000507    CYb =  -0.301720
 x' mom.  Cl'|    Cla =  -0.009157    Clb =  -0.036581
 y  mom.  Cm |    Cma =  -1.974754    Cmb =   0.029381
 z' mom.  Cn'|    Cna =   0.001201    Cnb =   0.117889

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005866    CLq =  10.577359    CLr =   0.008585
 y  force CY |    CYp =   0.074575    CYq =   0.023676    CYr =   0.250032
 x' mom.  Cl'|    Clp =  -0.464824    Clq =  -0.014329    Clr =   0.199740
 y  mom.  Cm |    Cmp =   0.003525    Cmq = -19.249396    Cmr =  -0.021929
 z' mom.  Cn'|    Cnp =  -0.046246    Cnq =  -0.012964    Cnr =  -0.139252

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.008019   CLd03 =  -0.000033
 y  force CY |   CYd01 =   0.000276   CYd02 =   0.000001   CYd03 =  -0.002868
 x' mom.  Cl'|   Cld01 =  -0.004532   Cld02 =  -0.000009   Cld03 =  -0.000255
 y  mom.  Cm |   Cmd01 =   0.000031   Cmd02 =  -0.030052   Cmd03 =   0.000118
 z' mom.  Cn'|   Cnd01 =   0.000070   Cnd02 =  -0.000001   Cnd03 =   0.001555
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000068 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000057    ed02 =   0.018242    ed03 =  -0.002581



 Neutral point  Xnp =   0.171326

 Clb Cnr / Clr Cnb  =   0.216329    (  > 1 if spirally stable )
