 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12590     Cltot =   0.01115     Cl'tot =   0.00918
  CYtot =   0.02542     Cmtot =  -0.18044
  CZtot =  -1.61700     Cntot =  -0.00924     Cn'tot =  -0.01120

  CLtot =   1.61132
  CDtot =   0.18495
  CDvis =   0.07000     CDind = 0.1149489
  CLff  =   1.64050     CDff  = 0.1197653    | Trefftz
  CYff  =   0.01908         e =    1.0015    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.464158    CLb =   0.291880
 y  force CY |    CYa =  -0.005561    CYb =  -0.288848
 x' mom.  Cl'|    Cla =   0.020090    Clb =  -0.104146
 y  mom.  Cm |    Cma =  -1.113888    Cmb =  -0.061075
 z' mom.  Cn'|    Cna =  -0.013017    Cnb =   0.127039

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013330    CLq =   7.367284    CLr =  -0.018319
 y  force CY |    CYp =   0.203685    CYq =  -0.083492    CYr =   0.192272
 x' mom.  Cl'|    Clp =  -0.419896    Clq =   0.017520    Clr =   0.387191
 y  mom.  Cm |    Cmp =  -0.004626    Cmq = -16.583923    Cmr =   0.032890
 z' mom.  Cn'|    Cnp =  -0.110334    Cnq =   0.039619    Cnr =  -0.154849

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000113   CLd02 =   0.007610   CLd03 =   0.000067
 y  force CY |   CYd01 =   0.000127   CYd02 =  -0.000002   CYd03 =  -0.002715
 x' mom.  Cl'|   Cld01 =  -0.004094   Cld02 =   0.000022   Cld03 =  -0.000455
 y  mom.  Cm |   Cmd01 =  -0.000045   Cmd02 =  -0.027687   Cmd03 =  -0.000228
 z' mom.  Cn'|   Cnd01 =  -0.000192   Cnd02 =   0.000003   Cnd03 =   0.001381
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =   0.001048 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000041    ed02 =   0.000742    ed03 =   0.001407



 Neutral point  Xnp =   0.196864

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
