 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06517     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.44600
  CZtot =  -1.46258     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.45477
  CDtot =   0.16443
  CDvis =   0.07000     CDind = 0.0944291
  CLff  =   1.46970     CDff  = 0.0964717    | Trefftz
  CYff  =   0.00000         e =    0.9978    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.581536    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.297193
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.076392
 y  mom.  Cm |    Cma =  -1.896597    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.129923

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  10.414308    CLr =  -0.000000
 y  force CY |    CYp =   0.218095    CYq =   0.000000    CYr =   0.215560
 x' mom.  Cl'|    Clp =  -0.432088    Clq =  -0.000000    Clr =   0.342696
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -19.211753    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.122668    Cnq =   0.000000    Cnr =  -0.159134

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007820   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000122   CYd02 =   0.000000   CYd03 =  -0.002788
 x' mom.  Cl'|   Cld01 =  -0.004241   Cld02 =   0.000000   Cld03 =  -0.000227
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.029728   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000136   Cnd02 =  -0.000000   Cnd03 =   0.001513
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000940 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.001046    ed03 =   0.000000



 Neutral point  Xnp =   0.174738

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
