 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06203     Cltot =  -0.00203     Cl'tot =  -0.00041
  CYtot =   0.02622     Cmtot =   0.16586
  CZtot =   0.08700     Cntot =  -0.01016     Cn'tot =  -0.01036

  CLtot =  -0.07623
  CDtot =   0.07487
  CDvis =   0.07000     CDind = 0.0048728
  CLff  =  -0.07661     CDff  = 0.0062427    | Trefftz
  CYff  =   0.01914         e =    0.0445    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.939152    CLb =   0.005631
 y  force CY |    CYa =   0.001908    CYb =  -0.297957
 x' mom.  Cl'|    Cla =   0.022604    Clb =   0.004666
 y  mom.  Cm |    Cma =  -1.850029    Cmb =  -0.020315
 z' mom.  Cn'|    Cna =   0.004200    Cnb =   0.117467

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.018148    CLq =  10.615912    CLr =  -0.022681
 y  force CY |    CYp =  -0.072256    CYq =  -0.059127    CYr =   0.237869
 x' mom.  Cl'|    Clp =  -0.477380    Clq =   0.030279    Clr =   0.046306
 y  mom.  Cm |    Cmp =  -0.017262    Cmq = -18.764556    Cmr =   0.052712
 z' mom.  Cn'|    Cnp =   0.025539    Cnq =   0.037575    Cnr =  -0.123110

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000126   CLd02 =   0.007686   CLd03 =   0.000091
 y  force CY |   CYd01 =   0.000425   CYd02 =  -0.000002   CYd03 =  -0.002792
 x' mom.  Cl'|   Cld01 =  -0.004578   Cld02 =   0.000023   Cld03 =  -0.000268
 y  mom.  Cm |   Cmd01 =  -0.000080   Cmd02 =  -0.028758   Cmd03 =  -0.000290
 z' mom.  Cn'|   Cnd01 =   0.000289   Cnd02 =   0.000003   Cnd03 =   0.001512
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =  -0.000796 CDffd03 =  -0.000172
 span eff.   |    ed01 =   0.000018    ed02 =  -0.002916    ed03 =   0.000481



 Neutral point  Xnp =   0.163627

 Clb Cnr / Clr Cnb  =  -0.105614    (  > 1 if spirally stable )
