 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10365     Cltot =  -0.00017     Cl'tot =  -0.00032
  CYtot =  -0.00528     Cmtot =  -0.00182
  CZtot =  -0.35261     Cntot =   0.00206     Cn'tot =   0.00204

  CLtot =   0.35898
  CDtot =   0.07880
  CDvis =   0.07000     CDind = 0.0087970
  CLff  =   0.35848     CDff  = 0.0090101    | Trefftz
  CYff  =  -0.00383         e =    0.6357    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.979275    CLb =  -0.015904
 y  force CY |    CYa =  -0.000030    CYb =  -0.302625
 x' mom.  Cl'|    Cla =  -0.004620    Clb =  -0.018222
 y  mom.  Cm |    Cma =  -1.950029    Cmb =   0.009907
 z' mom.  Cn'|    Cna =  -0.000042    Cnb =   0.116986

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003235    CLq =  10.627090    CLr =   0.004431
 y  force CY |    CYp =   0.008808    CYq =   0.011840    CYr =   0.250798
 x' mom.  Cl'|    Clp =  -0.473816    Clq =  -0.006696    Clr =   0.132536
 y  mom.  Cm |    Cmp =   0.002524    Cmq = -19.127572    Cmr =  -0.010816
 z' mom.  Cn'|    Cnp =  -0.013869    Cnq =  -0.006967    Cnr =  -0.131642

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007960   CLd03 =  -0.000017
 y  force CY |   CYd01 =   0.000345   CYd02 =   0.000000   CYd03 =  -0.002862
 x' mom.  Cl'|   Cld01 =  -0.004598   Cld02 =  -0.000005   Cld03 =  -0.000263
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.029764   Cmd03 =   0.000059
 z' mom.  Cn'|   Cnd01 =   0.000168   Cnd02 =  -0.000001   Cnd03 =   0.001551
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000324 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000052    ed02 =   0.051118    ed03 =  -0.002357



 Neutral point  Xnp =   0.168439

 Clb Cnr / Clr Cnb  =   0.154708    (  > 1 if spirally stable )
