 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01433     Cltot =  -0.00576     Cl'tot =  -0.00473
  CYtot =  -0.02081     Cmtot =  -0.37595
  CZtot =  -1.29438     Cntot =   0.00814     Cn'tot =   0.00878

  CLtot =   1.28647
  CDtot =   0.14352
  CDvis =   0.07000     CDind = 0.0735208
  CLff  =   1.29908     CDff  = 0.0759948    | Trefftz
  CYff  =  -0.01532         e =    0.9898    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.657368    CLb =  -0.189449
 y  force CY |    CYa =   0.002975    CYb =  -0.296427
 x' mom.  Cl'|    Cla =  -0.017147    Clb =  -0.067255
 y  mom.  Cm |    Cma =  -1.921721    Cmb =   0.092012
 z' mom.  Cn'|    Cna =   0.006746    Cnb =   0.125014

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.009841    CLq =  10.434152    CLr =   0.015813
 y  force CY |    CYp =   0.186811    CYq =   0.047323    CYr =   0.226575
 x' mom.  Cl'|    Clp =  -0.439799    Clq =  -0.031585    Clr =   0.311459
 y  mom.  Cm |    Cmp =   0.001652    Cmq = -19.216907    Cmr =  -0.044363
 z' mom.  Cn'|    Cnp =  -0.104974    Cnq =  -0.022229    Cnr =  -0.154185

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000095   CLd02 =   0.007870   CLd03 =  -0.000059
 y  force CY |   CYd01 =   0.000155   CYd02 =   0.000001   CYd03 =  -0.002805
 x' mom.  Cl'|   Cld01 =  -0.004304   Cld02 =  -0.000018   Cld03 =  -0.000233
 y  mom.  Cm |   Cmd01 =   0.000060   Cmd02 =  -0.029790   Cmd03 =   0.000234
 z' mom.  Cn'|   Cnd01 =  -0.000092   Cnd02 =  -0.000002   Cnd03 =   0.001522
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000747 CDffd03 =   0.000138
 span eff.   |    ed01 =   0.000038    ed02 =   0.002377    ed03 =  -0.001754



 Neutral point  Xnp =   0.174359

 Clb Cnr / Clr Cnb  =   0.266323    (  > 1 if spirally stable )
