 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10253     Cltot =   0.00379     Cl'tot =   0.00412
  CYtot =   0.02617     Cmtot =   0.04700
  CZtot =  -0.52976     Cntot =  -0.00950     Cn'tot =  -0.00936

  CLtot =   0.53301
  CDtot =   0.08398
  CDvis =   0.07000     CDind = 0.0139754
  CLff  =   0.53524     CDff  = 0.0159939    | Trefftz
  CYff  =   0.01908         e =    0.7992    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.948875    CLb =   0.109203
 y  force CY |    CYa =  -0.001073    CYb =  -0.297421
 x' mom.  Cl'|    Cla =   0.023763    Clb =  -0.046727
 y  mom.  Cm |    Cma =  -0.856403    Cmb =  -0.021278
 z' mom.  Cn'|    Cna =  -0.002892    Cnb =   0.106209

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.018602    CLq =   7.998839    CLr =  -0.020636
 y  force CY |    CYp =  -0.001137    CYq =  -0.083492    CYr =   0.233078
 x' mom.  Cl'|    Clp =  -0.477689    Clq =   0.008159    Clr =   0.184435
 y  mom.  Cm |    Cmp =  -0.011906    Cmq = -16.351696    Cmr =   0.031007
 z' mom.  Cn'|    Cnp =  -0.008187    Cnq =   0.042544    Cnr =  -0.117232

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000123   CLd02 =   0.007886   CLd03 =   0.000085
 y  force CY |   CYd01 =   0.000351   CYd02 =  -0.000002   CYd03 =  -0.002843
 x' mom.  Cl'|   Cld01 =  -0.004512   Cld02 =   0.000023   Cld03 =  -0.000506
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.027827   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =   0.000108   Cnd02 =   0.000003   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000152 CDffd03 =  -0.000176
 span eff.   |    ed01 =  -0.000260    ed02 =   0.031168    ed03 =   0.008501



 Neutral point  Xnp =   0.175300

 Clb Cnr / Clr Cnb  =   0.279649    (  > 1 if spirally stable )
