 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08515     Cltot =  -0.00087     Cl'tot =   0.00038
  CYtot =   0.02628     Cmtot =   0.10054
  CZtot =  -0.08671     Cntot =  -0.01021     Cn'tot =  -0.01024

  CLtot =   0.09644
  CDtot =   0.07395
  CDvis =   0.07000     CDind = 0.0039461
  CLff  =   0.09701     CDff  = 0.0054760    | Trefftz
  CYff  =   0.01914         e =    0.0796    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.951807    CLb =   0.035034
 y  force CY |    CYa =   0.001205    CYb =  -0.298573
 x' mom.  Cl'|    Cla =   0.022842    Clb =  -0.004334
 y  mom.  Cm |    Cma =  -1.891270    Cmb =  -0.031745
 z' mom.  Cn'|    Cna =   0.002613    Cnb =   0.116118

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.017340    CLq =  10.608685    CLr =  -0.022501
 y  force CY |    CYp =  -0.040105    CYq =  -0.059127    CYr =   0.244371
 x' mom.  Cl'|    Clp =  -0.476033    Clq =   0.031572    Clr =   0.080786
 y  mom.  Cm |    Cmp =  -0.015412    Cmq = -18.899096    Cmr =   0.053282
 z' mom.  Cn'|    Cnp =   0.009905    Cnq =   0.036495    Cnr =  -0.126110

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000126   CLd02 =   0.007790   CLd03 =   0.000090
 y  force CY |   CYd01 =   0.000392   CYd02 =  -0.000002   CYd03 =  -0.002817
 x' mom.  Cl'|   Cld01 =  -0.004581   Cld02 =   0.000023   Cld03 =  -0.000266
 y  mom.  Cm |   Cmd01 =  -0.000080   Cmd02 =  -0.029126   Cmd03 =  -0.000292
 z' mom.  Cn'|   Cnd01 =   0.000240   Cnd02 =   0.000003   Cnd03 =   0.001526
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =  -0.000608 CDffd03 =  -0.000173
 span eff.   |    ed01 =  -0.000007    ed02 =   0.021311    ed03 =   0.001657



 Neutral point  Xnp =   0.165706

 Clb Cnr / Clr Cnb  =   0.058262    (  > 1 if spirally stable )
