 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01410     Cltot =  -0.00289     Cl'tot =  -0.00237
  CYtot =  -0.01042     Cmtot =  -0.37837
  CZtot =  -1.29941     Cntot =   0.00408     Cn'tot =   0.00440

  CLtot =   1.29144
  CDtot =   0.14436
  CDvis =   0.07000     CDind = 0.0743609
  CLff  =   1.30146     CDff  = 0.0759920    | Trefftz
  CYff  =  -0.00766         e =    0.9933    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.673871    CLb =  -0.094956
 y  force CY |    CYa =   0.001491    CYb =  -0.298224
 x' mom.  Cl'|    Cla =  -0.008594    Clb =  -0.067750
 y  mom.  Cm |    Cma =  -1.928765    Cmb =   0.046118
 z' mom.  Cn'|    Cna =   0.003381    Cnb =   0.125935

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004924    CLq =  10.453259    CLr =   0.007912
 y  force CY |    CYp =   0.187153    CYq =   0.023676    CYr =   0.226990
 x' mom.  Cl'|    Clp =  -0.440605    Clq =  -0.015802    Clr =   0.312030
 y  mom.  Cm |    Cmp =   0.000826    Cmq = -19.252098    Cmr =  -0.022195
 z' mom.  Cn'|    Cnp =  -0.105166    Cnq =  -0.011121    Cnr =  -0.154468

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000048   CLd02 =   0.007899   CLd03 =  -0.000030
 y  force CY |   CYd01 =   0.000155   CYd02 =   0.000001   CYd03 =  -0.002815
 x' mom.  Cl'|   Cld01 =  -0.004320   Cld02 =  -0.000009   Cld03 =  -0.000234
 y  mom.  Cm |   Cmd01 =   0.000030   Cmd02 =  -0.029899   Cmd03 =   0.000117
 z' mom.  Cn'|   Cnd01 =  -0.000093   Cnd02 =  -0.000001   Cnd03 =   0.001528
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000749 CDffd03 =   0.000069
 span eff.   |    ed01 =   0.000019    ed02 =   0.002351    ed03 =  -0.000882



 Neutral point  Xnp =   0.174373

 Clb Cnr / Clr Cnb  =   0.266323    (  > 1 if spirally stable )
