 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04780     Cltot =   0.00105     Cl'tot =   0.00032
  CYtot =  -0.01051     Cmtot =   0.19740
  CZtot =   0.17361     Cntot =   0.00407     Cn'tot =   0.00419

  CLtot =  -0.16267
  CDtot =   0.07722
  CDvis =   0.07000     CDind = 0.0072219
  CLff  =  -0.16393     CDff  = 0.0072174    | Trefftz
  CYff  =  -0.00766         e =    0.1663    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.958352    CLb =   0.003631
 y  force CY |    CYa =  -0.000907    CYb =  -0.300719
 x' mom.  Cl'|    Cla =  -0.009016    Clb =   0.009244
 y  mom.  Cm |    Cma =  -1.837750    Cmb =   0.005906
 z' mom.  Cn'|    Cna =  -0.002003    Cnb =   0.119910

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007430    CLq =  10.651659    CLr =   0.009110
 y  force CY |    CYp =  -0.088425    CYq =   0.023676    CYr =   0.234531
 x' mom.  Cl'|    Clp =  -0.479195    Clq =  -0.011860    Clr =   0.029102
 y  mom.  Cm |    Cmp =   0.007280    Cmq = -18.748662    Cmr =  -0.020983
 z' mom.  Cn'|    Cnp =   0.033418    Cnq =  -0.015255    Cnr =  -0.122117

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000051   CLd02 =   0.007675   CLd03 =  -0.000037
 y  force CY |   CYd01 =   0.000444   CYd02 =   0.000001   CYd03 =  -0.002795
 x' mom.  Cl'|   Cld01 =  -0.004601   Cld02 =  -0.000009   Cld03 =  -0.000271
 y  mom.  Cm |   Cmd01 =   0.000032   Cmd02 =  -0.028732   Cmd03 =   0.000116
 z' mom.  Cn'|   Cnd01 =   0.000315   Cnd02 =  -0.000001   Cnd03 =   0.001514
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000894 CDffd03 =   0.000069
 span eff.   |    ed01 =   0.000022    ed02 =   0.004690    ed03 =  -0.001328



 Neutral point  Xnp =   0.162520

 Clb Cnr / Clr Cnb  =  -0.323490    (  > 1 if spirally stable )
