 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03943     Cltot =   0.00949     Cl'tot =   0.00810
  CYtot =   0.02568     Cmtot =  -0.12313
  CZtot =  -1.38123     Cntot =  -0.00935     Cn'tot =  -0.01057

  CLtot =   1.37328
  CDtot =   0.15318
  CDvis =   0.07000     CDind = 0.0831791
  CLff  =   1.39089     CDff  = 0.0865902    | Trefftz
  CYff  =   0.01908         e =    0.9958    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.623848    CLb =   0.251670
 y  force CY |    CYa =  -0.004543    CYb =  -0.291849
 x' mom.  Cl'|    Cla =   0.021341    Clb =  -0.091831
 y  mom.  Cm |    Cma =  -1.073270    Cmb =  -0.051047
 z' mom.  Cn'|    Cna =  -0.010846    Cnb =   0.119947

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014444    CLq =   7.533857    CLr =  -0.019063
 y  force CY |    CYp =   0.158404    CYq =  -0.083492    CYr =   0.209896
 x' mom.  Cl'|    Clp =  -0.436338    Clq =   0.015423    Clr =   0.343623
 y  mom.  Cm |    Cmp =  -0.006341    Cmq = -16.606056    Cmr =   0.032603
 z' mom.  Cn'|    Cnp =  -0.085249    Cnq =   0.040481    Cnr =  -0.145740

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000116   CLd02 =   0.007761   CLd03 =   0.000072
 y  force CY |   CYd01 =   0.000178   CYd02 =  -0.000002   CYd03 =  -0.002770
 x' mom.  Cl'|   Cld01 =  -0.004228   Cld02 =   0.000022   Cld03 =  -0.000471
 y  mom.  Cm |   Cmd01 =  -0.000046   Cmd02 =  -0.027975   Cmd03 =  -0.000230
 z' mom.  Cn'|   Cnd01 =  -0.000128   Cnd02 =   0.000003   Cnd03 =   0.001408
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =   0.000780 CDffd03 =  -0.000174
 span eff.   |    ed01 =  -0.000058    ed02 =   0.002263    ed03 =   0.001952



 Neutral point  Xnp =   0.191957

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
