 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00729     Cltot =  -0.00837     Cl'tot =  -0.00734
  CYtot =  -0.02583     Cmtot =  -0.08624
  CZtot =  -1.21768     Cntot =   0.00940     Cn'tot =   0.01022

  CLtot =   1.21024
  CDtot =   0.13453
  CDvis =   0.07000     CDind = 0.0645326
  CLff  =   1.22233     CDff  = 0.0674064    | Trefftz
  CYff  =  -0.01908         e =    0.9880    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.715297    CLb =  -0.224087
 y  force CY |    CYa =   0.003856    CYb =  -0.293511
 x' mom.  Cl'|    Cla =  -0.022046    Clb =  -0.083239
 y  mom.  Cm |    Cma =  -1.039625    Cmb =   0.044591
 z' mom.  Cn'|    Cna =   0.009330    Cnb =   0.115951

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015228    CLq =   7.638786    CLr =   0.019492
 y  force CY |    CYp =   0.127300    CYq =   0.083492    CYr =   0.218973
 x' mom.  Cl'|    Clp =  -0.446369    Clq =  -0.014000    Clr =   0.313392
 y  mom.  Cm |    Cmp =   0.007475    Cmq = -16.595523    Cmr =  -0.032362
 z' mom.  Cn'|    Cnp =  -0.069047    Cnq =  -0.040995    Cnr =  -0.139713

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000118   CLd02 =   0.007834   CLd03 =  -0.000075
 y  force CY |   CYd01 =   0.000212   CYd02 =   0.000002   CYd03 =  -0.002798
 x' mom.  Cl'|   Cld01 =  -0.004306   Cld02 =  -0.000022   Cld03 =  -0.000480
 y  mom.  Cm |   Cmd01 =   0.000046   Cmd02 =  -0.028083   Cmd03 =   0.000231
 z' mom.  Cn'|   Cnd01 =  -0.000083   Cnd02 =  -0.000003   Cnd03 =   0.001422
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =   0.000597 CDffd03 =   0.000175
 span eff.   |    ed01 =   0.000074    ed02 =   0.003980    ed03 =  -0.002498



 Neutral point  Xnp =   0.188675

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
