 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07331     Cltot =   0.00434     Cl'tot =   0.00398
  CYtot =   0.02622     Cmtot =  -0.20453
  CZtot =  -0.87173     Cntot =  -0.01025     Cn'tot =  -0.01039

  CLtot =   0.86864
  CDtot =   0.10369
  CDvis =   0.07000     CDind = 0.0336892
  CLff  =   0.87383     CDff  = 0.0359566    | Trefftz
  CYff  =   0.01914         e =    0.9468    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.832176    CLb =   0.166245
 y  force CY |    CYa =  -0.001966    CYb =  -0.297893
 x' mom.  Cl'|    Cla =   0.022531    Clb =  -0.045089
 y  mom.  Cm |    Cma =  -1.960994    Cmb =  -0.085125
 z' mom.  Cn'|    Cna =  -0.004573    Cnb =   0.117879

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013936    CLq =  10.513903    CLr =  -0.021018
 y  force CY |    CYp =   0.106923    CYq =  -0.059127    CYr =   0.245481
 x' mom.  Cl'|    Clp =  -0.457538    Clq =   0.036893    Clr =   0.231880
 y  mom.  Cm |    Cmp =  -0.006887    Cmq = -19.217875    Cmr =   0.055037
 z' mom.  Cn'|    Cnp =  -0.062566    Cnq =   0.031107    Cnr =  -0.142954

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000123   CLd02 =   0.007964   CLd03 =   0.000080
 y  force CY |   CYd01 =   0.000240   CYd02 =  -0.000002   CYd03 =  -0.002843
 x' mom.  Cl'|   Cld01 =  -0.004456   Cld02 =   0.000023   Cld03 =  -0.000248
 y  mom.  Cm |   Cmd01 =  -0.000077   Cmd02 =  -0.029907   Cmd03 =  -0.000294
 z' mom.  Cn'|   Cnd01 =   0.000022   Cnd02 =   0.000003   Cnd03 =   0.001542
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000263 CDffd03 =  -0.000174
 span eff.   |    ed01 =  -0.000098    ed02 =   0.010354    ed03 =   0.004449



 Neutral point  Xnp =   0.172441

 Clb Cnr / Clr Cnb  =   0.235816    (  > 1 if spirally stable )
