 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15800     Cltot =  -0.00201     Cl'tot =  -0.00155
  CYtot =  -0.00513     Cmtot =  -0.54334
  CZtot =  -1.69398     Cntot =   0.00201     Cn'tot =   0.00238

  CLtot =   1.68982
  CDtot =   0.19765
  CDvis =   0.07000     CDind = 0.1276505
  CLff  =   1.71717     CDff  = 0.1315256    | Trefftz
  CYff  =  -0.00383         e =    0.9991    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.411496    CLb =  -0.060888
 y  force CY |    CYa =   0.001091    CYb =  -0.294080
 x' mom.  Cl'|    Cla =  -0.003941    Clb =  -0.088520
 y  mom.  Cm |    Cma =  -1.826998    Cmb =   0.028811
 z' mom.  Cn'|    Cna =   0.002412    Cnb =   0.136447

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002183    CLq =  10.337335    CLr =   0.003651
 y  force CY |    CYp =   0.262598    CYq =   0.011840    CYr =   0.194220
 x' mom.  Cl'|    Clp =  -0.417489    Clq =  -0.008357    Clr =   0.386757
 y  mom.  Cm |    Cmp =  -0.000556    Cmq = -19.086865    Cmr =  -0.011093
 z' mom.  Cn'|    Cnp =  -0.149314    Cnq =  -0.004852    Cnr =  -0.165974

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000023   CLd02 =   0.007642   CLd03 =  -0.000013
 y  force CY |   CYd01 =   0.000073   CYd02 =   0.000000   CYd03 =  -0.002730
 x' mom.  Cl'|   Cld01 =  -0.004096   Cld02 =  -0.000005   Cld03 =  -0.000216
 y  mom.  Cm |   Cmd01 =   0.000014   Cmd02 =  -0.029274   Cmd03 =   0.000058
 z' mom.  Cn'|   Cnd01 =  -0.000199   Cnd02 =  -0.000001   Cnd03 =   0.001482
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.001215 CDffd03 =   0.000034
 span eff.   |    ed01 =   0.000005    ed02 =  -0.000087    ed03 =  -0.000253



 Neutral point  Xnp =   0.174789

 Clb Cnr / Clr Cnb  =   0.278406    (  > 1 if spirally stable )
