 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06098     Cltot =  -0.00296     Cl'tot =  -0.00263
  CYtot =  -0.01575     Cmtot =  -0.24127
  CZtot =  -0.96227     Cntot =   0.00616     Cn'tot =   0.00631

  CLtot =   0.95776
  CDtot =   0.11126
  CDvis =   0.07000     CDind = 0.0412551
  CLff  =   0.96150     CDff  = 0.0425255    | Trefftz
  CYff  =  -0.01149         e =    0.9689    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.824123    CLb =  -0.108652
 y  force CY |    CYa =   0.001395    CYb =  -0.299886
 x' mom.  Cl'|    Cla =  -0.013458    Clb =  -0.050022
 y  mom.  Cm |    Cma =  -1.966411    Cmb =   0.054843
 z' mom.  Cn'|    Cna =   0.003225    Cnb =   0.120035

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008161    CLq =  10.522990    CLr =   0.012484
 y  force CY |    CYp =   0.123399    CYq =   0.035505    CYr =   0.243348
 x' mom.  Cl'|    Clp =  -0.455408    Clq =  -0.022476    Clr =   0.248654
 y  mom.  Cm |    Cmp =   0.003558    Cmq = -19.271102    Cmr =  -0.033116
 z' mom.  Cn'|    Cnp =  -0.071063    Cnq =  -0.018290    Cnr =  -0.145449

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000074   CLd02 =   0.007992   CLd03 =  -0.000048
 y  force CY |   CYd01 =   0.000223   CYd02 =   0.000001   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004450   Cld02 =  -0.000014   Cld03 =  -0.000246
 y  mom.  Cm |   Cmd01 =   0.000046   Cmd02 =  -0.030050   Cmd03 =   0.000177
 z' mom.  Cn'|   Cnd01 =  -0.000001   Cnd02 =  -0.000002   Cnd03 =   0.001546
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000362 CDffd03 =   0.000105
 span eff.   |    ed01 =   0.000051    ed02 =   0.007858    ed03 =  -0.002317



 Neutral point  Xnp =   0.172949

 Clb Cnr / Clr Cnb  =   0.243762    (  > 1 if spirally stable )
