 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12474     Cltot =   0.00756     Cl'tot =   0.00589
  CYtot =   0.02056     Cmtot =  -0.50761
  CZtot =  -1.61047     Cntot =  -0.00804     Cn'tot =  -0.00934

  CLtot =   1.60469
  CDtot =   0.18485
  CDvis =   0.07000     CDind = 0.1148457
  CLff  =   1.63136     CDff  = 0.1190834    | Trefftz
  CYff  =   0.01532         e =    0.9960    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.450865    CLb =   0.232410
 y  force CY |    CYa =  -0.004078    CYb =  -0.292922
 x' mom.  Cl'|    Cla =   0.016041    Clb =  -0.083768
 y  mom.  Cm |    Cma =  -1.843820    Cmb =  -0.110424
 z' mom.  Cn'|    Cna =  -0.009066    Cnb =   0.132881

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008930    CLq =  10.339743    CLr =  -0.014852
 y  force CY |    CYp =   0.247437    CYq =  -0.047323    CYr =   0.201379
 x' mom.  Cl'|    Clp =  -0.421540    Clq =   0.033059    Clr =   0.371424
 y  mom.  Cm |    Cmp =   0.001447    Cmq = -19.089651    Cmr =   0.044370
 z' mom.  Cn'|    Cnp =  -0.140037    Cnq =   0.019971    Cnr =  -0.163319

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000092   CLd02 =   0.007671   CLd03 =   0.000054
 y  force CY |   CYd01 =   0.000089   CYd02 =  -0.000001   CYd03 =  -0.002738
 x' mom.  Cl'|   Cld01 =  -0.004127   Cld02 =   0.000018   Cld03 =  -0.000219
 y  mom.  Cm |   Cmd01 =  -0.000058   Cmd02 =  -0.029305   Cmd03 =  -0.000231
 z' mom.  Cn'|   Cnd01 =  -0.000178   Cnd02 =   0.000002   Cnd03 =   0.001486
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.001119 CDffd03 =  -0.000137
 span eff.   |    ed01 =  -0.000023    ed02 =   0.000241    ed03 =   0.001114



 Neutral point  Xnp =   0.174822

 Clb Cnr / Clr Cnb  =   0.277193    (  > 1 if spirally stable )
