 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06110     Cltot =  -0.00401     Cl'tot =  -0.00371
  CYtot =  -0.01564     Cmtot =  -0.03431
  CZtot =  -0.96987     Cntot =   0.00569     Cn'tot =   0.00590

  CLtot =   0.96534
  CDtot =   0.11177
  CDvis =   0.07000     CDind = 0.0417737
  CLff  =   0.96911     CDff  = 0.0430908    | Trefftz
  CYff  =  -0.01146         e =    0.9714    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.851306    CLb =  -0.109396
 y  force CY |    CYa =   0.001697    CYb =  -0.297891
 x' mom.  Cl'|    Cla =  -0.013785    Clb =  -0.070569
 y  mom.  Cm |    Cma =  -0.984515    Cmb =   0.021269
 z' mom.  Cn'|    Cna =   0.004199    Cnb =   0.112200

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.009881    CLq =   7.804749    CLr =   0.012029
 y  force CY |    CYp =   0.079842    CYq =   0.050136    CYr =   0.229025
 x' mom.  Cl'|    Clp =  -0.460980    Clq =  -0.007107    Clr =   0.267076
 y  mom.  Cm |    Cmp =   0.005500    Cmq = -16.582253    Cmr =  -0.019171
 z' mom.  Cn'|    Cnp =  -0.045620    Cnq =  -0.025023    Cnr =  -0.131212

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000073   CLd02 =   0.007937   CLd03 =  -0.000048
 y  force CY |   CYd01 =   0.000265   CYd02 =   0.000001   CYd03 =  -0.002842
 x' mom.  Cl'|   Cld01 =  -0.004425   Cld02 =  -0.000014   Cld03 =  -0.000495
 y  mom.  Cm |   Cmd01 =   0.000028   Cmd02 =  -0.028253   Cmd03 =   0.000140
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =  -0.000002   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000319 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000070    ed02 =   0.008681    ed03 =  -0.002321



 Neutral point  Xnp =   0.183729

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
