 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06131     Cltot =   0.00268     Cl'tot =   0.00247
  CYtot =   0.01044     Cmtot =  -0.03462
  CZtot =  -0.97148     Cntot =  -0.00380     Cn'tot =  -0.00393

  CLtot =   0.96694
  CDtot =   0.11207
  CDvis =   0.07000     CDind = 0.0420654
  CLff  =   0.96985     CDff  = 0.0430367    | Trefftz
  CYff  =   0.00764         e =    0.9740    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.858478    CLb =   0.073005
 y  force CY |    CYa =  -0.001132    CYb =  -0.298642
 x' mom.  Cl'|    Cla =   0.009199    Clb =  -0.070785
 y  mom.  Cm |    Cma =  -0.986017    Cmb =  -0.014193
 z' mom.  Cn'|    Cna =  -0.002802    Cnb =   0.112544

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006589    CLq =   7.810699    CLr =  -0.008021
 y  force CY |    CYp =   0.079903    CYq =  -0.033432    CYr =   0.229199
 x' mom.  Cl'|    Clp =  -0.461331    Clq =   0.004739    Clr =   0.267279
 y  mom.  Cm |    Cmp =  -0.003667    Cmq = -16.594894    Cmr =   0.012784
 z' mom.  Cn'|    Cnp =  -0.045655    Cnq =   0.016686    Cnr =  -0.131312

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000048   CLd02 =   0.007949   CLd03 =   0.000032
 y  force CY |   CYd01 =   0.000266   CYd02 =  -0.000001   CYd03 =  -0.002846
 x' mom.  Cl'|   Cld01 =  -0.004431   Cld02 =   0.000009   Cld03 =  -0.000495
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028296   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =   0.000001   Cnd03 =   0.001446
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000320 CDffd03 =  -0.000071
 span eff.   |    ed01 =  -0.000047    ed02 =   0.008685    ed03 =   0.001555



 Neutral point  Xnp =   0.183731

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
