 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03916     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.12536
  CZtot =  -1.39239     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.38429
  CDtot =   0.15501
  CDvis =   0.07000     CDind = 0.0850081
  CLff  =   1.39621     CDff  = 0.0866519    | Trefftz
  CYff  =   0.00000         e =    1.0025    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.658048    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.295541
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.093248
 y  mom.  Cm |    Cma =  -1.081485    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.121797

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.562635    CLr =   0.000000
 y  force CY |    CYp =   0.159009    CYq =   0.000000    CYr =   0.210698
 x' mom.  Cl'|    Clp =  -0.438005    Clq =  -0.000000    Clr =   0.344935
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.669488    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.085575    Cnq =  -0.000000    Cnr =  -0.146297

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007821   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000179   CYd02 =   0.000000   CYd03 =  -0.002791
 x' mom.  Cl'|   Cld01 =  -0.004260   Cld02 =   0.000000   Cld03 =  -0.000474
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028189   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =  -0.000000   Cnd03 =   0.001419
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000786 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.002218    ed03 =   0.000000



 Neutral point  Xnp =   0.191974

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
