 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06519     Cltot =   0.00334     Cl'tot =   0.00266
  CYtot =   0.01037     Cmtot =  -0.44512
  CZtot =  -1.46071     Cntot =  -0.00406     Cn'tot =  -0.00453

  CLtot =   1.45292
  CDtot =   0.16412
  CDvis =   0.07000     CDind = 0.0941217
  CLff  =   1.46880     CDff  = 0.0964477    | Trefftz
  CYff  =   0.00766         e =    0.9968    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.576149    CLb =   0.105851
 y  force CY |    CYa =  -0.001769    CYb =  -0.296597
 x' mom.  Cl'|    Cla =   0.008338    Clb =  -0.076206
 y  mom.  Cm |    Cma =  -1.894287    Cmb =  -0.050780
 z' mom.  Cn'|    Cna =  -0.003972    Cnb =   0.129607

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.004687    CLq =  10.407964    CLr =  -0.007679
 y  force CY |    CYp =   0.217962    CYq =  -0.023676    CYr =   0.215429
 x' mom.  Cl'|    Clp =  -0.431825    Clq =   0.016181    Clr =   0.342487
 y  mom.  Cm |    Cmp =  -0.000051    Cmq = -19.200050    Cmr =   0.022210
 z' mom.  Cn'|    Cnp =  -0.122593    Cnq =   0.010563    Cnr =  -0.159037

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000047   CLd02 =   0.007810   CLd03 =   0.000028
 y  force CY |   CYd01 =   0.000122   CYd02 =  -0.000001   CYd03 =  -0.002785
 x' mom.  Cl'|   Cld01 =  -0.004236   Cld02 =   0.000009   Cld03 =  -0.000227
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.029692   Cmd03 =  -0.000117
 z' mom.  Cn'|   Cnd01 =  -0.000136   Cnd02 =   0.000001   Cnd03 =   0.001511
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000938 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000015    ed02 =   0.001054    ed03 =   0.000694



 Neutral point  Xnp =   0.174733

 Clb Cnr / Clr Cnb  =   0.273033    (  > 1 if spirally stable )
