 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06305     Cltot =   0.00041     Cl'tot =   0.00008
  CYtot =  -0.00527     Cmtot =   0.16501
  CZtot =   0.08692     Cntot =   0.00204     Cn'tot =   0.00208

  CLtot =  -0.07599
  CDtot =   0.07587
  CDvis =   0.07000     CDind = 0.0058698
  CLff  =  -0.07689     CDff  = 0.0057246    | Trefftz
  CYff  =  -0.00383         e =    0.0461    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.974481    CLb =  -0.001132
 y  force CY |    CYa =  -0.000383    CYb =  -0.301592
 x' mom.  Cl'|    Cla =  -0.004543    Clb =   0.004735
 y  mom.  Cm |    Cma =  -1.863622    Cmb =   0.004083
 z' mom.  Cn'|    Cna =  -0.000844    Cnb =   0.119207

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003634    CLq =  10.654840    CLr =   0.004542
 y  force CY |    CYp =  -0.072521    CYq =   0.011840    CYr =   0.238741
 x' mom.  Cl'|    Clp =  -0.479131    Clq =  -0.006063    Clr =   0.046476
 y  mom.  Cm |    Cmp =   0.003457    Cmq = -18.833365    Cmr =  -0.010555
 z' mom.  Cn'|    Cnp =   0.025632    Cnq =  -0.007524    Cnr =  -0.123561

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007742   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000428   CYd02 =   0.000000   CYd03 =  -0.002813
 x' mom.  Cl'|   Cld01 =  -0.004611   Cld02 =  -0.000005   Cld03 =  -0.000270
 y  mom.  Cm |   Cmd01 =   0.000016   Cmd02 =  -0.028969   Cmd03 =   0.000058
 z' mom.  Cn'|   Cnd01 =   0.000291   Cnd02 =  -0.000001   Cnd03 =   0.001524
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000802 CDffd03 =   0.000035
 span eff.   |    ed01 =  -0.000004    ed02 =  -0.002975    ed03 =  -0.000115



 Neutral point  Xnp =   0.163647

 Clb Cnr / Clr Cnb  =  -0.105614    (  > 1 if spirally stable )
