 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.58000E-01   Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12491     Cltot =   0.00379     Cl'tot =   0.00295
  CYtot =   0.01030     Cmtot =  -0.51050
  CZtot =  -1.61665     Cntot =  -0.00403     Cn'tot =  -0.00468

  CLtot =   1.61078
  CDtot =   0.18585
  CDvis =   0.07000     CDind = 0.1158533
  CLff  =   1.63435     CDff  = 0.1192386    | Trefftz
  CYff  =   0.00766         e =    0.9983    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.466595    CLb =   0.116489
 y  force CY |    CYa =  -0.002044    CYb =  -0.294693
 x' mom.  Cl'|    Cla =   0.008040    Clb =  -0.084385
 y  mom.  Cm |    Cma =  -1.850579    Cmb =  -0.055347
 z' mom.  Cn'|    Cna =  -0.004544    Cnb =   0.133860

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.004468    CLq =  10.358678    CLr =  -0.007430
 y  force CY |    CYp =   0.247890    CYq =  -0.023676    CYr =   0.201747
 x' mom.  Cl'|    Clp =  -0.422312    Clq =   0.016540    Clr =   0.372104
 y  mom.  Cm |    Cmp =   0.000724    Cmq = -19.124609    Cmr =   0.022198
 z' mom.  Cn'|    Cnp =  -0.140294    Cnq =   0.009992    Cnr =  -0.163618

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000046   CLd02 =   0.007699   CLd03 =   0.000027
 y  force CY |   CYd01 =   0.000089   CYd02 =  -0.000001   CYd03 =  -0.002748
 x' mom.  Cl'|   Cld01 =  -0.004142   Cld02 =   0.000009   Cld03 =  -0.000219
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.029413   Cmd03 =  -0.000116
 z' mom.  Cn'|   Cnd01 =  -0.000178   Cnd02 =   0.000001   Cnd03 =   0.001492
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.001123 CDffd03 =  -0.000069
 span eff.   |    ed01 =  -0.000012    ed02 =   0.000220    ed03 =   0.000559



 Neutral point  Xnp =   0.174837

 Clb Cnr / Clr Cnb  =   0.277193    (  > 1 if spirally stable )
