 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12627     Cltot =   0.00224     Cl'tot =   0.00185
  CYtot =   0.00510     Cmtot =  -0.18301
  CZtot =  -1.62942     Cntot =  -0.00186     Cn'tot =  -0.00225

  CLtot =   1.62357
  CDtot =   0.18696
  CDvis =   0.07000     CDind = 0.1169614
  CLff  =   1.64652     CDff  = 0.1200683    | Trefftz
  CYff  =   0.00382         e =    1.0062    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.495790    CLb =   0.058661
 y  force CY |    CYa =  -0.001118    CYb =  -0.292348
 x' mom.  Cl'|    Cla =   0.004038    Clb =  -0.105688
 y  mom.  Cm |    Cma =  -1.122072    Cmb =  -0.012275
 z' mom.  Cn'|    Cna =  -0.002616    Cnb =   0.128920

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002669    CLq =   7.394299    CLr =  -0.003668
 y  force CY |    CYp =   0.204432    CYq =  -0.016719    CYr =   0.192977
 x' mom.  Cl'|    Clp =  -0.421435    Clq =   0.003508    Clr =   0.388610
 y  mom.  Cm |    Cmp =  -0.000926    Cmq = -16.644736    Cmr =   0.006586
 z' mom.  Cn'|    Cnp =  -0.110738    Cnq =   0.007933    Cnr =  -0.155417

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000023   CLd02 =   0.007666   CLd03 =   0.000014
 y  force CY |   CYd01 =   0.000128   CYd02 =  -0.000000   CYd03 =  -0.002735
 x' mom.  Cl'|   Cld01 =  -0.004124   Cld02 =   0.000004   Cld03 =  -0.000458
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.027890   Cmd03 =  -0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000194   Cnd02 =   0.000001   Cnd03 =   0.001391
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.001056 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000008    ed02 =   0.000704    ed03 =   0.000283



 Neutral point  Xnp =   0.196882

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
