 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08660     Cltot =  -0.00036     Cl'tot =  -0.00082
  CYtot =  -0.01051     Cmtot =   0.11505
  CZtot =  -0.09053     Cntot =   0.00380     Cn'tot =   0.00373

  CLtot =   0.10040
  CDtot =   0.07492
  CDvis =   0.07000     CDind = 0.0049223
  CLff  =   0.09999     CDff  = 0.0051415    | Trefftz
  CYff  =  -0.00764         e =    0.0872    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.011724    CLb =  -0.014215
 y  force CY |    CYa =  -0.000273    CYb =  -0.300791
 x' mom.  Cl'|    Cla =  -0.009603    Clb =  -0.023374
 y  mom.  Cm |    Cma =  -0.711608    Cmb =   0.003740
 z' mom.  Cn'|    Cna =  -0.000513    Cnb =   0.106773

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008338    CLq =   8.192940    CLr =   0.008352
 y  force CY |    CYp =  -0.081757    CYq =   0.033432    CYr =   0.224309
 x' mom.  Cl'|    Clp =  -0.490629    Clq =  -0.001770    Clr =   0.099255
 y  mom.  Cm |    Cmp =   0.005832    Cmq = -16.088576    Cmr =  -0.011953
 z' mom.  Cn'|    Cnp =   0.027181    Cnq =  -0.017256    Cnr =  -0.105845

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007775   CLd03 =  -0.000036
 y  force CY |   CYd01 =   0.000438   CYd02 =   0.000001   CYd03 =  -0.002833
 x' mom.  Cl'|   Cld01 =  -0.004581   Cld02 =  -0.000009   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.027294   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000234   Cnd02 =  -0.000001   Cnd03 =   0.001438
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000620 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000011    ed02 =   0.024122    ed03 =  -0.000826



 Neutral point  Xnp =   0.166541

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
