 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06611     Cltot =  -0.01005     Cl'tot =  -0.00847
  CYtot =  -0.02560     Cmtot =  -0.14199
  CZtot =  -1.46119     Cntot =   0.00931     Cn'tot =   0.01077

  CLtot =   1.45354
  CDtot =   0.16329
  CDvis =   0.07000     CDind = 0.0932889
  CLff  =   1.47455     CDff  = 0.0970748    | Trefftz
  CYff  =  -0.01908         e =    0.9983    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.573535    CLb =  -0.265238
 y  force CY |    CYa =   0.004884    CYb =  -0.290916
 x' mom.  Cl'|    Cla =  -0.020949    Clb =  -0.096018
 y  mom.  Cm |    Cma =  -1.088140    Cmb =   0.054347
 z' mom.  Cn'|    Cna =   0.011584    Cnb =   0.122167

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.014064    CLq =   7.479491    CLr =   0.018828
 y  force CY |    CYp =   0.173700    CYq =   0.083492    CYr =   0.204550
 x' mom.  Cl'|    Clp =  -0.431035    Clq =  -0.016127    Clr =   0.358390
 y  mom.  Cm |    Cmp =   0.005771    Cmq = -16.603735    Cmr =  -0.032709
 z' mom.  Cn'|    Cnp =  -0.093506    Cnq =  -0.040206    Cnr =  -0.148775

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000115   CLd02 =   0.007716   CLd03 =  -0.000071
 y  force CY |   CYd01 =   0.000161   CYd02 =   0.000002   CYd03 =  -0.002753
 x' mom.  Cl'|   Cld01 =  -0.004186   Cld02 =  -0.000022   Cld03 =  -0.000466
 y  mom.  Cm |   Cmd01 =   0.000045   Cmd02 =  -0.027896   Cmd03 =   0.000230
 z' mom.  Cn'|   Cnd01 =  -0.000150   Cnd02 =  -0.000003   Cnd03 =   0.001400
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =   0.000870 CDffd03 =   0.000174
 span eff.   |    ed01 =   0.000051    ed02 =   0.001648    ed03 =  -0.001741



 Neutral point  Xnp =   0.193594

 Clb Cnr / Clr Cnb  =   0.326266    (  > 1 if spirally stable )
