 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15956     Cltot =  -0.00235     Cl'tot =  -0.00192
  CYtot =  -0.00508     Cmtot =  -0.20269
  CZtot =  -1.70562     Cntot =   0.00185     Cn'tot =   0.00230

  CLtot =   1.70152
  CDtot =   0.19855
  CDvis =   0.07000     CDind = 0.1285456
  CLff  =   1.72906     CDff  = 0.1323361    | Trefftz
  CYff  =  -0.00382         e =    1.0067    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.436473    CLb =  -0.061286
 y  force CY |    CYa =   0.001185    CYb =  -0.291197
 x' mom.  Cl'|    Cla =  -0.003944    Clb =  -0.109677
 y  mom.  Cm |    Cma =  -1.132997    Cmb =   0.012962
 z' mom.  Cn'|    Cna =   0.002755    Cnb =   0.131605

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.002599    CLq =   7.336384    CLr =   0.003614
 y  force CY |    CYp =   0.219138    CYq =   0.016719    CYr =   0.186036
 x' mom.  Cl'|    Clp =  -0.415595    Clq =  -0.003646    Clr =   0.402682
 y  mom.  Cm |    Cmp =   0.000811    Cmq = -16.627187    Cmr =  -0.006601
 z' mom.  Cn'|    Cnp =  -0.119339    Cnq =  -0.007871    Cnr =  -0.158450

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000022   CLd02 =   0.007604   CLd03 =  -0.000013
 y  force CY |   CYd01 =   0.000111   CYd02 =   0.000000   CYd03 =  -0.002713
 x' mom.  Cl'|   Cld01 =  -0.004074   Cld02 =  -0.000004   Cld03 =  -0.000452
 y  mom.  Cm |   Cmd01 =   0.000009   Cmd02 =  -0.027760   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000214   Cnd02 =  -0.000001   Cnd03 =   0.001380
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.001143 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000007    ed02 =   0.000372    ed03 =  -0.000256



 Neutral point  Xnp =   0.198518

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
