 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04808     Cltot =   0.00017     Cl'tot =  -0.00016
  CYtot =  -0.00525     Cmtot =   0.14968
  CZtot =   0.17254     Cntot =   0.00189     Cn'tot =   0.00189

  CLtot =  -0.16157
  CDtot =   0.07731
  CDvis =   0.07000     CDind = 0.0073126
  CLff  =  -0.16285     CDff  = 0.0071173    | Trefftz
  CYff  =  -0.00382         e =    0.1661    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.992067    CLb =   0.001801
 y  force CY |    CYa =  -0.000348    CYb =  -0.300519
 x' mom.  Cl'|    Cla =  -0.004751    Clb =  -0.009077
 y  mom.  Cm |    Cma =  -0.611287    Cmb =   0.000661
 z' mom.  Cn'|    Cna =  -0.000758    Cnb =   0.108491

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004438    CLq =   8.273818    CLr =   0.004166
 y  force CY |    CYp =  -0.128959    CYq =   0.016719    CYr =   0.212009
 x' mom.  Cl'|    Clp =  -0.494354    Clq =  -0.000432    Clr =   0.046725
 y  mom.  Cm |    Cmp =   0.003225    Cmq = -15.847503    Cmr =  -0.005817
 z' mom.  Cn'|    Cnp =   0.047673    Cnq =  -0.008664    Cnr =  -0.099998

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007616   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000487   CYd02 =   0.000000   CYd03 =  -0.002799
 x' mom.  Cl'|   Cld01 =  -0.004576   Cld02 =  -0.000004   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.026697   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =   0.000309   Cnd02 =  -0.000001   Cnd03 =   0.001420
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000892 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000017    ed02 =   0.004928    ed03 =  -0.000683



 Neutral point  Xnp =   0.161031

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
