 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08675     Cltot =  -0.00018     Cl'tot =  -0.00041
  CYtot =  -0.00526     Cmtot =   0.11500
  CZtot =  -0.09069     Cntot =   0.00190     Cn'tot =   0.00187

  CLtot =   0.10059
  CDtot =   0.07505
  CDvis =   0.07000     CDind = 0.0050490
  CLff  =   0.10003     CDff  = 0.0050744    | Trefftz
  CYff  =  -0.00382         e =    0.0880    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.016185    CLb =  -0.007112
 y  force CY |    CYa =  -0.000137    CYb =  -0.301246
 x' mom.  Cl'|    Cla =  -0.004804    Clb =  -0.023417
 y  mom.  Cm |    Cma =  -0.712259    Cmb =   0.001871
 z' mom.  Cn'|    Cna =  -0.000257    Cnb =   0.106968

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004169    CLq =   8.196686    CLr =   0.004177
 y  force CY |    CYp =  -0.081795    CYq =   0.016719    CYr =   0.224412
 x' mom.  Cl'|    Clp =  -0.490854    Clq =  -0.000885    Clr =   0.099300
 y  mom.  Cm |    Cmp =   0.002916    Cmq = -16.095931    Cmr =  -0.005977
 z' mom.  Cn'|    Cnp =   0.027193    Cnq =  -0.008629    Cnr =  -0.105893

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007782   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000438   CYd02 =   0.000000   CYd03 =  -0.002836
 x' mom.  Cl'|   Cld01 =  -0.004586   Cld02 =  -0.000004   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.027319   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =   0.000234   Cnd02 =  -0.000001   Cnd03 =   0.001439
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000621 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000006    ed02 =   0.024567    ed03 =  -0.000425



 Neutral point  Xnp =   0.166542

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
