 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02795     Cltot =  -0.00313     Cl'tot =  -0.00279
  CYtot =  -0.01039     Cmtot =  -0.06978
  CZtot =  -1.14208     Cntot =   0.00379     Cn'tot =   0.00404

  CLtot =   1.13530
  CDtot =   0.12738
  CDvis =   0.07000     CDind = 0.0573818
  CLff  =   1.14112     CDff  = 0.0586031    | Trefftz
  CYff  =  -0.00764         e =    0.9902    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.785868    CLb =  -0.084396
 y  force CY |    CYa =   0.001411    CYb =  -0.297373
 x' mom.  Cl'|    Cla =  -0.008981    Clb =  -0.079865
 y  mom.  Cm |    Cma =  -1.027454    Cmb =   0.016649
 z' mom.  Cn'|    Cna =   0.003437    Cnb =   0.115659

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.006259    CLq =   7.713889    CLr =   0.007883
 y  force CY |    CYp =   0.111888    CYq =   0.033432    CYr =   0.223406
 x' mom.  Cl'|    Clp =  -0.452528    Clq =  -0.005319    Clr =   0.298900
 y  mom.  Cm |    Cmp =   0.003219    Cmq = -16.635875    Cmr =  -0.012904
 z' mom.  Cn'|    Cnp =  -0.061297    Cnq =  -0.016511    Cnr =  -0.137175

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000048   CLd02 =   0.007912   CLd03 =  -0.000031
 y  force CY |   CYd01 =   0.000231   CYd02 =   0.000001   CYd03 =  -0.002828
 x' mom.  Cl'|   Cld01 =  -0.004369   Cld02 =  -0.000009   Cld03 =  -0.000488
 y  mom.  Cm |   Cmd01 =   0.000019   Cmd02 =  -0.028291   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =  -0.000061   Cnd02 =  -0.000001   Cnd03 =   0.001437
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000508 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000035    ed02 =   0.005155    ed03 =  -0.001159



 Neutral point  Xnp =   0.187041

 Clb Cnr / Clr Cnb  =   0.316900    (  > 1 if spirally stable )
