 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10073     Cltot =  -0.00041     Cl'tot =  -0.00058
  CYtot =  -0.00526     Cmtot =   0.08902
  CZtot =  -0.26794     Cntot =   0.00191     Cn'tot =   0.00186

  CLtot =   0.27570
  CDtot =   0.07699
  CDvis =   0.07000     CDind = 0.0069923
  CLff  =   0.27518     CDff  = 0.0071851    | Trefftz
  CYff  =  -0.00382         e =    0.4697    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.014246    CLb =  -0.013060
 y  force CY |    CYa =   0.000004    CYb =  -0.301379
 x' mom.  Cl'|    Cla =  -0.004811    Clb =  -0.033032
 y  mom.  Cm |    Cma =  -0.775303    Cmb =   0.002778
 z' mom.  Cn'|    Cna =   0.000079    Cnb =   0.106790

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003991    CLq =   8.135086    CLr =   0.004168
 y  force CY |    CYp =  -0.049743    CYq =   0.016719    CYr =   0.229909
 x' mom.  Cl'|    Clp =  -0.487107    Clq =  -0.001186    Clr =   0.133957
 y  mom.  Cm |    Cmp =   0.002706    Cmq = -16.237077    Cmr =  -0.006076
 z' mom.  Cn'|    Cnp =   0.013244    Cnq =  -0.008593    Cnr =  -0.110328

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007864   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000405   CYd02 =   0.000000   CYd03 =  -0.002852
 x' mom.  Cl'|   Cld01 =  -0.004578   Cld02 =  -0.000005   Cld03 =  -0.000515
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.027653   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =   0.000184   Cnd02 =  -0.000001   Cnd03 =   0.001448
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000435 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000065    ed02 =   0.055406    ed03 =  -0.002174



 Neutral point  Xnp =   0.170103

 Clb Cnr / Clr Cnb  =   0.254756    (  > 1 if spirally stable )
