 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09403     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =   0.01500
  CZtot =  -0.71120     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.71120
  CDtot =   0.09403
  CDvis =   0.07000     CDind = 0.0240295
  CLff  =   0.71123     CDff  = 0.0245000    | Trefftz
  CYff  =   0.00000         e =    0.9201    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.947649    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.300628
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.056953
 y  mom.  Cm |    Cma =  -0.916040    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.109342

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.948932    CLr =   0.000000
 y  force CY |    CYp =   0.031383    CYq =   0.000000    CYr =   0.233817
 x' mom.  Cl'|    Clp =  -0.473093    Clq =   0.000000    Clr =   0.218560
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.505592    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.022933    Cnq =  -0.000000    Cnr =  -0.122969

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007969   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000319   CYd02 =   0.000000   CYd03 =  -0.002864
 x' mom.  Cl'|   Cld01 =  -0.004511   Cld02 =   0.000000   Cld03 =  -0.000505
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028208   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =  -0.000000   Cnd03 =   0.001455
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000036 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.019184    ed03 =   0.000000



 Neutral point  Xnp =   0.178711

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
