 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10367     Cltot =  -0.00152     Cl'tot =  -0.00165
  CYtot =  -0.01051     Cmtot =   0.04621
  CZtot =  -0.53373     Cntot =   0.00382     Cn'tot =   0.00376

  CLtot =   0.53702
  CDtot =   0.08498
  CDvis =   0.07000     CDind = 0.0149785
  CLff  =   0.53696     CDff  = 0.0155919    | Trefftz
  CYff  =  -0.00764         e =    0.8242    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.979767    CLb =  -0.043868
 y  force CY |    CYa =   0.000431    CYb =  -0.300594
 x' mom.  Cl'|    Cla =  -0.009546    Clb =  -0.047332
 y  mom.  Cm |    Cma =  -0.861907    Cmb =   0.008548
 z' mom.  Cn'|    Cna =   0.001162    Cnb =   0.107584

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007449    CLq =   8.024502    CLr =   0.008263
 y  force CY |    CYp =  -0.001141    CYq =   0.033432    CYr =   0.233826
 x' mom.  Cl'|    Clp =  -0.479221    Clq =  -0.003267    Clr =   0.185027
 y  mom.  Cm |    Cmp =   0.004768    Cmq = -16.404158    Cmr =  -0.012416
 z' mom.  Cn'|    Cnp =  -0.008213    Cnq =  -0.017036    Cnr =  -0.117608

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007937   CLd03 =  -0.000034
 y  force CY |   CYd01 =   0.000353   CYd02 =   0.000001   CYd03 =  -0.002861
 x' mom.  Cl'|   Cld01 =  -0.004541   Cld02 =  -0.000009   Cld03 =  -0.000510
 y  mom.  Cm |   Cmd01 =   0.000019   Cmd02 =  -0.028006   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000109   Cnd02 =  -0.000001   Cnd03 =   0.001453
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000153 CDffd03 =   0.000071
 span eff.   |    ed01 =   0.000111    ed02 =   0.032423    ed03 =  -0.003616



 Neutral point  Xnp =   0.175309

 Clb Cnr / Clr Cnb  =   0.279649    (  > 1 if spirally stable )
