 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02779     Cltot =  -0.00470     Cl'tot =  -0.00418
  CYtot =  -0.01558     Cmtot =  -0.06941
  CZtot =  -1.14022     Cntot =   0.00567     Cn'tot =   0.00606

  CLtot =   1.13346
  CDtot =   0.12706
  CDvis =   0.07000     CDind = 0.0570627
  CLff  =   1.14025     CDff  = 0.0586335    | Trefftz
  CYff  =  -0.01146         e =    0.9883    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.778811    CLb =  -0.126465
 y  force CY |    CYa =   0.002114    CYb =  -0.296626
 x' mom.  Cl'|    Cla =  -0.013458    Clb =  -0.079621
 y  mom.  Cm |    Cma =  -1.025889    Cmb =   0.024948
 z' mom.  Cn'|    Cna =   0.005150    Cnb =   0.115307

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.009386    CLq =   7.708013    CLr =   0.011821
 y  force CY |    CYp =   0.111802    CYq =   0.050136    CYr =   0.223235
 x' mom.  Cl'|    Clp =  -0.452183    Clq =  -0.007976    Clr =   0.298672
 y  mom.  Cm |    Cmp =   0.004827    Cmq = -16.623202    Cmr =  -0.019352
 z' mom.  Cn'|    Cnp =  -0.061250    Cnq =  -0.024760    Cnr =  -0.137070

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000072   CLd02 =   0.007900   CLd03 =  -0.000046
 y  force CY |   CYd01 =   0.000230   CYd02 =   0.000001   CYd03 =  -0.002823
 x' mom.  Cl'|   Cld01 =  -0.004362   Cld02 =  -0.000014   Cld03 =  -0.000487
 y  mom.  Cm |   Cmd01 =   0.000028   Cmd02 =  -0.028248   Cmd03 =   0.000139
 z' mom.  Cn'|   Cnd01 =  -0.000061   Cnd02 =  -0.000002   Cnd03 =   0.001435
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000507 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000052    ed02 =   0.005161    ed03 =  -0.001732



 Neutral point  Xnp =   0.187038

 Clb Cnr / Clr Cnb  =   0.316900    (  > 1 if spirally stable )
