 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07427     Cltot =   0.00367     Cl'tot =   0.00347
  CYtot =   0.01567     Cmtot =  -0.01732
  CZtot =  -0.88353     Cntot =  -0.00570     Cn'tot =  -0.00583

  CLtot =   0.88040
  CDtot =   0.10506
  CDvis =   0.07000     CDind = 0.0350585
  CLff  =   0.88308     CDff  = 0.0362854    | Trefftz
  CYff  =   0.01146         e =    0.9579    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.882494    CLb =   0.100764
 y  force CY |    CYa =  -0.001487    CYb =  -0.298420
 x' mom.  Cl'|    Cla =   0.013923    Clb =  -0.065968
 y  mom.  Cm |    Cma =  -0.962016    Cmb =  -0.019488
 z' mom.  Cn'|    Cna =  -0.003715    Cnb =   0.110886

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010133    CLq =   7.850811    CLr =  -0.012119
 y  force CY |    CYp =   0.063730    CYq =  -0.050136    CYr =   0.231079
 x' mom.  Cl'|    Clp =  -0.465039    Clq =   0.006669    Clr =   0.250984
 y  mom.  Cm |    Cmp =  -0.005833    Cmq = -16.554198    Cmr =   0.019073
 z' mom.  Cn'|    Cnp =  -0.037953    Cnq =   0.025143    Cnr =  -0.128351

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000073   CLd02 =   0.007946   CLd03 =   0.000048
 y  force CY |   CYd01 =   0.000283   CYd02 =  -0.000001   CYd03 =  -0.002848
 x' mom.  Cl'|   Cld01 =  -0.004452   Cld02 =   0.000014   Cld03 =  -0.000498
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.028229   Cmd03 =  -0.000140
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =   0.000002   Cnd03 =   0.001447
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000225 CDffd03 =  -0.000106
 span eff.   |    ed01 =  -0.000082    ed02 =   0.011252    ed03 =   0.002719



 Neutral point  Xnp =   0.182064

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
