 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07395     Cltot =  -0.00488     Cl'tot =  -0.00462
  CYtot =  -0.02087     Cmtot =  -0.01693
  CZtot =  -0.88146     Cntot =   0.00759     Cn'tot =   0.00776

  CLtot =   0.87834
  CDtot =   0.10467
  CDvis =   0.07000     CDind = 0.0346678
  CLff  =   0.88214     CDff  = 0.0363755    | Trefftz
  CYff  =  -0.01527         e =    0.9536    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.872397    CLb =  -0.134161
 y  force CY |    CYa =   0.001980    CYb =  -0.297368
 x' mom.  Cl'|    Cla =  -0.018538    Clb =  -0.065686
 y  mom.  Cm |    Cma =  -0.959964    Cmb =   0.025947
 z' mom.  Cn'|    Cna =   0.004946    Cnb =   0.110412

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.013506    CLq =   7.842434    CLr =   0.016153
 y  force CY |    CYp =   0.063662    CYq =   0.066824    CYr =   0.230833
 x' mom.  Cl'|    Clp =  -0.464543    Clq =  -0.008889    Clr =   0.250716
 y  mom.  Cm |    Cmp =   0.007775    Cmq = -16.536536    Cmr =  -0.025421
 z' mom.  Cn'|    Cnp =  -0.037913    Cnq =  -0.033513    Cnr =  -0.128214

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000097   CLd02 =   0.007930   CLd03 =  -0.000064
 y  force CY |   CYd01 =   0.000282   CYd02 =   0.000001   CYd03 =  -0.002842
 x' mom.  Cl'|   Cld01 =  -0.004442   Cld02 =  -0.000018   Cld03 =  -0.000497
 y  mom.  Cm |   Cmd01 =   0.000038   Cmd02 =  -0.028169   Cmd03 =   0.000186
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =  -0.000002   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000224 CDffd03 =   0.000141
 span eff.   |    ed01 =   0.000109    ed02 =   0.011226    ed03 =  -0.003594



 Neutral point  Xnp =   0.182060

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
