 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12628     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.18311
  CZtot =  -1.62993     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   1.62408
  CDtot =   0.18705
  CDvis =   0.07000     CDind = 0.1170455
  CLff  =   1.64677     CDff  = 0.1200809    | Trefftz
  CYff  =   0.00000         e =    1.0064    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.497111    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.292494
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.105752
 y  mom.  Cm |    Cma =  -1.122414    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.128999

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.395426    CLr =   0.000000
 y  force CY |    CYp =   0.204463    CYq =   0.000000    CYr =   0.193006
 x' mom.  Cl'|    Clp =  -0.421499    Clq =  -0.000000    Clr =   0.388670
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.647271    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.110755    Cnq =  -0.000000    Cnr =  -0.155440

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007668   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000128   CYd02 =   0.000000   CYd03 =  -0.002736
 x' mom.  Cl'|   Cld01 =  -0.004125   Cld02 =   0.000000   Cld03 =  -0.000458
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027899   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000194   Cnd02 =  -0.000000   Cnd03 =   0.001391
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.001056 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.000702    ed03 =   0.000000



 Neutral point  Xnp =   0.196883

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
