 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01466     Cltot =   0.00538     Cl'tot =   0.00465
  CYtot =   0.01550     Cmtot =  -0.10587
  CZtot =  -1.30677     Cntot =  -0.00564     Cn'tot =  -0.00626

  CLtot =   1.29882
  CDtot =   0.14470
  CDvis =   0.07000     CDind = 0.0747023
  CLff  =   1.31000     CDff  = 0.0766877    | Trefftz
  CYff  =   0.01146         e =    0.9973    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.693234    CLb =   0.143236
 y  force CY |    CYa =  -0.002528    CYb =  -0.295084
 x' mom.  Cl'|    Cla =   0.013066    Clb =  -0.088434
 y  mom.  Cm |    Cma =  -1.062265    Cmb =  -0.028769
 z' mom.  Cn'|    Cna =  -0.006076    Cnb =   0.119036

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.008907    CLq =   7.605521    CLr =  -0.011580
 y  force CY |    CYp =   0.143281    CYq =  -0.050136    CYr =   0.215231
 x' mom.  Cl'|    Clp =  -0.442531    Clq =   0.008835    Clr =   0.329424
 y  mom.  Cm |    Cmp =  -0.004149    Cmq = -16.643899    Cmr =   0.019508
 z' mom.  Cn'|    Cnp =  -0.077285    Cnq =   0.024466    Cnr =  -0.143065

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000071   CLd02 =   0.007838   CLd03 =   0.000044
 y  force CY |   CYd01 =   0.000196   CYd02 =  -0.000001   CYd03 =  -0.002798
 x' mom.  Cl'|   Cld01 =  -0.004289   Cld02 =   0.000013   Cld03 =  -0.000478
 y  mom.  Cm |   Cmd01 =  -0.000028   Cmd02 =  -0.028175   Cmd03 =  -0.000139
 z' mom.  Cn'|   Cnd01 =  -0.000106   Cnd02 =   0.000002   Cnd03 =   0.001422
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000692 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000039    ed02 =   0.002997    ed03 =   0.001332



 Neutral point  Xnp =   0.190328

 Clb Cnr / Clr Cnb  =   0.322640    (  > 1 if spirally stable )
