 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09357     Cltot =  -0.00298     Cl'tot =  -0.00298
  CYtot =  -0.01572     Cmtot =   0.01542
  CZtot =  -0.70902     Cntot =   0.00571     Cn'tot =   0.00571

  CLtot =   0.70902
  CDtot =   0.09357
  CDvis =   0.07000     CDind = 0.0235660
  CLff  =   0.71025     CDff  = 0.0246480    | Trefftz
  CYff  =  -0.01146         e =    0.9123    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.934495    CLb =  -0.083337
 y  force CY |    CYa =   0.001067    CYb =  -0.299269
 x' mom.  Cl'|    Cla =  -0.014148    Clb =  -0.056641
 y  mom.  Cm |    Cma =  -0.913530    Cmb =   0.016055
 z' mom.  Cn'|    Cna =   0.002735    Cnb =   0.108743

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010647    CLq =   7.938038    CLr =   0.012274
 y  force CY |    CYp =   0.031340    CYq =   0.050136    CYr =   0.233496
 x' mom.  Cl'|    Clp =  -0.472444    Clq =  -0.005788    Clr =   0.218260
 y  mom.  Cm |    Cmp =   0.006495    Cmq = -16.482971    Cmr =  -0.018857
 z' mom.  Cn'|    Cnp =  -0.022901    Cnq =  -0.025361    Cnr =  -0.122801

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000074   CLd02 =   0.007948   CLd03 =  -0.000050
 y  force CY |   CYd01 =   0.000318   CYd02 =   0.000001   CYd03 =  -0.002856
 x' mom.  Cl'|   Cld01 =  -0.004499   Cld02 =  -0.000014   Cld03 =  -0.000504
 y  mom.  Cm |   Cmd01 =   0.000029   Cmd02 =  -0.028130   Cmd03 =   0.000140
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =  -0.000002   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =   0.000036 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000116    ed02 =   0.019028    ed03 =  -0.003809



 Neutral point  Xnp =   0.178707

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
