 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09477     Cltot =  -0.00059     Cl'tot =  -0.00098
  CYtot =  -0.01052     Cmtot =   0.10235
  CZtot =  -0.17896     Cntot =   0.00381     Cn'tot =   0.00373

  CLtot =   0.18789
  CDtot =   0.07554
  CDvis =   0.07000     CDind = 0.0055439
  CLff  =   0.18755     CDff  = 0.0058492    | Trefftz
  CYff  =  -0.00764         e =    0.2684    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.012566    CLb =  -0.020161
 y  force CY |    CYa =  -0.000132    CYb =  -0.300893
 x' mom.  Cl'|    Cla =  -0.009615    Clb =  -0.028171
 y  mom.  Cm |    Cma =  -0.743554    Cmb =   0.004627
 z' mom.  Cn'|    Cna =  -0.000178    Cnb =   0.106600

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.008159    CLq =   8.163149    CLr =   0.008347
 y  force CY |    CYp =  -0.065787    CYq =   0.033432    CYr =   0.227336
 x' mom.  Cl'|    Clp =  -0.488896    Clq =  -0.002071    Clr =   0.116623
 y  mom.  Cm |    Cmp =   0.005622    Cmq = -16.161579    Cmr =  -0.012053
 z' mom.  Cn'|    Cnp =   0.020242    Cnq =  -0.017222    Cnr =  -0.108013

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000050   CLd02 =   0.007819   CLd03 =  -0.000036
 y  force CY |   CYd01 =   0.000421   CYd02 =   0.000001   CYd03 =  -0.002843
 x' mom.  Cl'|   Cld01 =  -0.004579   Cld02 =  -0.000009   Cld03 =  -0.000515
 y  mom.  Cm |   Cmd01 =   0.000020   Cmd02 =  -0.027469   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000209   Cnd02 =  -0.000001   Cnd03 =   0.001443
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =  -0.000528 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000081    ed02 =   0.046720    ed03 =  -0.002908



 Neutral point  Xnp =   0.168331

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
