 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10524     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.06088
  CZtot =  -0.44575     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   0.45065
  CDtot =   0.08177
  CDvis =   0.07000     CDind = 0.0117658
  CLff  =   0.45006     CDff  = 0.0120436    | Trefftz
  CYff  =   0.00000         e =    0.7495    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.999301    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.301381
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.042662
 y  mom.  Cm |    Cma =  -0.834823    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.107349

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.066918    CLr =   0.000000
 y  force CY |    CYp =  -0.017388    CYq =   0.000000    CYr =   0.233193
 x' mom.  Cl'|    Clp =  -0.482336    Clq =  -0.000000    Clr =   0.168212
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.360933    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.000986    Cnq =  -0.000000    Cnr =  -0.115150

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007926   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000371   CYd02 =   0.000000   CYd03 =  -0.002863
 x' mom.  Cl'|   Cld01 =  -0.004560   Cld02 =   0.000000   Cld03 =  -0.000512
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027931   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000134   Cnd02 =  -0.000000   Cnd03 =   0.001454
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000248 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.041804    ed03 =   0.000000



 Neutral point  Xnp =   0.173591

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
