 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04578     Cltot =   0.00291     Cl'tot =   0.00263
  CYtot =   0.01042     Cmtot =  -0.05202
  CZtot =  -1.05720     Cntot =  -0.00379     Cn'tot =  -0.00399

  CLtot =   1.05143
  CDtot =   0.11942
  CDvis =   0.07000     CDind = 0.0494193
  CLff  =   1.05565     CDff  = 0.0505005    | Trefftz
  CYff  =   0.00764         e =    0.9834    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.823843    CLb =   0.078723
 y  force CY |    CYa =  -0.001272    CYb =  -0.298042
 x' mom.  Cl'|    Cla =   0.009096    Clb =  -0.075352
 y  mom.  Cm |    Cma =  -1.007349    Cmb =  -0.015409
 z' mom.  Cn'|    Cna =  -0.003121    Cnb =   0.114022

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006423    CLq =   7.763044    CLr =  -0.007955
 y  force CY |    CYp =   0.095946    CYq =  -0.033432    CYr =   0.226582
 x' mom.  Cl'|    Clp =  -0.457040    Clq =   0.005030    Clr =   0.283191
 y  mom.  Cm |    Cmp =  -0.003444    Cmq = -16.617916    Cmr =   0.012846
 z' mom.  Cn'|    Cnp =  -0.053426    Cnq =   0.016601    Cnr =  -0.134222

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000048   CLd02 =   0.007933   CLd03 =   0.000031
 y  force CY |   CYd01 =   0.000248   CYd02 =  -0.000001   CYd03 =  -0.002838
 x' mom.  Cl'|   Cld01 =  -0.004401   Cld02 =   0.000009   Cld03 =  -0.000492
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028302   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =   0.000001   Cnd03 =   0.001442
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000414 CDffd03 =  -0.000071
 span eff.   |    ed01 =  -0.000040    ed02 =   0.006698    ed03 =   0.001337



 Neutral point  Xnp =   0.185389

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
