 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12604     Cltot =  -0.00894     Cl'tot =  -0.00736
  CYtot =  -0.02037     Cmtot =  -0.18140
  CZtot =  -1.62165     Cntot =   0.00741     Cn'tot =   0.00898

  CLtot =   1.61590
  CDtot =   0.18570
  CDvis =   0.07000     CDind = 0.1157025
  CLff  =   1.64276     CDff  = 0.1198788    | Trefftz
  CYff  =  -0.01527         e =    1.0033    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.476002    CLb =  -0.233931
 y  force CY |    CYa =   0.004457    CYb =  -0.290158
 x' mom.  Cl'|    Cla =  -0.016102    Clb =  -0.104723
 y  mom.  Cm |    Cma =  -1.116952    Cmb =   0.048949
 z' mom.  Cn'|    Cna =   0.010433    Cnb =   0.127743

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.010669    CLq =   7.377411    CLr =   0.014662
 y  force CY |    CYp =   0.203965    CYq =   0.066824    CYr =   0.192536
 x' mom.  Cl'|    Clp =  -0.420473    Clq =  -0.014022    Clr =   0.387723
 y  mom.  Cm |    Cmp =   0.003703    Cmq = -16.606719    Cmr =  -0.026324
 z' mom.  Cn'|    Cnp =  -0.110485    Cnq =  -0.031709    Cnr =  -0.155062

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000090   CLd02 =   0.007631   CLd03 =  -0.000054
 y  force CY |   CYd01 =   0.000127   CYd02 =   0.000001   CYd03 =  -0.002722
 x' mom.  Cl'|   Cld01 =  -0.004105   Cld02 =  -0.000018   Cld03 =  -0.000456
 y  mom.  Cm |   Cmd01 =   0.000036   Cmd02 =  -0.027763   Cmd03 =   0.000183
 z' mom.  Cn'|   Cnd01 =  -0.000193   Cnd02 =  -0.000002   Cnd03 =   0.001385
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.001051 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000033    ed02 =   0.000728    ed03 =  -0.001129



 Neutral point  Xnp =   0.196871

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
