 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10474     Cltot =   0.00193     Cl'tot =   0.00223
  CYtot =   0.01576     Cmtot =   0.06118
  CZtot =  -0.44428     Cntot =  -0.00572     Cn'tot =  -0.00561

  CLtot =   0.44916
  CDtot =   0.08135
  CDvis =   0.07000     CDind = 0.0113488
  CLff  =   0.44944     CDff  = 0.0122257    | Trefftz
  CYff  =   0.01146         e =    0.7368    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.985993    CLb =   0.056885
 y  force CY |    CYa =  -0.000435    CYb =  -0.300017
 x' mom.  Cl'|    Cla =   0.014357    Clb =  -0.042428
 y  mom.  Cm |    Cma =  -0.832537    Cmb =  -0.011260
 z' mom.  Cn'|    Cna =  -0.001241    Cnb =   0.106761

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.011435    CLq =   8.055862    CLr =  -0.012437
 y  force CY |    CYp =  -0.017364    CYq =  -0.050136    CYr =   0.232873
 x' mom.  Cl'|    Clp =  -0.481675    Clq =   0.004453    Clr =   0.167981
 y  mom.  Cm |    Cmp =  -0.007473    Cmq = -16.338511    Cmr =   0.018492
 z' mom.  Cn'|    Cnp =  -0.000985    Cnq =   0.025629    Cnr =  -0.114992

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000074   CLd02 =   0.007904   CLd03 =   0.000052
 y  force CY |   CYd01 =   0.000370   CYd02 =  -0.000001   CYd03 =  -0.002855
 x' mom.  Cl'|   Cld01 =  -0.004548   Cld02 =   0.000014   Cld03 =  -0.000511
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.027854   Cmd03 =  -0.000140
 z' mom.  Cn'|   Cnd01 =   0.000133   Cnd02 =   0.000002   Cnd03 =   0.001450
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000247 CDffd03 =  -0.000106
 span eff.   |    ed01 =  -0.000188    ed02 =   0.040811    ed03 =   0.006148



 Neutral point  Xnp =   0.173587

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
