 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08680     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.11498
  CZtot =  -0.09075     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   0.10065
  CDtot =   0.07509
  CDvis =   0.07000     CDind = 0.0050912
  CLff  =   0.10005     CDff  = 0.0050520    | Trefftz
  CYff  =  -0.00000         e =    0.0883    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.017673    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.301398
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.023431
 y  mom.  Cm |    Cma =  -0.712476    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.107034

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.197934    CLr =   0.000000
 y  force CY |    CYp =  -0.081807    CYq =   0.000000    CYr =   0.224446
 x' mom.  Cl'|    Clp =  -0.490928    Clq =   0.000000    Clr =   0.099315
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.098383    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.027197    Cnq =  -0.000000    Cnr =  -0.105910

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007784   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000439   CYd02 =   0.000000   CYd03 =  -0.002837
 x' mom.  Cl'|   Cld01 =  -0.004587   Cld02 =   0.000000   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027327   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000234   Cnd02 =  -0.000000   Cnd03 =   0.001440
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000621 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.024719    ed03 =   0.000000



 Neutral point  Xnp =   0.166542

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
