 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08549     Cltot =   0.00111     Cl'tot =   0.00108
  CYtot =   0.00524     Cmtot =  -0.00115
  CZtot =  -0.79869     Cntot =  -0.00191     Cn'tot =  -0.00193

  CLtot =   0.79708
  CDtot =   0.09941
  CDvis =   0.07000     CDind = 0.0294135
  CLff  =   0.79776     CDff  = 0.0300172    | Trefftz
  CYff  =   0.00382         e =    0.9449    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.921867    CLb =   0.030742
 y  force CY |    CYa =  -0.000427    CYb =  -0.300086
 x' mom.  Cl'|    Cla =   0.004689    Clb =  -0.061624
 y  mom.  Cm |    Cma =  -0.940636    Cmb =  -0.005926
 z' mom.  Cn'|    Cna =  -0.001077    Cnb =   0.110271

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003464    CLq =   7.904889    CLr =  -0.004069
 y  force CY |    CYp =   0.047614    CYq =  -0.016719    CYr =   0.232854
 x' mom.  Cl'|    Clp =  -0.469435    Clq =   0.002077    Clr =   0.234995
 y  mom.  Cm |    Cmp =  -0.002056    Cmq = -16.541254    Cmr =   0.006325
 z' mom.  Cn'|    Cnp =  -0.030418    Cnq =   0.008422    Cnr =  -0.125699

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007969   CLd03 =   0.000016
 y  force CY |   CYd01 =   0.000301   CYd02 =  -0.000000   CYd03 =  -0.002860
 x' mom.  Cl'|   Cld01 =  -0.004488   Cld02 =   0.000005   Cld03 =  -0.000503
 y  mom.  Cm |   Cmd01 =  -0.000010   Cmd02 =  -0.028257   Cmd03 =  -0.000047
 z' mom.  Cn'|   Cnd01 =   0.000035   Cnd02 =   0.000001   Cnd03 =   0.001453
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000131 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000033    ed02 =   0.014682    ed03 =   0.001082



 Neutral point  Xnp =   0.180394

 Clb Cnr / Clr Cnb  =   0.298923    (  > 1 if spirally stable )
