 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02729     Cltot =  -0.00780     Cl'tot =  -0.00695
  CYtot =  -0.02589     Cmtot =  -0.06826
  CZtot =  -1.13428     Cntot =   0.00942     Cn'tot =   0.01007

  CLtot =   1.12758
  CDtot =   0.12604
  CDvis =   0.07000     CDind = 0.0560438
  CLff  =   1.13747     CDff  = 0.0587304    | Trefftz
  CYff  =  -0.01908         e =    0.9820    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.756278    CLb =  -0.210090
 y  force CY |    CYa =   0.003512    CYb =  -0.294241
 x' mom.  Cl'|    Cla =  -0.022358    Clb =  -0.078843
 y  mom.  Cm |    Cma =  -1.020893    Cmb =   0.041445
 z' mom.  Cn'|    Cna =   0.008555    Cnb =   0.114180

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015630    CLq =   7.689220    CLr =   0.019686
 y  force CY |    CYp =   0.111530    CYq =   0.083492    CYr =   0.222691
 x' mom.  Cl'|    Clp =  -0.451080    Clq =  -0.013283    Clr =   0.297944
 y  mom.  Cm |    Cmp =   0.008039    Cmq = -16.582672    Cmr =  -0.032227
 z' mom.  Cn'|    Cnp =  -0.061101    Cnq =  -0.041233    Cnr =  -0.136736

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000119   CLd02 =   0.007861   CLd03 =  -0.000076
 y  force CY |   CYd01 =   0.000229   CYd02 =   0.000002   CYd03 =  -0.002810
 x' mom.  Cl'|   Cld01 =  -0.004341   Cld02 =  -0.000022   Cld03 =  -0.000485
 y  mom.  Cm |   Cmd01 =   0.000047   Cmd02 =  -0.028111   Cmd03 =   0.000231
 z' mom.  Cn'|   Cnd01 =  -0.000060   Cnd02 =  -0.000003   Cnd03 =   0.001428
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =   0.000504 CDffd03 =   0.000175
 span eff.   |    ed01 =   0.000085    ed02 =   0.005181    ed03 =  -0.002854



 Neutral point  Xnp =   0.187029

 Clb Cnr / Clr Cnb  =   0.316900    (  > 1 if spirally stable )
