 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10518     Cltot =   0.00065     Cl'tot =   0.00074
  CYtot =   0.00526     Cmtot =   0.06092
  CZtot =  -0.44559     Cntot =  -0.00191     Cn'tot =  -0.00187

  CLtot =   0.45048
  CDtot =   0.08172
  CDvis =   0.07000     CDind = 0.0117194
  CLff  =   0.44999     CDff  = 0.0120638    | Trefftz
  CYff  =   0.00382         e =    0.7481    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.997821    CLb =   0.018992
 y  force CY |    CYa =  -0.000145    CYb =  -0.301229
 x' mom.  Cl'|    Cla =   0.004793    Clb =  -0.042636
 y  mom.  Cm |    Cma =  -0.834569    Cmb =  -0.003759
 z' mom.  Cn'|    Cna =  -0.000414    Cnb =   0.107284

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003813    CLq =   8.065689    CLr =  -0.004147
 y  force CY |    CYp =  -0.017386    CYq =  -0.016719    CYr =   0.233157
 x' mom.  Cl'|    Clp =  -0.482263    Clq =   0.001485    Clr =   0.168186
 y  mom.  Cm |    Cmp =  -0.002492    Cmq = -16.358441    Cmr =   0.006166
 z' mom.  Cn'|    Cnp =  -0.000986    Cnq =   0.008546    Cnr =  -0.115133

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007923   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000371   CYd02 =  -0.000000   CYd03 =  -0.002862
 x' mom.  Cl'|   Cld01 =  -0.004559   Cld02 =   0.000005   Cld03 =  -0.000512
 y  mom.  Cm |   Cmd01 =  -0.000010   Cmd02 =  -0.027922   Cmd03 =  -0.000047
 z' mom.  Cn'|   Cnd01 =   0.000134   Cnd02 =   0.000001   Cnd03 =   0.001453
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000248 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000065    ed02 =   0.041691    ed03 =   0.002113



 Neutral point  Xnp =   0.173590

 Clb Cnr / Clr Cnb  =   0.272050    (  > 1 if spirally stable )
