 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00752     Cltot =   0.00671     Cl'tot =   0.00588
  CYtot =   0.02070     Cmtot =  -0.08694
  CZtot =  -1.22124     Cntot =  -0.00753     Cn'tot =  -0.00819

  CLtot =   1.21377
  CDtot =   0.13513
  CDvis =   0.07000     CDind = 0.0651321
  CLff  =   1.22401     CDff  = 0.0673757    | Trefftz
  CYff  =   0.01527         e =    0.9911    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.727847    CLb =   0.179598
 y  force CY |    CYa =  -0.003091    CYb =  -0.294848
 x' mom.  Cl'|    Cla =   0.017669    Clb =  -0.083700
 y  mom.  Cm |    Cma =  -1.042486    Cmb =  -0.035738
 z' mom.  Cn'|    Cna =  -0.007478    Cnb =   0.116594

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012188    CLq =   7.649286    CLr =  -0.015601
 y  force CY |    CYp =   0.127475    CYq =  -0.066824    CYr =   0.219274
 x' mom.  Cl'|    Clp =  -0.446983    Clq =   0.011205    Clr =   0.313823
 y  mom.  Cm |    Cmp =  -0.005983    Cmq = -16.618335    Cmr =   0.025901
 z' mom.  Cn'|    Cnp =  -0.069142    Cnq =   0.032811    Cnr =  -0.139905

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000095   CLd02 =   0.007855   CLd03 =   0.000060
 y  force CY |   CYd01 =   0.000212   CYd02 =  -0.000001   CYd03 =  -0.002806
 x' mom.  Cl'|   Cld01 =  -0.004317   Cld02 =   0.000018   Cld03 =  -0.000482
 y  mom.  Cm |   Cmd01 =  -0.000037   Cmd02 =  -0.028160   Cmd03 =  -0.000185
 z' mom.  Cn'|   Cnd01 =  -0.000084   Cnd02 =   0.000002   Cnd03 =   0.001426
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000599 CDffd03 =  -0.000140
 span eff.   |    ed01 =  -0.000060    ed02 =   0.003965    ed03 =   0.002009



 Neutral point  Xnp =   0.188681

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
