 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07584     Cltot =   0.00018     Cl'tot =   0.00097
  CYtot =   0.01575     Cmtot =   0.12724
  CZtot =  -0.00225     Cntot =  -0.00569     Cn'tot =  -0.00561

  CLtot =   0.01279
  CDtot =   0.07478
  CDvis =   0.07000     CDind = 0.0047846
  CLff  =   0.01238     CDff  = 0.0052397    | Trefftz
  CYff  =   0.01146         e =    0.0024    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.999849    CLb =   0.012392
 y  force CY |    CYa =   0.000621    CYb =  -0.299863
 x' mom.  Cl'|    Cla =   0.014354    Clb =  -0.018530
 y  mom.  Cm |    Cma =  -0.677761    Cmb =  -0.004335
 z' mom.  Cn'|    Cna =   0.001271    Cnb =   0.106786

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012772    CLq =   8.214446    CLr =  -0.012524
 y  force CY |    CYp =  -0.097538    CYq =  -0.050136    CYr =   0.220558
 x' mom.  Cl'|    Clp =  -0.491706    Clq =   0.002202    Clr =   0.081742
 y  mom.  Cm |    Cmp =  -0.009057    Cmq = -15.998477    Cmr =   0.017770
 z' mom.  Cn'|    Cnp =   0.034033    Cnq =   0.025920    Cnr =  -0.103698

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000075   CLd02 =   0.007713   CLd03 =   0.000054
 y  force CY |   CYd01 =   0.000454   CYd02 =  -0.000001   CYd03 =  -0.002818
 x' mom.  Cl'|   Cld01 =  -0.004574   Cld02 =   0.000013   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =  -0.000030   Cmd02 =  -0.027061   Cmd03 =  -0.000139
 z' mom.  Cn'|   Cnd01 =   0.000259   Cnd02 =   0.000002   Cnd03 =   0.001430
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =  -0.000710 CDffd03 =  -0.000105
 span eff.   |    ed01 =   0.000041    ed02 =   0.001977    ed03 =  -0.000485



 Neutral point  Xnp =   0.164727

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
