 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04589     Cltot =  -0.00145     Cl'tot =  -0.00132
  CYtot =  -0.00521     Cmtot =  -0.05222
  CZtot =  -1.05824     Cntot =   0.00190     Cn'tot =   0.00199

  CLtot =   1.05247
  CDtot =   0.11960
  CDvis =   0.07000     CDind = 0.0496025
  CLff  =   1.05613     CDff  = 0.0504748    | Trefftz
  CYff  =  -0.00382         e =    0.9848    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.828117    CLb =  -0.039386
 y  force CY |    CYa =   0.000636    CYb =  -0.298492
 x' mom.  Cl'|    Cla =  -0.004551    Clb =  -0.075490
 y  mom.  Cm |    Cma =  -1.008270    Cmb =   0.007709
 z' mom.  Cn'|    Cna =   0.001562    Cnb =   0.114231

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.003212    CLq =   7.766593    CLr =   0.003978
 y  force CY |    CYp =   0.095990    CYq =   0.016719    CYr =   0.226685
 x' mom.  Cl'|    Clp =  -0.457249    Clq =  -0.002515    Clr =   0.283320
 y  mom.  Cm |    Cmp =   0.001722    Cmq = -16.625512    Cmr =  -0.006424
 z' mom.  Cn'|    Cnp =  -0.053451    Cnq =  -0.008302    Cnr =  -0.134284

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000024   CLd02 =   0.007941   CLd03 =  -0.000016
 y  force CY |   CYd01 =   0.000248   CYd02 =   0.000000   CYd03 =  -0.002840
 x' mom.  Cl'|   Cld01 =  -0.004405   Cld02 =  -0.000005   Cld03 =  -0.000492
 y  mom.  Cm |   Cmd01 =   0.000009   Cmd02 =  -0.028328   Cmd03 =   0.000047
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =  -0.000001   Cnd03 =   0.001443
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =   0.000414 CDffd03 =   0.000035
 span eff.   |    ed01 =   0.000020    ed02 =   0.006696    ed03 =  -0.000670



 Neutral point  Xnp =   0.185391

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
