 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10415     Cltot =   0.00053     Cl'tot =   0.00066
  CYtot =   0.00526     Cmtot =   0.07523
  CZtot =  -0.35677     Cntot =  -0.00191     Cn'tot =  -0.00187

  CLtot =   0.36316
  CDtot =   0.07901
  CDvis =   0.07000     CDind = 0.0090083
  CLff  =   0.36264     CDff  = 0.0092796    | Trefftz
  CYff  =   0.00382         e =    0.6316    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.007843    CLb =   0.016029
 y  force CY |    CYa =  -0.000075    CYb =  -0.301339
 x' mom.  Cl'|    Cla =   0.004805    Clb =  -0.037838
 y  mom.  Cm |    Cma =  -0.805426    Cmb =  -0.003260
 z' mom.  Cn'|    Cna =  -0.000247    Cnb =   0.106953

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003902    CLq =   8.101342    CLr =  -0.004159
 y  force CY |    CYp =  -0.033593    CYq =  -0.016719    CYr =   0.231816
 x' mom.  Cl'|    Clp =  -0.484820    Clq =   0.001335    Clr =   0.151131
 y  mom.  Cm |    Cmp =  -0.002599    Cmq = -16.300242    Cmr =   0.006122
 z' mom.  Cn'|    Cnp =   0.006166    Cnq =   0.008571    Cnr =  -0.112686

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000025   CLd02 =   0.007897   CLd03 =   0.000017
 y  force CY |   CYd01 =   0.000388   CYd02 =  -0.000000   CYd03 =  -0.002858
 x' mom.  Cl'|   Cld01 =  -0.004570   Cld02 =   0.000005   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =  -0.000010   Cmd02 =  -0.027796   Cmd03 =  -0.000047
 z' mom.  Cn'|   Cnd01 =   0.000159   Cnd02 =   0.000001   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =  -0.000342 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000070    ed02 =   0.050807    ed03 =   0.002302



 Neutral point  Xnp =   0.171855

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
