 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09930     Cltot =  -0.00350     Cl'tot =  -0.00363
  CYtot =  -0.02095     Cmtot =   0.03144
  CZtot =  -0.61955     Cntot =   0.00761     Cn'tot =   0.00755

  CLtot =   0.62119
  CDtot =   0.08847
  CDvis =   0.07000     CDind = 0.0184677
  CLff  =   0.62283     CDff  = 0.0199554    | Trefftz
  CYff  =  -0.01527         e =    0.8668    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.944964    CLb =  -0.099266
 y  force CY |    CYa =   0.001141    CYb =  -0.298531
 x' mom.  Cl'|    Cla =  -0.018953    Clb =  -0.051706
 y  mom.  Cm |    Cma =  -0.885710    Cmb =   0.019183
 z' mom.  Cn'|    Cna =   0.002981    Cnb =   0.107456

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.014538    CLq =   7.970585    CLr =   0.016444
 y  force CY |    CYp =   0.015085    CYq =   0.066824    CYr =   0.233606
 x' mom.  Cl'|    Clp =  -0.475270    Clq =  -0.007123    Clr =   0.201434
 y  mom.  Cm |    Cmp =   0.009095    Cmq = -16.422280    Cmr =  -0.024979
 z' mom.  Cn'|    Cnp =  -0.015495    Cnq =  -0.033932    Cnr =  -0.119995

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000098   CLd02 =   0.007922   CLd03 =  -0.000067
 y  force CY |   CYd01 =   0.000334   CYd02 =   0.000001   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004508   Cld02 =  -0.000018   Cld03 =  -0.000506
 y  mom.  Cm |   Cmd01 =   0.000039   Cmd02 =  -0.027995   Cmd03 =   0.000186
 z' mom.  Cn'|   Cnd01 =   0.000084   Cnd02 =  -0.000002   Cnd03 =   0.001448
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000059 CDffd03 =   0.000141
 span eff.   |    ed01 =   0.000182    ed02 =   0.024558    ed03 =  -0.005941



 Neutral point  Xnp =   0.177010

 Clb Cnr / Clr Cnb  =   0.286642    (  > 1 if spirally stable )
