 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09368     Cltot =   0.00147     Cl'tot =   0.00245
  CYtot =   0.02620     Cmtot =   0.10277
  CZtot =  -0.17722     Cntot =  -0.00948     Cn'tot =  -0.00928

  CLtot =   0.18605
  CDtot =   0.07464
  CDvis =   0.07000     CDind = 0.0046438
  CLff  =   0.18695     CDff  = 0.0063134    | Trefftz
  CYff  =   0.01908         e =    0.2493    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.981421    CLb =   0.050187
 y  force CY |    CYa =   0.000330    CYb =  -0.297716
 x' mom.  Cl'|    Cla =   0.023935    Clb =  -0.027811
 y  mom.  Cm |    Cma =  -0.738806    Cmb =  -0.011519
 z' mom.  Cn'|    Cna =   0.000443    Cnb =   0.105237

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.020375    CLq =   8.137042    CLr =  -0.020845
 y  force CY |    CYp =  -0.065576    CYq =  -0.083492    CYr =   0.226609
 x' mom.  Cl'|    Clp =  -0.487332    Clq =   0.005171    Clr =   0.116250
 y  mom.  Cm |    Cmp =  -0.014040    Cmq = -16.109893    Cmr =   0.030101
 z' mom.  Cn'|    Cnp =   0.020177    Cnq =   0.043010    Cnr =  -0.107668

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000124   CLd02 =   0.007769   CLd03 =   0.000089
 y  force CY |   CYd01 =   0.000419   CYd02 =  -0.000002   CYd03 =  -0.002824
 x' mom.  Cl'|   Cld01 =  -0.004550   Cld02 =   0.000022   Cld03 =  -0.000512
 y  mom.  Cm |   Cmd01 =  -0.000049   Cmd02 =  -0.027294   Cmd03 =  -0.000231
 z' mom.  Cn'|   Cnd01 =   0.000208   Cnd02 =   0.000003   Cnd03 =   0.001434
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000524 CDffd03 =  -0.000175
 span eff.   |    ed01 =  -0.000169    ed02 =   0.041417    ed03 =   0.006175



 Neutral point  Xnp =   0.168324

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
