 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10030     Cltot =  -0.00123     Cl'tot =  -0.00173
  CYtot =  -0.01576     Cmtot =   0.08922
  CZtot =  -0.26706     Cntot =   0.00571     Cn'tot =   0.00558

  CLtot =   0.27479
  CDtot =   0.07664
  CDvis =   0.07000     CDind = 0.0066413
  CLff  =   0.27484     CDff  = 0.0073588    | Trefftz
  CYff  =  -0.01146         e =    0.4582    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.002369    CLb =  -0.039116
 y  force CY |    CYa =   0.000013    CYb =  -0.300166
 x' mom.  Cl'|    Cla =  -0.014408    Clb =  -0.032871
 y  mom.  Cm |    Cma =  -0.773414    Cmb =   0.008321
 z' mom.  Cn'|    Cna =   0.000236    Cnb =   0.106270

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011967    CLq =   8.125175    CLr =   0.012500
 y  force CY |    CYp =  -0.049682    CYq =   0.050136    CYr =   0.229629
 x' mom.  Cl'|    Clp =  -0.486513    Clq =  -0.003556    Clr =   0.133794
 y  mom.  Cm |    Cmp =   0.008114    Cmq = -16.217295    Cmr =  -0.018219
 z' mom.  Cn'|    Cnp =   0.013227    Cnq =  -0.025769    Cnr =  -0.110194

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000075   CLd02 =   0.007845   CLd03 =  -0.000053
 y  force CY |   CYd01 =   0.000404   CYd02 =   0.000001   CYd03 =  -0.002846
 x' mom.  Cl'|   Cld01 =  -0.004567   Cld02 =  -0.000013   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =   0.000029   Cmd02 =  -0.027586   Cmd03 =   0.000139
 z' mom.  Cn'|   Cnd01 =   0.000184   Cnd02 =  -0.000002   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =  -0.000003 CDffd02 =  -0.000434 CDffd03 =   0.000106
 span eff.   |    ed01 =   0.000185    ed02 =   0.053287    ed03 =  -0.006193



 Neutral point  Xnp =   0.170100

 Clb Cnr / Clr Cnb  =   0.254756    (  > 1 if spirally stable )
