 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00782     Cltot =   0.00336     Cl'tot =   0.00295
  CYtot =   0.01037     Cmtot =  -0.08788
  CZtot =  -1.22601     Cntot =  -0.00378     Cn'tot =  -0.00411

  CLtot =   1.21847
  CDtot =   0.13593
  CDvis =   0.07000     CDind = 0.0659332
  CLff  =   1.22625     CDff  = 0.0673348    | Trefftz
  CYff  =   0.00764         e =    0.9952    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.744616    CLb =   0.090018
 y  force CY |    CYa =  -0.001549    CYb =  -0.296634
 x' mom.  Cl'|    Cla =   0.008856    Clb =  -0.084317
 y  mom.  Cm |    Cma =  -1.046307    Cmb =  -0.017913
 z' mom.  Cn'|    Cna =  -0.003748    Cnb =   0.117453

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006098    CLq =   7.663293    CLr =  -0.007805
 y  force CY |    CYp =   0.127709    CYq =  -0.033432    CYr =   0.219675
 x' mom.  Cl'|    Clp =  -0.447801    Clq =   0.005606    Clr =   0.314397
 y  mom.  Cm |    Cmp =  -0.002993    Cmq = -16.648767    Cmr =   0.012959
 z' mom.  Cn'|    Cnp =  -0.069269    Cnq =   0.016415    Cnr =  -0.140161

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000047   CLd02 =   0.007884   CLd03 =   0.000030
 y  force CY |   CYd01 =   0.000213   CYd02 =  -0.000001   CYd03 =  -0.002816
 x' mom.  Cl'|   Cld01 =  -0.004333   Cld02 =   0.000009   Cld03 =  -0.000483
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028263   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =  -0.000084   Cnd02 =   0.000001   Cnd03 =   0.001431
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000601 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000030    ed02 =   0.003945    ed03 =   0.001012



 Neutral point  Xnp =   0.188688

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
