 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.09506     Cltot =  -0.00426     Cl'tot =  -0.00355
  CYtot =  -0.01024     Cmtot =  -0.16323
  CZtot =  -1.55019     Cntot =   0.00373     Cn'tot =   0.00441

  CLtot =   1.54314
  CDtot =   0.17557
  CDvis =   0.07000     CDind = 0.1055710
  CLff  =   1.56276     CDff  = 0.1083279    | Trefftz
  CYff  =  -0.00764         e =    1.0047    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.548311    CLb =  -0.111934
 y  force CY |    CYa =   0.002098    CYb =  -0.292991
 x' mom.  Cl'|    Cla =  -0.008248    Clb =  -0.101421
 y  mom.  Cm |    Cma =  -1.108766    Cmb =   0.023175
 z' mom.  Cn'|    Cna =   0.004944    Cnb =   0.126145

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005483    CLq =   7.447762    CLr =   0.007440
 y  force CY |    CYp =   0.189405    CYq =   0.033432    CYr =   0.199310
 x' mom.  Cl'|    Clp =  -0.426916    Clq =  -0.006738    Clr =   0.374111
 y  mom.  Cm |    Cmp =   0.002082    Cmq = -16.649604    Cmr =  -0.013136
 z' mom.  Cn'|    Cnp =  -0.102195    Cnq =  -0.015984    Cnr =  -0.152301

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000046   CLd02 =   0.007715   CLd03 =  -0.000028
 y  force CY |   CYd01 =   0.000145   CYd02 =   0.000001   CYd03 =  -0.002752
 x' mom.  Cl'|   Cld01 =  -0.004167   Cld02 =  -0.000009   Cld03 =  -0.000463
 y  mom.  Cm |   Cmd01 =   0.000018   Cmd02 =  -0.027979   Cmd03 =   0.000092
 z' mom.  Cn'|   Cnd01 =  -0.000173   Cnd02 =  -0.000001   Cnd03 =   0.001400
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000966 CDffd03 =   0.000070
 span eff.   |    ed01 =   0.000018    ed02 =   0.001114    ed03 =  -0.000629



 Neutral point  Xnp =   0.195245

 Clb Cnr / Clr Cnb  =   0.327311    (  > 1 if spirally stable )
