 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09382     Cltot =  -0.00199     Cl'tot =  -0.00199
  CYtot =  -0.01049     Cmtot =   0.01519
  CZtot =  -0.71023     Cntot =   0.00381     Cn'tot =   0.00381

  CLtot =   0.71023
  CDtot =   0.09382
  CDvis =   0.07000     CDind = 0.0238234
  CLff  =   0.71079     CDff  = 0.0245658    | Trefftz
  CYff  =  -0.00764         e =    0.9166    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.941800    CLb =  -0.055615
 y  force CY |    CYa =   0.000712    CYb =  -0.300024
 x' mom.  Cl'|    Cla =  -0.009442    Clb =  -0.056815
 y  mom.  Cm |    Cma =  -0.914924    Cmb =   0.010715
 z' mom.  Cn'|    Cna =   0.001825    Cnb =   0.109076

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.007100    CLq =   7.944090    CLr =   0.008184
 y  force CY |    CYp =   0.031364    CYq =   0.033432    CYr =   0.233674
 x' mom.  Cl'|    Clp =  -0.472804    Clq =  -0.003860    Clr =   0.218427
 y  mom.  Cm |    Cmp =   0.004331    Cmq = -16.495537    Cmr =  -0.012575
 z' mom.  Cn'|    Cnp =  -0.022919    Cnq =  -0.016912    Cnr =  -0.122895

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000049   CLd02 =   0.007960   CLd03 =  -0.000033
 y  force CY |   CYd01 =   0.000318   CYd02 =   0.000001   CYd03 =  -0.002860
 x' mom.  Cl'|   Cld01 =  -0.004505   Cld02 =  -0.000009   Cld03 =  -0.000505
 y  mom.  Cm |   Cmd01 =   0.000019   Cmd02 =  -0.028173   Cmd03 =   0.000093
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =  -0.000001   Cnd03 =   0.001453
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.000036 CDffd03 =   0.000071
 span eff.   |    ed01 =   0.000078    ed02 =   0.019114    ed03 =  -0.002563



 Neutral point  Xnp =   0.178709

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
