 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07450     Cltot =   0.00245     Cl'tot =   0.00231
  CYtot =   0.01046     Cmtot =  -0.01761
  CZtot =  -0.88500     Cntot =  -0.00381     Cn'tot =  -0.00389

  CLtot =   0.88186
  CDtot =   0.10534
  CDvis =   0.07000     CDind = 0.0353379
  CLff  =   0.88376     CDff  = 0.0362210    | Trefftz
  CYff  =   0.00764         e =    0.9610    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.889715    CLb =   0.067244
 y  force CY |    CYa =  -0.000993    CYb =  -0.299173
 x' mom.  Cl'|    Cla =   0.009291    Clb =  -0.066170
 y  mom.  Cm |    Cma =  -0.963483    Cmb =  -0.013005
 z' mom.  Cn'|    Cna =  -0.002479    Cnb =   0.111225

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006757    CLq =   7.856796    CLr =  -0.008081
 y  force CY |    CYp =   0.063779    CYq =  -0.033432    CYr =   0.231255
 x' mom.  Cl'|    Clp =  -0.465393    Clq =   0.004447    Clr =   0.251175
 y  mom.  Cm |    Cmp =  -0.003890    Cmq = -16.566818    Cmr =   0.012718
 z' mom.  Cn'|    Cnp =  -0.037982    Cnq =   0.016767    Cnr =  -0.128449

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000049   CLd02 =   0.007959   CLd03 =   0.000032
 y  force CY |   CYd01 =   0.000283   CYd02 =  -0.000001   CYd03 =  -0.002852
 x' mom.  Cl'|   Cld01 =  -0.004459   Cld02 =   0.000009   Cld03 =  -0.000499
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028272   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =   0.000001   Cnd03 =   0.001449
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000225 CDffd03 =  -0.000071
 span eff.   |    ed01 =  -0.000055    ed02 =   0.011270    ed03 =   0.001824



 Neutral point  Xnp =   0.182066

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
