 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06604     Cltot =   0.00404     Cl'tot =   0.00340
  CYtot =   0.01028     Cmtot =  -0.14399
  CZtot =  -1.47107     Cntot =  -0.00374     Cn'tot =  -0.00433

  CLtot =   1.46329
  CDtot =   0.16490
  CDvis =   0.07000     CDind = 0.0948968
  CLff  =   1.47928     CDff  = 0.0971939    | Trefftz
  CYff  =   0.00764         e =    1.0034    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.601920    CLb =   0.106549
 y  force CY |    CYa =  -0.001962    CYb =  -0.294004
 x' mom.  Cl'|    Cla =   0.008416    Clb =  -0.097262
 y  mom.  Cm |    Cma =  -1.095134    Cmb =  -0.021832
 z' mom.  Cn'|    Cna =  -0.004653    Cnb =   0.123749

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.005632    CLq =   7.503487    CLr =  -0.007539
 y  force CY |    CYp =   0.174257    CYq =  -0.033432    CYr =   0.205206
 x' mom.  Cl'|    Clp =  -0.432418    Clq =   0.006458    Clr =   0.359540
 y  mom.  Cm |    Cmp =  -0.002311    Cmq = -16.657006    Cmr =   0.013098
 z' mom.  Cn'|    Cnp =  -0.093806    Cnq =   0.016100    Cnr =  -0.149252

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000046   CLd02 =   0.007766   CLd03 =   0.000028
 y  force CY |   CYd01 =   0.000162   CYd02 =  -0.000001   CYd03 =  -0.002771
 x' mom.  Cl'|   Cld01 =  -0.004212   Cld02 =   0.000009   Cld03 =  -0.000469
 y  mom.  Cm |   Cmd01 =  -0.000018   Cmd02 =  -0.028075   Cmd03 =  -0.000092
 z' mom.  Cn'|   Cnd01 =  -0.000151   Cnd02 =   0.000001   Cnd03 =   0.001409
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000876 CDffd03 =  -0.000070
 span eff.   |    ed01 =  -0.000021    ed02 =   0.001611    ed03 =   0.000702



 Neutral point  Xnp =   0.193608

 Clb Cnr / Clr Cnb  =   0.326266    (  > 1 if spirally stable )
