 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  12.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.15959     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.20280
  CZtot =  -1.70616     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.70206
  CDtot =   0.19863
  CDvis =   0.07000     CDind = 0.1286335
  CLff  =   1.72932     CDff  = 0.1323525    | Trefftz
  CYff  =   0.00000         e =    1.0069    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.437776    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.291342
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.109744
 y  mom.  Cm |    Cma =  -1.133342    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.131685

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.337502    CLr =  -0.000000
 y  force CY |    CYp =   0.219171    CYq =  -0.000000    CYr =   0.186064
 x' mom.  Cl'|    Clp =  -0.415659    Clq =  -0.000000    Clr =   0.402744
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.629719    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.119358    Cnq =   0.000000    Cnr =  -0.158475

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007606   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000111   CYd02 =   0.000000   CYd03 =  -0.002714
 x' mom.  Cl'|   Cld01 =  -0.004075   Cld02 =   0.000000   Cld03 =  -0.000452
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027768   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000214   Cnd02 =  -0.000000   Cnd03 =   0.001381
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.001144 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.000371    ed03 =   0.000000



 Neutral point  Xnp =   0.198519

 Clb Cnr / Clr Cnb  =   0.327926    (  > 1 if spirally stable )
