 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08534     Cltot =   0.00222     Cl'tot =   0.00215
  CYtot =   0.01047     Cmtot =  -0.00100
  CZtot =  -0.79788     Cntot =  -0.00381     Cn'tot =  -0.00385

  CLtot =   0.79627
  CDtot =   0.09925
  CDvis =   0.07000     CDind = 0.0292526
  CLff  =   0.79740     CDff  = 0.0300615    | Trefftz
  CYff  =   0.00764         e =    0.9427    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.917504    CLb =   0.061446
 y  force CY |    CYa =  -0.000853    CYb =  -0.299633
 x' mom.  Cl'|    Cla =   0.009372    Clb =  -0.061511
 y  mom.  Cm |    Cma =  -0.939776    Cmb =  -0.011845
 z' mom.  Cn'|    Cna =  -0.002153    Cnb =   0.110069

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.006928    CLq =   7.901277    CLr =  -0.008136
 y  force CY |    CYp =   0.047592    CYq =  -0.033432    CYr =   0.232748
 x' mom.  Cl'|    Clp =  -0.469220    Clq =   0.004154    Clr =   0.234888
 y  mom.  Cm |    Cmp =  -0.004111    Cmq = -16.533696    Cmr =   0.012648
 z' mom.  Cn'|    Cnp =  -0.030404    Cnq =   0.016842    Cnr =  -0.125641

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000049   CLd02 =   0.007962   CLd03 =   0.000033
 y  force CY |   CYd01 =   0.000301   CYd02 =  -0.000001   CYd03 =  -0.002857
 x' mom.  Cl'|   Cld01 =  -0.004483   Cld02 =   0.000009   Cld03 =  -0.000502
 y  mom.  Cm |   Cmd01 =  -0.000019   Cmd02 =  -0.028231   Cmd03 =  -0.000093
 z' mom.  Cn'|   Cnd01 =   0.000035   Cnd02 =   0.000001   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =   0.000002 CDffd02 =   0.000131 CDffd03 =  -0.000071
 span eff.   |    ed01 =  -0.000066    ed02 =   0.014657    ed03 =   0.002155



 Neutral point  Xnp =   0.180393

 Clb Cnr / Clr Cnb  =   0.298923    (  > 1 if spirally stable )
