 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10302     Cltot =   0.00304     Cl'tot =   0.00330
  CYtot =   0.02097     Cmtot =   0.04666
  CZtot =  -0.53146     Cntot =  -0.00762     Cn'tot =  -0.00750

  CLtot =   0.53473
  CDtot =   0.08440
  CDvis =   0.07000     CDind = 0.0144048
  CLff  =   0.53598     CDff  = 0.0158218    | Trefftz
  CYff  =   0.01527         e =    0.8098    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.962098    CLb =   0.087523
 y  force CY |    CYa =  -0.000860    CYb =  -0.298780
 x' mom.  Cl'|    Cla =   0.019046    Clb =  -0.046986
 y  mom.  Cm |    Cma =  -0.858759    Cmb =  -0.017054
 z' mom.  Cn'|    Cna =  -0.002318    Cnb =   0.106797

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.014888    CLq =   8.009834    CLr =  -0.016516
 y  force CY |    CYp =  -0.001139    CYq =  -0.066824    CYr =   0.233398
 x' mom.  Cl'|    Clp =  -0.478345    Clq =   0.006530    Clr =   0.184688
 y  mom.  Cm |    Cmp =  -0.009529    Cmq = -16.374173    Cmr =   0.024817
 z' mom.  Cn'|    Cnp =  -0.008198    Cnq =   0.034051    Cnr =  -0.117393

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000099   CLd02 =   0.007908   CLd03 =   0.000068
 y  force CY |   CYd01 =   0.000352   CYd02 =  -0.000001   CYd03 =  -0.002851
 x' mom.  Cl'|   Cld01 =  -0.004525   Cld02 =   0.000018   Cld03 =  -0.000508
 y  mom.  Cm |   Cmd01 =  -0.000039   Cmd02 =  -0.027904   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =   0.000108   Cnd02 =   0.000002   Cnd03 =   0.001448
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =  -0.000153 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000214    ed02 =   0.031695    ed03 =   0.006981



 Neutral point  Xnp =   0.175304

 Clb Cnr / Clr Cnb  =   0.279649    (  > 1 if spirally stable )
