 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06336     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.13870
  CZtot =   0.08528     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =  -0.07432
  CDtot =   0.07592
  CDvis =   0.07000     CDind = 0.0059163
  CLff  =  -0.07525     CDff  = 0.0057198    | Trefftz
  CYff  =  -0.00000         e =    0.0441    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.005171    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.300983
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.013847
 y  mom.  Cm |    Cma =  -0.645942    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.107882

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.251444    CLr =   0.000000
 y  force CY |    CYp =  -0.113402    CYq =   0.000000    CYr =   0.216725
 x' mom.  Cl'|    Clp =  -0.493549    Clq =   0.000000    Clr =   0.064322
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -15.937602    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =   0.040905    Cnq =  -0.000000    Cnr =  -0.101874

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007679   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000471   CYd02 =   0.000000   CYd03 =  -0.002814
 x' mom.  Cl'|   Cld01 =  -0.004583   Cld02 =   0.000000   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.026928   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000285   Cnd02 =  -0.000000   Cnd03 =   0.001428
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000802 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =  -0.002974    ed03 =  -0.000000



 Neutral point  Xnp =   0.162893

 Clb Cnr / Clr Cnb  =   0.203280    (  > 1 if spirally stable )
