 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09274     Cltot =   0.00494     Cl'tot =   0.00494
  CYtot =   0.02612     Cmtot =   0.01617
  CZtot =  -0.70514     Cntot =  -0.00949     Cn'tot =  -0.00949

  CLtot =   0.70514
  CDtot =   0.09274
  CDvis =   0.07000     CDind = 0.0227440
  CLff  =   0.70852     CDff  = 0.0249105    | Trefftz
  CYff  =   0.01908         e =    0.8987    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.911169    CLb =   0.138445
 y  force CY |    CYa =  -0.001773    CYb =  -0.296858
 x' mom.  Cl'|    Cla =   0.023504    Clb =  -0.056088
 y  mom.  Cm |    Cma =  -0.909081    Cmb =  -0.026672
 z' mom.  Cn'|    Cna =  -0.004543    Cnb =   0.107681

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.017730    CLq =   7.918684    CLr =  -0.020439
 y  force CY |    CYp =   0.031263    CYq =  -0.083492    CYr =   0.232927
 x' mom.  Cl'|    Clp =  -0.471292    Clq =   0.009639    Clr =   0.217728
 y  mom.  Cm |    Cmp =  -0.010817    Cmq = -16.442783    Cmr =   0.031403
 z' mom.  Cn'|    Cnp =  -0.022846    Cnq =   0.042234    Cnr =  -0.122502

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000122   CLd02 =   0.007909   CLd03 =   0.000083
 y  force CY |   CYd01 =   0.000316   CYd02 =  -0.000002   CYd03 =  -0.002842
 x' mom.  Cl'|   Cld01 =  -0.004477   Cld02 =   0.000023   Cld03 =  -0.000502
 y  mom.  Cm |   Cmd01 =  -0.000048   Cmd02 =  -0.027993   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =   0.000059   Cnd02 =   0.000003   Cnd03 =   0.001444
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =   0.000036 CDffd03 =  -0.000176
 span eff.   |    ed01 =  -0.000188    ed02 =   0.018755    ed03 =   0.006164



 Neutral point  Xnp =   0.178700

 Clb Cnr / Clr Cnb  =   0.293061    (  > 1 if spirally stable )
