 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00790     Cltot =   0.00168     Cl'tot =   0.00147
  CYtot =   0.00519     Cmtot =  -0.08811
  CZtot =  -1.22720     Cntot =  -0.00189     Cn'tot =  -0.00205

  CLtot =   1.21965
  CDtot =   0.13613
  CDvis =   0.07000     CDind = 0.0661338
  CLff  =   1.22681     CDff  = 0.0673246    | Trefftz
  CYff  =   0.00382         e =    0.9962    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.748815    CLb =   0.045037
 y  force CY |    CYa =  -0.000775    CYb =  -0.297081
 x' mom.  Cl'|    Cla =   0.004431    Clb =  -0.084472
 y  mom.  Cm |    Cma =  -1.047264    Cmb =  -0.008962
 z' mom.  Cn'|    Cna =  -0.001875    Cnb =   0.117668

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003049    CLq =   7.666797    CLr =  -0.003903
 y  force CY |    CYp =   0.127767    CYq =  -0.016719    CYr =   0.219775
 x' mom.  Cl'|    Clp =  -0.448006    Clq =   0.002804    Clr =   0.314541
 y  mom.  Cm |    Cmp =  -0.001497    Cmq = -16.656378    Cmr =   0.006480
 z' mom.  Cn'|    Cnp =  -0.069300    Cnq =   0.008209    Cnr =  -0.140225

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007891   CLd03 =   0.000015
 y  force CY |   CYd01 =   0.000213   CYd02 =  -0.000000   CYd03 =  -0.002818
 x' mom.  Cl'|   Cld01 =  -0.004337   Cld02 =   0.000005   Cld03 =  -0.000484
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.028289   Cmd03 =  -0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000084   Cnd02 =   0.000001   Cnd03 =   0.001433
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000601 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000015    ed02 =   0.003940    ed03 =   0.000507



 Neutral point  Xnp =   0.188690

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
