 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07468     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.01783
  CZtot =  -0.88618     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.88304
  CDtot =   0.10556
  CDvis =   0.07000     CDind = 0.0355616
  CLff  =   0.88430     CDff  = 0.0361694    | Trefftz
  CYff  =   0.00000         e =    0.9635    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.895497    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.299775
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.066331
 y  mom.  Cm |    Cma =  -0.964658    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.111497

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.861585    CLr =   0.000000
 y  force CY |    CYp =   0.063818    CYq =   0.000000    CYr =   0.231396
 x' mom.  Cl'|    Clp =  -0.465677    Clq =  -0.000000    Clr =   0.251328
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.576917    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.038005    Cnq =  -0.000000    Cnr =  -0.128527

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007968   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000284   CYd02 =   0.000000   CYd03 =  -0.002856
 x' mom.  Cl'|   Cld01 =  -0.004464   Cld02 =   0.000000   Cld03 =  -0.000500
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028307   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =  -0.000000   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000225 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.011284    ed03 =   0.000000



 Neutral point  Xnp =   0.182068

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
