 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  11.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   2.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.12622     Cltot =  -0.00448     Cl'tot =  -0.00369
  CYtot =  -0.01020     Cmtot =  -0.18269
  CZtot =  -1.62786     Cntot =   0.00371     Cn'tot =   0.00450

  CLtot =   1.62204
  CDtot =   0.18671
  CDvis =   0.07000     CDind = 0.1167093
  CLff  =   1.64577     CDff  = 0.1200303    | Trefftz
  CYff  =  -0.00764         e =    1.0056    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.491827    CLb =  -0.117251
 y  force CY |    CYa =   0.002234    CYb =  -0.291909
 x' mom.  Cl'|    Cla =  -0.008071    Clb =  -0.105495
 y  mom.  Cm |    Cma =  -1.121047    Cmb =   0.024535
 z' mom.  Cn'|    Cna =   0.005229    Cnb =   0.128685

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.005338    CLq =   7.390920    CLr =   0.007335
 y  force CY |    CYp =   0.204338    CYq =   0.033432    CYr =   0.192889
 x' mom.  Cl'|    Clp =  -0.421243    Clq =  -0.007016    Clr =   0.388433
 y  mom.  Cm |    Cmp =   0.001852    Cmq = -16.637130    Cmr =  -0.013170
 z' mom.  Cn'|    Cnp =  -0.110688    Cnq =  -0.015864    Cnr =  -0.155346

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000045   CLd02 =   0.007659   CLd03 =  -0.000027
 y  force CY |   CYd01 =   0.000128   CYd02 =   0.000001   CYd03 =  -0.002732
 x' mom.  Cl'|   Cld01 =  -0.004120   Cld02 =  -0.000009   Cld03 =  -0.000458
 y  mom.  Cm |   Cmd01 =   0.000018   Cmd02 =  -0.027865   Cmd03 =   0.000092
 z' mom.  Cn'|   Cnd01 =  -0.000194   Cnd02 =  -0.000001   Cnd03 =   0.001390
 Trefftz drag| CDffd01 =  -0.000002 CDffd02 =   0.001055 CDffd03 =   0.000069
 span eff.   |    ed01 =   0.000016    ed02 =   0.000709    ed03 =  -0.000566



 Neutral point  Xnp =   0.196880

 Clb Cnr / Clr Cnb  =   0.327859    (  > 1 if spirally stable )
