 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07621     Cltot =  -0.00006     Cl'tot =  -0.00033
  CYtot =  -0.00526     Cmtot =   0.12714
  CZtot =  -0.00249     Cntot =   0.00190     Cn'tot =   0.00187

  CLtot =   0.01308
  CDtot =   0.07512
  CDvis =   0.07000     CDind = 0.0051180
  CLff  =   0.01240     CDff  = 0.0050608    | Trefftz
  CYff  =  -0.00382         e =    0.0015    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.011733    CLb =  -0.004137
 y  force CY |    CYa =  -0.000207    CYb =  -0.301074
 x' mom.  Cl'|    Cla =  -0.004792    Clb =  -0.018620
 y  mom.  Cm |    Cma =  -0.679416    Cmb =   0.001447
 z' mom.  Cn'|    Cna =  -0.000424    Cnb =   0.107309

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.004259    CLq =   8.224466    CLr =   0.004176
 y  force CY |    CYp =  -0.097657    CYq =   0.016719    CYr =   0.220827
 x' mom.  Cl'|    Clp =  -0.492306    Clq =  -0.000734    Clr =   0.081841
 y  mom.  Cm |    Cmp =   0.003020    Cmq = -16.017992    Cmr =  -0.005926
 z' mom.  Cn'|    Cnp =   0.034074    Cnq =  -0.008643    Cnr =  -0.103824

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000025   CLd02 =   0.007732   CLd03 =  -0.000018
 y  force CY |   CYd01 =   0.000455   CYd02 =   0.000000   CYd03 =  -0.002825
 x' mom.  Cl'|   Cld01 =  -0.004585   Cld02 =  -0.000004   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =   0.000010   Cmd02 =  -0.027127   Cmd03 =   0.000046
 z' mom.  Cn'|   Cnd01 =   0.000259   Cnd02 =  -0.000001   Cnd03 =   0.001434
 Trefftz drag| CDffd01 =  -0.000001 CDffd02 =  -0.000712 CDffd03 =   0.000035
 span eff.   |    ed01 =  -0.000014    ed02 =   0.001920    ed03 =   0.000174



 Neutral point  Xnp =   0.164729

 Clb Cnr / Clr Cnb  =   0.220128    (  > 1 if spirally stable )
