 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08475     Cltot =   0.00442     Cl'tot =   0.00429
  CYtot =   0.02090     Cmtot =  -0.00038
  CZtot =  -0.79466     Cntot =  -0.00760     Cn'tot =  -0.00768

  CLtot =   0.79306
  CDtot =   0.09861
  CDvis =   0.07000     CDind = 0.0286100
  CLff  =   0.79594     CDff  = 0.0302385    | Trefftz
  CYff  =   0.01527         e =    0.9340    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.900079    CLb =   0.122593
 y  force CY |    CYa =  -0.001701    CYb =  -0.297825
 x' mom.  Cl'|    Cla =   0.018699    Clb =  -0.061061
 y  mom.  Cm |    Cma =  -0.936344    Cmb =  -0.023632
 z' mom.  Cn'|    Cna =  -0.004296    Cnb =   0.109264

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.013847    CLq =   7.886834    CLr =  -0.016262
 y  force CY |    CYp =   0.047505    CYq =  -0.066824    CYr =   0.232322
 x' mom.  Cl'|    Clp =  -0.468362    Clq =   0.008303    Clr =   0.234458
 y  mom.  Cm |    Cmp =  -0.008217    Cmq = -16.503474    Cmr =   0.025281
 z' mom.  Cn'|    Cnp =  -0.030349    Cnq =   0.033663    Cnr =  -0.125412

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000098   CLd02 =   0.007933   CLd03 =   0.000065
 y  force CY |   CYd01 =   0.000300   CYd02 =  -0.000001   CYd03 =  -0.002847
 x' mom.  Cl'|   Cld01 =  -0.004467   Cld02 =   0.000018   Cld03 =  -0.000500
 y  mom.  Cm |   Cmd01 =  -0.000038   Cmd02 =  -0.028128   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =   0.000035   Cnd02 =   0.000002   Cnd03 =   0.001446
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000130 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000129    ed02 =   0.014555    ed03 =   0.004234



 Neutral point  Xnp =   0.180387

 Clb Cnr / Clr Cnb  =   0.298923    (  > 1 if spirally stable )
