 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -7.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08556     Cltot =   0.00089     Cl'tot =   0.00203
  CYtot =   0.02619     Cmtot =   0.11539
  CZtot =  -0.08934     Cntot =  -0.00947     Cn'tot =  -0.00929

  CLtot =   0.09910
  CDtot =   0.07404
  CDvis =   0.07000     CDind = 0.0040375
  CLff  =   0.09967     CDff  = 0.0056102    | Trefftz
  CYff  =   0.01908         e =    0.0818    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.980573    CLb =   0.035386
 y  force CY |    CYa =   0.000680    CYb =  -0.297616
 x' mom.  Cl'|    Cla =   0.023905    Clb =  -0.023075
 y  mom.  Cm |    Cma =  -0.707064    Cmb =  -0.009311
 z' mom.  Cn'|    Cna =   0.001278    Cnb =   0.105408

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.020822    CLq =   8.166739    CLr =  -0.020859
 y  force CY |    CYp =  -0.081496    CYq =  -0.083492    CYr =   0.223592
 x' mom.  Cl'|    Clp =  -0.489060    Clq =   0.004420    Clr =   0.098937
 y  mom.  Cm |    Cmp =  -0.014563    Cmq = -16.037124    Cmr =   0.029851
 z' mom.  Cn'|    Cnp =   0.027094    Cnq =   0.043094    Cnr =  -0.105506

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000124   CLd02 =   0.007725   CLd03 =   0.000089
 y  force CY |   CYd01 =   0.000435   CYd02 =  -0.000002   CYd03 =  -0.002815
 x' mom.  Cl'|   Cld01 =  -0.004552   Cld02 =   0.000022   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =  -0.000049   Cmd02 =  -0.027119   Cmd03 =  -0.000231
 z' mom.  Cn'|   Cnd01 =   0.000233   Cnd02 =   0.000003   Cnd03 =   0.001429
 Trefftz drag| CDffd01 =   0.000006 CDffd02 =  -0.000616 CDffd03 =  -0.000175
 span eff.   |    ed01 =  -0.000019    ed02 =   0.021377    ed03 =   0.001718



 Neutral point  Xnp =   0.166534

 Clb Cnr / Clr Cnb  =   0.233452    (  > 1 if spirally stable )
