 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   2.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.07463     Cltot =   0.00122     Cl'tot =   0.00116
  CYtot =   0.00523     Cmtot =  -0.01778
  CZtot =  -0.88589     Cntot =  -0.00190     Cn'tot =  -0.00195

  CLtot =   0.88274
  CDtot =   0.10551
  CDvis =   0.07000     CDind = 0.0355057
  CLff  =   0.88416     CDff  = 0.0361823    | Trefftz
  CYff  =   0.00382         e =    0.9628    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.894051    CLb =   0.033643
 y  force CY |    CYa =  -0.000497    CYb =  -0.299624
 x' mom.  Cl'|    Cla =   0.004649    Clb =  -0.066291
 y  mom.  Cm |    Cma =  -0.964365    Cmb =  -0.006507
 z' mom.  Cn'|    Cna =  -0.001240    Cnb =   0.111429

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.003379    CLq =   7.860387    CLr =  -0.004041
 y  force CY |    CYp =   0.063808    CYq =  -0.016719    CYr =   0.231361
 x' mom.  Cl'|    Clp =  -0.465606    Clq =   0.002224    Clr =   0.251290
 y  mom.  Cm |    Cmp =  -0.001945    Cmq = -16.574392    Cmr =   0.006360
 z' mom.  Cn'|    Cnp =  -0.038000    Cnq =   0.008385    Cnr =  -0.128508

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000024   CLd02 =   0.007966   CLd03 =   0.000016
 y  force CY |   CYd01 =   0.000283   CYd02 =  -0.000000   CYd03 =  -0.002855
 x' mom.  Cl'|   Cld01 =  -0.004463   Cld02 =   0.000005   Cld03 =  -0.000499
 y  mom.  Cm |   Cmd01 =  -0.000010   Cmd02 =  -0.028298   Cmd03 =  -0.000047
 z' mom.  Cn'|   Cnd01 =   0.000010   Cnd02 =   0.000001   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000225 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000028    ed02 =   0.011281    ed03 =   0.000915



 Neutral point  Xnp =   0.182068

 Clb Cnr / Clr Cnb  =   0.304235    (  > 1 if spirally stable )
