 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   8.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -1.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.03917     Cltot =   0.00191     Cl'tot =   0.00163
  CYtot =   0.00516     Cmtot =  -0.12527
  CZtot =  -1.39194     Cntot =  -0.00188     Cn'tot =  -0.00213

  CLtot =   1.38385
  CDtot =   0.15493
  CDvis =   0.07000     CDind = 0.0849348
  CLff  =   1.39599     CDff  = 0.0866494    | Trefftz
  CYff  =   0.00382         e =    1.0023    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.656677    CLb =   0.050580
 y  force CY |    CYa =  -0.000913    CYb =  -0.295393
 x' mom.  Cl'|    Cla =   0.004289    Clb =  -0.093191
 y  mom.  Cm |    Cma =  -1.081155    Cmb =  -0.010259
 z' mom.  Cn'|    Cna =  -0.002180    Cnb =   0.121723

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.002892    CLq =   7.561483    CLr =  -0.003817
 y  force CY |    CYp =   0.158985    CYq =  -0.016719    CYr =   0.210666
 x' mom.  Cl'|    Clp =  -0.437938    Clq =   0.003088    Clr =   0.344883
 y  mom.  Cm |    Cmp =  -0.001270    Cmq = -16.666949    Cmr =   0.006529
 z' mom.  Cn'|    Cnp =  -0.085562    Cnq =   0.008106    Cnr =  -0.146274

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000023   CLd02 =   0.007818   CLd03 =   0.000014
 y  force CY |   CYd01 =   0.000179   CYd02 =  -0.000000   CYd03 =  -0.002790
 x' mom.  Cl'|   Cld01 =  -0.004259   Cld02 =   0.000004   Cld03 =  -0.000474
 y  mom.  Cm |   Cmd01 =  -0.000009   Cmd02 =  -0.028181   Cmd03 =  -0.000046
 z' mom.  Cn'|   Cnd01 =  -0.000129   Cnd02 =   0.000001   Cnd03 =   0.001418
 Trefftz drag| CDffd01 =   0.000001 CDffd02 =   0.000786 CDffd03 =  -0.000035
 span eff.   |    ed01 =  -0.000012    ed02 =   0.002220    ed03 =   0.000395



 Neutral point  Xnp =   0.191973

 Clb Cnr / Clr Cnb  =   0.324713    (  > 1 if spirally stable )
