 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   1.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.08510     Cltot =   0.00332     Cl'tot =   0.00322
  CYtot =   0.01570     Cmtot =  -0.00074
  CZtot =  -0.79654     Cntot =  -0.00571     Cn'tot =  -0.00577

  CLtot =   0.79493
  CDtot =   0.09898
  CDvis =   0.07000     CDind = 0.0289847
  CLff  =   0.79679     CDff  = 0.0301353    | Trefftz
  CYff  =   0.01146         e =    0.9390    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.910238    CLb =   0.092076
 y  force CY |    CYa =  -0.001278    CYb =  -0.298879
 x' mom.  Cl'|    Cla =   0.014044    Clb =  -0.061323
 y  mom.  Cm |    Cma =  -0.938345    Cmb =  -0.017750
 z' mom.  Cn'|    Cna =  -0.003227    Cnb =   0.109733

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.010389    CLq =   7.895258    CLr =  -0.012201
 y  force CY |    CYp =   0.047556    CYq =  -0.050136    CYr =   0.232570
 x' mom.  Cl'|    Clp =  -0.468863    Clq =   0.006230    Clr =   0.234709
 y  mom.  Cm |    Cmp =  -0.006165    Cmq = -16.521101    Cmr =   0.018968
 z' mom.  Cn'|    Cnp =  -0.030381    Cnq =   0.025256    Cnr =  -0.125545

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000073   CLd02 =   0.007950   CLd03 =   0.000049
 y  force CY |   CYd01 =   0.000300   CYd02 =  -0.000001   CYd03 =  -0.002853
 x' mom.  Cl'|   Cld01 =  -0.004477   Cld02 =   0.000014   Cld03 =  -0.000501
 y  mom.  Cm |   Cmd01 =  -0.000029   Cmd02 =  -0.028188   Cmd03 =  -0.000140
 z' mom.  Cn'|   Cnd01 =   0.000035   Cnd02 =   0.000002   Cnd03 =   0.001449
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000130 CDffd03 =  -0.000106
 span eff.   |    ed01 =  -0.000098    ed02 =   0.014614    ed03 =   0.003209



 Neutral point  Xnp =   0.180390

 Clb Cnr / Clr Cnb  =   0.298923    (  > 1 if spirally stable )
