 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00793     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =   0.00000     Cmtot =  -0.08819
  CZtot =  -1.22760     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   1.22005
  CDtot =   0.13620
  CDvis =   0.07000     CDind = 0.0662007
  CLff  =   1.22699     CDff  = 0.0673212    | Trefftz
  CYff  =   0.00000         e =    0.9966    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.750215    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.297230
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.084523
 y  mom.  Cm |    Cma =  -1.047583    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.117740

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.667965    CLr =   0.000000
 y  force CY |    CYp =   0.127787    CYq =   0.000000    CYr =   0.219809
 x' mom.  Cl'|    Clp =  -0.448074    Clq =  -0.000000    Clr =   0.314589
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.658915    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.069311    Cnq =  -0.000000    Cnr =  -0.140247

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007894   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000214   CYd02 =   0.000000   CYd03 =  -0.002819
 x' mom.  Cl'|   Cld01 =  -0.004339   Cld02 =   0.000000   Cld03 =  -0.000484
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028298   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000084   Cnd02 =  -0.000000   Cnd03 =   0.001433
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000601 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.003938    ed03 =   0.000000



 Neutral point  Xnp =   0.188691

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
