 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -3.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.00770     Cltot =   0.00504     Cl'tot =   0.00442
  CYtot =   0.01554     Cmtot =  -0.08749
  CZtot =  -1.22402     Cntot =  -0.00566     Cn'tot =  -0.00615

  CLtot =   1.21651
  CDtot =   0.13560
  CDvis =   0.07000     CDind = 0.0655992
  CLff  =   1.22531     CDff  = 0.0673519    | Trefftz
  CYff  =   0.01146         e =    0.9935    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.737624    CLb =   0.134891
 y  force CY |    CYa =  -0.002321    CYb =  -0.295889
 x' mom.  Cl'|    Cla =   0.013270    Clb =  -0.084060
 y  mom.  Cm |    Cma =  -1.044714    Cmb =  -0.026842
 z' mom.  Cn'|    Cna =  -0.005617    Cnb =   0.117095

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.009144    CLq =   7.657456    CLr =  -0.011705
 y  force CY |    CYp =   0.127611    CYq =  -0.050136    CYr =   0.219508
 x' mom.  Cl'|    Clp =  -0.447460    Clq =   0.008407    Clr =   0.314158
 y  mom.  Cm |    Cmp =  -0.004489    Cmq = -16.636084    Cmr =   0.019433
 z' mom.  Cn'|    Cnp =  -0.069216    Cnq =   0.024617    Cnr =  -0.140054

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000071   CLd02 =   0.007872   CLd03 =   0.000045
 y  force CY |   CYd01 =   0.000213   CYd02 =  -0.000001   CYd03 =  -0.002812
 x' mom.  Cl'|   Cld01 =  -0.004327   Cld02 =   0.000014   Cld03 =  -0.000483
 y  mom.  Cm |   Cmd01 =  -0.000028   Cmd02 =  -0.028220   Cmd03 =  -0.000139
 z' mom.  Cn'|   Cnd01 =  -0.000084   Cnd02 =   0.000002   Cnd03 =   0.001429
 Trefftz drag| CDffd01 =   0.000003 CDffd02 =   0.000600 CDffd03 =  -0.000105
 span eff.   |    ed01 =  -0.000045    ed02 =   0.003953    ed03 =   0.001513



 Neutral point  Xnp =   0.188685

 Clb Cnr / Clr Cnb  =   0.320038    (  > 1 if spirally stable )
