 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   9.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.06608     Cltot =  -0.00805     Cl'tot =  -0.00678
  CYtot =  -0.02051     Cmtot =  -0.14285
  CZtot =  -1.46542     Cntot =   0.00746     Cn'tot =   0.00863

  CLtot =   1.45771
  CDtot =   0.16398
  CDvis =   0.07000     CDind = 0.0939771
  CLff  =   1.47658     CDff  = 0.0971258    | Trefftz
  CYff  =  -0.01527         e =    1.0005    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.585685    CLb =  -0.212579
 y  force CY |    CYa =   0.003914    CYb =  -0.292238
 x' mom.  Cl'|    Cla =  -0.016790    Clb =  -0.096550
 y  mom.  Cm |    Cma =  -1.091134    Cmb =   0.043558
 z' mom.  Cn'|    Cna =   0.009284    Cnb =   0.122844

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.011257    CLq =   7.489772    CLr =   0.015069
 y  force CY |    CYp =   0.173939    CYq =   0.066824    CYr =   0.204831
 x' mom.  Cl'|    Clp =  -0.431627    Clq =  -0.012907    Clr =   0.358882
 y  mom.  Cm |    Cmp =   0.004619    Cmq = -16.626558    Cmr =  -0.026179
 z' mom.  Cn'|    Cnp =  -0.093635    Cnq =  -0.032179    Cnr =  -0.148979

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000092   CLd02 =   0.007738   CLd03 =  -0.000057
 y  force CY |   CYd01 =   0.000161   CYd02 =   0.000001   CYd03 =  -0.002760
 x' mom.  Cl'|   Cld01 =  -0.004197   Cld02 =  -0.000018   Cld03 =  -0.000467
 y  mom.  Cm |   Cmd01 =   0.000036   Cmd02 =  -0.027973   Cmd03 =   0.000184
 z' mom.  Cn'|   Cnd01 =  -0.000150   Cnd02 =  -0.000002   Cnd03 =   0.001404
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000873 CDffd03 =   0.000139
 span eff.   |    ed01 =   0.000041    ed02 =   0.001632    ed03 =  -0.001398



 Neutral point  Xnp =   0.193600

 Clb Cnr / Clr Cnb  =   0.326266    (  > 1 if spirally stable )
