 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06081     Cltot =  -0.00534     Cl'tot =  -0.00494
  CYtot =  -0.02084     Cmtot =  -0.03388
  CZtot =  -0.96763     Cntot =   0.00758     Cn'tot =   0.00785

  CLtot =   0.96312
  CDtot =   0.11137
  CDvis =   0.07000     CDind = 0.0413657
  CLff  =   0.96808     CDff  = 0.0431664    | Trefftz
  CYff  =  -0.01527         e =    0.9677    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.841279    CLb =  -0.145654
 y  force CY |    CYa =   0.002259    CYb =  -0.296842
 x' mom.  Cl'|    Cla =  -0.018354    Clb =  -0.070268
 y  mom.  Cm |    Cma =  -0.982416    Cmb =   0.028318
 z' mom.  Cn'|    Cna =   0.005590    Cnb =   0.111721

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.013170    CLq =   7.796422    CLr =   0.016032
 y  force CY |    CYp =   0.079757    CYq =   0.066824    CYr =   0.228780
 x' mom.  Cl'|    Clp =  -0.460488    Clq =  -0.009473    Clr =   0.266791
 y  mom.  Cm |    Cmp =   0.007330    Cmq = -16.564561    Cmr =  -0.025553
 z' mom.  Cn'|    Cnp =  -0.045572    Cnq =  -0.033352    Cnr =  -0.131072

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000097   CLd02 =   0.007920   CLd03 =  -0.000063
 y  force CY |   CYd01 =   0.000265   CYd02 =   0.000001   CYd03 =  -0.002835
 x' mom.  Cl'|   Cld01 =  -0.004415   Cld02 =  -0.000018   Cld03 =  -0.000494
 y  mom.  Cm |   Cmd01 =   0.000038   Cmd02 =  -0.028192   Cmd03 =   0.000186
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =  -0.000002   Cnd03 =   0.001441
 Trefftz drag| CDffd01 =  -0.000004 CDffd02 =   0.000318 CDffd03 =   0.000141
 span eff.   |    ed01 =   0.000093    ed02 =   0.008674    ed03 =  -0.003073



 Neutral point  Xnp =   0.183725

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
