 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.10420     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.07520
  CZtot =  -0.35690     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.36330
  CDtot =   0.07905
  CDvis =   0.07000     CDind = 0.0090534
  CLff  =   0.36270     CDff  = 0.0092585    | Trefftz
  CYff  =  -0.00000         e =    0.6332    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.009327    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.301491
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.037861
 y  mom.  Cm |    Cma =  -0.805672    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.107018

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.102576    CLr =   0.000000
 y  force CY |    CYp =  -0.033598    CYq =   0.000000    CYr =   0.231851
 x' mom.  Cl'|    Clp =  -0.484894    Clq =   0.000000    Clr =   0.151154
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.302725    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.006167    Cnq =  -0.000000    Cnr =  -0.112704

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007899   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000388   CYd02 =   0.000000   CYd03 =  -0.002859
 x' mom.  Cl'|   Cld01 =  -0.004571   Cld02 =   0.000000   Cld03 =  -0.000514
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027805   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000159   Cnd02 =  -0.000000   Cnd03 =   0.001451
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000342 CDffd03 =  -0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.050996    ed03 =   0.000000



 Neutral point  Xnp =   0.171855

 Clb Cnr / Clr Cnb  =   0.263788    (  > 1 if spirally stable )
