 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   4.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04501     Cltot =   0.00723     Cl'tot =   0.00656
  CYtot =   0.02595     Cmtot =  -0.05061
  CZtot =  -1.04993     Cntot =  -0.00944     Cn'tot =  -0.00992

  CLtot =   1.04424
  CDtot =   0.11814
  CDvis =   0.07000     CDind = 0.0481404
  CLff  =   1.05227     CDff  = 0.0506795    | Trefftz
  CYff  =   0.01908         e =    0.9740    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.794002    CLb =   0.195969
 y  force CY |    CYa =  -0.003166    CYb =  -0.294902
 x' mom.  Cl'|    Cla =   0.022643    Clb =  -0.074389
 y  mom.  Cm |    Cma =  -1.000916    Cmb =  -0.038357
 z' mom.  Cn'|    Cna =  -0.007770    Cnb =   0.112564

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.016039    CLq =   7.738218    CLr =  -0.019866
 y  force CY |    CYp =   0.095639    CYq =  -0.083492    CYr =   0.225857
 x' mom.  Cl'|    Clp =  -0.455578    Clq =   0.012561    Clr =   0.282285
 y  mom.  Cm |    Cmp =  -0.008600    Cmq = -16.564770    Cmr =   0.032081
 z' mom.  Cn'|    Cnp =  -0.053255    Cnq =   0.041458    Cnr =  -0.133793

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000120   CLd02 =   0.007883   CLd03 =   0.000078
 y  force CY |   CYd01 =   0.000247   CYd02 =  -0.000002   CYd03 =  -0.002819
 x' mom.  Cl'|   Cld01 =  -0.004373   Cld02 =   0.000023   Cld03 =  -0.000489
 y  mom.  Cm |   Cmd01 =  -0.000047   Cmd02 =  -0.028121   Cmd03 =  -0.000232
 z' mom.  Cn'|   Cnd01 =  -0.000037   Cnd02 =   0.000003   Cnd03 =   0.001433
 Trefftz drag| CDffd01 =   0.000005 CDffd02 =   0.000411 CDffd03 =  -0.000176
 span eff.   |    ed01 =  -0.000099    ed02 =   0.006708    ed03 =   0.003283



 Neutral point  Xnp =   0.185377

 Clb Cnr / Clr Cnb  =   0.313222    (  > 1 if spirally stable )
