 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =  -4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02757     Cltot =   0.00625     Cl'tot =   0.00557
  CYtot =   0.02075     Cmtot =  -0.06891
  CZtot =  -1.13762     Cntot =  -0.00755     Cn'tot =  -0.00807

  CLtot =   1.13089
  CDtot =   0.12662
  CDvis =   0.07000     CDind = 0.0566165
  CLff  =   1.13903     CDff  = 0.0586759    | Trefftz
  CYff  =   0.01527         e =    0.9855    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.768944    CLb =   0.168380
 y  force CY |    CYa =  -0.002814    CYb =  -0.295581
 x' mom.  Cl'|    Cla =   0.017919    Clb =  -0.079280
 y  mom.  Cm |    Cma =  -1.023701    Cmb =  -0.033217
 z' mom.  Cn'|    Cna =  -0.006857    Cnb =   0.114813

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.012510    CLq =   7.699789    CLr =  -0.015756
 y  force CY |    CYp =   0.111683    CYq =  -0.066824    CYr =   0.222997
 x' mom.  Cl'|    Clp =  -0.451700    Clq =   0.010631    Clr =   0.298353
 y  mom.  Cm |    Cmp =  -0.006434    Cmq = -16.605466    Cmr =   0.025793
 z' mom.  Cn'|    Cnp =  -0.061185    Cnq =   0.033001    Cnr =  -0.136924

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000095   CLd02 =   0.007883   CLd03 =   0.000061
 y  force CY |   CYd01 =   0.000230   CYd02 =  -0.000001   CYd03 =  -0.002817
 x' mom.  Cl'|   Cld01 =  -0.004353   Cld02 =   0.000018   Cld03 =  -0.000486
 y  mom.  Cm |   Cmd01 =  -0.000037   Cmd02 =  -0.028188   Cmd03 =  -0.000186
 z' mom.  Cn'|   Cnd01 =  -0.000061   Cnd02 =   0.000002   Cnd03 =   0.001432
 Trefftz drag| CDffd01 =   0.000004 CDffd02 =   0.000506 CDffd03 =  -0.000141
 span eff.   |    ed01 =  -0.000069    ed02 =   0.005170    ed03 =   0.002298



 Neutral point  Xnp =   0.187034

 Clb Cnr / Clr Cnb  =   0.316900    (  > 1 if spirally stable )
