 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   5.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09944     Cltot =  -0.00205     Cl'tot =  -0.00287
  CYtot =  -0.02620     Cmtot =   0.08960
  CZtot =  -0.26531     Cntot =   0.00949     Cn'tot =   0.00928

  CLtot =   0.27297
  CDtot =   0.07594
  CDvis =   0.07000     CDind = 0.0059410
  CLff  =   0.27417     CDff  = 0.0077055    | Trefftz
  CYff  =  -0.01908         e =    0.4368    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.978674    CLb =  -0.064981
 y  force CY |    CYa =   0.000021    CYb =  -0.297747
 x' mom.  Cl'|    Cla =  -0.023936    Clb =  -0.032550
 y  mom.  Cm |    Cma =  -0.769648    Cmb =   0.013823
 z' mom.  Cn'|    Cna =   0.000393    Cnb =   0.105232

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.019930    CLq =   8.105364    CLr =   0.020816
 y  force CY |    CYp =  -0.049561    CYq =   0.083492    CYr =   0.229069
 x' mom.  Cl'|    Clp =  -0.485327    Clq =  -0.005921    Clr =   0.133467
 y  mom.  Cm |    Cmp =   0.013513    Cmq = -16.177754    Cmr =  -0.030341
 z' mom.  Cn'|    Cnp =   0.013195    Cnq =  -0.042913    Cnr =  -0.109925

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000124   CLd02 =   0.007807   CLd03 =  -0.000088
 y  force CY |   CYd01 =   0.000402   CYd02 =   0.000002   CYd03 =  -0.002832
 x' mom.  Cl'|   Cld01 =  -0.004545   Cld02 =  -0.000022   Cld03 =  -0.000511
 y  mom.  Cm |   Cmd01 =   0.000049   Cmd02 =  -0.027452   Cmd03 =   0.000231
 z' mom.  Cn'|   Cnd01 =   0.000183   Cnd02 =  -0.000003   Cnd03 =   0.001437
 Trefftz drag| CDffd01 =  -0.000006 CDffd02 =  -0.000432 CDffd03 =   0.000175
 span eff.   |    ed01 =   0.000277    ed02 =   0.049441    ed03 =  -0.009339



 Neutral point  Xnp =   0.170094

 Clb Cnr / Clr Cnb  =   0.254756    (  > 1 if spirally stable )
