 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.06147     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.03487
  CZtot =  -0.97276     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.96821
  CDtot =   0.11230
  CDvis =   0.07000     CDind = 0.0422990
  CLff  =   0.97044     CDff  = 0.0429934    | Trefftz
  CYff  =   0.00000         e =    0.9761    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.864220    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.299243
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.070958
 y  mom.  Cm |    Cma =  -0.987219    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.112819

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   7.815460    CLr =   0.000000
 y  force CY |    CYp =   0.079952    CYq =   0.000000    CYr =   0.229339
 x' mom.  Cl'|    Clp =  -0.461612    Clq =  -0.000000    Clr =   0.267442
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.605010    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.045683    Cnq =  -0.000000    Cnr =  -0.131392

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007959   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000266   CYd02 =   0.000000   CYd03 =  -0.002849
 x' mom.  Cl'|   Cld01 =  -0.004437   Cld02 =   0.000000   Cld03 =  -0.000496
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.028330   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000014   Cnd02 =  -0.000000   Cnd03 =   0.001448
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000320 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.008689    ed03 =  -0.000000



 Neutral point  Xnp =   0.183733

 Clb Cnr / Clr Cnb  =   0.309001    (  > 1 if spirally stable )
