 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -5.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   4.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09992     Cltot =  -0.00164     Cl'tot =  -0.00230
  CYtot =  -0.02099     Cmtot =   0.08939
  CZtot =  -0.26629     Cntot =   0.00761     Cn'tot =   0.00744

  CLtot =   0.27399
  CDtot =   0.07633
  CDvis =   0.07000     CDind = 0.0063346
  CLff  =   0.27455     CDff  = 0.0075106    | Trefftz
  CYff  =  -0.01527         e =    0.4486    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.991993    CLb =  -0.052080
 y  force CY |    CYa =   0.000017    CYb =  -0.299107
 x' mom.  Cl'|    Cla =  -0.019184    Clb =  -0.032730
 y  mom.  Cm |    Cma =  -0.771765    Cmb =   0.011078
 z' mom.  Cn'|    Cna =   0.000315    Cnb =   0.105816

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.015951    CLq =   8.116506    CLr =   0.016661
 y  force CY |    CYp =  -0.049629    CYq =   0.066824    CYr =   0.229384
 x' mom.  Cl'|    Clp =  -0.485994    Clq =  -0.004739    Clr =   0.133651
 y  mom.  Cm |    Cmp =   0.010815    Cmq = -16.199992    Cmr =  -0.024284
 z' mom.  Cn'|    Cnp =   0.013213    Cnq =  -0.034346    Cnr =  -0.110076

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000099   CLd02 =   0.007829   CLd03 =  -0.000070
 y  force CY |   CYd01 =   0.000403   CYd02 =   0.000001   CYd03 =  -0.002839
 x' mom.  Cl'|   Cld01 =  -0.004557   Cld02 =  -0.000018   Cld03 =  -0.000513
 y  mom.  Cm |   Cmd01 =   0.000039   Cmd02 =  -0.027527   Cmd03 =   0.000186
 z' mom.  Cn'|   Cnd01 =   0.000183   Cnd02 =  -0.000002   Cnd03 =   0.001441
 Trefftz drag| CDffd01 =  -0.000005 CDffd02 =  -0.000433 CDffd03 =   0.000141
 span eff.   |    ed01 =   0.000235    ed02 =   0.051544    ed03 =  -0.007899



 Neutral point  Xnp =   0.170097

 Clb Cnr / Clr Cnb  =   0.254756    (  > 1 if spirally stable )
