 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -6.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.09498     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.10227
  CZtot =  -0.17929     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =   0.18824
  CDtot =   0.07572
  CDvis =   0.07000     CDind = 0.0057158
  CLff  =   0.18766     CDff  = 0.0057606    | Trefftz
  CYff  =  -0.00000         e =    0.2724    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.018513    CLb =  -0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.301499
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.028240
 y  mom.  Cm |    Cma =  -0.744461    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.106861

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.168125    CLr =   0.000000
 y  force CY |    CYp =  -0.065827    CYq =   0.000000    CYr =   0.227475
 x' mom.  Cl'|    Clp =  -0.489194    Clq =   0.000000    Clr =   0.116694
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -16.171430    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.020254    Cnq =  -0.000000    Cnr =  -0.108079

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007829   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000422   CYd02 =   0.000000   CYd03 =  -0.002846
 x' mom.  Cl'|   Cld01 =  -0.004585   Cld02 =   0.000000   Cld03 =  -0.000516
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.027503   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000209   Cnd02 =  -0.000000   Cnd03 =   0.001445
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000529 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.047865    ed03 =  -0.000000



 Neutral point  Xnp =   0.168333

 Clb Cnr / Clr Cnb  =   0.244763    (  > 1 if spirally stable )
