 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tilt                                                        
     # Surfaces =   5
     # Strips   = 110
     # Vortices = 550

  Sref = 0.56000       Cref = 0.28200       Bref =  2.0000    
  Xref = 0.12650       Yref =  0.0000       Zref =-0.26800E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha = -10.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.04812     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =  -0.00000     Cmtot =   0.14967
  CZtot =   0.17256     Cntot =  -0.00000     Cn'tot =   0.00000

  CLtot =  -0.16158
  CDtot =   0.07735
  CDvis =   0.07000     CDind = 0.0073538
  CLff  =  -0.16288     CDff  = 0.0070955    | Trefftz
  CYff  =  -0.00000         e =    0.1666    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   4.993549    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.300671
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.009082
 y  mom.  Cm |    Cma =  -0.611474    Cmb =   0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.108557

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =   8.275078    CLr =   0.000000
 y  force CY |    CYp =  -0.128978    CYq =   0.000000    CYr =   0.212042
 x' mom.  Cl'|    Clp =  -0.494429    Clq =   0.000000    Clr =   0.046732
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -15.849917    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =   0.047681    Cnq =  -0.000000    Cnr =  -0.100013

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =   0.000000   CLd02 =   0.007618   CLd03 =   0.000000
 y  force CY |   CYd01 =   0.000487   CYd02 =   0.000000   CYd03 =  -0.002800
 x' mom.  Cl'|   Cld01 =  -0.004577   Cld02 =   0.000000   Cld03 =  -0.000517
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.026705   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =   0.000310   Cnd02 =  -0.000000   Cnd03 =   0.001420
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =  -0.000892 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.005003    ed03 =  -0.000000



 Neutral point  Xnp =   0.161032

 Clb Cnr / Clr Cnb  =   0.179051    (  > 1 if spirally stable )
