function [op,opreport] = trim_hover(model,alt)
%% Search for a specified operating point for the model - GT_trim.
%
% This MATLAB script is the command line equivalent of the trim model
% tab in linear analysis tool with current specifications and options.
% It produces the exact same operating points as hitting the Trim button.

% MATLAB(R) file generated by MATLAB(R) 24.1 and Simulink Control Design (TM) 24.1.
%
% Generated on: 24-Sep-2024 23:05:08

%% Create the operating point specification object.
opspec = operspec(model);

%% Set the constraints on the states in the model.
% - The defaults for all states are Known = false, SteadyState = true,
%   Min = -Inf, Max = Inf, dxMin = -Inf, and dxMax = Inf.

% State (1) - GT_trim/GT/ /Calculate DCM & Euler Angles/phi theta psi
opspec.States(1).x = 0;

% State (2) - GT_trim/GT/ /Calculate DCM & Euler Angles/phi theta psi
opspec.States(2).x = 0;

% State (3) - GT_trim/GT/ /Calculate DCM & Euler Angles/phi theta psi
% - Default model initial conditions are used to initialize optimization.
opspec.States(3).Known = true;

% State (4) - GT_trim/GT/ /p,q,r
% - Default model initial conditions are used to initialize optimization.
opspec.States(4).Known = true;

% State (5) - GT_trim/GT/ /p,q,r
% - Default model initial conditions are used to initialize optimization.
opspec.States(5).Known = true;

% State (6) - GT_trim/GT/ /p,q,r
% - Default model initial conditions are used to initialize optimization.
opspec.States(6).Known = true;

% State (7) - GT_trim/GT/ /ub,vb,wb
% - Default model initial conditions are used to initialize optimization.
opspec.States(7).Known = true;

% State (8) - GT_trim/GT/ /ub,vb,wb
% - Default model initial conditions are used to initialize optimization.
opspec.States(8).Known = true;

% State (9) - GT_trim/GT/ /ub,vb,wb
% - Default model initial conditions are used to initialize optimization.
opspec.States(9).Known = true;

% State (10) - GT_trim/GT/ /xe,ye,ze
% - Default model initial conditions are used to initialize optimization.
opspec.States(10).Known = true;
opspec.States(10).x = 0;

% State (11) - GT_trim/GT/ /xe,ye,ze
% - Default model initial conditions are used to initialize optimization.
opspec.States(11).Known = true;
opspec.States(11).x = 0;

% State (12) - GT_trim/GT/ /xe,ye,ze
% - Default model initial conditions are used to initialize optimization.
% opspec.States(12).Known = true;
% opspec.States(12).x = alt;

%% Set the constraints on the inputs in the model.
% - The defaults for all inputs are Known = false, Min = -Inf, and
% Max = Inf.

% Input (1) - GT_trim/aileron
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(1).Known = true;

% Input (2) - GT_trim/elevator
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(2).Known = true;

% Input (3) - GT_trim/rudder
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(3).Known = true;

% Input (4) - GT_trim/rpm1
opspec.Inputs(4).u = 0.7;
opspec.Inputs(4).Min = 0;
opspec.Inputs(4).Max = 1;

% Input (5) - GT_trim/rpm2
opspec.Inputs(5).u = 0.7;
opspec.Inputs(5).Min = 0;
opspec.Inputs(5).Max = 1;

% Input (6) - GT_trim/rpm3
opspec.Inputs(6).u = 0.7;
opspec.Inputs(6).Min = 0;
opspec.Inputs(6).Max = 1;

% Input (7) - GT_trim/rpm4
opspec.Inputs(7).u = 0.7;
opspec.Inputs(7).Min = 0;
opspec.Inputs(7).Max = 1;

% Input (8) - GT_trim/lambda1
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(8).Known = true;
opspec.Inputs(8).u = 0;

% Input (9) - GT_trim/lambda2
% - Default model initial conditions are used to initialize optimization.
opspec.Inputs(9).Known = true;
opspec.Inputs(9).u = 0;

%% Set the constraints on the outputs in the model.
% - The defaults for all outputs are Known = false, Min = -Inf, and
% Max = Inf.

% Output (1) - GT_trim/u
% - Default model initial conditions are used to initialize optimization.

% Output (2) - GT_trim/v
% - Default model initial conditions are used to initialize optimization.

% Output (3) - GT_trim/w
% - Default model initial conditions are used to initialize optimization.

% Output (4) - GT_trim/p
% - Default model initial conditions are used to initialize optimization.

% Output (5) - GT_trim/q
% - Default model initial conditions are used to initialize optimization.

% Output (6) - GT_trim/r
% - Default model initial conditions are used to initialize optimization.

% Output (7) - GT_trim/phi
% - Default model initial conditions are used to initialize optimization.

% Output (8) - GT_trim/theta
% - Default model initial conditions are used to initialize optimization.

% Output (9) - GT_trim/psi
% - Default model initial conditions are used to initialize optimization.

% Output (10) - GT_trim/x
% - Default model initial conditions are used to initialize optimization.

% Output (11) - GT_trim/y
% - Default model initial conditions are used to initialize optimization.

% Output (12) - GT_trim/z
% - Default model initial conditions are used to initialize optimization.

% Output (13) - GT_trim/V
% - Default model initial conditions are used to initialize optimization.
opspec.Outputs(10).Known = true;
opspec.Outputs(10).y = 0;

opspec.Outputs(15).Known = true;
opspec.Outputs(15).y = alt;

% Output (14) - GT_trim/nz
% - Default model initial conditions are used to initialize optimization.

% Output (15) - GT_trim/abbx
% - Default model initial conditions are used to initialize optimization.

% Output (16) - GT_trim/abby
% - Default model initial conditions are used to initialize optimization.

% Output (17) - GT_trim/abbz
% - Default model initial conditions are used to initialize optimization.

%% Create the options
opt = findopOptions('DisplayReport','off');
opt.OptimizationOptions.Algorithm = 'sqp';

%% Perform the operating point search.
[op,opreport] = findop(model,opspec,opt);
end
